### ISSUE TITLE
[AVM Module Issue]: Unable to create Block Blob Storage

### ISSUE THREAD

**Issue by coolhome** [Azure/bicep-registry-modules#1012]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### (Optional) Module Version

0.6.0

### Description

```bicep
module StorageAccount 'br/public:avm/res/storage/storage-account:0.6.0' = {
  scope: resourceGroup('DefaultManagedClusters')
  name: '${deployment().name}-Storage'
  params: {
    name: 'throwaway20240215'
    kind: 'BlockBlobStorage'
    skuName: 'Premium_LRS'
    accessTier: null # Unable to set NULL, defaults to `Hot`
    location: 'southcentralus'
  }
}
```

ARM Deployment Error:
```json
{
  "code": "InvalidRequestPropertyValue",
  "message": "Account property Hot is invalid for the request."
}
```

Root Problem: **BlockBlobStorage** does not offer accessTier
https://github.com/Azure/bicep-registry-modules/blob/768cb8d34794193299bf6eeced02f8161b357d18/avm/res/storage/storage-account/main.bicep#L290

Documentation: https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview#blob-lifecycle-management (purple note)

Possible Solution:
```bicep
accessTier: kind != 'Storage' && kind != 'BlockBlobStorage' ? accessTier : null
```

**Comment by fblix** [comment]
Thanks for opening this bug, will take a look as soon as I have time.

**Comment by krbar** [comment]
Working on a fix...

**Comment by coolhome** [comment]
Thanks for fixing! 🚀
