### ISSUE TITLE
[AVM Module Issue]: Unable to set support for accelerated networking and hybernation for image definitions in the compute/gallery res module

### ISSUE THREAD

**Issue by pazdedav** [Azure/bicep-registry-modules#1024]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/gallery

### (Optional) Module Version

0.2

### Description

This module contains `image` child module allowing to create **image definition** resources inside the Compute Gallery.

One important property of image definitions is `isAcceleratedNetworkSupported` which is set to `false` as a default in the child module. This also applies to `isHybernateSupported` property (currently in Preview).

However, these properties are not exposed in the parent `gallery` module - [lines 119-148](https://github.com/Azure/bicep-registry-modules/blob/a293736d20c9553fa8351ea72bf570ef5342245b/avm/res/compute/gallery/main.bicep#L119), so the default value cannot be overwritten to `true`, even if the `images` parameter (array of objects) contain the property and the value.

**Comment by pazdedav** [comment]
That's strange, dear bot, I can see that @ReneHezser does exist on GitHub 😄 .

**Comment by ReneHezser** [comment]
👋🏻 Indeed. And I got the notification. I'll look for the problem.

**Comment by pazdedav** [comment]
Thanks @ReneHezser. I believe there is a quick fix for it, so if external contributions were allowed, I could have proposed a change via a PR. But I'll let you investigate this first.

**Comment by AlexanderSehr** [comment]
> Thanks @ReneHezser. I believe there is a quick fix for it, so if external contributions were allowed, I could have proposed a change via a PR. But I'll let you investigate this first.

External contributions are more than welcome :) But in this case @ReneHezser already open the PR 🚀
