### ISSUE TITLE
[AVM Question/Feedback]: Virtual Network module should define a `subnetType`

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/bicep-registry-modules#1025]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

The Virtual Network module expects the subnet array to be an array of custom types, but the custom type isn't defined. This means IntelliSense can't be used to create the object, nor will validation pick up mistakes.

**Comment by ChrisSidebotham** [comment]
@elbatane - Are you able to pick this up. 

@SvenAelterman - During the current phase we are migrating the CARML Modules. It is down to the module owner to create custom types outside of that of the Azure Verified Modules Specs during the current pre 1.0.0 release. However I am sure the team will happily implement this. :)

**Comment by elbatane** [comment]
Will add this feature to the next version of the module, timescale unknown
