### ISSUE TITLE
[AVM Module Issue]: Virtual Network module `subnets` should gracefully handle `null` values for route table and network security group IDs

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/bicep-registry-modules#1026]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/virtual-network

### (Optional) Module Version

0.1.1

### Description

It should be possible to specify `null` for `networkResourceGroupResourceId` and `routeTableResourceId` properties on the subnet objects.

This could be allowed by adding a further condition:

```bicep
contains(subnet, 'networkSecurityGroupResourceId') && !empty(subnet.networkSecurityGroupResourceId)
```

### (Optional) Correlation Id

38c7350b-4223-41aa-8e43-6c33ef1dd4d5

**Comment by ChrisSidebotham** [comment]
@elbatane - Can you take a look into this please?

**Comment by elbatane** [comment]
Hi @SvenAelterman, thank you very much for reporting the issue. We are working on fixing it and will create the PR soon. We will inform you once is done. Thanks.

**Comment by elbatane** [comment]
This issue has been addressed here:https://github.com/Azure/bicep-registry-modules/pull/1772  So I will close it.
