### ISSUE TITLE
[Bug Report]: AKS examples documented configuring NoSchedule taint on wrong node pools

### ISSUE THREAD

**Issue by jonasssa** [Azure/bicep-registry-modules#1064]
### Module path

avm/res/container-service/managed-cluster/README.md

### Bicep version

0.1.1

### Describe the bug

Looks like the examples in the documentation are setting the following taint on the user agent pool, while it should be on the system node pool if im not mistaken.

```bicep
nodeTaints: [
          'CriticalAddonsOnly=true:NoSchedule'
        ]
```

L90-L92 should be on L73-L75
L115-L117 should be removed
L667-L669 should be on L650-L652
L690-L692 should be removed
etc... (same goes for all 4 examples)

### To reproduce

Open the readme here and look at the examples: avm/res/container-service/managed-cluster/README.md

**Comment by JPEasier** [comment]
Hi @jonasssa, I will take look and will update the docs as soon as possible.
