### ISSUE TITLE
[AVM Question/Feedback]: VM extension

### ISSUE THREAD

**Issue by Gijsreyn** [Azure/bicep-registry-modules#1067]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Dear AVM maintainers, 

While deploying the Azure Virtual Machine, it is required to perform a domain join (AD). In the extension, you can of course set the restarted setting to false, as such:

```
extensionDomainJoinConfig: {
      enabled: true
      settings: {
        name: '' 
        user: '
        restart: 'false' // setting
        options: 3
        ouPath:
      }
    }
```

But the virtual machine needs to be restarted anyway and this is particularly helpful when doing post deployment task. The only thing that I'm looking for, is that after the domain join has happened, the custom script extension sometime fails if you combine them (because of the restart). Is it possible to do a "dependsOn"?

Another extension that I was missing, was the GuestConfiguration extension. Are there any plans on adding it to the VM?

Thanks in advance.

**Comment by AlexanderSehr** [comment]
@Gijsreyn can't argue with the asks. What's your take @rahalan ?

**Comment by rahalan** [comment]
Good idea. I will look into that. There are also some other extensions that I want to add.

**Comment by rahalan** [comment]
@matebarabas why are those warnings coming, I already answered?

**Comment by AlexanderSehr** [comment]
It'll be added time and time again if I'm not mistaken

**Comment by matebarabas** [comment]
Not anymore, as once the "Needs: triage" label is removed, the bot will not say a single thing again. 😉👍

**Comment by rahalan** [comment]
@Gijsreyn FYI, PR is nearly done. Currently I am unfortunately blocked by a bug in the readme generation. I expect it to be solved in the next days. After that, I will promote the PR, so it can be reviewed.

**Comment by Gijsreyn** [comment]
@rahalan Love the work you did!

**Comment by rahalan** [comment]
@Gijsreyn PR is finally merged
