### ISSUE TITLE
[AVM Module Issue]: topic/subscription sets forwardto by default to parent topic

### ISSUE THREAD

**Issue by dennyhabich** [Azure/bicep-registry-modules#1078]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/service-bus/namespace

### (Optional) Module Name if not listed above

topic/subscription

### Description

I am using the service-bus/namespace module to create a namespace, topics and subscriptions. The created subscriptions get a forward to by default, even though I have not set one. Since that forward to is pointed at the parent topic, messages get forwarded to the same topic, which causes problems when using duplicate detection.
Since there is a check on an empty forwardTo parameter, it is impossible to override this behavior.

To me it does not make sense to have the parent topic as the forwardTo by default as I cant really imagine a use case for this. Whatever the case, it should be possible to not have a forward to, as it is optional in the API.

**Comment by ChrisSidebotham** [comment]
Thanks for raising this @dennyhabich - I will take a look at rectifying this in the coming version :)
