### ISSUE TITLE
Would it be possible to add decorator @description(''' ''') support for the brm tool?

### ISSUE THREAD

**Issue by bengeset96** [Azure/bicep-registry-modules#109]
@shenglol 

Would it be possible for you to add support around decorator description(''' ''') support for the brm tool?

Example

```
@description('''
Storage account name restrictions:
- Storage account names must be between 3 and 24 characters in length and may contain numbers and lowercase letters only.
- Your storage account name must be unique within Azure. No two storage accounts can have the same name.
''')
@minLength(3)
@maxLength(24)
param storageAccountName string
```
It would be awesome if brm generate and brm validate could support such functionality for readme.

**Comment by shenglol** [comment]
Didn't realize that multiline strings in descriptions will break the markdown table, so this should be a bug. I'm going to fix it.

**Comment by bengeset96** [comment]
Great! Thank you.
