### ISSUE TITLE
Could it be possible to extend maxLength for description in metadata.json?

### ISSUE THREAD

**Issue by bengeset96** [Azure/bicep-registry-modules#110]
@shenglol 

Could it be possible to extend maxLength for description in metadata.json?

Current is 1000.

In some cases it would be great to have the module detail oriented for the consumer by describing. Then you also have the README.md table and examples for full understanding.

**Comment by shenglol** [comment]
How about we add a `summary` for short description and increase the max length limit for `description`? Also, what do you think is the best max length for `description`? Would 6000 be enough?

**Comment by bengeset96** [comment]
I would prefer a new `## Detailed Description` or `## Details` heading like ` ## Examples` in the README.md instead of having to work with string in `metadata.json` for this matter. A place where you can write whatever you want about the module. Just another section that you are free to work with and brm does not really care about what you have written, just like `Examples`. 

When manually adding it now in README.md and running `brm generate` it just overwrites it.

Adding 6000 for `description` in `metadata.json` would be great to add just since we're in the loop.

What do you think about that?

**Comment by shenglol** [comment]
That sounds good. Will update the `brm` tool to implement it.

**Comment by bengeset96** [comment]
Thank you so much! Really grateful.

**Comment by bengeset96** [comment]
@shenglol 

Awesome!

When invoking the tool using brm generate it is still referring to v1 schema.

`
Tool 'azure.bicep.registrymoduletool' (version '0.6.18') was successfully installed.`

Any idea how to achieve this?

**Comment by shenglol** [comment]
The feature will be shipped as part of next Bicep release, which will be published on 6/10.
