### ISSUE TITLE
[AVM Module Issue]: Public ip adress for API Management

### ISSUE THREAD

**Issue by MichelleBarlo** [Azure/bicep-registry-modules#1104]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/api-management/service

### Description

At this moment the property 'publicIpAddressId' is not exposed in this module.

Creating a APIM with the virtualNetworkType set to 'Internal' without specifying a public ip adress will result in a APIM with a platformVersion stv1 to be created. stv1 will retire on august 2024.
[stv1-platform-retirement-august-2024](https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/stv1-platform-retirement-august-2024)

Can you expose the property 'publicIpAddressId' to work around this issue.

**Comment by tony-box** [comment]
@MichelleBarlo thank you for the suggestion. Work on this now!

**Comment by dewolfs** [comment]
linked: https://github.com/Azure/ResourceModules/issues/3465

**Comment by gvdmaaden** [comment]
I am experiencing the same issue. Also waiting for the PR to complete.
