### ISSUE TITLE
[AVM Module Issue]: Microsoft.Web/sites add "app,linux" as an allowed kind

### ISSUE THREAD

**Issue by rodney-almeida** [Azure/bicep-registry-modules#1105]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### Description

Module has an allowed kind list that does not comprise of all kinds. Have a need to deploy an web app of kind "app,linux" and cant use module. I don't believe any config change is needed to support "app,linux" kinds that are not already covered by the kind "app"

**Comment by tsc-buddy** [comment]
Hi! I am scheduled for AVM Module work from 11/3-21/3. I shall review this and provide updates accordingly.
Thanks

**Comment by dslatkin** [comment]
Eagerly awaiting this. Finally got a Windows server (`kind: 'app'`) working for a Node.js app for the time being but it was a huge pain and many hoops to jump through. Linux would have been so much easier.
