### ISSUE TITLE
[Bug Report]: vnet module improvements

### ISSUE THREAD

**Issue by miqm** [Azure/bicep-registry-modules#111]
### Module path

/modules/network/vnet

### Bicep version

0.6.18

### Describe the bug

bicep resource name is `appServiceEnvironment_diagnosticSettings` while it should be `virtualNetwork_diagnosticSettings`

additionally, new diagnosticSettings API (2021-05-01-preview) introduced `categoryGroup: 'allLogs'` and `categoryGroup: 'allMetrics'` which simplifies setting up all logs collection into particular destination

### To reproduce

https://github.com/Azure/bicep-registry-modules/blob/main/modules/network/virtual-network/main.bicep#L172

**Comment by alex-frankel** [comment]
@MrMCake -- can you take a look at this one?

**Comment by MrMCake** [comment]
@alex-frankel, a PullRequest was opened.
