### ISSUE TITLE
[AVM Module Issue]: KeyVault should have user defined types also for keys and secrets, as it already has it for access policies

### ISSUE THREAD

**Issue by rahalan** [Azure/bicep-registry-modules#1122]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/key-vault/vault

### Description

Please add user defined types for keys and secrets, so the user gets IntelliSense for them. It is already done for access polcies.

**Comment by fblix** [comment]
Will take a look

**Comment by ChrisSidebotham** [comment]
Completed under #1986
