### ISSUE TITLE
[AVM Module Issue]: API Management Module should add the creation of 'Microsoft.ApiManagement/service/loggers' and 'Microsoft.ApiManagement/service/apis/diagnostics'

### ISSUE THREAD

**Issue by Menghua1** [Azure/bicep-registry-modules#1124]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/api-management/service

### (Optional) Module Name if not listed above

avm/res/api-management/service

### Description

Please add the creation of `Microsoft.ApiManagement/service/loggers` and `Microsoft.ApiManagement/service/apis/diagnostics`.
For example (azd): 
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/gateway/apim.bicep#L61
https://github.com/Azure-Samples/todo-java-mongo/blob/main/infra/app/apim-api.bicep#L56

CC: @jongio

**Comment by tony-box** [comment]
Assigning to myself due to issue with auto group assignment.

**Comment by jongio** [comment]
@tony-box - Do you have an ETA for this?

**Comment by Menghua1** [comment]
@jongio There is a question here that I need to confirm with you.
For AVM’s APIM module, compared with the files in **infra/core**, only the `Microsoft.ApiManagement/service/loggers` function is missing.
However, compared with the [infra/app/apim-api.bicep](https://github.com/Azure-Samples/todo-java-mongo/blob/main/infra/app/apim-api.bicep#L56C26-L56C64) file currently used by this `todo-java-mongo` template, the `Microsoft.ApiManagement/service/apis/diagnostics` function is also missing.

Regarding this issue, do you think it is necessary to add the missing feature `Microsoft.ApiManagement/service/apis/diagnostics` to the issue https://github.com/Azure/bicep-registry-modules/issues/1124?
