### ISSUE TITLE
[AVM Module Issue]: DocumentDB Database should add the creation of 'Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions' and ‘Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments’ and the output of 'cosmos.properties.documentEndpoint'

### ISSUE THREAD

**Issue by Menghua1** [Azure/bicep-registry-modules#1126]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/document-db/database-account

### (Optional) Module Name if not listed above

avm/res/document-db/database-account

### Description

Please add the creation of `Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions` and `Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments` the output of `roleDefinition.outputs.id` and `cosmos.properties.documentEndpoint`.
For example (azd): 
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/cosmos/sql/cosmos-sql-role-def.bicep#L4
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/cosmos/sql/cosmos-sql-role-assign.bicep#L7
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/cosmos/sql/cosmos-sql-role-def.bicep#L30
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/cosmos/cosmos-account.bicep#L47

CC: @jongio

**Comment by bryansan-msft** [comment]
Hello hello, I will come back as soon as the development of the feature is ready

**Comment by jongio** [comment]
@bryansan-msft - Any questions about this?  Do you have an ETA?

**Comment by zedy-wj** [comment]
@bryansan-msft - Any progress about this? If you haven't started it yet, we will do a PR on it.

**Comment by jongio** [comment]
@zedy-wj - Let's do it.

**Comment by zedy-wj** [comment]
@jongio - PR: https://github.com/Azure/bicep-registry-modules/pull/2103 is ready. Please review it, thanks!

**Comment by Menghua1** [comment]
Update the title, remove the output `roleDefinition.outputs.id`. In `AVM`, the parameter `roleDefinition.outputs.id` is already called [internally](https://github.com/Azure/bicep-registry-modules/pull/2103/files#diff-086e9c1330030c1e3a0215fee43268af12373b51a0773dc246a63d9a1cad56e5R55) to implement the role-assignments function, and there is no need to output the `roleDefinition.outputs.id` parameter.
