### ISSUE TITLE
[AVM Module Issue]: SQL Servers should add the creation of 'Microsoft.Resources/deploymentScripts'

### ISSUE THREAD

**Issue by Menghua1** [Azure/bicep-registry-modules#1127]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/sql/server

### (Optional) Module Name if not listed above

avm/res/sql/server

### Description

Please add the creation of `Microsoft.Resources/deploymentScripts` to execute SQL initialization scripts in Azure environment.
For example (azd): https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/sqlserver/sqlserver.bicep#L46

CC: @jongio

**Comment by AlexanderSehr** [comment]
Hey @Menghua1,

thanks for raising the issue. While I'm not the owner of the module, I'd still be curious why this should be part of the module itself and whether it's not too specific for a use case. Mind you, if anything is added in the module, all module users will have in as part of their deployment not matter if they need it or not, so we have to make sure only to add elements that are relevant for the general audience.
If something **is** specific to a use case (or a group of users), one could argue it should be part of a pattern module that uses the SQL resource module and combines it will other elements (like the aforementioned deployment script) to create a pattern for a use case (that in itself would be published in addition to it's elements).

**Comment by v-xuto** [comment]
@AlexanderSehr Thanks for your advice. `Microsoft.Resources/deploymentScripts` may not need to be part of the `sql` module itself.

@Jongio We found that referencing the [deployment script](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/resources/deployment-script/main.bicep) module of AVM can also implement the `Microsoft.Resources/deploymentScripts` function in `infra/bicep/core/database/sqlserver/sqlserver.bicep`. The missing feature  `Microsoft.Resources/deploymentScripts` probably does not need to be added in the `sql` module. What do you think?

**Comment by bryansan-msft** [comment]
We can close this issue as you found a workaround and having a deployment script to provision the content of a database it is not a very popular request. In case there is more need for this we can open it again
