### ISSUE TITLE
[AVM Module Issue]: AKS Module should add output 'kubeletidentityClientId' and 'kubeletidentityResourceId'

### ISSUE THREAD

**Issue by Menghua1** [Azure/bicep-registry-modules#1128]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/container-service/managed-cluster

### (Optional) Module Name if not listed above

avm/res/container-service/managed-cluster

### Description

Please add the output of the following two parameters:

1.  `kubeletidentityClientId`: managedCluster.properties.identityProfile.kubeletidentity.clientId(The Client ID of the AKS identity).
2. `kubeletidentityResourceId`: managedCluster.properties.identityProfile.kubeletidentity.resourceId(The Resource ID of the AKS identity).

For example (azd): https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/host/aks-managed-cluster.bicep#L136

CC: @jongio

**Comment by ilhaan** [comment]
Thanks for submitting this @Menghua1. I can work on adding this to the module soon

**Comment by v-xuto** [comment]
@JPEasier - Any questions about this? Do you have an ETA?

**Comment by JPEasier** [comment]
@jongio, @v-xuto,
from my side an update will come in may at the earliest, but i will check with @ilhaan and see what is possible.

if you need the feature very urgently, i welcome you to create a pull request.

**Comment by jongio** [comment]
@zedy-wj/@v-xuto, Can you please create a PR for this?

**Comment by zedy-wj** [comment]
@jongio - We have done a PR for this issue.
PR link: https://github.com/Azure/bicep-registry-modules/pull/1464, please review it, thanks!
