### ISSUE TITLE
[Module Proposal]: All CARML modules

### ISSUE THREAD

**Issue by itpropro** [Azure/bicep-registry-modules#113]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

I think it would make sense to have all modules from the Common Azure Resource Module Library ([CARML](https://github.com/Azure/ResourceModules)) automatically published to the public bicep library, instead of manually tranfering every single module and to avoid duplicates (like we already have with e.g. virtual-network).
The maintenance overhead would be incredibly high and implementing a CI in the CARML repo to automatically push them to the registry on change would be the much better solution.

### Module path

provider/module

### Describe the module

Respective module description

**Comment by alex-frankel** [comment]
Hi @itpropro -- we are working with the CARML team to move all of their content to the public registry, but the CI in each repo does not work the same way, so are working through how the code needs to be refactored accordingly.

At the end of the process there should not be duplicates. I am not sure why the virtual-network module is not identical. @MrMCake -- is the intention to keep these in sync?

**Comment by MrMCake** [comment]
Hey @alex-frankel,
the virtual network module naturally evolved together with all other modules in the CARML repository and was not re-published to the Public Bicep Registry, given the involved effort (e.g. removing our telemetry ID, adjusting our file names, adjusting our readme, updating the test file etc. etc.) to convert one schema to another. 

So yes, we have duplicates, i.e. a module in CARML & one in the Public Bicep Registry - and yes, they are not identical.

I guess, in an ideal world all modules we have in CARML are always published to the registry on any given change (be it to the repository / the ACR directly). But to automate this will take time - and require changes.

**Comment by itpropro** [comment]
I think to avoid drift between the modules in this repo and ResourceModules, we should focus on the ones that are either not already in CARML or that have a soley different purpose like the samples or deployment-scripts.
What do you think @MrMCake how long it would take to make it possible for modules from the ResourceModules repository to be automatically pushed into the ACR during CI runs?
For me one of the important dates is the end of July when third-party bicep providers are probably introduced (at least the Kubernetes one regarding to the public roadmap) which could lead to many new people trying out Bicep and take a look and the current state of the ecosystem :)

**Comment by MrMCake** [comment]
Hey @itpropro, 
publishing at scale stands and falls with the capabilities to automate it. 

Currently, our only path into the Official Public Bicep Registry is a path with manual steps like creating an issue, waiting for approval, creating and adjusting the code base, etc. Likewise, we cannot just migrate the full codebase as is, as we have different designs, approaches and frankly too many enhancements happening to too many modules - which would also massively increase the workload in this team's side.

Ideally we'll be able to resolve these challenges some time in the future, or even publish to a [dedicated registry](https://github.com/Azure/ResourceModules/issues/1645) and reference one another. From a CARML perspective, our most important issue (and step closer to the Public Registry) will be the implementation of the new [dependency approach](https://github.com/Azure/ResourceModules/issues/1583) we've started working on last year in November.

**Comment by ChrisSidebotham** [comment]
Closing this issue as its a module proposal. We are currently in the process of migrating all CARML Modules to AVM. Please open module specific issues and requests

Dear @itpropro , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, module proposals for new, non-AVM modules will no longer be accepted and we encourage you to propose a new AVM module, which you can file here: Module Proposal, [here](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
