### ISSUE TITLE
[AVM Module Issue]: Application Insight Module should add the creation of 'Microsoft.Portal/dashboards'

### ISSUE THREAD

**Issue by Menghua1** [Azure/bicep-registry-modules#1130]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/insights/component

### (Optional) Module Name if not listed above

avm/res/insights/component

### Description

Please add the creation of `Microsoft.Portal/dashboards` and the output `applicationInsights.properties.ConnectionString`.
For example (azd): 
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/monitor/applicationinsights.bicep#L19
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/monitor/applicationinsights.bicep#L28

CC: @jongio

**Comment by v-xuto** [comment]
@krbar Do you have an ETA for this?

**Comment by Menghua1** [comment]
The issue of the output parameters `applicationInSights.properties.connectionString` has been fixed by https://github.com/hundredacres/bicep-registry-modules/commit/038de41cfa745bbc4d2f1714e56e194f514f2261.

**Comment by zedy-wj** [comment]
This issue is fixing by pr: https://github.com/Azure/bicep-registry-modules/pull/2016.

**Comment by krbar** [comment]
Dear @Menghua1, 

please note that after merging the [PR 2016](https://github.com/Azure/bicep-registry-modules/pull/2016) the following resource modules are now available:

- [Application Insights](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/insights/component) ([Module Proposal](https://github.com/Azure/Azure-Verified-Modules/issues/297))
- [Portal Dashboard](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/portal/dashboard) ([Module Proposal](https://github.com/Azure/Azure-Verified-Modules/issues/980))

If I understand correctly, you need a pattern module that deploys these resources together. Can you confirm?

If yes, please be aware that this will require a separate module proposal for the new pattern, which you can submit [here](https://aka.ms/AVM/ModuleProposal). This proposal needs a module owner responsible for developing and maintaining the module. While we can assist with the initial development, we cannot take on ownership of this module. Would you or someone from your team be willing to own it? If so, do you need help with the initial development?

CC: @matebarabas @jtracey93 @jongio @puicchan

**Comment by Menghua1** [comment]
@jongio Do you have any ideas?  Now, as the `Portal Dashboard` is independent module, when moving azd to use avm, need to set about 1000 lines content to the `Portal Dashboard` module to associate `Application Insights` and the code is here: https://github.com/Azure/azure-dev/blob/avmupdates/templates/todo/common/infra/bicep/app/applicationinsights-dashboard.bicep

**Comment by jongio** [comment]
Let's keep that in azure-dev repo for now and take the pattern modules as a separate effort.

**Comment by v-xuto** [comment]
@jongio Got it. Besides, we will submit a new module [here ](https://aka.ms/AVM/ModuleProposal) to deploy these resources together. Should our team take ownership of this module and develop it?

**Comment by Menghua1** [comment]
@jongio we have opened a new Module Proposal issue here: https://github.com/Azure/Azure-Verified-Modules/issues/1206. If there are no problems, we will close this issue.

**Comment by jongio** [comment]
Ok
