### ISSUE TITLE
[AVM Module Issue]: Cognitive Service should add the creation of 'Microsoft.CognitiveServices/accounts/deployments'

### ISSUE THREAD

**Issue by Menghua1** [Azure/bicep-registry-modules#1131]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cognitive-services/account

### (Optional) Module Name if not listed above

avm/res/cognitive-services/account

### Description

Please add the creation of 'Microsoft.CognitiveServices/accounts/deployments'.
For example (azd): https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/ai/cognitiveservices.bicep#L38

CC: @jongio

**Comment by ilhaan** [comment]
@Menghua1 thanks for submitting this. I will take a look at this and make an update soon

**Comment by jongio** [comment]
@ilhaan - Did you get a chance to take a look?

**Comment by jongio** [comment]
@v-xuto @zedy-wj - Can you please submit a PR to AVM for this feature?

**Comment by zedy-wj** [comment]
@jongio - We have done a PR for this issue.
PR link: https://github.com/Azure/bicep-registry-modules/pull/1466, please review it, thanks!
