### ISSUE TITLE
[Module Proposal]: Deployment delay

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#114]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

When deploying some Azure services together that use AzureAD for RBAC, it is common to receive errors regarding propagation time.

> "Caller is not authorized to perform action on resource. If role assignments, deny assignments or role definitions were changed recently, please observe propagation time."

An example is when Azure Application Gateway is created that uses Key Vault for its SSL Certificates. On some tenants, success rate is at about 20%.

### Module path

deployment-scripts/wait

### Describe the module

This new module would create a sleep for a configurable number of seconds to be used in other resources `DependsOn` in order to delay resource creation. EG. [wait.bicep](https://github.com/Azure/azure-quickstart-templates/pull/12524/files#diff-cbe0f293f3aec177575c790878a3fb776fa65342455911c10f346ffef798217e)

**Comment by alex-frankel** [comment]
Approved. We definitely have some reservations about the pattern, but don't want to block the creation of the module if you plan to use it.
