### ISSUE TITLE
[AVM Question/Feedback]: `avm/res/sql/server` additional InteliSense for database options 

### ISSUE THREAD

**Issue by Ralph101** [Azure/bicep-registry-modules#1141]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Is it possible to add some InteliSense if you are adding a database to the server. Default it wil not show any option you can add, so you need to dive into the GitHub docs how to a database to a sql server. Also when you add a Standard S1 the to maximum disk storage is to high. Maybe it's possible to add some condition based on sku type?

**Comment by matebarabas** [comment]
@bryansan-msft, @Azure/avm-res-sql-server-module-owners-bicep, @Azure/avm-res-sql-server-module-contributors-bicep-bicep, this issue was just transferred from the AVM repo.

**Comment by bryansan-msft** [comment]
Hello @Ralph101, I have been internally discussing with the team how we can approach this, and I will be making the necessary changes to improve the user experience when specifying parameters for the module in the next days

**Comment by peterbud** [comment]
Closing as #3582 is adding the UDTs and IntelliSense for the most important objects
