### ISSUE TITLE
[Brm Feature] Check for newer version

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#117]
## Problem
When you use brm, it doesn't currently check to see if there's a newer version of itself available. 
This will lead to some users unknowingly testing locally with an older version, and then having PR checks fail on module submission. It could also lead to the issue of old (invalid) scaffolds being generated, which then requires troubleshooting.

## Solution
When using brm generate/validate, check to see if the local version is the latest version.

**Comment by ChrisSidebotham** [comment]
Dear @Gordonby, Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

As part of this transition, the new AVM CI environment is replacing the existing CI formerly leveraged within the Bicep Registry Modules (BRM) repository. As a result of this, issues and features related to the existing BRM CI will be closed. If you think your issue still needs addressing, please raise a new issue related to the AVM CI, [here](https://aka.ms/BRM/AVMQuestionFeedback).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
