### ISSUE TITLE
[AVM Question/Feedback]: In the roleAssignments for user-assigned-identity the principalId is referencing itself?

### ISSUE THREAD

**Issue by ramuvr** [Azure/bicep-registry-modules#1185]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I am creating a UMI using the module user-assigned-identity. This has a roleAssignment in Example 2 Bicep, where you can create and assign in one go, which is great, but the principalId referenced is its own in my case. 
I am then getting 
"This expression is referencing its own declaration, which is not allowed.bicep(BCP079)"
"module userAssignedIdentity 'br/public:identity/user-assigned-identity:1.0.2'
Azure managed identities provide an easy way for applications to access resources securely in Azure."

Is there a way around it ?

![image](https://github.com/Azure/bicep-registry-modules/assets/27629864/1ff35c69-49f8-4147-8019-57097377f48d)

**Comment by ramuvr** [comment]
Sorry, was making an assignment to the ResourceGroup itself as that was the scope of the parent resource (i.e UMI). The UMI obviously inherits the assignment as its inside the same RG. 
In hindsight, what I would have liked to do was to role Managed Identity Operator so that the UMI can then be used to do Microsoft.VirtualMachineImages/imageTemplates

**Comment by elanzel** [comment]
Hi @ramuvr,
i confirm you should before create the identity and then you can call the module to assign the role.
An example is here [max test](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/managed-identity/user-assigned-identity/tests/e2e/max/main.test.bicep), where the identity is deployed before as a needed dependency and then we called the module to assign the role

**Comment by ramuvr** [comment]
Thanks @elanzel . I can confirm that I can use that model to create UMI and do roleassignment separately without any issues, using local bicep module. 

But was having the error with the AVM which had this combined module.

 As I was starting to write this I am realising the module I used was "br/public:identity/user-assigned-identity" which was populated by intellisense on vscode, and the one in AVM is listed as "br/public:avm/res/managed-identity/user-assigned-identity" not sure if that makes any difference. 

But I do see that the 
https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/managed-identity/user-assigned-identity
module does have a roleAssignments attribute rolled into the user-assigned-identity. So does that mean this doesn't work ?

**Comment by AlexanderSehr** [comment]
Hey @ramuvr,
the original module you mentioned wasn't an AVM module (which essentially just means somebody else contributed it and we cannot speak for it necessarily).
For the AVM one it is as you said (and the same is true for all AVM modules): The module itself is intended to deploy a service (in this case a User-assigned identity), and optionally additional settings if supported (including role assignments, diagnostic settings, locks, private endpoints etc.) which are not provided by the raw resources - so each module just tries to make their usage easier as you can deploy a service and assign e.g. permissions on it in one go.
However, as you need to know the principal ID of an identity to perform a role assignment, you cannot deploy an identity and immediately perform a role assignment on it for the same identity as the principal ID wouldn't be known at the start of the deployment. Technically speaking we could cramp it in somehow as the service deployment always comes before the role assignment, but it would add quite some complexity for a seemingly rare use case. HOWEVER, if you say it's actually more common than I might think, we can certainly ideate how this could look like from an implementation perspective (which would mean processing the `roleAssignments`  parameter using some internal module magic).
