### ISSUE TITLE
[WAF - Reliability Review] -	`avm/res/app/managed-environment`

### ISSUE THREAD

**Issue by jtracey93** [Azure/bicep-registry-modules#1186]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/managed-environment

### Description

Hello team,

The AVM core team are performing a review of all AVM modules to ensure they are aligned to the WAF reliability pillar by default, and in the future they will be checking against other WAF pillars also. This is a requirement we have before we can go `v1.0.0` for any AVM module.

Links to AVM specs:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr2---category-composition---waf-aligned
- https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr5---category-composition---availability-zones

Links to WAF Reliability, APRL & Product Docs recommendations used for analysis:

- https://learn.microsoft.com/azure/well-architected/reliability/checklist
- https://learn.microsoft.com/en-us/azure/reliability/reliability-azure-container-apps?tabs=azure-cli

Whilst reviewing this module the following issues have been found that are non-compliant with the AVM specs that need to be resolved in a new version release:

- [ ] The `zoneRedundant` property should default to `true` - https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/app/managed-environment/main.bicep#L49-L51

Please make these changes in a PR to the parameter defaults so a new minor version can be published.

Thanks

The AVM Core Team

**Comment by hundredacres** [comment]
Working on it.

**Comment by hundredacres** [comment]
PR here: https://github.com/Azure/bicep-registry-modules/pull/1391
