### ISSUE TITLE
[WAF - Reliability Review] -	`avm/res/app/container-app`

### ISSUE THREAD

**Issue by jtracey93** [Azure/bicep-registry-modules#1188]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/container-app

### Description

Hello team,

The AVM core team are performing a review of all AVM modules to ensure they are aligned to the WAF reliability pillar by default, and in the future they will be checking against other WAF pillars also. This is a requirement we have before we can go `v1.0.0` for any AVM module.

Links to AVM specs:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr2---category-composition---waf-aligned
- https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr5---category-composition---availability-zones

Links to WAF Reliability, APRL & Product Docs recommendations used for analysis:

- https://learn.microsoft.com/azure/well-architected/reliability/checklist
- https://learn.microsoft.com/en-us/azure/reliability/reliability-azure-container-apps?tabs=azure-cli#availability-zone-support

Whilst reviewing this module the following issues have been found that are non-compliant with the AVM specs that need to be resolved in a new version release:

- [x] Set the scaleMinReplicas to `3` & set `scaleMaxReplicas` to 10 to match description - https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/app/container-app/main.bicep#L29-L33

Please make these changes in a PR to the parameter defaults so a new minor version can be published.

### PSRule

It also seems that PSRule is not picking up these checks via its tests and that has been logged in the issue: https://github.com/Azure/PSRule.Rules.Azure/issues/2790

Thanks

The AVM Core Team

**Comment by oZakari** [comment]
Hey @jtracey93, will work on getting this in.
