### ISSUE TITLE
[AVM Module Issue]:  Synapse - Firewall and Sparkpool

### ISSUE THREAD

**Issue by Jackmt9** [Azure/bicep-registry-modules#1189]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/synapse/workspace

### Description

The synapse module should support the creation of firewall rules and sparkpools.

**Comment by Ralph101** [comment]
This would be very helpful!!

**Comment by AlexanderSehr** [comment]
Hey @Jackmt9, thanks for the issue :) Please note that the module current does not have an owner which means the implementation may be delayed.

**Comment by elanzel** [comment]
Hi @Jackmt9, since there's no owner for this module, but i've contributed to migrate it, i'll try to support in best-effort for this issue. Let me validate your requirement and i'll be back to you

**Comment by Ralph101** [comment]
Is there an update on this topic? I believe it's a minor change that would be very helpful. Thank you in advance.

**Comment by elanzel** [comment]
Add child:
Microsoft.Synapse/workspaces/firewallRules@2021-06-01

**Comment by Ralph101** [comment]
@elanzel do you have any idea when the PR will be merged so we can ut the Firewall functionality?

**Comment by elanzel** [comment]
> @elanzel do you have any idea when the PR will be merged so we can ut the Firewall functionality?

Hi @Ralph101 , i'm working on it
