### ISSUE TITLE
[AVM Module Issue]: Private Endpoints Scope

### ISSUE THREAD

**Issue by Jackmt9** [Azure/bicep-registry-modules#1190]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

All modules supporting Private Endpoints.

### Description

Private endpoints should support deployment in other scopes. For example, I'd like to deploy a storage account in one resource group but the private endpoint for that storage account in another.

This comes in handy when separating all networking components into one resource group in a subscription and have resources live in other resource groups.

This change will require an adjustment on all modules that create private endpoints.

**Comment by AlexanderSehr** [comment]
Hey @Jackmt9,
thanks for the issue. I guess to realize this we'd need to add the scope statement to each PE implementation like this:
```bicep
  scope: resourceGroup(privateEndpoint.?resourceGroupName) ?? resourceGroup()
``` 

@segraef, @eriqua, @ChrisSidebotham, @jtracey93  thoughts?

**Comment by Jackmt9** [comment]
> Hey @Jackmt9, thanks for the issue. I guess to realize this we'd need to add the scope statement to each PE implementation like this:
> 
> ```bicep
>   scope: resourceGroup(privateEndpoint.?resourceGroupName) ?? resourceGroup()
> ```
> 
> @segraef, @eriqua, @ChrisSidebotham, @jtracey93 thoughts?

This is exactly the solution I am looking for.

**Comment by eriqua** [comment]
Fine for me. A fair feature request which won't hurt the default implementation.

**Comment by AlexanderSehr** [comment]
To implement this, I'd suggest to first update the spec in the Azure/Azure-Verified-Modules repository, and then move and on bulk-edit the modules here in the BRM repository.
@Jackmt9 we cannot give a definitive statement 'when' we'll get to implement the change. While the update to the AVM repository should be quick, the one to this repository needs a bit more work as we'd not want to open one big bang PR but split it into multiple, test them, etc.

Further, it's actually not a change in the `private-endpoint` module to which end I'll unassign @segraef

**Comment by AlexanderSehr** [comment]
Quick update, I did test and update the proposed implemention and it's successful. I'll open a PR to update the specs next:

Resource Group 1: 
![image](https://github.com/Azure/bicep-registry-modules/assets/5365358/a74d4a15-4caf-48be-b578-9f2833cd1cfa)

Resource Group 2:
![image](https://github.com/Azure/bicep-registry-modules/assets/5365358/bd091acc-010d-4f47-8cf8-e49c8aa33e3b)

Connections in KeyVault
![image](https://github.com/Azure/bicep-registry-modules/assets/5365358/d1b3f376-fa04-4a3b-94e3-b151a457d8f6)

Used test (which deploys 2 RGs instead of 1):
![image](https://github.com/Azure/bicep-registry-modules/assets/5365358/e6e7b308-1f94-4dc7-89a8-70f1a0b67f1f)

Added line in PE deployment in /key-vault/vault `main.bicep`:
```bicep
scope: resourceGroup(privateEndpoint.?resourceGroupName ?? '')
```

**Comment by Jackmt9** [comment]
@AlexanderSehr Note that everywhere a private endpoint is being created (keyVault, storage, ...) should now start optionally accepting a scope for just the private endpoint creation.

**Comment by Jackmt9** [comment]
Great work @AlexanderSehr . Looking forward to seeing this implemented across all resources that implement a private endpoint.

**Comment by AlexanderSehr** [comment]
> Great work @AlexanderSehr . Looking forward to seeing this implemented across all resources that implement a private endpoint.

We're currently just waiting to get all templates formatted with the V2 formatter to avoid conflicts and will then proceed with this as an update across all modules :)

cc: @krbar
