### ISSUE TITLE
[Module Proposal]: Azure Gaming: GameDev VMSS

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#121]
### Have you checked this module does not already exist in the registry?
Yes

### Why is the module needed?
We would like to simplify our template [here](https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/azure-gamedev/gamedev-vmss) by using a Bicep module. We will then go back and replace the Template with a direct call to the public module.

### Module path
modules/azure-gaming/game-dev-vmss

### Describe the module
This Bicep module makes it easier for users to leverage the Game Dev Virtual Machine on a VMSS cluster via ARM.
https://docs.microsoft.com/en-us/gaming/azure/game-dev-virtual-machine/

**Comment by shenglol** [comment]
I wonder if it makes sense to put the module under the `vm` folder. @alex-frankel thoughts?

**Comment by alex-frankel** [comment]
@dciborow -- do you expect any other modules to be added to the `azure-gaming` folder? If so, I am ok with adding this directory because it looks like "azure gaming" is a branded entity in MS Docs. If this will be the only module in this folder for the foreseeable future, then I agree it makes more sense to go in a `vmss` directory.

**Comment by dciborow** [comment]
@alex-frankel , yes. I will be immediately following this up "modules/azure-gaming/game-dev-vm" based on https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/azure-gamedev/gamedev-vm

My team is generally driving the _Branded Entity_ "azure gaming". Right now our offerings are all marketplace images, and these bicep modules provide a better way to expose the "Custom Options" to our customers then the generic VM resource.

It is likely that our future marketplace offerings have 1 or more Bicep modules to make them easier to consume for customers.

**Comment by alex-frankel** [comment]
sounds good! Is `azure` implied? What if we just call it `gaming`?

**Comment by dciborow** [comment]
@alex-frankel , in the gaming industry... 'azure' is never implied (in my org, gaming usually implies xbox, without any thought of cloud). We recently made a herculean effort to have our marketplace publisher be "azure-gaming"... let me give it some thought, as my knee jerk reaction is I would prefer "azure-gaming" be the public facing declaration in the bicep module.

**Comment by alex-frankel** [comment]
Makes sense. I guess I was thinking for anyone using bicep, then azure is implied. I get that outside of the context of bicep, this is more ambiguous. 

I am good either way. If you have a strong preference for `azure-gaming` then let's keep it.
