### ISSUE TITLE
[AVM Module Issue]: Synapse Datalake Storage RA

### ISSUE THREAD

**Issue by Jackmt9** [Azure/bicep-registry-modules#1211]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/synapse/workspace

### Description

Considering that a default datalake storage account needs to exist before the Synapse Workspace is deployed, it would be very convenient if this module can handle the appropriate role assignment to the storage account after the creation of the workspace. (or at least have a boolean parameter to optionally do this)

**Comment by Jackmt9** [comment]
likewise with function app

**Comment by Jackmt9** [comment]
linking #937

**Comment by AlexanderSehr** [comment]
Please note that this module currently has no owner. As a result, triaging the change may take longer than usual.

**Comment by elanzel** [comment]
Hi @Jackmt9, since there's no owner for this module, but i've contributed to migrate it, i'll try to support in best-effort for this issue. Let me validate your requirement and i'll be back to you

**Comment by elanzel** [comment]
@AlexanderSehr, @Jackmt9 referring also to the issue #937 , we have the pattern for the resource role assignment now available https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/authorization/resource-role-assignment .
Wouldn't be the right option to use that call: module resourceRoleAssignment 'br/public:avm/ptn/authorization/resource-role-assignment:<version>' ?

**Comment by AlexanderSehr** [comment]
Hey @elanzel, 
there are basically two options I'm seeing here. Either
- Create the role assignment in the scope of the storage account as part of the module if the user wants that, OR
- Push back and have the user rather take care of that.

Now I don't know the resource well enough to make an informed call. From the tests it appears no role assignment is require / the deployment doesn't fail if you just provide the required `defaultDataLakeStorageAccountResourceId` to the workspace without a role assignment (would be great @Jackmt9 if you could elaborate what permissions are required for what).
Assuming that, for example, the workspace's identity needs permission on the storage account, then one could argue that in case of a user assigned identity, this role assignment should be done before the module is deployed (as described above), and only in case of the system-assigned identity, a role assignment in the module may make sense. But for that I'd need @Jackmt9 to provide more information.

I guess at the end of the day, the workspace does not fail if no permissions are set outright and one could set the permissions for the storage account of parameter `defaultDataLakeStorageAccountResourceId` after the module deployment, - and it's just a matter of convenience if the module could do this implicitly.

**Comment by elanzel** [comment]
This feature should be implemented as a pattern, not implicitly in the module
