### ISSUE TITLE
[AVM Module Issue]: DF Integration Runtime Description

### ISSUE THREAD

**Issue by Jackmt9** [Azure/bicep-registry-modules#1254]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/data-factory/factory

### Description

DF is missing the description parameter for integration runtime. Can we please add it, as I have many IR's and setting a description would be a great help. 
See [here](https://learn.microsoft.com/en-us/azure/templates/microsoft.datafactory/factories/integrationruntimes?pivots=deployment-language-bicep#resource-format)

**Comment by clintgrove** [comment]
Hi @Jackmt9  I am looking into making a fix for this. Give us a few days to sort it out
