### ISSUE TITLE
[AVM Module Issue]: Disable or restrict public network access for Cosmos DB account support

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/bicep-registry-modules#1255]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/document-db/database-account

### (Optional) Module Version

0.3.0

### Description

The module does not currently support disabling or restricting public network access.

**Comment by bryansan-msft** [comment]
Hello hello, I will have a look at it as soon as I can
