### ISSUE TITLE
[AVM Module Issue]: Mount File Share

### ISSUE THREAD

**Issue by Jackmt9** [Azure/bicep-registry-modules#1278]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### Description

Support Mounting of File Share

// Mount FileShare
resource storageSetting 'Microsoft.Web/sites/config@2021-01-15' = {
  name: 'azurestorageaccounts'
  parent: webApp
  properties: {
    '${shareName}': {
      type: 'AzureFiles'
      shareName: shareName
      mountPath: mountPath
      accountName: storageAccount.name
      accessKey: storageAccount.listKeys().keys[0].value
    }
  }
}

**Comment by tsc-buddy** [comment]
Hey! Thanks for opening the issue. We will look to investigate this WC 8 April.

**Comment by tsc-buddy** [comment]
@Jackmt9 Just double checked some testing regarding this. You should be able to achieve this by providing the properties under SiteConfig as below. Also add the app setting there too. 

Let us know how you, ill keep this open for a little while longer.

![image](https://github.com/Azure/bicep-registry-modules/assets/38195643/9ef7bac0-c0b0-45e1-90be-e82b97d8a656)
