### ISSUE TITLE
[AVM Question/Feedback]: Configuration Assignments

### ISSUE THREAD

**Issue by Gijsreyn** [Azure/bicep-registry-modules#1279]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

When getting started with Azure Update Manager, the maintenance configuration module is available. However, the configuration assignment module is not available. 

Do we have any information on when configuration assignment will be added? I also couldn’t locate it in the CARML repository. 

Cheers!

**Comment by AlexanderSehr** [comment]
Hey @Gijsreyn,
to request a missing module, I'd suggest to open an issue for it in the [AVM](https://github.com/Azure/Azure-Verified-Modules/issues/new?assignees=&labels=Type%3A+New+Module+Proposal+%3Abulb%3A%2CNeeds%3A+Triage+%3Amag%3A&projects=Azure%2F529&template=module_proposal.yml&title=%5BModule+Proposal%5D%3A+%60MODULE_NAME_BETWEEN_BACKTICKS%60) repository :)

Once created, it can be triaged, a module owner searched and once found, implemented.

**Comment by Gijsreyn** [comment]
@AlexanderSehr Done! I guess this one can be closed then!

**Comment by AlexanderSehr** [comment]
Closing as moved to AVM issue https://github.com/Azure/Azure-Verified-Modules/issues/758 . Thanks @Gijsreyn
