### ISSUE TITLE
[Module Proposal]: Game Developer Virtual Machine 

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#129]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We would like to simplify our template [here](https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/azure-gamedev/gamedev-vm) by using a Bicep module. We will then go back and replace the Template with a direct call to the public module.

### Module path

modules/azure-gaming/game-dev-vm

### Describe the module

This Bicep module makes it easier for users to leverage the Game Dev Virtual Machine on a VM via ARM.
https://docs.microsoft.com/en-us/gaming/azure/game-dev-virtual-machine/

**Comment by alex-frankel** [comment]
Left a comment on the other proposal. What do you think about changing the directory to `gaming` instead of `azure-gaming` since that seems implied?
