### ISSUE TITLE
[AVM Module Issue]: nat-gateway claims missing PIP when called in a module multiple times

### ISSUE THREAD

**Issue by h2floh** [Azure/bicep-registry-modules#1290]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/nat-gateway

### (Optional) Module Version

1.0.4

### Description

👋 I came across this when playing around with Hub Spokes configurations. I could isolate the issue and it is reproducible [here](https://github.com/h2floh/azure-verified-modules/tree/h2floh/avm-nat-gateway-bug/avm-nat-gateway).

Isolated scenario:

- Want to create a PIP and a NAT Gateway for several regions
- Created a bicep module using avm-nat-gateway module
- Call the custom module for two regions (sweden, poland) from main bicep file

Error:

- There is a race condition as well, depending on wether poland or sweden nat deployment finishes first, the other nat gateway fails claiming that it can't find the PIP for the **other** region
- Checking deployment logs, the input parameters are correct sweden PIP for sweden NAT and poland PIP for poland NAT

```
/subscriptions//resourceGroups/rg-avm-nat-gateway-bug/providers/Microsoft.Resources/deployments/pvk5ah5axffra-nat-poland","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"NotFound","message":"Resource /subscriptions//resourceGroups/RG-AVM-NAT-GATEWAY-BUG/providers/Microsoft.Network/publicIPAddresses/PIP-NAT-SWEDEN not found.
```

That is why I assume it could be some bug within the nat-gateway module when resolving the PIP input parameters.

Thanks for having a look ❤️ 

![image](https://github.com/Azure/bicep-registry-modules/assets/29010283/ccd85518-f229-4ad3-a3f4-e6c606b750c8)
![image](https://github.com/Azure/bicep-registry-modules/assets/29010283/ac10c4aa-990a-4566-a7cf-4b097194e4ac)

### (Optional) Correlation Id

c9afebf5-59e5-4368-a3cd-a9e787145bf3

**Comment by AlexanderSehr** [comment]
Hey @fabmas, please take a look as soon as you can to sort this it if we can reproduce the behavior.
@h2floh thanks for raising the issue (:

**Comment by fabmas** [comment]
@h2floh can you consider the following workaround in the main.bicep file?

module hubSpokePoland './hubSpoke.bicep' = {
  **dependsOn: [
    hubSpokeSweden
  ]**

**Comment by h2floh** [comment]
Hey @fabmas completely missed to try that out 🤦 I'll check if it will work but I guess you already verified that it does. Thanks for checking in. Can you share some details on why that is, I didn't had time to drill into the code.

**Comment by fabmas** [comment]
Hello, @h2floh! The issue stemmed from the formattedPublicIpResourceIds module, which lacked a unique deployment name. I’ve created a Pull Request to address this issue. Thank you once again for identifying it

**Comment by h2floh** [comment]
Thanks @fabmas and @AlexanderSehr !
