### ISSUE TITLE
[AVM Module Issue]: Database account missing support disallowing local authentication

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/bicep-registry-modules#1291]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/document-db/database-account

### (Optional) Module Version

0.3.0

### Description

This module is currently missing support for two important features.

In one of the examples disabling local authentication is passed to the module, but it is not supported.

1. It should be possible to specify if the account should disallow the execution of non-data operations with keys.
2. It should be possible to specify if the account disallow local authentication methods so the account exclusively require Entra ID identities for authentication.

**Comment by bryansan-msft** [comment]
Hey @BenjaminEngeset, I have implemented this feature last week. Have a look at the new version. I believe it is 0.3.1

#1228

**Comment by BenjaminEngeset** [comment]
> Hey @BenjaminEngeset, I have implemented this feature last week. Have a look at the new version. I believe it is 0.3.1
> 
> #1228

Great news! I didn't see that a newer version had been merged.

Would you mind adding the support for `It should be possible to specify if the account should disallow the execution of non-data operations with keys.`

This is done by setting `properties.disableKeyBasedMetadataWriteAccess` to true.

In some cases disabling local authentication fully would not work with SDKs.

**Comment by bryansan-msft** [comment]
> > Hey @BenjaminEngeset, I have implemented this feature last week. Have a look at the new version. I believe it is 0.3.1
> > #1228
> 
> Great news! I didn't see that a newer version had been merged.
> 
> Would you mind adding the support for `It should be possible to specify if the account should disallow the execution of non-data operations with keys.`
> 
> This is done by setting `properties.disableKeyBasedMetadataWriteAccess` to true.
> 
> In some cases disabling local authentication fully would not work with SDKs.

I'm tracking that here #1233. 

Just out of curiosity. What do you mean by "In some cases disabling local authentication fully would not work with SDKs." Could you provide an example?

**Comment by BenjaminEngeset** [comment]
> > > Hey @BenjaminEngeset, I have implemented this feature last week. Have a look at the new version. I believe it is 0.3.1
> > > #1228
> > 
> > 
> > Great news! I didn't see that a newer version had been merged.
> > Would you mind adding the support for `It should be possible to specify if the account should disallow the execution of non-data operations with keys.`
> > This is done by setting `properties.disableKeyBasedMetadataWriteAccess` to true.
> > In some cases disabling local authentication fully would not work with SDKs.
> 
> I'm tracking that here #1233.
> 
> Just out of curiosity. What do you mean by "In some cases disabling local authentication fully would not work with SDKs." Could you provide an example?

It's only the API for NoSQL that supports this feature on the data-plane level, and it's only specific SDKs within the API that supports it from my understanding.

https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#which-azure-cosmos-db-apis-support-data-plane-role-based-access-control

https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#which-sdks-in-azure-cosmos-db-api-for-nosql-support-role-based-access-control
