### ISSUE TITLE
[AVM Module Issue]: Support PostgreSQL 16 in PostgreSQL Flexible Server module

### ISSUE THREAD

**Issue by dslatkin** [Azure/bicep-registry-modules#1310]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/db-for-postgre-sql/flexible-server

### Description

Right now the PostgreSQL Flexible Server module's `version` param only allows up to version 15, despite 16 being [generally available](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-supported-versions) in all Azure versions.

Also, **thank you** for picking up and maintaining this module! 🙏 😄 I saw it was orphaned until recently.

**Comment by josearper** [comment]
Thanks @AlexanderSehr, I will be adding that in the future.

**Comment by AlexanderSehr** [comment]
Great. Will remove the Triage tag then :)

**Comment by josearper** [comment]
Looking into this one now.

**Comment by DanGiffen** [comment]
Hi Nate,

2nd this one, also commented on the other issue https://github.com/Azure/bicep-registry-modules/issues/2203.

**Comment by DanGiffen** [comment]
Thanks @AlexanderSehr. Just for info, not sure if it's a timing or sync thing, but the versioning is not tying up. vs code intellisense only shows tags up to 0.1.6 as does the module index https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/ although this reports correctly https://[mcr.microsoft.com/v2/bicep/avm/res/db-for-postgre-sql/flexible-server/tags/list](https://mcr.microsoft.com/v2/bicep/avm/res/db-for-postgre-sql/flexible-server/tags/list). You can't see the tag list in the browser on github as they're too long but if I clone the repo I can list them. `\bicep-registry-modules\avm\res\db-for-postgre-sql\flexible-server [main]> git tag -l "avm/res/db-for-postgre-sql/flexible-server/*"`. My deployment is working now btw, much appreciated 👍

**Comment by AlexanderSehr** [comment]
> nfo, not sure if it's a timing or sync thin

Hey @DanGiffen,
'sadly' this is expected, yet only a caching issue. The VSCode caches the data und only updates it in a few cases (e.g. after restarting VSCode). I'm not entirely sure 'when' it happens, but the references will already resolve. It's really only the lists in VSCode that may not show it for a period of time.

**Comment by DanGiffen** [comment]
Ah ok yep, no worries cheers @AlexanderSehr
