### ISSUE TITLE
[AVM Module Issue]: Container registry module not taking SKU for quarantine policy in consideration

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/bicep-registry-modules#1316]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/container-registry/registry

### (Optional) Module Version

0.1.1

### Description

The quarantine policy requires the `Premium` SKU. The module should take this into consideration as the output emitted with it enabled now will just be `SkuNotSupported","message":"The SKU Basic is not supported."`

**Comment by AlexanderSehr** [comment]
Hey @JPEasier, could you please respond to the issue :)

**Comment by JPEasier** [comment]
Hi @BenjaminEngeset, thank you for your input.
realistically, I won't be able to implement the feature until May.

**Comment by AlexanderSehr** [comment]
Maybe somebody else will implement the contribution in the meantime. A review should be easier to handle. 🤞

**Comment by rodney-almeida** [comment]
@JPEasier @AlexanderSehr 
Is this all that is required for this fix?
https://github.com/Azure/bicep-registry-modules/pull/1967

**Comment by AlexanderSehr** [comment]
> @JPEasier @AlexanderSehr Is this all that is required for this fix? #1967

Doesn't look too bad :) @JPEasier, please take a look when you have a chance. Afterall, you're the expert 😉
