### ISSUE TITLE
[AVM Module Issue]: App Configuration does not output endpoint

### ISSUE THREAD

**Issue by adrianhall** [Azure/bicep-registry-modules#1323]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app-configuration/configuration-store

### (Optional) Module Version

0.1.1

### Description

Many operations (including, for example, creating a new app configuration settings) require the "endpoint".  Output the endpoint property of the app configuration resource.

(Inbound - will do a PR for this)

**Comment by matebarabas** [comment]
This module is currently orphaned: https://github.com/Azure/Azure-Verified-Modules/issues/731

**Comment by Menghua1** [comment]
@jongio for notification.

**Comment by v-xuto** [comment]
@adrianhall We have created a PR for this issue. Please review.
- PR link: https://github.com/Azure/bicep-registry-modules/pull/2586
