### ISSUE TITLE
[Feedback]: SQL Server module documentation inaccurate

### ISSUE THREAD

**Issue by teemukom** [Azure/bicep-registry-modules#1324]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/sql/server

Usage examples 3 and 6 have a database parameter '**capacity**' which should be skuCapacity as described in the https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/sql/server/database/main.bicep

**Comment by matebarabas** [comment]
@bryansan-msft, can you please help @teemukom with this issue? Thank you!
