### ISSUE TITLE
brm validate does not detect indirect module tests

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#133]
I'm authoring some complex tests for a new module. I've therefore split the tests out into their own files, and referenced them from main.test.bicep

However this does seem to cause the `brm validate` an issue

> dapr-containerapps-environment\test\main.test.bicep" is invalid. Could not find tests in the file. Please make sure to add at least one module referencing the main Bicep file.

![image](https://user-images.githubusercontent.com/17914476/182915743-b5cd2e32-d8d6-4f34-b07d-b1585e34e67b.png)

**Comment by shenglol** [comment]
Do you think if this still needed if we add the support for running multiple test files?

**Comment by Gordonby** [comment]
> Do you think if this still needed if we add the support for running multiple test files?

Nope, that'd do it.
