### ISSUE TITLE
[AVM Module Issue]: No ipRestriction option for Azure Functions

### ISSUE THREAD

**Issue by Ralph101** [Azure/bicep-registry-modules#1342]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### (Optional) Module Version

0.3.1

### Description

I want to disable public inbound access only allowing DevOps connection. But it's not permitted to add ipRestriction in the AVM Module

**Comment by tsc-buddy** [comment]
Hey! Thanks for opening the issue. We will look to investigate this WC 8 April.

**Comment by tsc-buddy** [comment]
Hey @Ralph101 - You should be able to achieve this using the following structure (see this [link ](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites?pivots=deployment-language-bicep)also). 

`module site 'br/public:avm/res/web/site:0.3.1' = {
  name: 'functionApp'
  params: {
    // Required parameters
    kind: 'functionapp'
    name: ....
    serverFarmResourceId: ....
    // Non-required parameters
    location: ....
    siteConfig: {
      alwaysOn: true
      ipSecurityRestrictions: [
        {
          ipAddress: '123.123.123.123/32'
          action: 'Allow'
          priority: 202
          name: 'AllowMYPIP'
          description: 'Allow strict access'
        }
      ]
    }
  }
}`

Let us know how you go, I'll keep this open for a little longer.

**Comment by Ralph101** [comment]
Only thing I'm missing is when you want to use a  service. For example DevOps

**Comment by tsc-buddy** [comment]
You can use any of the following to build out your configuration, I would suggest using tag in your rule for ADO. 

ipSecurityRestrictions: [
        {
          action: 'string'
          description: 'string'
          headers: {}
          ipAddress: 'string'
          name: 'string'
          priority: int
          subnetMask: 'string'
          subnetTrafficTag: int
          tag: 'string'
          vnetSubnetResourceId: 'string'
          vnetTrafficTag: int
        }
