### ISSUE TITLE
[AVM Module Issue]: Create custom NIC without the need of nicSuffix

### ISSUE THREAD

**Issue by Ralph101** [Azure/bicep-registry-modules#1345]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/compute/virtual-machine

### Description

Is it possible to create the NIC name with a custom name? Without the need of the nicSuffix?

**Comment by AlexanderSehr** [comment]
Hey @Ralph101, that sounds reasonable (i.e., to only apply the suffix when falling back to a default). @rahalan, can you take a look?

**Comment by rahalan** [comment]
@Ralph101 @AlexanderSehr sounds good, I will add this.

**Comment by rahalan** [comment]
Will be included in #1515
