### ISSUE TITLE
[AVM Module Issue]: Cannot create a storage account with public network access

### ISSUE THREAD

**Issue by sebassem** [Azure/bicep-registry-modules#1346]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### (Optional) Module Version

0.8.0

### Description

I'm trying the below code where I expect a storage account with public access but I always get it configured as "Enabled from selected virtual networks and IP addresses"

`module storageAccount 'br/public:avm/res/storage/storage-account:0.8.0' = {
  name: 'storageAccount'
  params: {
    name: 'stgsbfinops9823'
    location:'eastus'
    publicNetworkAccess: 'Enabled'
    allowBlobPublicAccess: false
  }
}
`

**Comment by AlexanderSehr** [comment]
Hey @sebassem,
if I'm not mistaken this comes down to the 'secure' default for the firewall settings:
https://github.com/Azure/bicep-registry-modules/blob/e91b62bfb6f6c1921adf3b53b7cc95f73542ccd8/avm/res/storage/storage-account/main.bicep#L72-L75
cc: @fblix

**Comment by matebarabas** [comment]
Please note that @fblix is OOF until April 2nd. I've pinged him internally and asked him to pick this up when he's back.

**Comment by pamelafox** [comment]
I just spent an hour trying to figure out why publicNetworkAccess wasn't working. Do you think a note could be added to https://github.com/Azure/bicep-registry-modules/blob/avm/res/storage/storage-account/0.9.1/avm/res/storage/storage-account/README.md#parameter-publicnetworkaccess with the recommended networkAcls setting?

**Comment by AlexanderSehr** [comment]
Hey @pamelafox,
I'm sorry to hear, and certainly. The best path of action would be to open a module-issue for the Storage Account module [here](https://github.com/Azure/bicep-registry-modules/issues/new?assignees=&labels=Type%3A+AVM+%3Aa%3A+%3Av%3A+%3Am%3A%2CNeeds%3A+Triage+%3Amag%3A&projects=Azure%2F566&template=avm_module_issue.yml&title=%5BAVM+Module+Issue%5D%3A+). This will automatically be assigned to the module owner(s) that can then triage and work on the issue. You're of course also more than welcome to contribute the note yourself, if you're willing to share your insights :)
