### ISSUE TITLE
[AVM Module Issue]: Storage account changeFeedRetentionInDays minValue should be set to 1 to avoid Warning BCP329

### ISSUE THREAD

**Issue by brazarb** [Azure/bicep-registry-modules#1385]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/storage/storage-account

### Description

https://github.com/Azure/bicep-registry-modules/blob/e53c0369ea43e08229ff8992874fb4965f421b08/avm/res/storage/storage-account/blob-service/main.bicep#L15

![image](https://github.com/Azure/bicep-registry-modules/assets/111027880/ede1bc0e-6a6c-45c5-81b6-5b17ce56e3a1)

**Comment by matebarabas** [comment]
Hi @brazarb, thank you for submitting this issue! Please note that owner of this module (@fblix) is currently OOF until April 2nd. We've raised this issue to his attention internally and asked him to pick this up when he's back. Thank you for your patience!
