### ISSUE TITLE
[AVM Question/Feedback]: Consumption of child modules?

### ISSUE THREAD

**Issue by joostm1** [Azure/bicep-registry-modules#1390]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Are there any ideas around the ability to consume child modules?

I read [here](https://azure.github.io/Azure-Verified-Modules/faq/#can-i-call-a-bicep-child-module-directly-eg-can-i-update-or-add-a-secret-in-an-existing-key-vault-or-a-route-in-an-existing-route-table) in the FAQ that currently this is not possible.

I would love to see the ability to use child modules. 
Why?

Most of my deployments are grouped in modules per workload with a resource group scope. I think this is fairly common.

Whenever a workload needs to deploy something in **another scope**, say a container in a 'central storage  account' or a role assignment somewhere , I need to add a separate module in my source tree just to add this child resource.

For example: in my deployment of appXYZ.bicep to rg-appXYZ, I need to add a container to a central storage account in centralRG. 
For that I need to do this:
```
appXYZ.bicep:
// add a container to the central storage account
module blobcontainer '../modules/blobcontainer.bicep' = {
  name: workloadName
  scope: centralRG
  param: {
    .....
  }
```
So I need to create the blobcontainer.bicep module just to change the deployment scope to another resource group.
Instead of creating the module, I would love the ability to do something like this:
```
appXYZ.bicep:
// add a container to the central storage account
module blobcontainer 'br/public:avm/res/storage/storage-account:0.8.0/blobservices/container' = {
  name: workloadName
  scope: centralRG
  param: {
    ......
  }
```
Appreciate any thoughts on this!

**Comment by matebarabas** [comment]
Hi @joostm1, thanks for opening this issue.

Please note that this topic was recently discussed in the following issues:
- https://github.com/Azure/Azure-Verified-Modules/issues/578
- https://github.com/Azure/Azure-Verified-Modules/issues/747

Please let us know if you have any additional questions. 

CC: @AlexanderSehr

**Comment by AlexanderSehr** [comment]
Thanks for tagging me @matebarabas. Yes I'd recommend to take a look at the linked issues. I would have loved to carry that functionality (we already implement in the [CARML CI](https://aka.ms/carml)) over to the Public-Bicep-Registry, but unfortunately it's technically much more complex. However, the modules are still setup in a way that they could be published - and there is an intend to ensure compatiblity withthe CARML CI once the migration of the modules concluded. So at least for inner-source purposes we could already ensure that child-modules would be published alongside their parent.
When we'd be able to do the same in the public registry is unclear as of this point. But as there is (unsuprisingly) definitely demand, I'm sure we'll get there.

**Comment by joostm1** [comment]
Thanks for sharing your insights @matebarabas @AlexanderSehr, much appreciated.
My summary is that this won't happen any time soon. Glad to see you recognize the need for this though.

**Comment by timdhaeyer** [comment]
This is the only thing holding us back from migrating away from CARML. So would be a nice feature. We have a big environment to setup, lot's of different parts that depend on each-other. So only having the "root" modules isn't going to cut it for us.

**Comment by AlexanderSehr** [comment]
> This is the only thing holding us back from migrating away from CARML. So would be a nice feature. We have a big environment to setup, lot's of different parts that depend on each-other. So only having the "root" modules isn't going to cut it for us.

Could not agree more...
