### ISSUE TITLE
[AVM Module Issue]: recent api-version of Event-grid required for key-vault secret notification

### ISSUE THREAD

**Issue by dewolfs** [Azure/bicep-registry-modules#1405]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/event-grid/topic

### (Optional) Module Version

0.2.3

### Description

Hi,

I want to setup a notification channel via an Azure action group which is triggered via Event Grid system topic with an event Subscription on Azure KeyVault looking for the event of a secret that will expire.

More info here: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/enable-automatic-secret-rotation-by-triggering-azure-function/ba-p/4055618

When I'm using the existing Event-grid module, I get the following deployment error:

`Message
Invalid event subscription request: The specified endpoint type is not supported with this API version.`

If I update the api version from **2021-12-01** to **2023-12-15-preview**, I can successfully setup the above solution.
Event-grid bicep docs api versions: https://learn.microsoft.com/en-us/azure/templates/microsoft.eventgrid/systemtopics?pivots=deployment-language-bicep

Changes to api version were made in the files:

- event-grid\system-topic\system-topic\main.bicep
- event-grid\system-topic\system-topic\event-subscription\main.bicep

Can you update the event-grid module to use the latest available api-version for this resource?

**Comment by fabmas** [comment]
@dewolfs thanks, I'll update the module asap with the latest api-version...

**Comment by dewolfs** [comment]
@fabmas thank you for updating the module!
Unfortunately I'm still getting the same error.

After checking the updated module, I could find back that the API version used in the lookup for the existing system topic wasn't updated.

https://github.com/Azure/bicep-registry-modules/blob/15e51b3267d92227cce975ee3389ecd292f6fddc/avm/res/event-grid/system-topic/event-subscription/main.bicep#L48
