### ISSUE TITLE
[AVM Module Issue]: web/sites not allowing kind app,linux

### ISSUE THREAD

**Issue by isehuetdk** [Azure/bicep-registry-modules#1408]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/site

### (Optional) Module Version

0.3.1

### Description

The module does not allow value 'app,linux' even though code and documentation states it is supported.
Seems an issue on all published versions.

Local bicep cache has been cleared and issue is reproducable.

https://github.com/Azure/bicep-registry-modules/blob/45b846ef8784d9c135a19be795227c6b3c2fcc98/avm/res/web/site/main.bicep#L17C2-L17C31

**Error:** 
Error BCP036: The property "kind" expected a value of type "'app' | 'functionapp' | 'functionapp,linux' | 'functionapp,workflowapp' | 'functionapp,workflowapp,linux'" but the provided value is of type "'app' | 'app,linux' | 'functionapp' | 'functionapp,linux' | 'functionapp,workflowapp' | 'functionapp,workflowapp,linux'".

![image](https://github.com/Azure/bicep-registry-modules/assets/57175079/bf5e09f3-5075-4c7f-b7ad-fa0d444c6f42)

Expected behavior:
Parameter allows value 'app/linux' value so Linux Web Apps can be deployed.

**Comment by tsc-buddy** [comment]
Hey @isehuetdk Thanks for logging this. We shall look into it WC 15 April.

**Comment by SvenAelterman** [comment]
While this issue is being addressed, please also add supported for `app,linux,container`.

**Comment by tsc-buddy** [comment]
@isehuetdk can you give this a test with version. Let me know how you go.
![image](https://github.com/Azure/bicep-registry-modules/assets/38195643/0eed64a8-b2c2-45f3-ab63-caf44990e05b)

**Comment by tsc-buddy** [comment]
Interesting, with Example 6, so long as the ASP has the `reserved: true` property set, (which will make it a Linux ASP) the App Service deploys as Linux. I will look to update the documentation to highlight this.

**Comment by isehuetdk** [comment]
That is set, and I was also confused that using the ASP (showing kind Linux both in template & portal), I deploy the App Service with kind `'app,linux'`, it shows the correct kind in the template (when clicking on Export Template) but in the portal it shows OS type Windows... Don't know if it was a UI clitch (happened though on multiple App Services). So redeployed with the netFrameworkVersion specified, which resulted in correct result

**Comment by tsc-buddy** [comment]
@isehuetdk - I cant for the life of me reproduce this one!! I have seen UI bugs this week where on the overview it looks shows Windows, but when i check Kudu, its in Bash. But not had to set the property mentioned to get a Linux ASP.
