### ISSUE TITLE
[Bug Report]: Virtual Network uses a preview api and there are more recent versions available

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#141]
### Module path

/modules/network/virtual-network

### Bicep version

1.0

### Describe the bug

Microsoft.Authorization/roleAssignments uses a preview version ( 2021-04-01-preview ) and there are more recent versions available.

### To reproduce

https://github.com/Azure/azure-quickstart-templates/pull/12782

### Code snippet

```Bicep
see PR
```

### Relevant log output

```Shell
##[error]        Microsoft.Authorization/roleAssignments uses a preview version ( 2021-04-01-preview ) and there are more recent versions available.
        Valid Api Versions:
        2022-04-01
        2022-04-01
        2022-01-01-preview
        2021-04-01-preview
        2020-10-01-preview
```

**Comment by shenglol** [comment]
Closed by https://github.com/Azure/bicep-registry-modules/pull/142.
