### ISSUE TITLE
[AVM Module Issue]: Private DNS Zone virtualNetworkLink description typo

### ISSUE THREAD

**Issue by colincmac** [Azure/bicep-registry-modules#1429]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/private-dns-zone

### (Optional) Module Version

0.2.4

### Description

The module's description & documentation of the virtualNetworkLinks parameter indicates it should be an array objects containing properties 'vnetResourceId' and 'registrationEnabled'. The corresponding parameter is actually named `virtualNetworkResourceId`, not `vnetResourceId`

[vnetResourceId](https://github.com/Azure/bicep-registry-modules/blob/b1ea42b883c0d6de54797342fe85634ae3b4d5b2/avm/res/network/private-dns-zone/virtual-network-link/main.bicep#L21)

https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/network/private-dns-zone#parameter-virtualnetworklinks

I can submit a PR, but wanted to make sure this isn't an issue with automation/doc-generation, rather than a typo.

**Comment by eriqua** [comment]
Good catch @colincmac and you are right. Feel free to raise a PR if you have availability, or to go the extra-mile and define a [user-defined type](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/user-defined-data-types) for the virtualNetworkLink 😉, if @ChrisSidebotham agrees.

**Comment by ChrisSidebotham** [comment]
Looking into this now
