### ISSUE TITLE
[AVM Module Issue]: compute/virtual-machine and name of OSDisk and DataDisk partly hardcoded in main.bicep

### ISSUE THREAD

**Issue by aavdberg** [Azure/bicep-registry-modules#1436]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine

### Description

When I want to use the module in existing pipeline and with existing resources i have the problem with OSDisk and Datadisk name are hardcoded in the bicep file.

![image](https://github.com/Azure/bicep-registry-modules/assets/22030609/862c0918-19db-493d-ad17-f07258ae6118)

and they are not to be changed on existing resources.

So you have to have the possibility to configure them with parameters.

**Comment by johnlokerse** [comment]
@AlexanderSehr @rahalan Can you assign this issue to me? I can pick this up.

**Comment by AlexanderSehr** [comment]
Hey @johnlokerse, done - thank you very much :)

cc: @rahalan

**Comment by rahalan** [comment]
@johnlokerse please see PR #1515 . There I did something similar for the NIC name.

**Comment by johnlokerse** [comment]
Opened PR #1517
