### ISSUE TITLE
[AVM Module Issue]: Enable Auto-Shutdown in VM module

### ISSUE THREAD

**Issue by Ralph101** [Azure/bicep-registry-modules#1437]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### Description

Is it possible to add the auto-shutdown option in the VM module?

**Comment by AlexanderSehr** [comment]
If I'm not mistaken, this would require an implementation of the DevTestLabs resource, right? @Ralph101

**Comment by Ralph101** [comment]
True example can be found below:

```bicep
var vmname = 'vm001'

resource autoShutdown 'Microsoft.DevTestLab/schedules@2018-09-15' = {
  name: 'shutdown-computevm-${vmname}'
  properties: {
    timeZoneId: 'W. Europe Standard Time'
    status: 'Enabled'
    notificationSettings: {
      status: 'Disabled'
    }
    dailyRecurrence: {
      time: '19:00:00'
    }
  }
}
```

**Comment by rahalan** [comment]
@Ralph101, thanks, will look into it.
