### ISSUE TITLE
[AVM Module Issue]: servicebus/namespace queue and topic name parameters minLength is wrong

### ISSUE THREAD

**Issue by marcusrangell** [Azure/bicep-registry-modules#1438]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/service-bus/namespace

### (Optional) Module Version

0.3.0

### Description

The current version of the queue and topic modules specify the name parameter as
```bicep
@minLength(6)
@maxLength(50)
param name string
```

Specifying a queue or topic name with 1-5 characters will result in the following error message:
> "details":[{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The provided value for the template parameter 'name' is not valid. Length of the value should be greater than or equal to '6'.

However, according to the [Naming rules and restrictions for Azure resources](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftservicebus), the min and max length for the namespaces / queues and namespaces / topics is 1-260 chars.

Currently, the AVM module throws an error if an individual queue or topic name is below 6 characters in length, even though it should be deployable. Changing the minLength for the name parameter in the queue/topic modules to 1 and testing with a single character name deploys fine. The same for manually creating a queue/topic with a single character name in the portal, via the REST API or using the standard bicep modules (not AVM).

Also, the maxLength for the same parameters could perhaps be increased as well, as long as the total name length is below 260 chars.

**Comment by ChrisSidebotham** [comment]
@marcusrangell - Good spot I will get this updated in the next version sometime early next week. I believe the name limits have increased since the modules initial creation back in CARML
