### ISSUE TITLE
[AVM Module Issue]: Unable to accept EULA for Azure VM Marketplace Images

### ISSUE THREAD

**Issue by Ralph101** [Azure/bicep-registry-modules#1439]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

Other, as defined below...

### Description

I want to use a specific CIS hardend image from the marketplace but I'm unable to agree the EULA. Is it possible to accept the EULA by default if you are using a image from the Azure Marketplace

**Comment by AlexanderSehr** [comment]
Hey @Ralph101, is this issue tied to a specific module in this repository? If not I'm not sure this is a good location for the question.
Given the proximity to the VM, would you happen to have an idea @rahalan?

**Comment by Ralph101** [comment]
I think it would be a nice feature if you want to use images from the Azure Marketplace and by default it will accept the EULA. For example I want to use the CIS hardend Windows Server image from the marketplace but with the current setup it's impossible.

**Comment by AlexanderSehr** [comment]
Can't argue with that. All I'm saying is that if we'd want to tie it to a module I guess that would mean to somehow accept the EULA for an image in the solution using, for example, a deployment script that runs before a VM deployment. This deployment script could run a logic similar to how shown [here](https://medium.com/@cmendibl3/accepting-azure-marketplace-terms-with-azure-cli-a6597743122a).
Just in case it wasn't obvious, we're no Product Group and would hence need to rely on the same feature said as anybody else (as opposed to implement e.g., a custom API endpoint). 

Happy to look into this deeper, I'm just not sure I'll be able to give you the answer you're hoping for 😄

**Comment by matebarabas** [comment]
@rahalan, please have a look at this one when you have a chance.

**Comment by rahalan** [comment]
@Ralph101 @AlexanderSehr I had a similar problem some years ago. We ran the following command in the pipeline as PS task:
Get-AzMarketplaceTerms -Publisher checkpoint -Product check-point-cg-r8030 -Name sg-ngtx | Set-AzMarketplaceTerms -Accept
