### ISSUE TITLE
[AVM Module Issue]: Automation account credentials

### ISSUE THREAD

**Issue by jwoernerasi** [Azure/bicep-registry-modules#1443]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/automation/automation-account

### Description

It doesn't seem like adding credential resources to an Automation Account is supported by the AVM. I'm having an extremely difficult time determining how to combin usage of the AA AVM with a manual declaration of a credential resource. Wondering if it's even possible.

**Comment by elanzel** [comment]
Hi @jwoernerasi thank you for contacting us. 
I confirm credentials is a feature not yet available for this module. We'll are adding this issue to the new features requests.
Thank you, 
best regards

**Comment by elanzel** [comment]
Added feature in my fork. Testing before opening the PR
