### ISSUE TITLE
[AVM Module Issue]: Runbook module's PowerShell version

### ISSUE THREAD

**Issue by jwoernerasi** [Azure/bicep-registry-modules#1445]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/automation/automation-account

### Description

The runbook module, when configured for PowerShell, defaults to 5.1 without an option to specify. This is not changeable within the portal, making this type of AVM deployment limited in usefulness.

**Comment by elanzel** [comment]
Hi @jwoernerasi can you confirm that what you need is to set the runtime version as showed here
https://learn.microsoft.com/en-us/azure/templates/microsoft.automation/automationaccounts/runtimeenvironments?pivots=deployment-language-bicep ?
If you confirm this is a new feature that we'll consider to add. 
Thank you

**Comment by jwoernerasi** [comment]
Yes, that’s exactly right. A PowerShell 5.1 environment is put in place that can’t be altered as far as I can tell.

**Comment by elanzel** [comment]
Thank you @jwoernerasi , adding this to the new features' request. We'll plan this in a compatible time with the other requests.
If you want to contribute directly, it's also possible for you to add the feature and i'll do the review for you. 
Thank you again, best regards

**Comment by jwoernerasi** [comment]
After doing a little poking around it seems the root cause here is that the Runbook ARM API version in use by the AVM is older than most recent, and therefore doesn’t support the additional Language property settings that were added. The solution here isn’t to “add support to configure the language for the runbook” but to support a newer API version.
