### ISSUE TITLE
[AVM Module Issue]: extensionDependencyAgentConfig in virtual-machine module missing enableAMA in Settings

### ISSUE THREAD

**Issue by PieterbasNagengast** [Azure/bicep-registry-modules#1446]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.2.2

### Description

The VM Extension Dependency Agent is missing the enableAMA. Without this the DependencyAgent sends its data to the Legacy LAWW agent instead of the AMA agent. ref: https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/agent-dependency-windows#extension-schema

example ARM template for DepencyAgent where 'enableAMA' is set to True:
``` arm
    {
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "name": "[concat(parameters('vmName'),'/DAExtension')]",
      "apiVersion": "[variables('vmExtensionsApiVersion')]",
      "location": "[resourceGroup().location]",
      "dependsOn": [],
      "properties": {
          "publisher": "Microsoft.Azure.Monitoring.DependencyAgent",
          "type": "DependencyAgentWindows",
          "typeHandlerVersion": "9.10",
          "autoUpgradeMinorVersion": true,
          "settings": {
                "enableAMA": "true"
		    }
      }
```

Suggesting to add a 'enableAMA' property to 'extensionDependencyAgentConfig'. example:

```bicep
      extensionDependencyAgentConfig: {
        enabled: true
        enableAMA: true
      }
```

gr, pb

**Comment by rahalan** [comment]
@PieterbasNagengast thanks for bringing this up. I will look into it.

**Comment by rahalan** [comment]
Added in #1515
