### ISSUE TITLE
[AVM Module Issue]: User Assigned Identity - Federated Identity Credential Concurrency

### ISSUE THREAD

**Issue by DavidLHannah** [Azure/bicep-registry-modules#1447]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/managed-identity/user-assigned-identity

### Description

When deploying with /avm/res/managed-identity/user-assigned-identity/main.bicep, if you specify multiple Federated Identity Credentials, the deployment will fail and produce the below error message.

To resolve this, the module should be updated so that the _userAssignedIdentity_federatedIdentityCredentials_ resource is set with `@batchSize(1)`.

``` JSON
{
    "code": "DeploymentFailed",
    "details": [
        {
            "code": "ConcurrentFederatedIdentityCredentialsWritesForSingleManagedIdentity",
            "message": "Too many Federated Identity Credentials are written concurrently for the managed identity '/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/MyRg/providers/microsoft.managedidentity/userassignedidentities/MyManagedIdentity'. Concurrent Federated Identity Credentials writes under the same managed identity are not supported."
        }
    ],
    "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see this link for usage details.",
    "target": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyRg/providers/Microsoft.Resources/deployments/magteazksze5u-UserMSI-FederatedIdentityCredential-1"
}
```

**Comment by elanzel** [comment]
Hi @DavidLHannah , thank you for contacting us.
Let me check and fix the issue, thanks

**Comment by DavidLHannah** [comment]
Now working properly with v0.2.1
Thank You!
