### ISSUE TITLE
[AVM Module Issue]: key vault does not include complete set of data plane operation roles for builtInRoleNames

### ISSUE THREAD

**Issue by robvangeloven** [Azure/bicep-registry-modules#1459]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/key-vault/vault

### Description

The key vault module does not implement all roles as described here: [Azure built-in roles for Key Vault data plane operations]( https://learn.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli#azure-built-in-roles-for-key-vault-data-plane-operations)

At least the role  Key Vault Certificate User (db79e9a7-68ee-4b58-9aeb-b90e7c24fcba) is missing

**Comment by AlexanderSehr** [comment]
I'll be damned. @robvangeloven you're absolutely right. @fblix please take a look and add the other roles to the maps where it makes sense (also consider the same tables in the `key` & `secret` child modules.

**Comment by fblix** [comment]
Will try to find some time next week to take a look.
