### ISSUE TITLE
[AVM Module Issue]: PostgreSQL Flexible Server module should output server FQDN

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/bicep-registry-modules#1461]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/db-for-postgre-sql/flexible-server

### (Optional) Module Version

latest

### Description

The module should output the server's FQDN.

**Comment by josearper** [comment]
Acknowledged
