### ISSUE TITLE
[AVM Module Issue]: Virtual Network Links are not uniquely named

### ISSUE THREAD

**Issue by coolhome** [Azure/bicep-registry-modules#1463]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/dns-forwarding-ruleset

### Description

DNS Forwarding Ruleset does not create unique naming when creating the vNetLinks and provides no alternative for providing a name with the current vNetLinks parameter. In the example below I have two virtual networks called 'spoke-network' in two different subscriptions.

**Error Produced**:
Frontend service lock could not be acquired.

**Pseudo Example**:

```bicep
module TestRuleset 'br/public:avm/res/network/dns-forwarding-ruleset:0.2.4' = {
  scope: ResourceGroup
  name: 'TestDnsRuleset'
  params: {
    name: 'TestDnsRuleset'
    forwardingRules: []
    vNetLinks: [
      '/subscriptions/<sub-a-redact>/resourceGroups/Network/providers/Microsoft.Network/virtualNetworks/spoke-network'
      '/subscriptions/<sub-b-redact>/resourceGroups/Network/providers/Microsoft.Network/virtualNetworks/spoke-network'
    ]
    dnsForwardingRulesetOutboundEndpointResourceIds: [
      '${DnsResolver.outputs.resourceId}/outboundEndpoints/Outbound-Resolver'
    ]
  }
}
```

Each resource id in **vNetLinks** will default to "spoke-network-vnetlink" causing the error from above.

https://github.com/Azure/bicep-registry-modules/blob/938fb7c3531e251c4e3f42023329bcc133452862/avm/res/network/dns-forwarding-ruleset/main.bicep#L105-L113

https://github.com/Azure/bicep-registry-modules/blob/938fb7c3531e251c4e3f42023329bcc133452862/avm/res/network/dns-forwarding-ruleset/virtual-network-link/main.bicep#L22

**Comment by AlexanderSehr** [comment]
Hey @ChrisSidebotham, please take a look once you have a moment to triage the issue :)

**Comment by ChrisSidebotham** [comment]
@coolhome - PR Opened, care you review?
