### ISSUE TITLE
[AVM Module Issue]: publicNetworkAccess property not exposed

### ISSUE THREAD

**Issue by zensqlmonitor** [Azure/bicep-registry-modules#1468]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/container-service/managed-cluster

### Description

Property **publicNetworkAccess**, as defined in the provider **Microsoft.ContainerService managedClusters** is not exposed.

With the AVF, when we set the property **enablePrivateCluster** to false, the public network access of the managed cluster is **Enabled**.

**Comment by AlexanderSehr** [comment]
@JPEasier maybe you can include the fix in your latest WAF PR - or right after.
