### ISSUE TITLE
[AVM Module Issue]: ServiceCidr not working

### ISSUE THREAD

**Issue by zensqlmonitor** [Azure/bicep-registry-modules#1469]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/container-service/managed-cluster

### Description

Parameters serviceCidr and dnsServiceIP at not properly working.

When I set **serviceCidr** to 172.16.0.0/16 and **dnsServiceIP**  to 172.16.0.10, I receive a validation error saying that the DNS service IP does not belong to the range **10.0.0.0/16.**

**Comment by zensqlmonitor** [comment]
Any news?

**Comment by JPEasier** [comment]
Hi @zensqlmonitor, I will check the bug as soon as possible.

**Comment by ruudje123** [comment]
Hi @zensqlmonitor 

I suspect the vnet in which you try to deploy your cluster has the address prefix of 10.0.0.0/16, this is set in some of the dependencies bicep files. If you are trying to configure a serviceCidr and dnsServiceIP (or even podCidr) with a range that does not fit within the address prefix of the vnet you use, the error you describe is exactly the on you get.

Cheers!

**Comment by zensqlmonitor** [comment]
Hi @ruudje123, no, the vnet I'm using has not this address prefix.

My target is to set a service CIDR range in such a way that it does not overlap with the VNet IP range where the AKS cluster is hosted. I'm using this for EKS in AWS as a best practice. 
For example, I'm using 10.104.124.0/22 for the VPC and 172.16.0.0/24 for the service IP address range.

Previously, Amazon EKS automatically chose a value for this range based on the primary CIDR block of the Amazon VPC used by the cluster. However, this approach sometimes caused conflicts with other IP ranges in use across the network, especially for customers with VPCs peered to on-premise networks or other Amazon VPCs.

**Comment by ruudje123** [comment]
Hi @zensqlmonitor 

I assume you use azure-cni-overlay to plug your cluster into your vnet? 
https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay?tabs=kubectl
Important settings for the template are networkPlugin, networkPluginMode, networkPolicy you can use 'azure' for plugin and policy and 'overlay' for plugin mode.

With Azure CNI Overlay if 10.104.124.0/22 is your vnet you should be able to use 172.16.0.0/24 as serviceCidr and also 172.16.0.10 as DNS IP. I would also configure a podCidr so none pods are exposed externally without an ingress loadbalancer.

If you are like me don't want the load balancers exposing the services or ingress not be in the same subnet as worker nodes, there is an annotation of the service manifest that allows you to configure this. I have yet to find the parameter I can configure in AKS to achieve this. the annotation is:
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnetname"

Hope it helps.

**Comment by zensqlmonitor** [comment]
No, I'm using Azure CNI and that configuration works when using the portal but **not** with the AVF.

- VNet: 10.234.20.0/22
- Service CIDR: 172.16.0.0/24
- DNS service IP: 172.16.0.10

@JPEasier any thoughts ?

**Comment by zensqlmonitor** [comment]
Hi, any news ?

**Comment by zensqlmonitor** [comment]
Hello @JPEasier, any assistance found for this ?
Thanks.

**Comment by PixelRobots** [comment]
Hi @zensqlmonitor I just tested this myself and did not get any issues. Azure CNI, 

My networking looks like:

```bicep
param vNetAddressPrefix = '10.240.0.0/16'
param aksPodSubnetPrefix = '10.240.0.0/20'
param aksLBSubnetPrefix = '10.240.16.0/28'
param serviceCidr = '172.16.0.0/24'
param dnsServiceIP = '172.16.0.10'
```
![image](https://github.com/Azure/bicep-registry-modules/assets/22979170/0d52c089-7985-4915-9059-1fb9dbe7a65c)

![image](https://github.com/Azure/bicep-registry-modules/assets/22979170/7b4baf3b-3376-4ce7-a73f-33872e39c81f)

Can you test again maybe and let us know which version of the module you are using?

**Comment by zensqlmonitor** [comment]
@PixelRobots @JPEasier 

Looks fine with the version 0.1.3: 
![image](https://github.com/Azure/bicep-registry-modules/assets/16494280/51381d01-d135-45c3-af87-418916dc9018)

**Comment by PixelRobots** [comment]
Awesome news. Should be ok to close this issue. Glad it's all working for you. 

Also keep an eye out on the module as I have been adding some new features!
