### ISSUE TITLE
[WAF - Reliability Review] - `avm/res/api-management/service`

### ISSUE THREAD

**Issue by jtracey93** [Azure/bicep-registry-modules#1473]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/api-management/service

### Description

Hello team,

The AVM core team are performing a review of all AVM modules to ensure they are aligned to the WAF reliability pillar by default, and in the future they will be checking against other WAF pillars also. This is a requirement we have before we can go `v1.0.0` for any AVM module.

Links to AVM specs:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr2---category-composition---waf-aligned
- https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr5---category-composition---availability-zones

Links to WAF Reliability, APRL & Product Docs recommendations used for analysis:

- https://learn.microsoft.com/azure/well-architected/reliability/checklist
- https://learn.microsoft.com/en-us/azure/api-management/high-availability?toc=%2Fazure%2Freliability%2Ftoc.json&bc=%2Fazure%2Freliability%2Fbreadcrumb%2Ftoc.json
- https://azure.github.io/Azure-Proactive-Resiliency-Library/services/integration/api-management

Whilst reviewing this module the following issues have been found that are non-compliant with the AVM specs that need to be resolved in a new version release:

- [Change the default for the `skuCount` parameter to `3` (to match the zones) and adjust/remove the allowed decorator for the module](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/api-management/service/main.bicep#L68-L71)
- [Change the default for the `zones` parameter to `[1,2,3]`](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/api-management/service/main.bicep#L92)
- [Change the default for the `sku` parameter to `Premium` tier to support AZs](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/api-management/service/main.bicep#L65)

Please make these changes in a PR to the parameter defaults so a new minor version can be published.

### PSRule

It also seems that PSRule is not picking up these checks under its [`Azure.Pillar.Reliability` baseline](https://azure.github.io/PSRule.Rules.Azure/en/baselines/Azure.Pillar.Reliability/) via its tests and that has been logged in the issue: https://github.com/Azure/PSRule.Rules.Azure/issues/2787

And there is also a missing check for the capacity instances which has been logged here: https://github.com/Azure/PSRule.Rules.Azure/issues/2788

Thanks

The AVM Core Team

**Comment by jtracey93** [comment]
@azure/avm-res-apimanagement-service-module-owners-bicep

**Comment by matebarabas** [comment]
@tony-box, can you please take a look at this one? Thanks!

**Comment by tony-box** [comment]
I am working to rebuild my test environment due to some issues with it. Will look into this as soon as I can.

**Comment by tony-box** [comment]
This is fixed in my latest MR #1989 @jtracey93 are you suggesting this change would require a new min version bump?
