### ISSUE TITLE
[Module Proposal]: Run Helm Commands with AKS

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#148]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

A similar module exists, with an example of how to run a helm script. But this module provides an easier to use notation for the helm repos. 

### Module path

modules/deployment-scripts/aks-run-helm

### Describe the module

It will provide specific top level input parameters to make it easier to use helm with aks.

| `helmRepo`                                 | `string` | No       | Public Helm Repo Name                                                           |
| `helmRepoURL`                              | `string` | No       | Public Helm Repo URL                                                            |
| `helmApps`                                 | `array`  | No       | Helm Apps {helmApp: 'azure-marketplace/wordpress', helmAppName: 'my-wordpress'} |

**Comment by shenglol** [comment]
Closed via https://github.com/Azure/bicep-registry-modules/pull/147.
