### ISSUE TITLE
[AVM Module Issue]: VM `availabilityZone` parameter should be renamed to `zone`

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/bicep-registry-modules#1496]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### Description

In alignment with the latest discussions, the `zones` implementation for the VM is mostly aligned, but should be changed from `availabilityZone` to `zone` - which we'll soon specify in the AVM specs too.

Reference: https://github.com/Azure/Azure-Verified-Modules/pull/805

**Comment by rahalan** [comment]
Will be fixed in #1515
