### ISSUE TITLE
[AVM Module Issue]: Subnet NetworkSecurityGroup association is not applied

### ISSUE THREAD

**Issue by kmosti** [Azure/bicep-registry-modules#1499]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/virtual-network

### (Optional) Module Version

0.1.5

### Description

When applying the following modules, the subnet is NOT updated with the nsg ID:

``` BICEP
param VNET object = {
  name: 'microservices-vnet'
  prefixes: ['10.8.0.0/16']
  subnets: [
    {
      name: 'microservices-snet'
      prefix: '10.8.0.0/27'
    }
  ]
}

module modExternalVNET 'br/public:avm/res/network/virtual-network:0.1.5' = {
  name: '${uniqueString(deployment().name)}-vnet'
  scope: resourceGroup()
  params: {
    name: VNET.name
    addressPrefixes: VNET.prefixes
    subnets: [
      for snet in VNET.subnets: {
        name: snet.name
        addressPrefix: snet.prefix
        networkSecurityGroupId: '/subscriptions/redacted/resourceGroups/microservices-rg/providers/Microsoft.Network/networkSecurityGroups/microservices-nsg'
        delegations: [
          {
            name: '${snet.name}-del'
            properties: {
              serviceName: 'Microsoft.Web/serverFarms'
            }
          }
        ]
        serviceEndpoints: [
          {
            service: 'Microsoft.KeyVault'
          }
          {
            service: 'Microsoft.Storage'
          }
          {
            service: 'Microsoft.Web'
          }
        ]
      }
    ]
  }
}
```

When I apply the same resources this way (without using avm), the subnet IS updated with the correct NSG id:

``` BICEP
param nsgName string = 'microservices-nsg'
param vnetName string = 'microservices-vnet'
param subnetName string = 'microservices-snet'

resource nsg 'Microsoft.Network/networkSecurityGroups@2023-09-01' existing = {
  name: nsgName
}

resource vnet 'Microsoft.Network/virtualNetworks@2023-09-01' existing = {
  name: vnetName
}

resource subnet 'Microsoft.Network/virtualNetworks/subnets@2023-09-01' = {
  name: subnetName
  parent: vnet
  properties: {
    addressPrefix: '10.8.0.0/27'
    networkSecurityGroup: {
      id: nsg.id
    }
    serviceEndpoints: [
      {
        service: 'Microsoft.KeyVault'
      }
      {
        service: 'Microsoft.Storage'
      }
      {
        service: 'Microsoft.Web'
      }
    ]
    delegations: [
      {
        name: '${subnetName}-del'
        properties: {
          serviceName: 'Microsoft.Web/serverFarms'
        }
      }
    ]
  }
}
```

There are no errors or failures in my deployment logs, the subnet is just not updated with the specified network security group.

**Comment by elbatane** [comment]
Hi @kmosti , thank you for reporting the bug. We will review it and come back as soon as possible. Thanks

**Comment by RodneyAlmeidaTEKenable** [comment]
@kmosti 
Not sure if this was a change in the last version but the nsg reference is now called
networkSecurityGroupResourceId
not 
networkSecurityGroupId

**Comment by rodney-almeida** [comment]
@kmosti 
Not sure if this was a change in the last version but the nsg reference is now called
networkSecurityGroupResourceId
not
networkSecurityGroupId

**Comment by AlexanderSehr** [comment]
Thanks for the callout @rodney-almeida, I also just checked. It's like he says, the parameter of the mdoule is called `networkSecurityGroupResourceId`. Unfortunately, the corresponding User-defined-type is not yet implemented which is why Linter did not warn you. Please double-check on your end and close the issue if it works for you :)

**Comment by elbatane** [comment]
Hi @kmosti, as @rodney-almeida mentioned and @AlexanderSehr confirmed, the parameter is called `networkSecurityGroupResourceId` instead of `networkSecurityGroupId`, which was the parameter name you where using. Please confirm on your end to close the issue. Thank you very much.

**Comment by kmosti** [comment]
I can confirm, thank you very much for your help
