### ISSUE TITLE
[WAF - Reliability Review] - `avm/res/app-configuration/configuration-store`

### ISSUE THREAD

**Issue by jtracey93** [Azure/bicep-registry-modules#1502]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app-configuration/configuration-store

### Description

Hello team,

The AVM core team are performing a review of all AVM modules to ensure they are aligned to the WAF reliability pillar by default, and in the future they will be checking against other WAF pillars also. This is a requirement we have before we can go `v1.0.0` for any AVM module.

Links to AVM specs:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr2---category-composition---waf-aligned
- https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr5---category-composition---availability-zones

Links to WAF Reliability, APRL & Product Docs recommendations used for analysis:

- https://learn.microsoft.com/azure/well-architected/reliability/checklist
- https://learn.microsoft.com/en-us/azure/azure-app-configuration/faq?toc=%2Fazure%2Freliability%2Ftoc.json&bc=%2Fazure%2Freliability%2Fbreadcrumb%2Ftoc.json#how-does-app-configuration-ensure-high-data-availability

Whilst reviewing this module the following issues have been found that are non-compliant with the AVM specs that need to be resolved in a new version release that can be seen in the PSRule for Azure run here: https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.app-configuration.configuration-store.yml#summary-23300173139

> The geo-replica PSRule check may need a [suppression rule](https://azure.github.io/PSRule.Rules.Azure/concepts/suppression/) creating as it may only be suitable for a pattern module and not a resource module. The AVM `.ps-rule` directory can be found here:  https://github.com/Azure/bicep-registry-modules/tree/main/avm/utilities/pipelines/staticValidation/psrule/.ps-rule

Please make these changes in a PR to the parameter defaults so a new minor version can be published.

Thanks

The AVM Core Team

**Comment by matebarabas** [comment]
Note, this module is currently orphaned: https://github.com/Azure/Azure-Verified-Modules/issues/731

**Comment by segraef** [comment]
Seems `"Microsoft.AppConfiguration/configurationStores/replicas"` needs to be added.

**Comment by eriqua** [comment]
@JFolberth is actively working on fixing this issue through PR #1696
