### ISSUE TITLE
[WAF - Reliability Review] - `avm/res/cache/redis`

### ISSUE THREAD

**Issue by jtracey93** [Azure/bicep-registry-modules#1504]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cache/redis

### Description

Hello team,

The AVM core team are performing a review of all AVM modules to ensure they are aligned to the WAF reliability pillar by default, and in the future they will be checking against other WAF pillars also. This is a requirement we have before we can go `v1.0.0` for any AVM module.

Links to AVM specs:

- https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr2---category-composition---waf-aligned
- https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr5---category-composition---availability-zones

Links to WAF Reliability, APRL & Product Docs recommendations used for analysis:

- https://learn.microsoft.com/azure/well-architected/reliability/checklist
- https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-zone-redundancy?toc=%2Fazure%2Freliability%2Ftoc.json&bc=%2Fazure%2Freliability%2Fbreadcrumb%2Ftoc.json
- https://learn.microsoft.com/en-us/azure/well-architected/service-guides/azure-cache-redis/reliability
- https://azure.github.io/Azure-Proactive-Resiliency-Library/services/database/redis-cache/
- https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Redis.AvailabilityZone/#configure-with-bicep

Whilst reviewing this module the following issues have been found that are non-compliant with the AVM specs that need to be resolved in a new version release:

- [Change the parameter of `zoneRedundant` to default to `true`](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cache/redis/main.bicep#L94) 
- [Change the parameter of `skuName` to default to `Premium`](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cache/redis/main.bicep#L82)
- [Change the parameter of `zones` to default to `[1,2,3]`](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cache/redis/main.bicep#L97)
    - May be able to remove the var for AZ logic https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cache/redis/main.bicep#L108-L110
- [Change the parameter of `replicasPerMaster` to default to `3`](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cache/redis/main.bicep#L54)

Please make these changes in a PR to the parameter defaults so a new minor version can be published.

Thanks

The AVM Core Team

**Comment by matebarabas** [comment]
@hundredacres, can you please take a look at this one? Thanks!

**Comment by hundredacres** [comment]
PR here: https://github.com/Azure/bicep-registry-modules/pull/1621
