### ISSUE TITLE
[AVM Module Issue]: /avm/res/web/serverfarm - add allowed values for SKU to help customers supply the right values when they need to overwrite SKU

### ISSUE THREAD

**Issue by puicchan** [Azure/bicep-registry-modules#1505]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/serverfarm

### Description

It is hard to find what are the supported SKU for App Service Plan. 

Can we include allowed values for SKU so intellisense in VS Code can help suggest the right value?

As sample sku is like so:
```bicep
  {
    name: 'P1v3'
    tier: 'Premium'
    size: 'P1v3'
    family: 'P'
    capacity: 3
  }
```

The less I need to overwrite, the better. Can we supply just **name** and have AVM module default the rest?

**Comment by tsc-buddy** [comment]
Hi @puicchan , Thanks for logging this. We shall triage it WC 15 April when we are next scheduled for AVM Work.

**Comment by Agazoth** [comment]
We need this module to be in conjunction with the readme. It is still required to pass a sku object to the module but the readme states that skuCapacity etc should be used.

**Comment by tsc-buddy** [comment]
Closing this one as we are going to hold out for some Bicep functionality to better serve this. Particularly with the large number of SKU options available.

The SKU simplification changes have been implemented.
