### ISSUE TITLE
[AVM Module Issue]: res/web/serverfarm - I need to specify tier in SKU I will otherwise get an error

### ISSUE THREAD

**Issue by puicchan** [Azure/bicep-registry-modules#1506]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/serverfarm

### Description

Related https://github.com/Azure/bicep-registry-modules/issues/1505

This is because AVM is WAF-aligned and the module checking the value for tier.
The less I need to overwrite, the better. Can we supply just name?

**Comment by tsc-buddy** [comment]
Hi @puicchan ,  Thanks for logging this. We shall triage it WC 15 April when we are next scheduled for AVM Work.
