### ISSUE TITLE
[AVM Module Issue]: res/web/serverfarm - can we default reserved = true when customer specify kind as Linux?

### ISSUE THREAD

**Issue by puicchan** [Azure/bicep-registry-modules#1507]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/serverfarm

### Description

Based on https://azure.github.io/AppService/2021/08/31/Kind-property-overview.html - you can set kind to “Linux” for the ASP, but that won’t make your ASP a Linux ASP; only if reserved = true, then it’s a Linux ASP. Let's help customer make the right default in the AVM module.

**Comment by tsc-buddy** [comment]
Hi @puicchan - Thanks for logging this. We shall triage it WC 15 April when we are next scheduled for AVM Work.

**Comment by tsc-buddy** [comment]
@puicchan this one is all done for you. Thanks for submitting it. I will look to submit a PR for the others later this week potentially.
