### ISSUE TITLE
[AVM Module Issue]: securityContext not configurable for Container Instances

### ISSUE THREAD

**Issue by mischavandenburg** [Azure/bicep-registry-modules#1514]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/container-instance/container-group

### (Optional) Module Version

0.1.0

### Description

The securityContext is not included in the type containerType.

I have a use case where I need to configure the capabilities for a container, and this is currently not possible.

I would be happy to create a PR for it.

**Comment by AlexanderSehr** [comment]
Hey @JPEasier, please triage the meeting if you have a moment :)
