### ISSUE TITLE
[AVM Module Issue]:  enableIPForwarding doesn't accept true when deploying NIC through virtual-machine

### ISSUE THREAD

**Issue by tig3r57** [Azure/bicep-registry-modules#1516]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine

### Description

Describe the bug
If i try to deploy a new virtual machine and when i set enableIPForwarding to true, i have a message arror

To reproduce
create a vm with enableipforwarding set to true

Code snippet
param enableIPForwarding bool = true
var nicConfigurations = [
    {
      nicSuffix: '-nic-01'
      enableIPForwarding: enableIPForwarding
      ipConfigurations: [
        {
          name: 'ipconfig1'
          subnetResourceId: subnetResourceId
          privateIPAllocationMethod: IPallocation
          privateIPAddress: privateIPAddress
          primary: true
        }
      ]
    }
]
Relevant log output
New-AzResourceGroupDeployment: 3:28:20 PM - The deployment 'main' failed with error(s). Showing 2 out of 2 error(s).
Status Message: Unable to process template language expressions for resource '/subscriptions/************/resourceGroups/***/providers/Microsoft.Resources/deployments/rusaxk4qxrx5o-VM-Nic-0' at line '1' and column '29126'. 'The template function 'empty' expects its parameter to be an object, an array, or a string. The provided value is of type 'Boolean'. Please see https://aka.ms/arm-function-empty for usage details.' (Code:InvalidTemplate)
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)
 - Unable to process template language expressions for resource '/subscriptions/**************/resourceGroups/*******/providers/Microsoft.Resources/deployments/rusaxk4qxrx5o-VM-Nic-0' at line '1' and column '29126'. 'The template function 'empty' expects its parameter to be an object, an array, or a string. The provided value is of type 'Boolean'. Please see https://aka.ms/arm-function-empty for usage details.' (Code:InvalidTemplate)
CorrelationId: ece39906-a82e-468e-8121-01ba7bd12b23

**Comment by rahalan** [comment]
@tig3r57 thank you! Will look into it.
