### ISSUE TITLE
[Question/Feedback]: Ignore (unchanged) read-only properties in Bicep during deployment

### ISSUE THREAD

**Issue by bartcode** [Azure/bicep-registry-modules#1522]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I'm using an AVM Bicep module to deploy a storage account that was created by a different language to deploy infrastructure.  I'm looking to migrate the infrastructure code to Bicep in combination with Azure deployment stacks to make our setup simpler and faster.

However, it seems like _because_ the resource already exists, it throws the following error:

```
Code: DeploymentFailed
Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
Target: /subscriptions/xxxx/resourceGroups/rg-xxx/providers/Microsoft.Resources/deployments/xxx
Exception Details:      (AccountPropertyCannotBeUpdated) The property 'isHnsEnabled' was specified in the input, but it cannot be updated as it is read-only. For more information, see - https://aka.ms/storageaccountupdate
```

I've tried setting the property `enableHierarchicalNamespace` for the `storage-account` AVM to `null`, `false`, `true`, and I've left it out entirely as well. But it always results into the same error.

I expect this same issue will arise when deploying other resources as well. It would help me if I can either ignore (unchanged) fields, or import resources somehow such that Azure at least thinks it has deployed that resource before.

There's [an open issue](https://github.com/Azure/azure-rest-api-specs/issues/18441) which is somewhat related, but this is about the actual Bicep resource, whereas my issue is with the Bicep AVM.

**Comment by bartcode** [comment]
@matebarabas , thanks for the help! When I run the pipeline, I'm getting (also, see draft PR):
```
  Error: [-] [storage/storage-account] Module identifier should be listed in issue template in the correct alphabetical position. 12ms (11ms|0ms)
Message
  Expected 'avm/res/storage/storage-account' to be found in collection $null, because the module should be listed in the issue template in the correct alphabetical position ([ref](https://azure.github.io/Azure-Verified-Modules/specs/bicep/#id-bcpnfr15---category-contributionsupport---avm-module-issue-template-file))., but it was not found.
```

Are you familiar with this error? The error message is hinting at issues in a file that I haven't even changed.

**Comment by o-l-a-v** [comment]
Are we waiting for the RP to fix their backend or has this gone stale? I just rewrote some IaC for existing infrastructure and now have to rewrite it _again_ due to this. 🥲

**Comment by bartcode** [comment]
@o-l-a-v , don't worry, I'm closing this now. I somehow can't reproduce it anymore...

**Comment by o-l-a-v** [comment]
Maybe the Azure portal now adds those properties with value null (or false / true), or maybe the resource provider does it behind the scenes for undefined properties. That does not help old already created resources, like in my case.

**Comment by bartcode** [comment]
You're actually having the same issue as I did? I thought I was the only one and somehow had made a mistake.

**Comment by o-l-a-v** [comment]
Yes I do. I tried setting versioning on blobs to disabled, it did not work. Also hns (`isHnsEnabled`) to false or null, did not work either. For an old storage account already in Azure. Ended up writing "raw" bicep without these properties instead of using AVM.

**Comment by AlexanderSehr** [comment]
Sounds like the union is in order afterall 🤔 damn

**Comment by matebarabas** [comment]
@jongio, @tonybaloney, reopening this issue as per your request.

**Comment by Agazoth** [comment]
@AlexanderSehr I am having this issue too. Since this is a  long running issue, I assume some code has been created to mitigate the issue. Do you have any insights in status or possible solution?

**Comment by michael-kilby-afs** [comment]
This isnt closed. You are unable to pass in a null as the variable is not nullable. I suggest converting the variable from bool -> bool?

**Comment by AlexanderSehr** [comment]
> This isnt closed. You are unable to pass in a null as the variable is not nullable. I suggest converting the variable from bool -> bool?

Hey @Agazoth, could you advice? I know you ran quite a few tests. @michael-kilby-afs's ask sounds reasonable, but you may have your own thoughts on the matter :)

**Comment by o-l-a-v** [comment]
Could this be solved with the spread operator `...` now?

* <https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/operator-spread>
* <https://github.com/Azure/bicep/issues/15451>

**Comment by AlexanderSehr** [comment]
> Could this be solved with the spread operator `...` now?
> 
> * https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/operator-spread
> * [Set or skip an object property based on a condition bicep#15451](https://github.com/Azure/bicep/issues/15451)

Absolutely. And it should be preferred over the `union()` to retain linter support 💪

**Comment by AlexanderSehr** [comment]
Re-opening and creating a new PR...
