### ISSUE TITLE
[Module Proposal]: Add Public IP to AKS via Helm

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#156]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Process can currently only be performed with Azure CLI. This will simplify automation.

### Module path

deployment-scripts/aks-config-ip

### Describe the module

This module takes an existing AKS and Public IP, and sets the Public IP to the AKS cluster.

**Comment by Gordonby** [comment]
I'm almost thinking that it's too specific a use case that is being solved with the module.
Could this not just be an example in the README.md of the AKS Run Command module? Is there an advantage to having it being a separate module?

**Comment by dciborow** [comment]
I am creating a example for a customer on how to create a Managed App with AKS that needs this. Anything that is not a "module", will end up being code I have to hand over to the customer. If they have issues with the "Public IP" portion in the future, this gives me a place to repro/fix the issue, and provide them an update. 
Without the module, I would have to take a more hands on approach with the customer to update. 

But, let me rework this to be a more generic "AKS Post-Deployment Setup", which includes the two other things I need. Once it's all on the table, may make it easier to organize.

**Comment by ChrisSidebotham** [comment]
Dear @dciborow , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, module proposals for new, non-AVM modules will no longer be accepted and we encourage you to propose a new AVM module, which you can file here: Module Proposal, [here](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
