### ISSUE TITLE
[AVM Question/Feedback]: Databricks Connector not correctly removed

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/bicep-registry-modules#1581]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

The `databricks/workspace` module creates an additional `-managed` resource group that is not removed by the CI. This can cause issues upon re-run if the location selector choses a different location to deploy to:

Example:
![image](https://github.com/Azure/bicep-registry-modules/assets/5365358/fdb08f67-a728-471d-8955-7f8d44b1e08b)

This means we need to investigate why this is the case, if there is a property we can set (similar to how you can specify on the VM that it should remove its NIC & PIP) or whether we can add something to the removal logic (e.g. adding it to the order in which resources are removed - to before the resource group is removed). 
```[tasklist]
### Tasks
```

**Comment by eriqua** [comment]
+ @clintgrove for alignment

**Comment by eriqua** [comment]
Looks like it is expected to be deleted automatically a few minutes after deleting the service https://learn.microsoft.com/en-us/answers/questions/1527601/azure-databricks-managed-resource-group-not-automa

To be investigated if transient

**Comment by AlexanderSehr** [comment]
I don't think it's transient. These RGs stayed around for weeks and months until manually removed

**Comment by clintgrove** [comment]
@AlexanderSehr  and @eriqua  do you think we should have a task in the yaml github action that maybe scans the subscription and finds any RG's that are databricks and deletes them? I've read this interesting line by a member of public "The managed resource group created by Databricks cannot be deleted from portal or through any scripts since it was created by the Databricks resource itself. The deny assignment prevents deletion of the managed resource group." and this site has a Q&A about it https://learn.microsoft.com/en-us/archive/msdn-technet-forums/70f21330-2102-4744-b116-2c5fcf0911d2

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr and @eriqua do you think we should have a task in the yaml github action that maybe scans the subscription and finds any RG's that are databricks and deletes them? I've read this interesting line by a member of public "The managed resource group created by Databricks cannot be deleted from portal or through any scripts since it was created by the Databricks resource itself. The deny assignment prevents deletion of the managed resource group." and this site has a Q&A about it https://learn.microsoft.com/en-us/archive/msdn-technet-forums/70f21330-2102-4744-b116-2c5fcf0911d2

Hey @clintgrove,
it cannot while the Databricks service is around, but we were able to consistently clean the (manged) resources up in the Portal after the workspace jumped ship. I'd at least like to give updating the removal logic a go. 
I'll try and look into this this week. Both @eriqua and I already gave it a go - but all tests with 'simple' solutions failed. So it appears we need to bring bigger tools.
