### ISSUE TITLE
[AVM Question/Feedback]: Update PE implementation in remaining modules

### ISSUE THREAD

**Issue by krbar** [Azure/bicep-registry-modules#1583]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Some modules had to be excluded from the PE implementations updates provided in #1472 due to unrelated issues preventing them to be merged. The purpose of this issue is to track the PE implementation updates of these modules:
- [x] #1827
  Can be done if green: [![avm.res.app-configuration.configuration-store](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.app-configuration.configuration-store.yml/badge.svg)](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.app-configuration.configuration-store.yml)

- [x] #1789
  Can be done if green: [![avm.res.container-registry.registry](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.container-registry.registry.yml/badge.svg)](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.container-registry.registry.yml)
- [x] #1943
  Can be done if green: [![avm.res.databricks.workspace](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.databricks.workspace.yml/badge.svg)](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.databricks.workspace.yml)
- [x] #2454
  Can be done if green: [![avm.res.event-hub.namespace](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.event-hub.namespace.yml/badge.svg)](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.event-hub.namespace.yml)
- [x] #1791
  Can be done if green: [![avm.res.machine-learning-services.workspace](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.machine-learning-services.workspace.yml/badge.svg)](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.machine-learning-services.workspace.yml)
- [x] #2455
  Can be done if green: [![avm.res.storage.storage-account](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.storage.storage-account.yml/badge.svg)](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.storage.storage-account.yml)
- [x] #1793
  Can be done if green: [![avm.res.web.site](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.web.site.yml/badge.svg)](https://github.com/Azure/bicep-registry-modules/actions/workflows/avm.res.web.site.yml)

**Comment by AlexanderSehr** [comment]
Closing as done
