### ISSUE TITLE
[AVM Question/Feedback]: Tests errors when there is an additional telemetery deployment

### ISSUE THREAD

**Issue by sebassem** [Azure/bicep-registry-modules#1612]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I'm building a pattern module for the
[finops-hub solution](https://github.com/microsoft/finops-toolkit)
and there is deployment telemetry collected by this solution in addition to the AVM telemetry. Having both triggers two errors in the static validation tests. I think the logic needs to change to only check for `avmTelemetry`

![image](https://github.com/Azure/bicep-registry-modules/assets/38246040/f182c347-6ee1-4a39-ab82-da31cd4944c8)

**Comment by AlexanderSehr** [comment]
Curious indeed and a great test case. I guess it's one of those issues we need to priorize to enable pattern modules 😊
