### ISSUE TITLE
[AVM Module Issue]: API Management Service - Please support API Management V2 SKUs

### ISSUE THREAD

**Issue by allanmodin** [Azure/bicep-registry-modules#1615]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/api-management/service

### Description

Can you add support for API Management V2 SKUs? We really want to use the new V2 SKU options, but are currently forced to write our own bicep instead of using the awesome AVM module.

**Comment by markdebruijne** [comment]
This is also blocking me from start using this template 🙏 , currently working around by using native resources in my BICEP file. 
Is this only a matter of adding the 2 new SKU names to that allowed parameter values, or are there more implications we need to cover? (just to know what might be outcoming). Thanks 👍

**Comment by tony-box** [comment]
I had some issues with the previous PR. I cleaned it all up and submitted the new PR #1777 which adds support for the V2 SKUs
