### ISSUE TITLE
[AVM Module Issue]: API Management consumption plan requires skuCount 0

### ISSUE THREAD

**Issue by cvs79** [Azure/bicep-registry-modules#1628]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/api-management/service

### Description

If you want to deploy a consumption sku for Api Management it fails because the skuCount is required to be set to 0. Error is 
_For Consumption SKU Type capacity must be specified as 0._

At the moment you can't specify skuCount as zero as the code for that is:

```
@description('Optional. The instance size of this API Management service.')
@allowed([
  1
  2
])
param skuCount int = 1
```

Please add allowed 0 to this list.

**Comment by tony-box** [comment]
Thank you @cvs79 for the PR! I'm reviewing now.
