### ISSUE TITLE
[AVM Module Issue]: Virtual Machine has no support for Custom Automanage configuration profiles

### ISSUE THREAD

**Issue by jbarrancos** [Azure/bicep-registry-modules#1630]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.2.3

### Description

The Virtual-Machine module does not support custom Automanage profiles. It only allows you to use the default ones.

When trying to deploy a VM with a custom Automanage profile: Microsoft.Automanage/configurationProfiles@2022-05-04 it is not allowed per module main.bicep restriction on the parameter:
_The property "configurationProfile" expected a value of type "'' | '/providers/Microsoft.Automanage/bestPractices/AzureBestPracticesDevTest' | '/providers/Microsoft.Automanage/bestPractices/AzureBestPracticesProduction' | null" but the provided value is of type "string".bicep(BCP036)_

**Comment by rahalan** [comment]
@jbarrancos Thank you, I will look into it.

**Comment by rahalan** [comment]
@jbarrancos according to the documentation that should work. See https://learn.microsoft.com/en-us/azure/automanage/arm-deploy I will update the API version and try myself. I'll keep you posted

**Comment by jbarrancos** [comment]
I know it works **without** the AVM module. But the allowed parameter values in the AVM doesn’t allow this.

**Comment by rahalan** [comment]
@jbarrancos you are correct. It will be fixed with PR #1515
