### ISSUE TITLE
[AVM Question/Feedback]: bicep targetScope subscription - resource-group module

### ISSUE THREAD

**Issue by Agazoth** [Azure/bicep-registry-modules#1633]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

When working with our own modules on our private bicep registry, we use subscription deployments. When doing that, we set the targetScope to subscription in the main.bicep. Then we create a resourceGroup and whatever resources are required for our product.

It could look like this:

```bicep
targetScope = 'subscription'

resource resourceGroup 'Microsoft.Resources/resourceGroups@2021-04-01' = {
  name: 'MyResourceGroup'
  location: 'westeurope'
}

module storage 'br/myregistry:storageaccount:1.0' = {
  scope: resourceGroup
  name: 'deploy-storage'
  params: {
    storageAccountName: 'mystorageaccount'
  }
}

```

Setting the scope parameter on our storage module implements the dependency on the resource group automatically, when running the New-AzSubscriptionDeployment command with this bicep file

I tried using the resource group module from AVM in a similar way:

```bicep
param rgName string
param location string

targetScope = 'subscription'

module resourceGroup 'br/public:avm/res/resources/resource-group:0.2.3' = {
  name: 'resourceGroupDeployment'
  params: {
    name: rgName
    location: location
  }
}

module storageAccount 'br/public:avm/res/storage/storage-account:0.8.2' = {
  name: 'storageAccountDeployment'
  scope: resourceGroup
  params: {
    name: 'sa${substring(uniqueString(resourceGroup.outputs.resourceId), 0, 6)}'
  }
}
```
The linter in vscode does not like this:
![image](https://github.com/Azure/bicep-registry-modules/assets/15127301/36452dda-7289-4a80-8476-aaf61a1498b1)

However, if I just revert to my old routine with creating a resource group without the module, the linter gets happy again:
```bicep
param rgName string
param location string

targetScope = 'subscription'


resource resourceGroup 'Microsoft.Resources/resourceGroups@2021-04-01' = {
  name: 'MyResourceGroup'
  location: 'westeurope'
}

module storageAccount 'br/public:avm/res/storage/storage-account:0.8.2' = {
  name: 'storageAccountDeployment'
  scope: resourceGroup
  params: {
    name: 'sa${substring(uniqueString(resourceGroup.id), 0, 6)}'
  }
}
```
It seems we need to figure out some sort of workaround, if we are going to use the resource-group module in any sensible way.

I do like the flexibility the resource group module provides us, but I do need to have the resource group deployment in the same deployment as the resources.

Any ideas on how I can use the resource group module along with other resources in the same bicep file?

**Comment by jbarrancos** [comment]
[Same issue as stated withing the Bicep Repo](https://github.com/Azure/bicep/issues/4992). Would be great if this could be resolved. You could for now use resourceId(resourceGroup.Name) as a workarround and also add resourceGroup(ResourceGroup.outputs.name).

**Comment by AlexanderSehr** [comment]
> [Same issue as stated withing the Bicep Repo](https://github.com/Azure/bicep/issues/4992). Would be great if this could be resolved. You could for now use as a workarround `scope: resourceGroup(ResourceGroup.outputs.name).`

Hey @Agazoth,
the solution mentioned by @jbarrancos is the way to go today. It's a limitation of Bicep itself. I expect this to be resolve once the Bicep team implements the feature to pass entire resource objects between modules.

I've seen this feature request a couple times in the Bicep Community calls, and I think these are the matching issues in the Bicep repository (though I'm not 100% sure):
- https://github.com/Azure/bicep/issues/2245
- https://github.com/Azure/bicep/issues/2246 

It's good that you raised the issue, yet I would suggest to close it and tackle it at the core, the Bicep repository :)

**Comment by Agazoth** [comment]
I agree. Closing this one and await the other feature.
