### ISSUE TITLE
[AVM Module Issue]: Error BCP037 - property is not allowed on objects of type "params"

### ISSUE THREAD

**Issue by Alexprosp247** [Azure/bicep-registry-modules#1636]
### Check for previous/existing GitHub issues

- [ ] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/bastion-host

### (Optional) Module Version

0.2.1

### Description

When trying to use the Bastion Host avm I get the following error:
"Error BCP037: The property "name" is not allowed on objects of type "params". No other properties are allowed. "

This same error applies for all the param values I specify, not quite sure what the issue is. This is the first time I'm playing around with avm so could be misunderstanding something.
```
param rg string = resourceGroup().location

module bastionHost 'br/public:avm/res/network/bastion-host:0.2.1' = {
  name: 'bastionDeployAVM'
  params: {
    // Required parameters
    name: 'bastiontest'
    virtualNetworkResourceId: bastionsubnet.id
    // Non-required parameters
    location: rg
  }
}

resource bastionsubnet 'Microsoft.Network/virtualNetworks/subnets@2023-06-01' existing = {
  name: 'vnet-hub-ne-200/AzureBastionSubnet'
  scope: resourceGroup('rg-hubvnet-ne-01')
}

```

**Comment by Alexprosp247** [comment]
Hi @AlexanderSehr seems like updating bicep to the latest version resolved the issue. Was previously running on 0.19.5. Thanks again for your help!.

**Comment by AlexanderSehr** [comment]
Glad to hear @Alexprosp247 💪. Have fun ;)
