### ISSUE TITLE
[AVM Module Issue]: Ability to assign multiple custom domains to an adfEndpoint route in `br/public:avm/res/cdn/profile`

### ISSUE THREAD

**Issue by ksstott** [Azure/bicep-registry-modules#1639]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cdn/profile

### Description

Currently there is a `customDomainName` prop on a route within an adfEndpoint but it is not possible to set multiple custom domains.
What we have now:
```bicep
afdEndpoints: [
      {
        name: 'endpoint1'
        routes: [
          {
            name: 'route1'
            customDomainName: 'test.com'
          }
        ]
      }
    ]
```
How we might solve this:
```bicep
afdEndpoints: [
      {
        name: 'endpoint1'
        routes: [
          {
            name: 'route1'
            customDomainNames: [
                'test.com'
                'test2.com'
            ]
          }
        ]
      }
    ]
```

**Comment by gbeaud** [comment]
The native Bicep resource afdEndpoints/routes supports customDomains as a list so the feature should be feasible, will look into it please allow some time 👍

Would you be available to test a beta version before it's released to the public AVM registry?

![image](https://github.com/Azure/bicep-registry-modules/assets/79973892/c7e68cf9-b8b0-41cf-94dd-27b0f44e9b9a)

**Comment by ksstott** [comment]
Certainly possible for us to help test a beta version and I'd love to get early access, depends on our workload

If I have some time I would love to help implement this fix too

**Comment by gbeaud** [comment]
Sure, I'll give it a crack next week then I'm out of office for 2 weeks so if you want to propose a version please go ahead 😊

**Comment by AlexanderSehr** [comment]
> Sure, I'll give it a crack next week then I'm out of office for 2 weeks so if you want to propose a version please go ahead 😊

Hey @gbeaud just a note (that you may not have known about): To not have GH constantly add new comments & tags you can remove the `Needs: Triage 🔍` label. That's the one that bugs you to please decide what to do 😄

**Comment by gbeaud** [comment]
@ksstott the feature has been implemented on my forked repo below (thanks @AlexanderSehr for the support); I still need to figure out a few things about our internal deployment process to push it to the public Bicep registry but if you want to test it in the meantime please go ahead (it works fine in my environment but your feedback is welcome). I'll be out of office the next two weeks but will push this to the public Bicep repo upon my return 👍

https://github.com/gbeaud/bicep-registry-modules/tree/main/avm/res/cdn/profile

**Comment by ksstott** [comment]
I've not been able to test this out properly but doing some basic `what-if` checks on my end suggests that these changes look good 👍🏻
