### ISSUE TITLE
[AVM Module Issue]: documentdb/database-account bicep does not create cosmos with only capabilitiesToAdd: [ 'EnableTable' ]

### ISSUE THREAD

**Issue by DJHaose** [Azure/bicep-registry-modules#1640]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/document-db/database-account

### Description

The bare minimum requirement to spin up a document-db/database-account is name and location, I want to enable table API so under capabilitiesToAdd I have EnableTable

```bicep
module databaseAccount 'br/public:avm/res/document-db/database-account:0.4.0' = {
  name: 'databaseAccountDeployment'
  params: {
    name: 'test-cosmos-3497'
    location: 'canadacentral'
    capabilitiesToAdd: [
        'EnableTable'
    ]
  }
}
```

After this is provisioned in resource explorer I only see "EnabledApiTypes": "Sql".  I noticed in [main.bicep - line 253](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/document-db/database-account/main.bicep#L253) capabilities does not get added unless sqlDatabases, mongodbDatabases or gremlinDatabases is populated.

**Comment by AlexanderSehr** [comment]
Just a quick update on this as the notifications keep on stacking up. @bryansan-msft is currently out of office which is why nothing happened yet. Darn summer vacations.

**Comment by AlexanderSehr** [comment]
Pinged @bryansan-msft internally
