### ISSUE TITLE
[Module Proposal]: Azure Container Registry

### ISSUE THREAD

**Issue by thomasriley** [Azure/bicep-registry-modules#166]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We have a number of common base Bicep modules and CI mechanisms that we have been using (similar to the virtual-network module that already exists in this repo) however we would prefer to move forward with using modules from the Bicep community and contribute anything that we might require, if it does not already exist, in alignment with the standards set out for modules here.

Starting with a module for ACR to get familiar with the contribution process. This module will be useful to anyone who wishes to use Bicep IaC for managing the lifecycle of an ACR instance. 

Regarding the module path, looking for input on the naming conventions used here if my suggestion is not suitable. Thanks!

### Module path

compute/container-registry

### Describe the module

The module will allow for the creation of an ACR and all of the associated configuration options available for ACR (Replications, ScopeMaps, WebHooks, etc).

**Comment by alex-frankel** [comment]
My experience with ACR is that the basic resource definition has good defaults, and the type is well documented, but I don't have much experience with advanced configuration. Do you find that ACR is a difficult resource to work with in bicep?

Regarding path, I don't think `compute` would have been my first thought, but I suppose it is relevant in the context of creating compute infra, so it seems reasonable to me.

**Comment by thomasriley** [comment]
Hey Alex,

I would refer to the type of module I am proposing as a 'base' or 'generic' module and it introduces a common pattern for consuming a given Azure resource. In fact, I see the [virtual-network module](https://github.com/Azure/bicep-registry-modules/blob/main/modules/network/virtual-network/main.bicep) has already gone down this path as it allows for configuration of the VNET, VNET peering, diagnostic settings, and RBAC assignments as feature toggles of a single module via parameters. The virtual-network module sets a pattern we can now look to follow for other Azure services, such as ACR.

In the case of ACR, the Microsoft.ContainerRegistry/registries resource standalone is indeed a very simple method of creating an ACR, however typically when using ACR we would also need to configure many other resources for advanced usage. For example, in addition to the ACR instance users may need to configure replications, scope maps, tokens, plus other ACR configurations. Also, as per the virtual-network module, there are common integrations such as diagnostic settings and RBAC assignments. And last but not least, in the case of ACR I would like to see support for configuring Private Endpoints via the module parameters.

I have opened this issue for ACR as as starting point but in time we would also need base modules for other services such as AKV and AKS. We are embarking on a journey to use Bicep for IaC, so ideally would prefer to contribute these type of modules here so they are useful to the community, instead of maintaining our own private collection of Bicep base modules (which is what we are currently doing).

Thanks,
Tom.

**Comment by alex-frankel** [comment]
Ok sounds good!
