### ISSUE TITLE
[AVM Module Issue]: Storage Account Customer Managed Keys has no parameter for Queue and Table storage KeyType

### ISSUE THREAD

**Issue by jbarrancos** [Azure/bicep-registry-modules#1674]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### Description

The module does not allow to set the value for KeyType as part of the Encryption properties in the storage account (Queue/Table). This conflicts with the Azure Policies: 'Table Storage should use customer-managed key for encryption' and 'Queue Storage should use customer-managed key for encryption'. Which validates that the KeyType is set to Account. 

(Deny) Policy validation:
```
"policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Storage/storageAccounts"
          },
          {
            "field": "Microsoft.Storage/storageAccounts/encryption.keySource",
            "equals": "Microsoft.Keyvault"
          },
          {
            "field": "Microsoft.Storage/storageAccounts/encryption.services.queue.keyType",
            "notEquals": "Account"
          }
        ]
      },
```

main.json (Storage Account module):
```
  encryption: union(
      {
        keySource: !empty(customerManagedKey) ? 'Microsoft.Keyvault' : 'Microsoft.Storage'
        services: {
          blob: supportsBlobService
            ? {
                enabled: true
              }
            : null
          file: supportsFileService
            ? {
                enabled: true
              }
            : null
          table: {
            enabled: true
          }
          queue: {
            enabled: true
          }
        }
```

Please allow for table and queue to have parameters for the KeyType. This can be a combined parameter as the Portal generation does. Account or Service are the allowed values: https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?pivots=deployment-language-bicep#encryptionservice

After deploying with exempts it shows the encryption as: Enable support for customer-managed keys
**Blobs and files only** which if KeyType is correctly set would include all service types.

**Comment by fblix** [comment]
Will have a look as soon as I find some spare time!
