### ISSUE TITLE
[AVM Module Issue]: Synapse Workspace deployment overwrites existing repository configuration

### ISSUE THREAD

**Issue by Kathedra** [Azure/bicep-registry-modules#1679]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/synapse/workspace

### (Optional) Module Version

0.1.0

### Description

the workspace repository configuration is overwritten whenever the workspacerepositoryconfiguration = {} and a workspace configuration is configured manually. also, when a configuration has been set with a previous deployment and the last published commit has not been provided in this configuration, the last published commit value will be empty resulting in an out-of-sync live synapse workspace in relation to the collaboration branch.

**Comment by matebarabas** [comment]
Hi @Kathedra, thank you for submitting this issue. Please note that this module is [currently orphaned](https://github.com/Azure/Azure-Verified-Modules/issues/668) (has no owner), which may result in slower response/resolution time. I've reached out to @elanzel who migrated who originally migrated this module from CARML. She'll respond here if/when she has bandwidth to help until the @Azure/avm-core-team-technical-bicep can find a new module owner.

**Comment by Kathedra** [comment]
@matebarabas thanks for your comment. I am aware of the fact it is an orphaned module and I'm okay with the response time being longer.
