### ISSUE TITLE
[AVM Module Issue]: VPN Gateway public ip incorrect configuration

### ISSUE THREAD

**Issue by teemukom** [Azure/bicep-registry-modules#1685]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/virtual-network-gateway

### (Optional) Module Version

0.1.1

### Description

If vpn gateway **skuName** is part of variable **zoneRedundantSkus** the public ip allocation method is set to Dynamic. Dynamic is only allowed when public ip sku is Basic. This leads to an error when the vpn sku is VpnGw1 (for example) where Basic IP configuration isn't supported

`Basic IP configuration for VPN Virtual Network Gateways is not supported. Follow the link for more details : https://go.microsoft.com/fwlink/p/?linkid=2241350 (Code: PublicIpWithBasicSkuNotAllowedOnVPNGateways)
`

Basic IP configuration is only allowed in the Basic SKU of VPN Gateway (support for Standard IP SKU is coming).

**Comment by fabmas** [comment]
Thank you @teemukom, I will handle this matter promptly.

**Comment by spaelling** [comment]
first time using AVM and just ran into this one :(
