### ISSUE TITLE
[AVM Module Issue]: Strict defaultDataLakeStorage transform

### ISSUE THREAD

**Issue by Wesleyrbk** [Azure/bicep-registry-modules#1690]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/synapse/workspace

### Description

Our current synapse workspace is deployed with a "/" at the end of the accountUrl for the defaultDataLakeStorage. It seems like the current AVM version transforms it without a "/". But due to this the deployment will try to update this particular value but is not able to and throws the following error: "DefaultDataLakeStorageCannotBeUpdated".

One way to resolve this is to recreate the entire workspace, but I rather not go through that proces.

**Comment by matebarabas** [comment]
Hi @Wesleyrbk, thank you for submitting this issue. Please note that this module is [currently orphaned](https://github.com/Azure/Azure-Verified-Modules/issues/668) (has no owner), which may result in slower response/resolution time. I've reached out to @elanzel who originally migrated this module from CARML. She'll respond here if/when she has bandwidth to help until the @Azure/avm-core-team-technical-bicep can find a new module owner.

**Comment by AlexanderSehr** [comment]
Hey @Wesleyrbk,
out of curiosity, does that mean it's just this calculated value that is the problem:
https://github.com/Azure/bicep-registry-modules/blob/e4baf3f37bab7dff7879e9c70ca5a4053616a447/avm/res/synapse/workspace/main.bicep#L189
so it might just solve it for you by updating it to something like
```bicep
param accountUrl string = 'https://${last(split(defaultDataLakeStorageAccountResourceId, '/'))!}.dfs.${environment().suffixes.storage}'

  (..)
  accountUrl: accountUrl
  (..)
```
which would allow you to overwrite the `accountUrl` value with your own custom one?

**Comment by Wesleyrbk** [comment]
Correct, I resolved the issue by pulling the module locally and adding a "/" at the end of that specific property.

**Comment by AlexanderSehr** [comment]
Alright then. Given that the module does not have an owner yet is a quick fix, I'll assign it to myself to work on it once I find a minute. 🤞
