### ISSUE TITLE
[Bug Report]:  AuthRule bicep referenced in queue bicep does not retrieve rights

### ISSUE THREAD

**Issue by Palving** [Azure/bicep-registry-modules#1694]
### Describe the bug

We've recently started developing biceps that wrap the resourcemodules located in this repository. Passing a value in authorizationRules or using the default value for authorizationRules in queue/deploy.bicep gives the following error 
```json
{
    "status": "Failed",
    "error": {
        "code": "EmptyAccessRights",
        "message": "Empty access rights. Supported claims count 3"
    }
}
```
We can also see this in the deployment itself
![image](https://user-images.githubusercontent.com/32174226/223110630-944dac16-f0e9-4175-8d0f-372bf266da02.png)

Setting authorizationRules to an empty array works as this makes sure we avoid calling the sub-bicep for authorizationRules. 

Error occurs in rights-parameter in this bicep 
![image](https://user-images.githubusercontent.com/32174226/223111674-951868ab-29fa-4f45-a94c-754bb38b2c95.png)

### To reproduce

Deploy a queue with with default authorizationRules

### Code snippet

```Bicep
This does not work as default parameter is used

@description('Optional. Authorization Rules for the Service Bus Queue.')
var authorizationRules  = [
  
]

module queue 'br:***.azurecr.io/resourcemodules/microsoft.servicebus/namespaces/queues:2023-02-16' = {
  name: '${queueName}-namespaces.queue-${deploymentSuffix}'
  params: {
    name:queueName
    namespaceName:serviceBusName
    duplicateDetectionHistoryTimeWindow: 'PT10M'
    enableBatchedOperations:             enableBatchedOperations
    enableExpress:                       enableExpress
    enablePartitioning:                  enablePartitioning
    maxSizeInMegabytes:                  maxSizeInMegabytes
    requiresDuplicateDetection:          requiresDuplicateDetection
    defaultMessageTimeToLive:            defaultMessageTimeToLive
    maxDeliveryCount:                    maxDeliveryCount
   // authorizationRules:authorizationRules

    
  }
}

This works as no rule is setup
@description('Optional. Authorization Rules for the Service Bus Queue.')
var authorizationRules  = [
  
]

module queue 'br:***.azurecr.io/resourcemodules/microsoft.servicebus/namespaces/queues:2023-02-16' = {
  name: '${queueName}-namespaces.queue-${deploymentSuffix}'
  params: {
    name:queueName
    namespaceName:serviceBusName
    duplicateDetectionHistoryTimeWindow: 'PT10M'
    enableBatchedOperations:             enableBatchedOperations
    enableExpress:                       enableExpress
    enablePartitioning:                  enablePartitioning
    maxSizeInMegabytes:                  maxSizeInMegabytes
    requiresDuplicateDetection:          requiresDuplicateDetection
    defaultMessageTimeToLive:            defaultMessageTimeToLive
    maxDeliveryCount:                    maxDeliveryCount
    authorizationRules:authorizationRules

    
  }
}
```

**Comment by AlexanderSehr** [comment]
Hey @ChrisSidebotham, just transfered the issue from CARML. Seems to be still a concern in AVM and fixed & covered via our test cases.

If I'm not mistaken, the default in question is this one
https://github.com/Azure/bicep-registry-modules/blob/b5d76b9c9931ba130db315643edcfc064e855bd2/avm/res/service-bus/namespace/queue/main.bicep#L75-L86

**Comment by ChrisSidebotham** [comment]
Thanks @AlexanderSehr are we saying the default should be `rights: []`? @Palving

**Comment by Palving** [comment]
Either works for us, we always define the authorization rules ourselves and pass it to the parameter. 

In my opinion however it should be empty by default, as developers should know what rights they are configuring by defining the rules themselves.

**Comment by AlexanderSehr** [comment]
Fair point. I'm not the original author and don't know why it was implemented this way (e.g. maybe because via the portal the `RootManageSharedAccessKey` would be configured with these permissions by default, but I don't know). I'll leave the decision to people that know the service 😄

**Comment by rodney-almeida** [comment]
Same, i don't know the service intimately to know what should or should not be configured. I just know that the current default value for the parameter with the resource module coding does not work. From a purely bicep coding point of view, either remove default value and make it mandatory or have a default value that works.

**Comment by ChrisSidebotham** [comment]
@Palving - PR Opened sorry for the delay on this

**Comment by AlexanderSehr** [comment]
The pipeline run after merge failed so a new version is not yet published. Just re-triggered the failed jobs to get it resolved. A new version should be available shortly
