### ISSUE TITLE
Virtual network module : Empty value for Route table/Network security group resource ID fails in loop

### ISSUE THREAD

**Issue by vipulkelkar** [Azure/bicep-registry-modules#1699]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/network/virtual-network

### (Optional) Module Version

0.1.5

### Description

Using the Virtual network module to create Vnet and several Subnets. The subnets for multiple environments are configured in the respective **.bicepparam** files. Made use of 'for' loop to iterate over the subnet configuration and create multiple subnets. For subnets where no Route table or Network security group is to be associated, passing an empty ('')  value fails. 
The module does not throw error if the property is not passed at all as explained in the 'usage examples' in documentation. However, it seems that if the property is passed, the module expects a non-empty value

Error : 
[{"code":"LinkedInvalidPropertyId","message":"Property id '' at path 'properties.subnets[0].properties.networkSecurityGroup.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."}]}]}]}}

![image](https://github.com/Azure/bicep-registry-modules/assets/13727430/a3bacd1e-2761-4220-8bb2-3f2cc07d1660)

Sample Subnet configuration in bicepparam file

![image](https://github.com/Azure/bicep-registry-modules/assets/13727430/613eb523-1f5e-48ed-b19f-6a42de33f02a)

The Azure Bicep resource for Subnets does accept empty values.

### (Optional) Correlation Id

-

**Comment by elbatane** [comment]
Hi, there is another issue where we are solving the same issue: https://github.com/Azure/bicep-registry-modules/issues/1026

**Comment by elbatane** [comment]
@vipulkelkar this issue has been addressed here: https://github.com/Azure/bicep-registry-modules/pull/1772. I am going o close this issue.
