### ISSUE TITLE
[AVM Module Issue]: Application Gateway not present in AVM?

### ISSUE THREAD

**Issue by janvanuytrecht** [Azure/bicep-registry-modules#1703]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/application-gateway-web-application-firewall-policy

### Description

Only the AGW WAF policy module is foreseen to be able to link it to an Application Gateway. Front door module is present with its policy module.
Application Gateway module (which was available in the previous modules setup) is missing it seems.

Is there a reason behind this or work in progress?

**Comment by janvanuytrecht** [comment]
FYI, the pipeline to set an owner to an issue fails. Dunno if it's according to your process, but I'll loop te owner of the policy module @ilhaan

**Comment by janvanuytrecht** [comment]
My Apoligies, I checked https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/ planning and AGW is on the road map. Any idea on a timeline perhaps?

**Comment by janvanuytrecht** [comment]
Maybe we can contribute via porting the previous module?

**Comment by ilhaan** [comment]
@janvanuytrecht The AppGw module is already being migrated and PR is being reviewed: https://github.com/Azure/bicep-registry-modules/pull/835

**Comment by janvanuytrecht** [comment]
Great! Sorry that I missed that, closing the issue
