### ISSUE TITLE
[AVM Module Issue]: web site without system or managed identity

### ISSUE THREAD

**Issue by scrocquesel-ml150** [Azure/bicep-registry-modules#1704]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/site

### Description

With

```bicep
{
    managedIdentities: {
        systemAssigned: false
        userAssignedResourceIds: []
    }    
}
```

the template will generate:

```bicep
identity: {
    type: null
    userAssignedIdentities: null
}
```

where it should be

```bicep
identity: {
    type: 'None'
    // not sure if null is supported but {} (empty object) is not.
    // I usually don't set the userAssignedIdentities property at all when empty and type does not contain UserAssigned
    userAssignedIdentities: null 
}
```

https://github.com/Azure/bicep-registry-modules/blob/6e086ba1bd31e3199954fbead329cf88d621a2ca/avm/res/web/site/main.bicep#L172

**Comment by tsc-buddy** [comment]
Hey @scrocquesel-ml150 - thanks for submitting the issue. We will take a look and triage this issue. I will aim to triage next week but it is a short week for us in NZ. I'll keep the issue posted.
