### ISSUE TITLE
[Bug Report]: aks-run-command does not fail on error

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#174]
### Module path

/modules/deployment-scripts/aks-run-command

### Bicep version

0.9.1

### Describe the bug

When running commands to AKS, if the command fails, this step continues as if it succeeded. This can lead to surprising outcomes in a deployment process. It is difficult to determine this step is responsible in a large pipeline when it finishes as "Succeeded".

### To reproduce

Running an AKS command which raises an error. (I have some branches to repro)

### Relevant log output

```Shell
...
Installing it now.
Error: execution error at (workload-identity-webhook/templates/azure-wi-webhook-config-configmap.yaml:4:22): A valid .Values.azureTenantID entry required!
", "provisioningState": "Succeeded", "reason": null, "startedAt": "2022-10-03T22:39:26+00:00" }
```

**Comment by Gordonby** [comment]
It's an interesting problem. Depending on the commands sent will change your measure of success.

Technically the deployment script worked great, but the objective of the users script was not met.

We won't be able to fail the deployment because of an error, but we could create a new output to try to indicate success. I just wonder if that will be useful.

**Comment by dciborow** [comment]
So, my original statement wasn't completely accurate, it seems the task does sometimes fail on error. I'm not sure why it fails for some issues but not others.

The Script task fails with the error: `"Unable to evaluate template outputs: 'commandOutput'. Please see error details and deployment operations. Please see https://aka.ms/arm-debug for usage details."`

This is possibly caused by a bug, where we should check to see if outputs exist before calling it. But it has a nice side effect of failing the task right now.
https://github.com/Azure/bicep-registry-modules/blob/03478531a2971aa819a0c232c1e79ac6bdbf5693/modules/deployment-scripts/aks-run-command/main.bicep#L136

I am able to reproduce this pretty easily trying to setup a workload identity on a subscription which has not set the following. 

While having the task fail is desired, would still like to have some errror output that is a bit more meaningful.
```
az feature register --namespace "Microsoft.ContainerService" --name "EnableWorkloadIdentityPreview"

az provider register --namespace Microsoft.ContainerService
```

**Comment by ChrisSidebotham** [comment]
Dear @dciborow , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
