### ISSUE TITLE
[AVM Module Issue]: Key Vault compiling errors

### ISSUE THREAD

**Issue by HadiMasri** [Azure/bicep-registry-modules#1740]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/key-vault/vault

### Description

I'm getting the following errors when trying to deploy key vault:
Error BCP293: All members of a union type declaration must be literal values.
Error BCP279: Expected a type at this location. Please specify a valid type expression or one of the following types: "array", 
"bool", "int", "object", "string".
Error BCP236: Expected a new line or comma character at this location.
Error BCP317: Expected an identifier, a string, or an asterisk at this location.
Error BCP296: Property names on types must be compile-time constant values.
Error BCP018: Expected the ":" character at this location.
Error BCP293: All members of a union type declaration must be literal values.
Error BCP279: Expected a type at this location. Please specify a valid type expression or one of the following types: "array", "bool", "int", "object", "string".
Error BCP236: Expected a new line or comma character at this location.
Error BCP317: Expected an identifier, a string, or an asterisk at this location.

<img width="745" alt="image" src="https://github.com/Azure/bicep-registry-modules/assets/46171322/1742d276-4417-4c0b-84bb-47536188b825">

**Comment by cloudchristoph** [comment]
Hello @HadiMasri,

I've tried to replicate your issue with your given code and couldn't reproduce this. I'm using the published module version here.

Here is my complete code - as short as possible, but also using your parameter definitions:

```bicep
targetScope = 'subscription'

param location string = 'westeurope'

param usecaseDevTestLab string = 'devtestlab-cc'
param keyVaultName string = '${usecaseDevTestLab}-kv'
param keyVaultSku string = 'standard'

resource devTestLabRG 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: '${usecaseDevTestLab}-rg'
  location: location
}

module keyVaultModule 'br/public:avm/res/key-vault/vault:0.5.1' = {
  name: '${usecaseDevTestLab}-kv'
  scope: devTestLabRG
  params: {
    location: location
    name: keyVaultName
    sku: keyVaultSku
    enableRbacAuthorization: true
  }
}
```

Here is my deployment result:
![image](https://github.com/Azure/bicep-registry-modules/assets/204027/e7e4cec0-bc71-4ec5-aee1-948cbfdde86e)


I'm using Bicep CLI 0.26.170 - maybe you wan't to check for the version you're using and also for errors elsewhere in your code or your cloned version of this repo.

**Comment by AlexanderSehr** [comment]
> ### Check for previous/existing GitHub issues
> * [x]  I have checked for previous/existing GitHub issues
> 
> ### Issue Type?
> Bug
> 
> ### Module Name
> avm/res/key-vault/vault
> 
> ### (Optional) Module Version
> _No response_
> 
> ### Description
> I'm getting the following errors when trying to deploy key vault: Error BCP293: All members of a union type declaration must be literal values. Error BCP279: Expected a type at this location. Please specify a valid type expression or one of the following types: "array", "bool", "int", "object", "string". Error BCP236: Expected a new line or comma character at this location. Error BCP317: Expected an identifier, a string, or an asterisk at this location. Error BCP296: Property names on types must be compile-time constant values. Error BCP018: Expected the ":" character at this location. Error BCP293: All members of a union type declaration must be literal values. Error BCP279: Expected a type at this location. Please specify a valid type expression or one of the following types: "array", "bool", "int", "object", "string". Error BCP236: Expected a new line or comma character at this location. Error BCP317: Expected an identifier, a string, or an asterisk at this location.
> 
> <img alt="image" width="745" src="https://private-user-images.githubusercontent.com/46171322/324518496-1742d276-4417-4c0b-84bb-47536188b825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNTM2NzUsIm5iZiI6MTcxNDE1MzM3NSwicGF0aCI6Ii80NjE3MTMyMi8zMjQ1MTg0OTYtMTc0MmQyNzYtNDQxNy00YzBiLTg0YmItNDc1MzYxODhiODI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE3NDI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNTExYjhkNTZlYTcyZDQ0NjZlY2I2MmY4NGEwMDM0YmQyZDg0YzM2ZjIyODM0M2JhMWI0YWZiM2ZiMDExM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pVKSi8Q_v-pjeOcwZmpvKt1lstKsDCYNhteugQLQ30A">
> ### (Optional) Correlation Id
> _No response_

Hey @HadiMasri,

thanks for opening the issue & @cloudchristoph for replying. Could you please check which Bicep version you're using? There is always a fair chance something was added that is only available in later Bicep versions - especially with respect to the Bicep CLI. To check, please run

```
bicep --version
```
for the Bicep CLI

and 
``` 
az bicep version
``` 
for the Aure CLI Bicep extension. The current latest is `v0.26.170`.
