### ISSUE TITLE
[AVM Module Issue]: Add support for PowerShell Core 'PowerShell72' as a Automation Runbook type

### ISSUE THREAD

**Issue by vipulkelkar** [Azure/bicep-registry-modules#1743]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/automation/automation-account

### (Optional) Module Version

0.4.1

### Description

Creation of 'PowerShell core' runbook is now supported through Azure Bicep, refer [runbookType](https://learn.microsoft.com/en-us/azure/templates/microsoft.automation/automationaccounts/runbooks?pivots=deployment-language-bicep#runbookcreateorupdatepropertiesorrunbookproperties)

The AVM module for Automation Account, does not support **"PowerShell72"** as a [runbook type](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/automation/automation-account/runbook#parameter-type). The allowed values at the moment are as below and the module fails when 'PowerShell72' is supplied as a type

**_'The provided value for the template parameter 'type' is not valid. The value 'PowerShell72' is not part of the allowed value(s):_**

[
  'Graph'
  'GraphPowerShell'
  'GraphPowerShellWorkflow'
  'PowerShell'
  'PowerShellWorkflow'
]

**Comment by AlexanderSehr** [comment]
Hey @elanzel, could you please take a look at your earliest convenience? :)

**Comment by elanzel** [comment]
Hi, i'm doing it
