### ISSUE TITLE
[AVM Module Issue]: virtual machine module diskname

### ISSUE THREAD

**Issue by jkamping** [Azure/bicep-registry-modules#1747]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.2.3

### Description

I am trying to change the defaultname off the osdisk within the virtual machine template, the syntax looks right but it seems to ignore my settings. I included the example from my code

    osDisk: {
      caching: 'ReadWrite'
      createOption: 'FromImage'
      deleteOption: diskDeleteOption
      diskSizeGB: '128'
      managedDisk: {
        storageAccountType: diskStorageAccountType
      }
      name: 'OSDISK'
    }

**Comment by rahalan** [comment]
@jkamping Thanks for bringing it up. I will look into it

**Comment by rahalan** [comment]
@jkamping Please use the newest version 4.0 of the VM module. There it is fixed. 
![image](https://github.com/Azure/bicep-registry-modules/assets/61878316/e1b98ff2-1641-4f57-a1be-935b59927610)
![image](https://github.com/Azure/bicep-registry-modules/assets/61878316/79e82f6f-b18b-4490-88fb-1650b0d5cc3f)
