### ISSUE TITLE
[AVM Module Issue]: Microsoft.ContainerService/managedClusters

### ISSUE THREAD

**Issue by zensqlmonitor** [Azure/bicep-registry-modules#1752]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/container-service/managed-cluster

### Description

Hello,

In our Azure Landing Zone definition, all private DNS zones are precreated in a dedicated subscription and RG.
We are registering the cluster API (and all private endpoints in general) in these zones with Azure Policy.
With this, we avoid to give any permission to the DEVs on these central DNS zones.

Unfortunately, it is not possible with AKS for a private cluster.

When I set 'None' to the parameter privateDNSZone the deployment failed with this error: _Private cluster with none private dns zone must enable public FQDN feature._ Which is normal, as defined in the documentation The default is public DNS. AKS won't create a private DNS zone.

We want to avoid giving Private DNS Zone Contributor to the MI of the cluster and let Azure Policy doing the job. 
Is there any solution for this ?
 
Reference:
https://learn.microsoft.com/en-us/azure/aks/private-clusters?tabs=azure-portal#configure-private-dns-zone

**Comment by JPEasier** [comment]
Hi @zensqlmonitor,
As far as I can see from my current knowledge, there is no way to enable a private dns zone configuration in aks without providing the resource id and aks permissions.

I will have to take a closer look if and how this might be possible.

If it is not technically possible, then we can't help here, this must be a feature request to the AKS product group.

**Comment by zensqlmonitor** [comment]
@AlexanderSehr @JPEasier 

To be clear for the AKS product team, the target for me is to have a private cluster **without** providing the DNS Zone ID as it required advanced permissions and done by an Azure policy.

Do I have to open support ticket to accelerate this ?

**Comment by AlexanderSehr** [comment]
Personally, I don't know the ins & outs of AKS on that level, so I have to rely on @JPEasier & @ilhaan.
I will however point out that neither of them are part of the AKS product group which may take an interest into the module, but in general are more concerned with the API itself than what's build on top of it (like ARM/Bicep). Which in turn also means that IF this is a non-supported scenario by the service itself today, it would require a ticket to the PG (e.g. via a support ticket). But IF it is instead actually supported already and just not by this module, the aforementioned owners should update the module to enable this scenario. But I'll leave that to the experts to discuss 😄

**Comment by zensqlmonitor** [comment]
@AlexanderSehr I confirm this is a supported scenario with other services/modules where a private endpoint can be set.

For example, for an App Service, we just need to set these properties and an Azure Policy will set the DNS registration.

 privateEndpoints: [   
      {   
        name: '${varAppServicePepName}-${appService.ix}' 
        service: 'sites'
        subnetResourceId: varSubnetPepResourceId
      }
    ]

**Comment by zensqlmonitor** [comment]
bump. 
Any news from the product team ? 
@JPEasier @ilhaan

**Comment by JPEasier** [comment]
@zensqlmonitor

after some internal research, the current bicep definition template dose not support this feature.
https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters?pivots=deployment-language-bicep

As the AVM team  only build a module based on the available resource definition and API version, we cannot help here,
the PG is primarily responsible for updating the resource functionality.

as @AlexanderSehr has already suggested, a support tiket should be opened for this, but this must come from a customer.

I would also like to point out that even if the PG looks at this request, it is very difficult to estimate whether and when the feature will be implemented.

sorry that we can't help you here.
