### ISSUE TITLE
[AVM Module Issue]: automation-account/runbook allow Python3 in type parameter 

### ISSUE THREAD

**Issue by jonnywinter** [Azure/bicep-registry-modules#1757]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/automation/automation-account

### Description

Within the module for automation-account/runbook, the type parameters are limited to - 
```json
[
  'Graph'
  'GraphPowerShell'
  'GraphPowerShellWorkflow'
  'PowerShell'
  'PowerShellWorkflow'
]
```
... however, the allowed values [here on microsoft.com](https://learn.microsoft.com/en-us/azure/templates/microsoft.automation/automationaccounts/runbooks?pivots=deployment-language-bicep) are - 
```json
[
  'Graph'
  'GraphPowerShell'
  'GraphPowerShellWorkflow'
  'PowerShell'
  'PowerShell72'
  'PowerShellWorkflow'
  'Python2'
  'Python3'
  'Script' 
]
```
Would it be possible to add the rest in? Or at least the Python ones? Apologies if there is more under the hood that is preventing this from being added that I haven't considered.

**Comment by AlexanderSehr** [comment]
Hey @elanzel, please take a look at your earliest convenience :)

**Comment by elanzel** [comment]
adding it
