### ISSUE TITLE
[AVM Module Issue]: avm/res/network/virtual-network - update API version

### ISSUE THREAD

**Issue by janegilring** [Azure/bicep-registry-modules#1758]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/virtual-network

### (Optional) Module Version

0.1.5

### Description

The module is [currently leveraging](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/network/virtual-network/main.bicep#L96) API-version Microsoft.Network/virtualNetworks@2023-04-01.

I would like to propose updating the API version to 2023-11-01, which supports [Azure Virtual Network now supports updates without subnet property](https://techcommunity.microsoft.com/t5/azure-networking-blog/azure-virtual-network-now-supports-updates-without-subnet/ba-p/4067952).

**Comment by elbatane** [comment]
Hi @janegilring , could you create a PR with he change proposed and link this issue?
