### ISSUE TITLE
[AVM Module Issue]: For Front door route, please support multiple custom domains 

### ISSUE THREAD

**Issue by keikoang** [Azure/bicep-registry-modules#1759]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cdn/profile

### Description

According to official bicep documentation, https://learn.microsoft.com/en-us/azure/templates/microsoft.cdn/profiles/afdendpoints/routes?pivots=deployment-language-bicep, a certain property called "customDomains" accept an array of object ids. In the AVM module, it is only allowed to supply one custom domain name (parameter "customDomainName"). Could you make it such as multiple domains are supported in the AVM module?

**Comment by AlexanderSehr** [comment]
Duplication of #1639. The good news is @keikoang, @gbeaud is already on it and there is a solution in sight 💪
