### ISSUE TITLE
[AVM Module Issue]: compute/virtual-machine needs support for VMSS Flex

### ISSUE THREAD

**Issue by hooverken** [Azure/bicep-registry-modules#1760]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

current

### Description

I want to use this module to add VMs to an existing VMSS.  There seems to be no way to actually do this, though the documentation refers multiple times to things that are not compatible with VMSS such as explicit zone assignments and putting the VM into an availability set.

The ARM reference for [Microsoft.Compute/virtualMachines](https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines) shows that all that's needed is the resource ID of the target VMSS so hopefully this is an easy add.  I may take a shot at it myself.

  virtualMachineScaleSet: {
    id: 'string'
  }

**Comment by rahalan** [comment]
@hooverken thanks! I will invesigate

**Comment by rahalan** [comment]
@hooverken will be solved with #1835
