### ISSUE TITLE
[AVM Module Issue]: VM can't have a DNS name set on their PIP

### ISSUE THREAD

**Issue by drewmacphee** [Azure/bicep-registry-modules#1775]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### Description

 dnsSettings: '<dnsSettings>' is missing from module networkInterface_publicIPAddresses 'br/public:avm/res/network/public-ip-address:0.2.1' in avm/res/compute/virtual-machine/modules/nic-configuration.bicep so can't set a DNS name for VMs.

**Comment by rahalan** [comment]
@drewmacphee I will investigate. Thanks for bringing it up.
