### ISSUE TITLE
[AVM Module Issue]: Missing "supressFailures" Parameter in Bicep

### ISSUE THREAD

**Issue by Voteax** [Azure/bicep-registry-modules#1779]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### Description

In the Bicep Template the Parameter "supressFailures" for extensions is missing.
The ARM Template (json) has this Parameter. Would be great if it can also be implemented in the Bicep Template.

**Comment by rahalan** [comment]
@Voteax thanks for bringing this up. I will look into it.

**Comment by rahalan** [comment]
@Voteax will be added with PR #1835
