### ISSUE TITLE
[AVM Module Issue]: Deploy Azure Firewall Across Availability zones

### ISSUE THREAD

**Issue by maurojasmsft** [Azure/bicep-registry-modules#1796]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/azure-firewall

### Description

Module not compliant with APRL: https://azure.github.io/Azure-Proactive-Resiliency-Library-v2/azure-resources/Network/azureFirewalls/#deploy-azure-firewall-across-multiple-availability-zones

Per: https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr5---category-composition---availability-zones

Modules that deploy zone-redundant resources MUST enable the spanning across as many zones as possible by default, typically all 3.

Modules that deploy zonal resources MUST provide the ability to specify a zone for the resources to be deployed/pinned to. However, they MUST NOT default to a particular zone by default, e.g. 1 in an effort to make the consumer aware of the zone they are selecting to suit their architecture requirements.

For both scenarios the modules MUST expose these configuration options via configurable parameters/variables.

Ask: The AZs parameter (zones) should be defaulted to [1,2,3] to span across all zones as its a PaaS resource

**Comment by hundredacres** [comment]
@maurojasmsft aren't the defaults of this module already in alignment with the proposed suggestions:

`@description('Optional. Zone numbers e.g. 1,2,3.')
param zones array = [
  '1'
  '2'
  '3'
]`

**Comment by AlexanderSehr** [comment]
> @maurojasmsft aren't the defaults of this module already in alignment with the proposed suggestions:
> 
> `@description('Optional. Zone numbers e.g. 1,2,3.') param zones array = [ '1' '2' '3' ]`

I agree. @maurojasmsft, could you elaborate?

That's what I see in the module
https://github.com/Azure/bicep-registry-modules/blob/3cfea57db03dc0d73fbad40a8a2924e6cb54fcdc/avm/res/network/azure-firewall/main.bicep#L63-L67

**Comment by hundredacres** [comment]
@AlexanderSehr This issue might also be fixed by https://github.com/Azure/bicep-registry-modules/pull/1939, as I had to update the formatting of the zones param.

**Comment by maurojasmsft** [comment]
I just came back from vacation. The problem is that this is optional when it should be mandatory. Can we make it mandatory to make  AZs parameter (zones) to be defaulted to [1,2,3] and span across all zones.

**Comment by hundredacres** [comment]
I set the param to conditional and indicated it was for WAF Alignment. The defaults do deploy to 3 zones.

PR: https://github.com/Azure/bicep-registry-modules/pull/2021

**Comment by eriqua** [comment]
Hey @maurojasmsft thanks for raising this issue.
I also share some confusion regarding this request.

The parameter type is `Optional` because of the default value already covering the WAF requirement. Making it mandatory (`Required`) would mean to remove the default value.

The type `Conditional`, on the other hand, is usually for parameters optional by default, but becoming required under a specific condition. For example, required if a different parameter is set to a certain value. They also require to specify the condition under which they become mandatory in the description metadata.

Given the above, I don't think this parameter type should change, but open for discussion 🙂

**Comment by maurojasmsft** [comment]
@eriqua I confirmed within my team and I think I understand better that the default value is to deploy all 3 zones in the Azure Firewall. Thanks a lot you may close the issue

**Comment by hundredacres** [comment]
Closing issue.
