### ISSUE TITLE
[AVM Module Issue]: VM Image Template module should support setting `optimize` property

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/bicep-registry-modules#1799]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/virtual-machine-images/image-template

### (Optional) Module Version

0.1.1

### Description

See https://learn.microsoft.com/azure/virtual-machines/linux/image-builder-json?tabs=bicep%2Cazure-powershell#properties-optimize

**Comment by ahmadabdalla** [comment]
@SvenAelterman thanks for raising the feature request. A PR has been raised and linked to this issue. Pending review

**Comment by AlexanderSehr** [comment]
Hey @ahmadabdalla, please note that I removed the `Needs: Triage 🔍` label as it tends to continuously add new comments to issues or pull request 😉 Just fyi
