### ISSUE TITLE
[AVM Module Issue]: SQL Server module adding support for auditingSettings

### ISSUE THREAD

**Issue by peterbud** [Azure/bicep-registry-modules#1825]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/sql/server

### Description

It would be great to have support for [auditingSettings](https://learn.microsoft.com/en-us/azure/templates/microsoft.sql/2022-05-01-preview/servers/auditingsettings?pivots=deployment-language-bicep). Proper SQL Server audit settings are now required by many internal compliance scans, so that would be a great addition.

**Comment by peterbud** [comment]
In case the maintainer is unavailable, should I maybe try to add this feature with a new PR?

**Comment by AlexanderSehr** [comment]
Hey @peterbud,
openening a PR is always an option. Yet, it's not exactly how this should go. I'll reach out to the maintainer internally too. I think he's back. Sorry for the inconvenience.

**Comment by bryansan-msft** [comment]
Hello, @peterbud and @AlexanderSehr, if Peter is happy to open a PR I am fine with it as long as we add a test for this new feature. I don't have availability to tackle this immediately so it will take a month or so for me to have a PR.

I don't think this feature is something complicated or critical. They are just a bunch of new options that we can group in a new UDT for these settings.
