### ISSUE TITLE
[AVM Module Issue]: DiskSizeGB Parameter has an incorrect Max Value.

### ISSUE THREAD

**Issue by drewmacphee** [Azure/bicep-registry-modules#1836]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.4.0

### Description

In 0.4.0 DiskSizeGB parameter is set to maxvalue of 1023, limiting disks to less than 1TB. This isn't a correct limit for disks.

"diskSizeGB": {
          "type": "int",
          **"maxValue": 1023,**
          "metadata": {
            "description": "Required. Specifies the size of an empty data disk in gigabytes."
          }
        },

**Comment by rahalan** [comment]
@drewmacphee Thanks, will look into it

**Comment by rahalan** [comment]
@drewmacphee according to the documentation, that is the maximum allowed value, see: 
![image](https://github.com/Azure/bicep-registry-modules/assets/61878316/0e334e24-0ebe-4325-a9f1-d3baae3b50a2)

**Comment by drewmacphee** [comment]
Hmm. What documentation? https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/disks?pivots=deployment-language-arm-template shows no max: 
diskSizeGB | If creationData.createOption is Empty, this field is mandatory and it indicates the size of the disk to create. If this field is present for updates or creation with other options, it indicates a resize. Resizes are only allowed if the disk is not attached to a running VM, and can only increase the disk's size. | int
Also: 
What is the largest managed disk size supported for operating system and data disks on Gen1 VMs?
The partition type that Azure supports for Gen1 operating system disks is the master boot record (MBR). Although Gen1 OS disks only support MBR the data disks support GPT. While you can allocate up to a 4-TiB OS disk, the MBR partition type can only use up to 2 TiB of this disk space for the operating system. Azure supports up to 32 TiB for managed data disks.

What is the largest Managed disk size supported for operating system and data disks on Gen2 VMs?
The partition type that Azure supports for Gen2 operating system disks is GUID Partition Table (GPT). Gen2 VMs support up to a 4-TiB OS disk. Azure supports up to 32 TiB for managed data disks.

What is the largest unmanaged disk size supported for operating system and data disks?
The partition type that Azure supports for an operating system disk using unmanaged disks is the master boot record (MBR). While you can allocate up to 4 TiB for an OS disk, the MBR partition type can only use up to 2 TiB of this disk space for the operating system. Azure supports up to 4 TiB for unmanaged data disks. From: https://learn.microsoft.com/en-us/azure/virtual-machines/faq-for-disks?tabs=azure-portal#new-disk-sizes

I'm also looking at a list of about 100 disks of 1024 and one of 4096 in my sub right now, so that can't be accurate. 
But thanks for looking into it so quickly!

**Comment by rahalan** [comment]
@drewmacphee Thanks for bringing that up. I will investigate further. My screenshot was from the ARM reference: https://learn.microsoft.com/en-us/azure/templates/Microsoft.Compute/2023-09-01/virtualMachines?pivots=deployment-language-bicep#datadisk

**Comment by jbarrancos** [comment]
It is correct that the referenced documentation does give this limitation, but i don't think this is correct. This is now giving issues as some VM's (most), i cannot move to AVM due to this issue.
