### ISSUE TITLE
[AVM Module Issue]: Doc bug nicConfigurations in Microsoft.Compute/virtualMachineScaleSets

### ISSUE THREAD

**Issue by mark-casey** [Azure/bicep-registry-modules#1851]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine-scale-set

### Description

nicConfigurations is marked as Required:No in the [parameter docs](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/compute/virtual-machine-scale-set#parameter-nicconfigurations) of Microsoft.Compute/virtualMachineScaleSets, but if I try to deploy one without nic I get:

```
Status Message: VM scale set network profile /subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Compute/virtualMachineScaleSets/xxxxxxxx/updateGroups/xxxxxxxxxxxxxx has no network interface configurations. (Code: VMScaleSetNetworkProfileHasNoNetworkInterfaceConfigs)
```

Naturally no one is going to get much use out of VMs with no network interfaces; I only tried it once with the nicConfigurations commented out to test the rest of my module call and then would have come back and completed that section. So it is not that I really want to do this, I just thought I could as a quick test because the doc said it was not required.

**Comment by rahalan** [comment]
@mark-casey Thanks. Will look into it.

**Comment by rahalan** [comment]
@mark-casey There was an error in the documentation. Will fix it
