### ISSUE TITLE
[AVM Module Issue]: container-instance/container-group doesnt allow for secure environmentVariables to be passed

### ISSUE THREAD

**Issue by rodney-almeida** [Azure/bicep-registry-modules#1868]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Security Bug

### Module Name

avm/res/container-instance/container-group

### Description

Current module doesn't allow for secure environmentVariables to be passed "securely".
This is an attribute of the containers object and therefore any environment variables passed will appear as plain text in the deployment.

Is there a way to decouple that attribute from the containers object as to pass it in a different parameter that can have the `secure()` decorator and then marry it back up with the object in the module?

I have done this for my specific requirement but have therefore not allowed for containers to be an array (as i only need to deploy 1).
Eg:
Module file: 
<img width="380" alt="image" src="https://github.com/Azure/bicep-registry-modules/assets/64196999/55660a93-4150-4fb7-b43f-56b8e51c0565">
<img width="329" alt="image" src="https://github.com/Azure/bicep-registry-modules/assets/64196999/f7607d54-5ba9-4efa-9577-1af9f4696ecd">

Calling bicep:
<img width="266" alt="image" src="https://github.com/Azure/bicep-registry-modules/assets/64196999/d8cc0fee-ed73-4d91-9f93-ebf8e303a750">

Of course this example above is not the best approach for this AVM module as it is limiting but happy to assist in modifying the module once approved approach is decided.

Thanks

**Comment by AlexanderSehr** [comment]
Hey @rodney-almeida, we should be able to achieve this by introducing a User Defined Type and specifying e.g., the `environmentVariables` property as `@secure`. What do you think @JPEasier?

**Comment by JPEasier** [comment]
Hi @rodney-almeida, as @AlexanderSehr already described, we can transfer this to the User Defined Type.

**Comment by rodney-almeida** [comment]
@AlexanderSehr & @JPEasier 
I have created a PR for this. Please let me know if there is anything i am missing. Cheers :)
https://github.com/Azure/bicep-registry-modules/pull/1919
