### ISSUE TITLE
[AVM Module Issue]: Virtual Network Gateway no Azure APIPA BGP Setting

### ISSUE THREAD

**Issue by marshalexander99** [Azure/bicep-registry-modules#1869]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/virtual-network-gateway

### (Optional) Module Version

0.1.3

### Description

There is no functionality to configure Azure APIPA address in the module currently

**Comment by fabmas** [comment]
Thank you. As soon as possible I will revise the module to add this functionality.

**Comment by fabmas** [comment]
@marshalexander99 A new PR has been raised to solve this issue
