### ISSUE TITLE
[AVM Module Issue]: Support for NIC name prefix and PIP name prefix

### ISSUE THREAD

**Issue by jensdiedrich** [Azure/bicep-registry-modules#1886]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### Description

Currently there is only support for NIC name suffix (nicSuffix)  and PIP name suffix (publicIpNameSuffix).
Would be great to have support for NIC name prefix and PIP name prefix, so the names could be better aligned to a different resource naming standard ( e.g. nic-XXXX / pip-XXXX )

Thanks

**Comment by rahalan** [comment]
@jensdiedrich you can give it a custom nic Name, see https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/compute/virtual-machine/tests/e2e/linux.max/main.test.bicep 
![image](https://github.com/Azure/bicep-registry-modules/assets/61878316/ed1bdf36-d55a-44f6-89be-8c25ceb1923e)

I will look into custom PIP name

**Comment by jensdiedrich** [comment]
@rahalan thanks for the hint about the custom nic name, would be great to have this for pip name as well

:thumbsup:
