### ISSUE TITLE
Storgae Account invalid Module

### ISSUE THREAD

**Issue by gsuttie** [Azure/bicep-registry-modules#1888]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### (Optional) Module Version

latest

### Description

This setting appears as invalid out of the box

@description('Required. Networks ACLs, this value contains IPs to whitelist and/or Subnet information. If in use, bypass needs to be supplied. For security reasons, it is recommended to set the DefaultAction Deny.')
param networkAcls networkAclsType = {
  bypass: 'AzureServices'
  defaultAction: 'Deny'
}

**Comment by AlexanderSehr** [comment]
Hey @gsuttie,
thanks for opening the issue and you're correct. There is already a Pull Request on the way (1508) that I just linked to this issue.

**Comment by gsuttie** [comment]
What do I need to do to be able to grab this fix in the mean time?

**Comment by AlexanderSehr** [comment]
Hey @gsuttie,
that's not an easy question to answer. Uou could temporarily overwrite the default of the parameter which you said is invalid by default. Question is if you want to enable the Firewall, or disable it. If I'm not mistaken, if you set the default action to allow the Firewall is actually disabled.
Alternativly, you can always grab a local copy of the module and e.g. implement the fix as suggested [here](https://github.com/Azure/bicep-registry-modules/pull/1508#discussion_r1575388807). But that's naturally not exactly a nice experience.

**Comment by gsuttie** [comment]
Will give that a go thank you

**Comment by AlexanderSehr** [comment]
Let me know how it's going. As per my linked suggestion this should work. I tested the behavior before commenting on the PR. Fingers crossed - and sorry for the inconvenience :-/

**Comment by Agazoth** [comment]
Running the main pipeline without any changes (from the Azure source) produces this error:
![image](https://github.com/Azure/bicep-registry-modules/assets/15127301/a74a0606-fb3b-492f-8435-3ea0b807d520)

Removing the custom test takes it away - obviously. It seems like PSRule has some sort of issue with the array of possilbe resources, judging by the System.String[] info - or it mighjt just not be a joined array in the log. I tried doing the complete string for Sku.name (Standard_ZRS and Standard_GRS) because there might be an issue finding an element in an array, if only part of the element was used, but that also complains.

The custom rule seems to be specific for the storage account module - after all there should not be other modules testing storage account specific rules.

**Comment by AlexanderSehr** [comment]
> Running the main pipeline without any changes (from the Azure source) produces this error: ![image](https://private-user-images.githubusercontent.com/15127301/330142761-a74a0606-fb3b-492f-8435-3ea0b807d520.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Njc3OTYsIm5iZiI6MTcxNTY2NzQ5NiwicGF0aCI6Ii8xNTEyNzMwMS8zMzAxNDI3NjEtYTc0YTA2MDYtZmIzYi00OTJmLTg0MzUtM2VhMGI4MDdkNTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA2MTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNTZhNDI2YzhkNGFlMmQxNTY4Nzc1OWRhOTQ3YjAzZTI2YWJjMzk1YjczYzY3YzM0OThjMjQyZDRkZGE3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qsWLEByq0ZEt52ridlvoJz863r8-JZPGSYPcYm5iFpc)
> 
> Removing the custom test takes it away - obviously. It seems like PSRule has some sort of issue with the array of possilbe resources, judging by the System.String[] info - or it mighjt just not be a joined array in the log. I tried doing the complete string for Sku.name (Standard_ZRS and Standard_GRS) because there might be an issue finding an element in an array, if only part of the element was used, but that also complains.
> 
> The custom rule seems to be specific for the storage account module - after all there should not be other modules testing storage account specific rules.

Ideally @fblix should resolve the issue in the linked PR #1508 . Reached out to him on the side and he should implement the fix shortly

**Comment by Agazoth** [comment]
Updating the sku name in the custom rule fixed the issue:
![image](https://github.com/Azure/bicep-registry-modules/assets/15127301/e483d6d4-3a26-4602-b8a1-908fd5d64cec)

**Comment by ChrisSidebotham** [comment]
Closing this issue as completed in #1987 (Missing from Closes List)
