### ISSUE TITLE
[AVM Module Issue]: Application Insights Workspace ID should be required.

### ISSUE THREAD

**Issue by JFolberth** [Azure/bicep-registry-modules#1897]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/insights/component

### Description

Workspace ID is listed as optional; however, Microsoft made it required and deprecated classic Application Insights: https://azure.microsoft.com/en-us/updates/we-re-retiring-classic-application-insights-on-29-february-2024/

This will cause issues as I am the owner of the Terraform App Insights as not all regions will support Classic and started receiving errors on the random region creation.....The Terraform provider also has this as optional and I have switched it to being required.

**Comment by krbar** [comment]
@JFolberth thanks for reporting the issue, I will take care of it.

**Comment by krbar** [comment]
@JFolberth I just had a look at the module and its [documentation](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/insights/component) and the `workspaceResourceId` is required, not optional. Am I missing something?

**Comment by JFolberth** [comment]
@krbar  deeply apologize...I am not sure what I was seeing when I opened this but you are correct. Clearly it is required. Closing this issue as it's a non issue.
