### ISSUE TITLE
[AVM Module Issue]: virtualMachines/compute module does not like default format for an image resource ID?

### ISSUE THREAD

**Issue by hooverken** [Azure/bicep-registry-modules#1908]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

current

### Description

I have a Bicep template which used AVM where need to deploy VMs using an imageReference that is passed in as the resource ID of the source image instead of the publisher/offer/sku combination.  I've noticed that when I pass in a resource ID the module will claim that the resource ID is not a valid resource reference.  It seems to be expecting the publisher/offer/sku when the underlying ARM for a virtualMachines resource supports either.  The module [README seems to say that both are OK](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/compute/virtual-machine#parameters) but there are no examples of how to use a resource ID.  Is this a bug?

```Line |
 570 |          $addSessionHostsResult = New-AzResourceGroupDeployment `
     |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 8:34:33 AM - The deployment '7bc5ee7f-5c7b-4cfb-b528-21a4bf323807' failed with error(s). Showing 3 out of 4
     | error(s). Status Message: Id
     | /Subscriptions/<subscriptionId>/Providers/Microsoft.Compute/Locations/eastus/Publishers/MicrosoftWindowsDesktop/ArtifactTypes/VMImage/Offers/windows-11/Skus/win11-23h2-avd/Versions/22631.3447.240405 is not a valid resource reference. (Code:BadRequest)  Status Message: Id /Subscriptions/ba55ad00-efe6-4eb5-863b-5fdcc6ff2351/Providers/Microsoft.Compute/Locations/eastus/Publishers/MicrosoftWindowsDesktop/ArtifactTypes/VMImage/Offers/windows-11/Skus/win11-23h2-avd/Versions/22631.3447.240405 is not a valid resource reference. (Code:BadRequest)  Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details. (Code: DeploymentFailed)  - Id /Subscriptions/<subscriptionId>/Providers/Microsoft.Compute/Locations/eastus/Publishers/MicrosoftWindowsDesktop/ArtifactTypes/VMImage/Offers/windows-11/Skus/win11-23h2-avd/Versions/22631.3447.240405 is not a valid resource reference. (Code:BadRequest)   CorrelationId: b3a594b6-716c-4f85-aa93-9268394ac71c


### (Optional) Correlation Id

b3a594b6-716c-4f85-aa93-9268394ac71c

**Comment by rahalan** [comment]
@hooverken thanks for bringing that up. I will look into it.
