### ISSUE TITLE
Bicep Landing Zone (Subscription) Vending module 

### ISSUE THREAD

**Issue by jtracey93** [Azure/bicep-registry-modules#191]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Customers today have a gap in being able to create subscriptions programmatically with the base networking resources they generally require in a repeatable fashion. 

We in the CAE team have created a Bicep Landing Zone vending module (https://github.com/Azure/bicep-lz-vending/), as well as a Terraform equivalent (HTTPS://aka.ms/LZ-vending/TF), to address this gap. 

We would like to have it consumable in the same way in bicep as it is via terraform in a public module registry to remove an additional step for consumers to have to worry about.  

### Module path

lz/subWithNetworking

### Describe the module

All details can be found in repo here https://github.com/Azure/bicep-lz-vending

**Comment by jtracey93** [comment]
https://github.com/Azure/bicep-lz-vending/issues/16

**Comment by alex-frankel** [comment]
Approved

**Comment by MilesCameron-DMs** [comment]
@jtracey93 does that mean the ability to consume this locally (in your own GitHub org) is now deprecated?

From what I can see the action to check for releases has been removed in the AVM version.

Help appreciated

**Comment by jtracey93** [comment]
Hey @MilesCameron-DMs 

You can still pull it down locally and copy the files from the modules folder in the public registry into your own source control if desired. 

We are looking into a bigger innersourcing story for AVM bicep with the public registry hopefully in the next financial year (starts in July)
