### ISSUE TITLE
[Question/Feedback from Discussions] Want to use already created PrivateDNSZone in Private AKS

### ISSUE THREAD

**Issue by eriqua** [Azure/bicep-registry-modules#1915]
### Discussed in https://github.com/Azure/ResourceModules/discussions/3121

<div type='discussions-op-text'>

<sup>Originally posted by **bansioza44** April 19, 2023</sup>
Hi Team, 
in container service's managed cluster module recently been change from allowing usePrivateDNSZone as string to bool.
For our requirement we want to use existing private DNS Zone Resource ID. How we leverage this now?   
</div>

**Comment by AlexanderSehr** [comment]
Hey @JPEasier, I believe this could be a duplicate of #1752.
However, I'll leave it to you to be the judge of that. Since this issue was opened already in CARML back in the day, there may be some merit to read through the comments before closing.

**Comment by AlexanderSehr** [comment]
To reiterate @JPEasier if you think it is a duplicate, please 'Close as not planned', if not, please triage 😉

**Comment by JPEasier** [comment]
> I've tested with 'system', 'none' and a resourceId and all work as expected.

I have the same outcome. @eriqua I don't see any issue here anymore, so I would close it.

**Comment by eriqua** [comment]
Sure @JPEasier, I'm not the author of the request, just converted the original discussion opened by @bansioza44 to a GH issue.
Feel free to triage/close based on your judgement 🙂

**Comment by JPEasier** [comment]
Hi @bansioza44, 
as the aks module provides the option for a custom DNZ zone like the template definition...
``` bicep
@description('Optional. Private DNS Zone configuration. Set to \'system\' and AKS will create a private DNS zone in the node resource group. Set to \'\' to disable private DNS Zone creation and use public DNS. Supply the resource ID here of an existing Private DNS zone to use an existing zone.')
param privateDNSZone string?
```
I will colse this issue 🙂
