### ISSUE TITLE
Could you provide instructions on how to use this code for a private registry?

### ISSUE THREAD

**Issue by michael-crawford** [Azure/bicep-registry-modules#192]
The `Publish-AzBicepModule` command appears to only support the upload of a single bicep file for use as a private module. This code appears to support more complex public module structure, including embedded bicep files in the ./.bicep folder, per-module READMEs, version and meta-data.

I have a need to create a module which loads JSON data from a file, came here hoping to find a way to perhaps extend the simpler functionality of the Publish-AzBicepModule CmdLet to do what it appears you're doing with a public repo. But, if that code is in here, it's not clear to me that it is or how customers can leverage this more advanced (and needed!) functionality to create private modules which might consist of more than a single file.

So, I thought I'd ask - is it possible to create private modules which similarly contain extra sub-modules in a ./.bicep directory? Is there a plan to document how this could be done in the works?

**Comment by shenglol** [comment]
The additional files, like README.md, metadata.json, etc., are not published to the public registry. They are checked in to this repo mainly for documentation purposes. If you check the [publish step](https://github.com/Azure/bicep-registry-modules/blob/main/.github/workflows/publish-module.yml#L73) you'll find that we are just using `bicep publish` to publish the `main.json` file. That being said, we do have a plan to add documentation link to module OCI artifact metadata / `main.json` and have the Bicep language server download the additional files. Once that is implemented, users will be able to view the module documentation in VS Code.

**Comment by michael-crawford** [comment]
Instructions are not clear enough for non-full-time .Net developers. I could not get the tool to work. Are these instructions current? Here's some of the issues I hit, for example:

1. There's a link to Install a .NET runtime: https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime, which takes us to a page with 3 variants on what to install, do we use the variant to "**run console apps**", "**run desktop apps**" or "**run server apps**". I picked "**run console apps**", downloaded and installed, but then when I ran the next statement, I got an error indicating the .Net was not installed. I killed and restarted Microsoft Terminal (running PowerShell 7.3.0 on Windows 11 fully updated.) Same error. I eventually found another link: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.403-windows-x64-installer, and installed that, version 6.0 as specified, but then I got more errors on the next step...
2. There's a link to Install the Bicep Registry Tool. The link takes you to a page which indicates you should use this command:
    ```PowerShell
    dotnet tool install --global Azure.Bicep.RegistryModuleTool --version 0.12.40
    ```
    While below on the CONTRIBUTING Page, it indicates you use this command:
    ```PowerShell
    dotnet tool install --global Azure.Bicep.RegistryModuleTool
    ``` 
    Both of these generate error messages which are not helpful in understanding what went wrong (same errors regardless of which command used above:
    ```PowerShell
    dotnet tool install --global Azure.Bicep.RegistryModuleTool --version 0.12.40
    ```
    Output
    ```text
    C:\Users\MxxxxxxCxxxxxxx\AppData\Local\Temp\f2a3fd85-fae2-4467-95ad-6799821fbb07\restore.csproj : error NU1100: Unable to resolve 'azure.bicep.registrymoduletool (>= 0.12.40)' for 'net6.0'.
    C:\Users\MxxxxxxCxxxxxxx\AppData\Local\Temp\f2a3fd85-fae2-4467-95ad-6799821fbb07\restore.csproj : error NU1100: Unable to resolve 'azure.bicep.registrymoduletool (>= 0.12.40)' for 'net6.0/any'.
    The tool package could not be restored.
    Tool 'azure.bicep.registrymoduletool' failed to install. This failure may have been caused by:

    * You are attempting to install a preview release and did not use the --version option to specify the version.
    * A package by this name was found, but it was not a .NET tool.
    * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
    * You mistyped the name of the tool.

    For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
    ```

Any idea what's going on and can you confirm the instructions on the CONTRIBUTING.md page are correct and up-to-date?

As a side note, I'd much prefer this tool to work in a manner similar to all other Azure functionality - as a PowerShell CmdLet installed like the other Az modules, ideally written in PowerShell, and not requiring these extra .Net install steps. I think the functionality being handled via this "out-of-band" method, would be better implemented as commands in the same module as the existing `Publish-AzBicepModule`, such as a `Generate-AzBicepModule` command to create the module structure. I think that would be easier for private registry developers to work with, as not all of us wanting to publish bicep IaC modules are going to be .Net developers (I'm more Linux and bash, JavaScript or Python, for example but know PowerShell pretty well). I also think you should have a way to use the Azure CLI within bash on a Microsoft Terminal running Ubuntu to generate the framework and publish modules. Just some customer feedback here!

**Comment by alex-frankel** [comment]
`brm` is not for publishing modules, it is for generating and validating metadata which is only a requirement for the public registry. There is only one tool for publishing modules, which is the `bicep publish` command (which we expose in both az CLI and azure powershell).

>the Publish-AzBicepModule isn't aware of and can't handle this extended structure it seems, only single-file bicep modules

Can you clarify what you mean by the above? What is not working and what errors are you getting?

I don't disagree that we should make the brm tool easier to consume without the .net dependency, but it is not a high priority for us at the moment. I will create a separate issue to capture this ask.

Unfortunately, I do not know why you are having those particular issues with your installation. It doesn't seem like it is specific to our tool. @Gordonby / @dciborow / @shenglol may be able to help here.

**Comment by shenglol** [comment]
@alex-frankel we have another thread here: #201. I was able to help @michael-crawford address the `brm` installation issue.
