### ISSUE TITLE
[AVM Module Issue]: Add managedIdentities to /res/app/managed-environment

### ISSUE THREAD

**Issue by sam-bryant** [Azure/bicep-registry-modules#1922]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/managed-environment

### Description

I need to associate a managed environment with a user assigned identity.  I apologize if this is possible and I'm not figuring it out.  I'm thinking something like:

    managedIdentities: {
      userAssignedResourceIds: [
        '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}'
      ]
    }

**Comment by hundredacres** [comment]
PR: https://github.com/Azure/bicep-registry-modules/pull/1972

**Comment by sam-bryant** [comment]
It works, thank you!
