### ISSUE TITLE
[AVM Module Issue]: `avm/res/web/site` - Package Deployment

### ISSUE THREAD

**Issue by Agazoth** [Azure/bicep-registry-modules#1924]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### (Optional) Module Version

current

### Description

avm/res/web/site module does not allow package deployment. A avm/res/web/site/extensions module should make it possible do a zip deployment on a wev site.

A basic working module would look like this:
``` bicep
param appServiceName string
param packageUri string

resource asw 'Microsoft.Web/sites@2022-09-01' existing = {
  name: appServiceName
}

resource appServiceWebDeploy 'Microsoft.Web/sites/extensions@2022-09-01' = {
  name: 'MSDeploy'
  kind: 'string'
  parent: asw
  properties: {
    packageUri: packageUri
  }
}
```

**Comment by tsc-buddy** [comment]
Hi @Agazoth - thanks for logging this issue. We shall schedule triage for this towards the end of May. Updates will be posted here.

**Comment by Agazoth** [comment]
Hi @tsc-buddy 

Any update on this?
