### ISSUE TITLE
[AVM Module Issue]: serverfarm docs incorrect

### ISSUE THREAD

**Issue by pinakighatak** [Azure/bicep-registry-modules#1928]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/serverfarm

### (Optional) Module Version

0.1.1

### Description

The docs illustrate to use `skuName` and `skuCapacity` values, but in reality, it does not work.
To make it work, you'd have to use it like this:

```bicep
sku:{
  tier: string
  name : string
  capacity: int
}
```

**Comment by picccard** [comment]
You might be looking at the newest docs and not the docs available at the time of the module release.
See step 5 and 6 here.
https://azure.github.io/Azure-Verified-Modules/faq/#how-can-i-use-bicep-modules-through-the-public-registry

**Comment by pinakighatak** [comment]
> You might be looking at the newest docs and not the docs available at the time of the module release. See step 5 and 6 here. https://azure.github.io/Azure-Verified-Modules/faq/#how-can-i-use-bicep-modules-through-the-public-registry

My comments still apply. The functionality - does not match, the published docs.

**Comment by picccard** [comment]
You might be looking at the docs on the main branch of the repo? This version of the docs is newer than the module-version you are looking at and therefore does not fit.

When you get to the README for the module, make sure you checkout the tag that matches the module version, [here is the url](https://github.com/Azure/bicep-registry-modules/blob/avm/res/web/serverfarm/0.1.1/avm/res/web/serverfarm/README.md).

In the following image; to the left you can see the README is set to the tag `avm/res/web/serverfarm/0.1.1`, and inside the docs `sku` is a required parameter for this version of the module.

![image](https://github.com/Azure/bicep-registry-modules/assets/7443949/1b79d04d-6594-448c-8fed-c74b9c300834)

**Comment by tsc-buddy** [comment]
@pinakighatak thanks for logging this. So the changes in SKU approach was based on some engineering team requests last month. Which were in turn implemented on [this PR:](https://github.com/Azure/bicep-registry-modules/pull/1736/files#diff-a300d6a540b148b4f5e418e3d92dd7fd2455f896a8d17a44b7d64f80b25ca241). I will look into this in some more detail next week as the docs should be highlighting the new approach.

**Comment by pinakighatak** [comment]
> @pinakighatak thanks for logging this. So the changes in SKU approach was based on some engineering team requests last month. Which were in turn implemented on [this PR:](https://github.com/Azure/bicep-registry-modules/pull/1736/files#diff-a300d6a540b148b4f5e418e3d92dd7fd2455f896a8d17a44b7d64f80b25ca241). I will look into this in some more detail next week as the docs should be highlighting the new approach.
> 
> Version 0.2 should be available.

Agree. I also confirm, the following example works.

```bicep
//App Service plan Azure veerified module for a function App
module functionAppServicePlan 'br/public:avm/res/web/serverfarm:0.1.1' = {
  name: '${name}-plan-module'
  params: {
    location: location
    name: '${name}-plan-module'
    perSiteScaling: false
    maximumElasticWorkerCount: 1
    
    // false == Windows; true == Linux
    reserved: OperatingSystem == 'Linux' ? true : false
    tags: tags
    sku: {
      capacity: 1
      family: functionSkuMap[planSku].name
      name: functionSkuMap[planSku].name
      tier: functionSkuMap[planSku].tier
    }
    diagnosticSettings: [
      {
        metricCategories: [
          {
            category: 'AllMetrics'
          }
        ]
        name: 'AppServicePlanDiagnosticSettings'
        workspaceResourceId: workspaceId
        logAnalyticsDestinationType: 'AzureDiagnostics'
      }
    ]
    kind: 'FunctionApp'
  }
}

```
