### ISSUE TITLE
[AVM Module Issue]: api management v2 sku not working due to api version

### ISSUE THREAD

**Issue by gvdmaaden** [Azure/bicep-registry-modules#1929]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/api-management/service

### (Optional) Module Version

0.1.7

### Description

Hi team,

Im using the AVM module /res/api-management/service:0.1.7 (latest version) which supports the new V2 sku's.
According to this pull request this should be supported now: https://github.com/Azure/bicep-registry-modules/pull/1777

During deployment I got an error (Bad Request) which the message:   "Operation on StandardV2 SKU is only supported in the api-versions 2023-03-01-preview,2023-05-01-preview,2023-09-01-preview (Code: NotSupported)"
![image](https://github.com/Azure/bicep-registry-modules/assets/42958576/480f2912-8683-48a2-bc35-9955a04e9edc)

![image](https://github.com/Azure/bicep-registry-modules/assets/42958576/05145c35-cb8c-4ff7-b24d-a4551b92aa00)

This is my Bicep configuration:

```bicep
module modApiManagementService 'br/public:avm/res/api-management/service:0.1.7' = {
  scope: 'resourcegroup'
  name: '${uniqueString(deployment().name)}-apim'
  params: {
    name: 'apinname'
    publisherEmail: 'email@test.nl'
    publisherName: 'somename'
    location: 'location'
    sku: 'StandardV2'
    virtualNetworkType:'Internal'
    subnetResourceId: 'somesubnet'
  }
}
```

**Comment by AlexanderSehr** [comment]
Hey @gvdmaaden,
I quickly checked and I think you're abslutely right. @tony-box could you check and update the module's primary resource's api version? [Spec-wise](https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr1---category-composition---preview-services), using the preview API versions should be justified. Would probably be worth to also update one of the tests to use a V2 version during the test. Thoughts?

**Comment by tony-box** [comment]
Absolutely agree--i actually thought I had updated the version in my own branch. I think it got lost somehow between all of the rebuilding of my dev environment. I will fix this.
