### ISSUE TITLE
[AVM Module Issue]: Set-AVMModule updates README.md with wrong sort order

### ISSUE THREAD

**Issue by Agazoth** [Azure/bicep-registry-modules#1930]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### Description

When running `Set-AVMModule -ModuleFolderPath .\avm\res\storage\storage-account\ -Recurse` locally, the README.md file gets updated with a wrong sort order on the allowedCopyScope parameter.
![image](https://github.com/Azure/bicep-registry-modules/assets/15127301/0875a403-c30d-4c05-bdf2-02a3eca4a0a8)

**Comment by AlexanderSehr** [comment]
Hey @Agazoth,
thanks for raising this. I'll look into this issue.
Before I do, one question though - The order of what is wrong? 😄 Is it about the 'AllowedValues' in your screenshot? Just want to make sure I look at the correct spot 😉

**Comment by Agazoth** [comment]
> Hey @Agazoth, thanks for raising this. I'll look into this issue. Before I do, one question though - The order of what is wrong? 😄 Is it about the 'AllowedValues' in your screenshot? Just want to make sure I look at the correct spot 😉

Thanks, Alexander.

Before running the Set-AVMModule command, 'AAD' was on line 2280 and 'PrivateLink' on line 2381. The screenshot is of those two lines after running the command.

**Comment by AlexanderSehr** [comment]
Gotcha, thank you @Agazoth - I'll work on this as soon as I find a moment. Non-deterministic results can be a pretty big issue - hence the sorting.

**Comment by Agazoth** [comment]
I just realized, that this might be caused by my Danish regional settings. In Danish AA is equivalent to Å, which is the last letter in our alphabet.

If the sort order is fixed to en-us, that ought to solve the issue.

**Comment by AlexanderSehr** [comment]
Hey @Agazoth, coincidentally, I just wanted to link it to this issue from the original CARML CI: https://github.com/Azure/ResourceModules/issues/3722

Given that you essentially just confirmed the same, this will make solving the issue a lot faster 😄 Thanks for the update.
