### ISSUE TITLE
[AVM Question/Feedback]: Allow specific submodule deployments?

### ISSUE THREAD

**Issue by Meertman** [Azure/bicep-registry-modules#1933]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

For some resources, e.g. API Management Service or Azure Service Bus, it might make sense to allow for deployments of sub-resources.

In order to save on costs, most companies allow for one shared API Management Service / Azure service bus to be used by multiple teams. Instead of handling all the configuration of that resource centrally, the deployment of APIM or Azure Service Bus is managed centrally (by the infrastructure / platform / system / ... team), but the deployments of queues / APIs are handled by the different development teams.

Therefore it would be nice if it was possible to use specific child resource of those resources directly, e.g. api, queue, subscription, ...

**Comment by odelaere** [comment]
Hello,

We could use such a feature as well.

Regards
