### ISSUE TITLE
[AVM Question/Feedback]: How do we handle resources that emit secrets?

### ISSUE THREAD

**Issue by Agazoth** [Azure/bicep-registry-modules#1934]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Building bicep modules is an exercise in making the module as slim and close to the desired resource as possible while still keeping it secure and compatible with larger deployments.

A SQL Server should not deploy a virtual network, but it might need some network resources to add it to a subnet. Likewise, we want our web site module to configure monitoring, without deploying the Insights resources.

Currently, the pattern (ptn) section of the repo is quite slim. We have some authorization stuff, some policy stuff and some security center stuff. According to the Module Classifications, a Pattern Module deploys multiple modules, usually in in alignment with the patterns in [Azure Architect Center](https://learn.microsoft.com/en-us/azure/architecture/) - that makes it safe to say, that we do not really have any pattern modules yet.

A Pattern module would always consist of several resources, that are deployed together in one or more resource groups distributed over one or more subscriptions. One might say, that any IaC deployment author is developing a pattern deployment for the specific project she is working on.

Authoring these patterns should be easy and secure and leverage the built-in benefits of the given language, be it bicep, terraform or others. If we need to attach a new cloud native application to an existing CAF Enterprise Scale environment, we need an easy way to add the application to the network, implement the required logging and store the secrets from the deployment in the appointed key vault.

Resources have some common requirements or behaviors that we need to address in a common way in order to keep the AVM slim and attractive. These are the things we always need to consider:

* Network
* Monitoring and logging
* Authorization
* Secrets

We often handle these requirements with the "existing" resource inside the module structure to reference the required endpoint for the integration of the specific resource we build in the module for. A quick count in the current repo reveals 358 "existing =" strings in 256 files. 32 results in 29 files are for existing key vault resources, 47 results in 46 files are for network resources and 14 results in 14 files are for insights.

The point of this specific discussion is, how we find a common way to handle resources, that _emit_ secrets. These secrets are often used in other modules and will be visible in the deployment log, if they are added to the output of the creating module.

Ideally modules should be able to emit `@secret` values or directly available in the module output, but that is not the case now and it does not seem to be solved in any sprint anytime soon.

If we want to make a secret emitting resource safe and secure for the deployment builder, we have 2 options:

1. Instruct the end users to create sub-deployments in their deployments, that handle the secrets like in this issue: [Accessing Storage Account Access Key](https://github.com/Azure/bicep-registry-modules/issues/1780#issuecomment-2093381334)
2. Add an optional option for storing secrets in a key vault like in the [Document DB solution](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/document-db/database-account#example-5-deploying-with-a-key-vault-reference-to-save-secrets)

I would love to hear pros and cons for different solutions. Alternative ways can also be discussed. I hope this discussion can help us find common grounds to make well structured and secure modules that deployment developers like to use.

**Comment by eriqua** [comment]
Thanks a lot @Agazoth for opening and elaborating on this issue.

@ChrisSidebotham @jtracey93 @AlexanderSehr FYI this started from the 2 PRs #1920 #1932

**Comment by Agazoth** [comment]
Hi @ilhaan 
Happy to have a senior engineer from security on the thread 💪. I hope you will find time to share your angle on the matter.

**Comment by AlexanderSehr** [comment]
Hey @Agazoth, thanks for opening the issue. We'll also discuss the topic with the other maintainers to define a general guideline

**Comment by eriqua** [comment]
Off the top of my head we have 3 options

- OPT1: integrate the kv secrets type in the resource module. This requires a reference implementation, possibly with a spec, interface, being consistent across all modules emitting secrets.
- OPT2: cover the secret handling scenario in a pattern module. Possibly one pattern for each resource emitting secrets. A pattern module only makes sense if we think of this scenario being reusable.
- OPT3 example usage. In this case no module would be published covering this scenario. Instead, we may add an e2e deployment test (e.g. "with secret backup") in the corresponding resource module, leveraging the module and the Key Vault module to show how to backup secrets in a secure way

**Comment by Agazoth** [comment]
Hey @eriqua - happy for your insights.

Option 2 would possibly mean, that we would have to create a pattern for each _resource_ that emit secrets alongside a module that does not emit the secrets for each of those resources.

The secrets generated at deployment time are almost always used elsewhere in a deployment, which makes the modules practically useless. 

Option 3 would mean, that we write the "workaround" sample into each resource module and it is the still up to the user to write the extra files for their deployment.

I agree with all your points in option 1. Option 1 is also the solution I would advocate for:

* It makes the module relevant as opposed to option 2.
* It implements a save, Azure native access to the secrets emitted
* It builds the "workaround" into the module making template authoring simpler and safer, thus surpasses option 3.

All 3 options will leave us with work, that needs to be done:

Option 1:
* Find a reference implementation (as stated, the one in document-db works like a charm)
* Define specs and interfaces

Option 2:
* If we want to use patterns for managing emitted secrets, we need to start working on patterns in general to clarify, how they are intendet to be used. At least for me, that is unclear, if not as described - for larger implementations.
* Define what goes in the module and what goes in the pattern for secret emitting resources - and if the modules should be built at all.

Option 3:
* Add the workaround sample into all secret emitting modules. This in turn calls for:
  * A reference implementation that exemplifies the implementation
  * Defining specs for the e2e deployment tests

In a more general view on modules, I find great inspiration in this article from Breandan Thomsen https://brendanthompson.com/posts/2020/terraform-to-module-or-not-to-module. He is a Terraform ambassador and has been working with modules and module building for many years. He highlights these 9 points for module creation:

1. If a resource MUST have security/audit/compliance controls enforced at provision and/or configuration time, this MUST then be encapsulated within a Terraform module. Otherwise, it SHOULD be consumed as a Terraform resource.
2. When specific configuration or metadata MUST be applied to a resource it MUST then be created as a Terraform module to enforce those requirements.
3. When a resource has a stringent/complex naming required that MUST be adhered to this resource MUST be created as a Terraform module.
4. When a resource relies on information/metadata/context that cannot be known by the consumer it MUST be created as a Terraform module.
5. If a Terraform module will reduce the complexity of either the configuration or its interface then a Terraform module SHOULD be used.
6. Resources that have an aligned business purpose/requirement SHOULD be grouped together as a Terraform module.
7. Resources that MUST satisfy multiple use cases SHOULD be created as a Terraform module.
8. When a group of resources shares a similar lifecycle they SHOULD be grouped together as a Terraform module.
9. If a resource is always going to be consumed by a higher-order module it SHOULD NOT be created as a bare/wrapper Terraform module

I see the first point as a clear indicator for option 1. Actually, it also solves the question about whether or not to create a module in option 2.

Point 5 is also a good argument for option 1. The end-user of the module gets a built-in option to safely store the secret in a place, where Azure native tooling can manage and cycle the secrets.

Point 7 would also favour option 1. The module can still be used in multiple use cases, whereas option 2 would need specific patterns for each secret emitting _resource_ leaving out the module, much like option 3 just describes how to work around a super common use case that is not implemented in the module

Point 9 too can be used for favouring option 1. The simplest example is the storage account. The storage account is used in a very high percentage of implementations and is almost always consumed by some other resource, that needs the functionality it provides. Stretching point 9 a bit, one could say, that a web app consumes the connection string or primary key of the storage account for the storage queue or DataLakeGen2 access. This means that secret emitting resource modules SHOULD NOT be mere wrappers.

I think my opinion is quite clear. Having secrets emitted directly to key vault from the module is the right implementation until the changes on ARM allows us to emit secrets directly from the bicep resources. It gives the module users a **simple**, **unified** solution to get access to secrets from the modules, that is **secure** and **supported** by the Azure platform _without having to remember to write workarounds_ every time a resource has a secret they want.

Modules with this implementation will also work very well in Pattern implementations, that often deploy their own key vaults. And pattern implementations that reference existing key vaults for that matter.

I'm looking forward to other viewpoints or angles and very eager to go to work on this - I have a private registry to dissolve 😸

**Comment by Agazoth** [comment]
Hey @AlexanderSehr  and @eriqua did you manage to find anyone with additional opinions or ideas on how to handle secrets?

**Comment by AlexanderSehr** [comment]
Hey @Agazoth,
that was quite a read. Thank you for that 💪 We did start debating it among the maintainers last week, but did not yet agree on the specific approach. Once we do, we'll let you know asap. And if we end up with option 1, for example, try to define a reasonable spec asap. It's unfortunately only one of many topics, so we have to do as much as we can with the capacity we have. 

For option 1,for example, I'd argue the interface/spec should ensure
- that a user can set names, but also have a default
- that a user must provide a key vault resource ID
- that the feature must be optional
- that the interface must have a user defined type
- that the template must be implemented in a `/modules/` subfolder (which is the convention for any helper templates)
- ...

**Comment by AlexanderSehr** [comment]
I had a bit of time so I did some trial & error how the interface could look like and currently ended up with the following proposal (using the CosmosDB solution as a use case):

## keyVaultExport.bicep 
Based on the solution of @bryansan-msft
```bicep
@description('Required. The name of the key vault to set the secrets in.')
param keyVaultName string

@description('Required. The secrets to set in the key vault.')
param keySecrets keySecret[]

resource keyVault 'Microsoft.KeyVault/vaults@2022-07-01' existing = {
  name: keyVaultName
}

resource keySecretsSecrets 'Microsoft.KeyVault/vaults/secrets@2022-07-01' = [
  for secret in keySecrets: {
    name: secret.name
    parent: keyVault
    properties: {
      value: secret.value
    }
  }
]

type keySecret = {
  @description('Required. The name of the secret to set.')
  name: string

  @description('Required. The value of the secret to set.')
  @secure()
  value: string
}
```

## main.bicep
```bicep
@description('Optional. Key vault reference and secret settings for the module''s secrets export.')
param secretsExportConfiguration secretsExportConfigurationType?

module keyVaultTest 'modules/secrets-key-vault.bicep' = if (secretsExportConfiguration != null) {
  name: '${uniqueString(deployment().name, location)}-secrets-kv'
  scope: resourceGroup(
    split(secretsExportConfiguration!.keyVaultResourceId, '/')[2],
    split(secretsExportConfiguration!.keyVaultResourceId, '/')[4]
  )
  params: {
    keyVaultName: last(split(secretsExportConfiguration!.keyVaultResourceId, '/'))
    keySecrets: union(
      [],
      secretsExportConfiguration.?setPrimaryWriteKey != false
        ? [
            {
              name: secretsExportConfiguration.?primaryWriteKeySecretName ?? 'Primary-Write-Key'
              value: databaseAccount.listKeys().primaryMasterKey
            }
          ]
        : [],
      secretsExportConfiguration.?setPrimaryReadOnlyKey != false
        ? [
            {
              name: secretsExportConfiguration.?primaryReadOnlyKeySecretName ?? 'Primary-Readonly-Key'
              value: databaseAccount.listKeys().primaryMasterKey
            }
          ]
        : []
        // (...)
    )
  }
}

type secretsExportConfigurationType = {
  @description('Required. The resource ID of the key vault where to store the secrets of this module.')
  keyVaultResourceId: string

  @description('Optional. The name for secret to create.')
  primaryWriteKeySecretName: string?
  @description('Optional. Set to control wether or not to create the secret. Defaults to true.')
  setPrimaryWriteKey: bool?
  
  @description('Optional. The name for secret to create.')
  primaryReadOnlyKeySecretName: string?
  @description('Optional. Set to control wether or not to create the secret. Defaults to true.')
  setPrimaryReadOnlyKey: bool?

  // (...)
}
```

## main.test.bicep
```bicep
module testDeployment '../../../main.bicep' = [
  for iteration in ['init', 'idem']: {
    scope: resourceGroup
    name: '${uniqueString(deployment().name, enforcedLocation)}-test-${serviceShort}-${iteration}'
    params: {
     secretsExportConfiguration: {
        keyVaultResourceId: keyVaultResourceId
        primaryReadOnlyKeySecretName: 'myName'
        setPrimaryReadonlyConnectionString: false
      }
     // (...)
}]
```

I did play around with a couple different variants like
- Having one object per secret with an optional name & enabled property: Turned out to be rather confusing to use if you don't ask the user to specify all secret 'objects' to set. However, as we want to set all by default it got a bit messy.
- Having an array `secretsToSet` and then one optional parameter for each name: Also this one was a bit confusion as you need to handle cases like 'somebody set the name, but did not configure the value in the `secretsToSet` property. And again, how to set all by default etc.
- Moving the 'pulling' of secrets from the `main.bicep` into the nested file to move the complexity: This would only work if the Key Vault is definitely in the same Resource Group as in this case the CosmosDB. Not a good restriction to have.

Nothing is yet decided, but I wanted to give it a shot anyways. Happy to hear some thoughts.

**Comment by AlexanderSehr** [comment]
Hey @Agazoth, just as a quick update to you: After some firefighting, I just put this item back on the agenda. I hope we can come to an agreement this Thursday, or the next. Fingers crossed. Please excuse that it takes longer than we would have hoped.

**Comment by Agazoth** [comment]
That is great news @AlexanderSehr - I'm looking forward to it 🙂. Thanks for your continued effort.

**Comment by AlexanderSehr** [comment]
Another proposal where the name is mandatory and no secrets are set by default:

## keyVaultExport.bicep 
Based on the solution of @bryansan-msft
```bicep
@description('Required. The name of the key vault to set the secrets in.')
param keyVaultName string

@description('Required. The secrets to set in the key vault.')
param keySecrets keySecret[]

resource keyVault 'Microsoft.KeyVault/vaults@2022-07-01' existing = {
  name: keyVaultName
}

resource keySecretsSecrets 'Microsoft.KeyVault/vaults/secrets@2022-07-01' = [
  for secret in keySecrets: {
    name: secret.name
    parent: keyVault
    properties: {
      value: secret.value
    }
  }
]

output secretResourceIds string[] = keySecrets.id // TODO: Fix syntax

type keySecret = {
  @description('Required. The name of the secret to set.')
  name: string

  @description('Required. The value of the secret to set.')
  @secure()
  value: string
}
```

## main.bicep
```bicep
@description('Optional. Key vault reference and secret settings for the module''s secrets export.')
param secretsExportConfiguration secretsExportConfigurationType?

module keyVaultTest 'modules/keyVaultExport.bicep' = if (secretsExportConfiguration != null) {
  name: '${uniqueString(deployment().name, location)}-secrets-kv'
  scope: resourceGroup(
    split(secretsExportConfiguration!.keyVaultResourceId, '/')[2],
    split(secretsExportConfiguration!.keyVaultResourceId, '/')[4]
  )
  params: {
    keyVaultName: last(split(secretsExportConfiguration!.keyVaultResourceId, '/'))
    keySecrets: union(
      [],
      contains(secretsExportConfiguration, 'primaryWriteKeySecretName')
        ? [
            {
              name: secretsExportConfiguration.primaryWriteKeySecretName
              value: databaseAccount.listKeys().primaryMasterKey
            }
          ]
        : [],
      contains(secretsExportConfiguration, 'primaryReadOnlyKeySecretName') 
        ? [
            {
              name: secretsExportConfiguration.primaryReadOnlyKeySecretName
              value: databaseAccount.listKeys().primaryReadonlyMasterKey
            }
          ]
        : []
        // (...)
    )
  }
}

output secretResourceIds string[] = keyVaultTest.outputs.secretResourceIds

type secretsExportConfigurationType = {
  @description('Required. The resource ID of the key vault where to store the secrets of this module.')
  keyVaultResourceId: string

  @description('Optional. The name for secret to create.')
  primaryWriteKeySecretName: string?
  
  @description('Optional. The name for secret to create.')
  primaryReadOnlyKeySecretName: string?

  // (...)
}
```

## main.test.bicep
```bicep
module testDeployment '../../../main.bicep' = [
  for iteration in ['init', 'idem']: {
    scope: resourceGroup
    name: '${uniqueString(deployment().name, enforcedLocation)}-test-${serviceShort}-${iteration}'
    params: {
     secretsExportConfiguration: {
        keyVaultResourceId: keyVaultResourceId
        primaryReadOnlyKeySecretName: 'myName'
        primaryWriteConnectionStringName: 'my2ndName'
      }
     // (...)
}]
```

**Comment by AlexanderSehr** [comment]
Hey @Agazoth,
we agreed on the last iteration suggested above - finally 😄 
That is
- The person deploying needs to 'opt-in' to set a secret (i.e., secrets are not set by default) by providing a name
- The implementation returns a hashtable of the configured secrets through which the person that set the secret could directly get access to the secret's resourceID & url, if needed
- If a module owner adds the feature, they should use the same implementation, excluding which secrets are set (as it's different from resource type to resource type) which will have an affect on the `keyVaultExport.bicep` module deployment in the `main.bicep` & the UDT

I'll go ahead and define a spec for that to document it on AVM. In the meantime, if you find time, please update your PRs to the above implementation and we can get them right in.

**Comment by Agazoth** [comment]
Hi @AlexanderSehr 

That is excellent news and a really good decision! I'll update the PRs accordingly as soon as I'm back from vacation (next week).

Thank you for your persistence!

**Comment by AlexanderSehr** [comment]
> Hi @AlexanderSehr
> 
> That is excellent news and a really good decision! I'll update the PRs accordingly as soon as I'm back from vacation (next week).
> 
> Thank you for your persistence!

Thank you for your partience. I'm sure we'll catch up soon. Enjoy your vacation, while you can 💪

**Comment by eriqua** [comment]
Hey @Agazoth, @AlexanderSehr as specs are defined and the first PRs implementing those are merged, shall we close this issue?

**Comment by Agazoth** [comment]
@eriqua that is fine with me. So glad this got implemented. Already using it in deployments and it works like a charm 😃

**Comment by eriqua** [comment]
Very glad to hear @Agazoth, thanks for triggering this conversation, that's only how this feature got implemented 😉

Will wait for Alex to confirm as well and then close.

**Comment by AlexanderSehr** [comment]
Sounds good. Thanks 💪

**Comment by riosengineer** [comment]
Hey @AlexanderSehr @Agazoth this looks really interesting thanks for the work. I am wondering, how could this help achieve `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` on a Function deployment? Following on from https://github.com/Azure/bicep-registry-modules/issues/1780 

I won't know the secret at runtime still so I assume I'm still tied to using `existing`?
