### ISSUE TITLE
[AVM Module Issue]: Deploy policy assignments to subription or resource group target scope

### ISSUE THREAD

**Issue by jensdiedrich** [Azure/bicep-registry-modules#1937]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/ptn/authorization/policy-assignment

### Description

Hello,

as far as I see it´s not possible to deploy a policy assignment on sub or rg level if the targetscope for the deployment is set to "subcription" or "resourcegroup" because the target scope for the policy-assignment pattern modules are set to "managementgroup".

In the CARML project there were modules for deployment to specific targetscopes (https://github.com/Azure/ResourceModules/tree/main/modules/authorization/policy-assignment)

Is it planned to implement this in AVM too ?

**Comment by arnoldna** [comment]
@jensdiedrich - Thanks for reaching out. You can still deploy at the Resource Group and subscription scopes. There is a directory called [modules](https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/authorization/policy-assignment/modules) that contains the modules for the management group, subscription and resource group deployments. You can look at the deployment [tests](https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/authorization/policy-assignment/tests/e2e) for examples on how to deploy to subscriptions and resource groups.

**Comment by jensdiedrich** [comment]
@arnoldna - Thanks for lighting me up, didn´t see the separate module because they´re not medntioned in the docs as far as I can see ?
Is it true that they can´t be referenced from the Public BRM registry ?

**Comment by AntoVie** [comment]
@arnoldna The solution you give is not good because the tests have targetScope = 'managementGroup'. I've try several time to make it work with a targetScope = 'subscription' and that dont work. Is there a way to call the module from the module directory from the public BRM registry ? If no it's a problem and the issue is not done.

**Comment by arnoldna** [comment]
@AntoVie  - See this existing issue for further information. https://github.com/Azure/bicep-registry-modules/issues/2688#issuecomment-2255459066
