### ISSUE TITLE
Public IP address DDoS Settings

### ISSUE THREAD

**Issue by darrenFrowen** [Azure/bicep-registry-modules#1940]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/network/public-ip-address

### (Optional) Module Version

0.4.0

### Description

Hi,

In my own public IP resource Bicep templates using 'Microsoft.Network/publicIPAddresses@2023-04-01' i have public IP address IP protection enabled not part of a DDoS Protection plan. This is defined using the following property. It appear this is not supported in the AVM module? If i specify only the protectionMode i see the following error "The specified "object" declaration is missing the following required properties: "ddosProtectionPlan". 

    ddosSettings: {
      protectionMode: 'Enabled'
    }

**Comment by AlexanderSehr** [comment]
Hey @ChrisSidebotham could you take a look at this issue?

@darrenfrowen, sorry for not coming around earlier. It seems something went wrong with the automatic issue assignment.

**Comment by darrenfrowen** [comment]
Hi Alex,No problem at all thanks for your response.RegardsOn 21 May 2024, at 18:35, Alexander Sehr ***@***.***> wrote:﻿
Hey @ChrisSidebotham could you take a look at this issue?
@darrenfrowen, sorry for not coming around earlier. It seems something went wrong with the automatic issue assignment.

**Comment by ChrisSidebotham** [comment]
@darrenfrowen - Thanks for submitting this, good to see you in this space! I have updated the `ddosSettingType` in #2006, once this is approved and merged a new version will be available for use

**Comment by darrenfrowen** [comment]
Hi Chris,

 

Thanks for the update and hope your well. I only found AVM a few months ago and think its such a great resource. Great community call on Tuesday by the way. 

 

Regards

**Comment by darrenFrowen** [comment]
Hi Chris,

 

Should I now be able to omit the ddosProtectionPlan’ object? If I remove the ‘ddosProtectionPlan’ object I see the following IntelliSense error declaring both required and optional .  Am missing something apologies in advance if I am?  

 



 

 

I also tried the ddosProtectionPlan object with an empty value for Id: ‘’ which doesn’t throw IntelliSense error allowing the deployment to run however when accessing the “protect IP address” I see the following .

 

 



 

Regards

**Comment by darrenFrowen** [comment]
@ChrisSidebotham 

There seems to be an issue, if i set the object on the module as follows, we can see a conflict where it specifies as both required and optional for the ddosProtectionPlan

![image](https://github.com/Azure/bicep-registry-modules/assets/16030060/1245315a-2bfd-4da4-aeaa-6828a0bc83de)

If i set the parameter object outside of the module then reference the parameter i see no error but the IP protection fails. without any error.  

![image](https://github.com/Azure/bicep-registry-modules/assets/16030060/d6084db5-5a6a-459e-b870-890386a695a5)

Can you confirm that it does work with the following result under Protect IP address of the public IP resource please?

![image](https://github.com/Azure/bicep-registry-modules/assets/16030060/238e0463-234b-4886-9127-69b23ec0a96e)

**Comment by ChrisSidebotham** [comment]
@darrenFrowen - Leave this with me and will investigate today! :)

**Comment by darrenFrowen** [comment]
@ChrisSidebotham thank you very much appreciated

**Comment by ChrisSidebotham** [comment]
@darrenFrowen it seems the CDN is being slow but the module version should actually be `0.4.1`.

example:
```bicep 
module pip 'br/public:avm/res/network/public-ip-address:0.4.1' = {
  name: 'myPipTest01'
  params: {
    name: 'csuk-tst-avmpip02'
    ddosSettings:{
      protectionMode: 'Enabled'
    }
    skuTier: 'Regional'
  }
}
```

**Comment by darrenFrowen** [comment]
@ChrisSidebotham yes i wasn't picking any new version up which i found strange. 

![image](https://github.com/Azure/bicep-registry-modules/assets/16030060/2eaae662-ee3f-4ad8-95aa-caec4ccf4051)

So i have just forced the module to version 4.0.1 the module now accepts the single protectionMode property and the deployment now works as expected.

![image](https://github.com/Azure/bicep-registry-modules/assets/16030060/66ec5c50-53d5-4bfd-a668-fbb973dead9c)

Thanks for your support Chris really appreciated.

**Comment by ChrisSidebotham** [comment]
Thanks for confirming @darrenFrowen. Sometimes your local client may be caching the available versions - il close this issue now :)

**Comment by darrenFrowen** [comment]
Thanks Chris I’ll keep that in mind next timeOn 24 May 2024, at 14:17, ChrisSidebotham-MSFT ***@***.***> wrote:﻿
Thanks for confirming @darrenFrowen. Sometimes your local client may be caching the available versions - il close this issue now :)

**Comment by darrenFrowen** [comment]
thanks @ChrisSidebotham ill keep that in mind next time
