### ISSUE TITLE
[AVM Question/Feedback]: virtual-machine Module - Application Profile / VMAppExtension

### ISSUE THREAD

**Issue by nalberti** [Azure/bicep-registry-modules#1947]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Not sure if I'm missing something I can't see to see if its possible to set an application profile as per: [microsoft.compute/virtualmachines](https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines?pivots=deployment-language-bicep#applicationprofile)

```
    applicationProfile: {
      galleryApplications: [
        {
          configurationReference: 'string'
          enableAutomaticUpgrade: bool
          order: int
          packageReferenceId: 'string'
          tags: 'string'
          treatFailureAsDeploymentFailure: bool
        }
      ]
    }
```

Could it be possible to include a set of default applications set to install ? or is there another supported way ?

I suspect there is a work around calling the extenstion module directly as this seems to call on VMAppExtension (Microsoft.CPlat.Core.VMApplicationManagerWindows)

**Comment by AlexanderSehr** [comment]
Hey @rahalan, please take a look whe  you have a moment :)

**Comment by rahalan** [comment]
@nalberti thanks for bringing it up. I will look into it
