### ISSUE TITLE
[AVM Module Issue]: Virtual Machine Module have issue with Windows machine configuration.

### ISSUE THREAD

**Issue by nehayadav210068** [Azure/bicep-registry-modules#1968]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine

### Description

I was trying to deploy the Windows VM with Standard_D2s_v3 size it only gives option to choose the patch Mode is 'AutomaticByOS' or 'Manual'.  I chose 'AutomaticByOS' and it started failing and while checking I identified that in Windows configuration section the condition for application setting was not passing through as it was only defined for 'AutomaticByPlatform'.

After modifying the module with additional check and bypass it for 'AutomaticByOS' or 'Manual' it worked.

[AVM VM module bug .docx](https://github.com/Azure/bicep-registry-modules/files/15349786/AVM.VM.module.bug.docx)

Original Module code:

var windowsConfiguration = {
  provisionVMAgent: provisionVMAgent
  enableAutomaticUpdates: enableAutomaticUpdates
  patchSettings: (provisionVMAgent && (patchMode =~ 'AutomaticByPlatform' || patchMode =~ 'AutomaticByOS' || patchMode =~ 'Manual'))
    ? {
        patchMode: patchMode
        assessmentMode: patchAssessmentMode
        automaticByPlatformSettings:  {
          bypassPlatformSafetyChecksOnUserSchedule: bypassPlatformSafetyChecksOnUserSchedule
          rebootSetting: rebootSetting
        } 
      }
    : null

Updated Module Code: 

var windowsConfiguration = {
  provisionVMAgent: provisionVMAgent
  enableAutomaticUpdates: enableAutomaticUpdates
  patchSettings: (provisionVMAgent && (patchMode =~ 'AutomaticByPlatform' || patchMode =~ 'AutomaticByOS' || patchMode =~ 'Manual'))
    ? {
        patchMode: patchMode
        assessmentMode: patchAssessmentMode
        automaticByPlatformSettings: (patchMode =~ 'AutomaticByPlatform') ? {
          bypassPlatformSafetyChecksOnUserSchedule: bypassPlatformSafetyChecksOnUserSchedule
          rebootSetting: rebootSetting
        } : null
      }
    : null

**Comment by rahalan** [comment]
@nehayadav210068 thanks for bringing it up. I will look into it.
