### ISSUE TITLE
[Feature Request]: Bump API versions for DataCollectionEndpoint/Rule

### ISSUE THREAD

**Issue by akata72** [Azure/bicep-registry-modules#1973]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/insights/data-collection-endpoint

### Description

Can you please bump the API version for the insights modules **datacollectionendpoint** and **datacollectionrule** modules. These are currently using a preview API.  (latest version is 2022-06-01).

**Comment by AlexanderSehr** [comment]
Hey @matebarabas, please note I ran a test by updating this issue's description and migrating it to AVM, yet the module owner was suprinsingly not set. Would you know if we have any documentation somewhere what the conditions are for the bot to pick it up, or do we need to reverse engineer? 😄

**Comment by AlexanderSehr** [comment]
@krbar please take a look when you have the chance :) Also, if there are any new features coming with the API version(s), please add them.

**Comment by matebarabas** [comment]
> Hey @matebarabas, please note I ran a test by updating this issue's description and migrating it to AVM, yet the module owner was suprinsingly not set. Would you know if we have any documentation somewhere what the conditions are for the bot to pick it up, or do we need to reverse engineer? 😄

@AlexanderSehr, the module owner's assignment is done by the solution @rahalan implemented. 

@rahalan, can you please look into this? This issue was migrated from CARML, but from the BRM repo's perspective, this should be perceived as a newly created one. CC: @ChrisSidebotham

**Comment by AlexanderSehr** [comment]
Hey @krbar please take a look when you have a moment.
