### ISSUE TITLE
[AVM Module Issue]: avm/res/web/site does not not allowing `kind` to contain `container`

### ISSUE THREAD

**Issue by ksstott** [Azure/bicep-registry-modules#1977]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/site

### Description

The avm/res/web/site module does not not allowing `kind` to contain `container`, e.g. `app,linux,container` or `functionapp,linux,container`

This issue is similar to the issue reported in #1408

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy, please take a look when you have a moment :)

**Comment by tsc-buddy** [comment]
Hey, Will triage and work on this Wc 3rd June

**Comment by ksstott** [comment]
@tsc-buddy thanks for getting this fixed up however it looks like container based functions apps e.g. `kind: functionapp,linux,container` are still not supported

**Comment by AlexanderSehr** [comment]
> @tsc-buddy thanks for getting this fixed up however it looks like container based functions apps e.g. `kind: functionapp,linux,container` are still not supported

I can confirm. @tsc-buddy I presume it was overlooked. You did add quite a few, but not all. I just found a (maybe outdated) list [here](https://github.com/Azure/app-service-linux-docs/blob/master/Things_You_Should_Know/kind_property.md#app-service-resource-kind-reference).

Re-opening
