### ISSUE TITLE
[AVM Question/Feedback]: How to use System Assigned Managed Identity for Role Assignments

### ISSUE THREAD

**Issue by russellds** [Azure/bicep-registry-modules#1978]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

 The following block is embedded in many different resource modules:

``` bicep
resource app_roleAssignments 'Microsoft.Authorization/roleAssignments@2022-04-01' = [
  for (roleAssignment, index) in (roleAssignments ?? []): {
    name: guid(app.id, roleAssignment.principalId, roleAssignment.roleDefinitionIdOrName)
    properties: {
      roleDefinitionId: contains(builtInRoleNames, roleAssignment.roleDefinitionIdOrName)
        ? builtInRoleNames[roleAssignment.roleDefinitionIdOrName]
        : contains(roleAssignment.roleDefinitionIdOrName, '/providers/Microsoft.Authorization/roleDefinitions/')
            ? roleAssignment.roleDefinitionIdOrName
            : subscriptionResourceId('Microsoft.Authorization/roleDefinitions', roleAssignment.roleDefinitionIdOrName)
      principalId: roleAssignment.principalId
      description: roleAssignment.?description
      principalType: roleAssignment.?principalType
      condition: roleAssignment.?condition
      conditionVersion: !empty(roleAssignment.?condition) ? (roleAssignment.?conditionVersion ?? '2.0') : null // Must only be set if condtion is set
      delegatedManagedIdentityResourceId: roleAssignment.?delegatedManagedIdentityResourceId
    }
    scope: app
  }
]
```

How do you use the modules primary resource type System Assigned Managed Identity?

It doesn't look like it is possible given the bicep above. This could be an issue for most modules.

**Comment by AlexanderSehr** [comment]
Hey @russellds,
could you lay out what you try to achieve? The `roleAssignments` interface implemented by modules is intended to apply role assignments to that resource. For example, you may deploy a virtual machine with a system-assigned identity enabled (which returns it's principal Id) and can then use that output to create a role assignment on let's say the Key Vault module deployment by using the interface like
```bicep
roleAssignments: [
  {
    roleDefinitionIdOrName: 'Key Vault Crypto Officer'
    principalId: virtualMachineModule.outputs.systemAssignedMIPrincipalId
    principalType: 'ServicePrincipal'
  }
]
```

**Comment by russellds** [comment]
I misunderstood how to use that role assignment. I was trying to use it to assign that resource roles to other resources. I was looking at it backwards.
