### ISSUE TITLE
[Module Proposal]: Automation Runbook

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#199]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Creating automation runbooks with schedules is a laborious task.
There are several resource abstracts to create, the schedule can be particularly onerous with the timezone string property.

This module would streamline the creation process.

The first use case is that of stopping and starting an AKS cluster at the beginning and end of the day. This is a feature that will be added to [AKSC](https://github.com/Azure/Aks-Construction), a bicep module in the registry would increase the reusability of the capability.

### Module path

automation/automationrunbook

### Describe the module

- An Automation Account (with system managed identity)
- A variety of schedules with configurable time zone via allowed param array
- A single runbook (via URL)
- The job, runbook->schedule mapping
- Will take an existing Log analytics workspace id for logging.

When the runbook params are null it will just create the account and scheduled.

The readme will include runbook examples of starting/stopping AKS as well as the most popular runbook from the gallery; stopping/Starting vms.

**Comment by ChrisSidebotham** [comment]
Dear @Gordonby , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
