### ISSUE TITLE
[Bug Report]: CONTRIBUTING instructions for .Net and brm tool setup do not work

### ISSUE THREAD

**Issue by michael-crawford** [Azure/bicep-registry-modules#201]
### Module path

CONTRIBUTING.md

### Bicep version

0.10.61

### Describe the bug

In response to a question I asked on how we could create our own private module registry which has the same features as this public registry (i.e. mainly sub-modules, not supported by the `Publish-AzBicepModule` tool), I was directed to the CONTRIBUTING.md page, and assumed this meant this method could be used by Azure bicep developers external to Microsoft creating private module registries.

However, the instructions do not appear to be clear enough for non-full-time .Net developers, or they may just be out of date. I could not get the tool to work. Are these instructions current?

Here's some of the issues I hit, for example:

1. There's a link to Install a .NET runtime: https://dotnet.microsoft.com/en-us/download/dotnet/6.0/runtime, which takes us to a page with 3 variants on what to install, do we use the variant to "run console apps", "run desktop apps" or "run server apps". I picked "run console apps", downloaded and installed, but then when I ran the next statement, I got an error indicating the .Net was not installed. I killed and restarted Microsoft Terminal (running PowerShell 7.3.0 on Windows 11 fully updated.) Same error. I eventually found another link: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.403-windows-x64-installer, and installed that, version 6.0 as specified, but then I got more errors on the next step...
2. There's a link to Install the Bicep Registry Tool. It's not clear which version is current, and both methods I read don't work. The link takes you to a page which indicates you should use this command:
```
dotnet tool install --global Azure.Bicep.RegistryModuleTool --version 0.12.40
```
While below on the CONTRIBUTING Page, it indicates you use this command:
```
dotnet tool install --global Azure.Bicep.RegistryModuleTool
```
Both of these generate error messages which are not helpful in understanding what went wrong (same errors regardless of which command used above):
```
dotnet tool install --global Azure.Bicep.RegistryModuleTool --version 0.12.40
```
Output
```
C:\Users\MxxxxxxCxxxxxxx\AppData\Local\Temp\f2a3fd85-fae2-4467-95ad-6799821fbb07\restore.csproj : error NU1100: Unable to resolve 'azure.bicep.registrymoduletool (>= 0.12.40)' for 'net6.0'.
C:\Users\MxxxxxxCxxxxxxx\AppData\Local\Temp\f2a3fd85-fae2-4467-95ad-6799821fbb07\restore.csproj : error NU1100: Unable to resolve 'azure.bicep.registrymoduletool (>= 0.12.40)' for 'net6.0/any'.
The tool package could not be restored.
Tool 'azure.bicep.registrymoduletool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```
Any idea what's going on and can you confirm the instructions on the CONTRIBUTING.md page are correct and up-to-date?

## Additional Customer Feedback Comments
As a side note, I'd much prefer this tool to work in a manner similar to all other Azure functionality - as a PowerShell CmdLet installed like the other Az modules, ideally written in PowerShell, and not requiring these extra .Net install steps. I think the functionality being handled via this "out-of-band" method, would be better implemented as commands in the same module as the existing `Publish-AzBicepModule`, such as a `Generate-AzBicepModule` command to create the module structure.

I think that would be easier for private registry developers to work with, as not all of us wanting to publish bicep IaC modules are going to be .Net developers (I'm more Linux and bash, JavaScript or Python, for example but know PowerShell pretty well). I also think you should have a way to use the Azure CLI within bash on a Microsoft Terminal running Ubuntu to generate the framework and publish modules.

One more thing - as noted above, the `Publish-AzBicepModule` isn't aware of and can't handle this extended structure it seems, only single-file bicep modules. Please think about the fact that you can't use your own PowerShell CmdLet to generate and publish the public modules and had to write this additional tool - do you think us customers are likely to have needs less than yours? If you felt you needed to create this additional non-PowerShell (out-of-band, hard-to-find) method - why not FIX the `Publish-AzBicepModule` tool to do what is necessary, not just for you, since it's likely also necessary for us, but for everyone? I don't see the logic in creating this separate method for publishing modules. There should be ONE method which can publish either a single-file by itself like the current functionality, or the module directory structure as defined on the CONTRIBUTING page. And, it should be as simple as using the current `Publish-AzBicepModule` Cmdlet, as noted above. Hope that's not asking too much!

### To reproduce

Follow the instructions on CONTRIBUTING.md verbatim on Windows 11, in a PowerShell 7.3.0 window.

### Code snippet

```Bicep
# Either of these generate a variant of the same error below:
dotnet tool install --global Azure.Bicep.RegistryModuleTool --version 0.12.40
# Or
dotnet tool install --global Azure.Bicep.RegistryModuleTool
```

### Relevant log output

```Shell
C:\Users\MxxxxxxCxxxxxxx\AppData\Local\Temp\f2a3fd85-fae2-4467-95ad-6799821fbb07\restore.csproj : error NU1100: Unable to resolve 'azure.bicep.registrymoduletool (>= 0.12.40)' for 'net6.0'.
C:\Users\MxxxxxxCxxxxxxx\AppData\Local\Temp\f2a3fd85-fae2-4467-95ad-6799821fbb07\restore.csproj : error NU1100: Unable to resolve 'azure.bicep.registrymoduletool (>= 0.12.40)' for 'net6.0/any'.
The tool package could not be restored.
Tool 'azure.bicep.registrymoduletool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

**Comment by shenglol** [comment]
> ...which takes us to a page with 3 variants on what to install, do we use the variant to "run console apps", "run desktop apps" or "run server apps".

Looks like the dotnet team updated the download webpage for Windows. I'll update the contribution doc to mention that the "run console apps" one is the one we need.

> There's a link to Install the Bicep Registry Tool. It's not clear which version is current, and both methods I read don't work.

Can you run the following command to see if you have additional NuGet sources configured on your machine? 

```
dotnet nuget list source
```

Regarding the additional feedback, the main reason why we didn't include the `brm` functionalities in the Bicep CLI was because the target user is Bicep module contributors, not Bicep users. We published the tool as a dotnet tool instead of PowerShell module because it doesn't force people using `bash` / `zsh` on Linux and macOS to switch to a different shell to be able to use the tool.

In the future, if we get more module contributors, we can revisit the decision and merge the `brm` tool and the Bicep CLI.

**Comment by michael-crawford** [comment]
Hi, thanks for looking at this.

Running `dotnet nuget list source` returns `no sources found`.

I'd appreciate it if you could have very specific instructions on how to install whatever pre-requisites needed prior to attempting to install the dotnet `brm` tool itself. Ideally, some sanity check steps in the form of `list x`, and `confirm x.y.z exists`, similar to your dotnet nuget command above.

What IS the correct output of that - should I show `no sources found` if I installed the dotnet prerequisites properly?

On my additional feedback - I was not asking for `brm` functionalities to be added to the bicep tool. (I agree with your reasoning as to why it's not in there, but I could argue for a `developer mode` or flag which exposes that additional capability.)

That said, I don't think that's the right place to put this cleaner/easier publish non-single-file bicep modules - since you already have a command that does this. It's just not comprehensive enough, as it only publishes single-file bicep modules, and can't handle the more complex multi-file structure Microsoft itself nearly always has inside your own public registry modules (i.e. `.bicep/*` sub-modules). My suggestion was to extend this tool with the functionality in `brm` so that it's no longer needed as a separate tool requiring dotnet pre-requisites and dotnet knowledge. 

If I run this command, I get this output:
```PowerShell
Get-Command -CommandType Cmdlet | FindStr Publish-AzBicepModule
```
Output
```text
Cmdlet          Publish-AzBicepModule                              6.2.0      Az.Resources
```

Why can't this existing PowerShell command, owned by whatever team creates the `Az.Resources` PowerShell Module, be improved to add publication of a directory structure compatible with these public modules and `CONTRIBUTING` directions? And also add a `Generate-AzBicepModule` to the same `Az.Resources` PowerShell Module.

You're already supporting this for single-file bicep module publications - don't you think it makes sense to just improve this and make things simpler for bicep developers?

**Comment by shenglol** [comment]
I> unning dotnet nuget list source returns no sources found.

I'd appreciate it if you could have very specific instructions on how to install whatever pre-requisites needed prior to attempting to install the dotnet brm tool itself. Ideally, some sanity check steps in the form of list x, and confirm x.y.z exists, similar to your dotnet nuget command above.

It's weird that it returns no nuget source found, but may try adding nuget.org as a source:
```
dotnet nuget add source "https://api.nuget.org/v3/index.json" --name "nuget.org"
```

I'm going to add this to the contribution document.

> That said, I don't think that's the right place to put this cleaner/easier publish non-single-file bicep modules - since you already have a command that does this.

To clarify, there never exists a "publish non-single-file bicep modules` feature. What get published is always a single ARM template JSON file, even for the modules within this repo. What the `brm` tool provides is just commands for generating and validating registry module files. The publish step is still done by `bicep publish`.

> Why can't this existing PowerShell command, owned by whatever team creates the Az.Resources PowerShell Module, be improved to add publication of a directory structure compatible with these public modules and CONTRIBUTING directions? And also add a Generate-AzBicepModule to the same Az.Resources PowerShell Module.

You're already supporting this for single-file bicep module publications - don't you think it makes sense to just improve this and make things simpler for bicep developers?

Because the `Publish-AzBicepModule` cmdlet internally just invokes Bicep CLI, and it requires Bicep CLI to be installed and added to PATH. Adding another cmdlet as a facade of the `brm` tool is possible, but I don't know if that will make things simpler, since you would have to install the tool via `dotnet` anyway = at which point you could just invoke `brm`. It would make more sense to add such a cmdlet if we integrate the `brm` functionalities into Bicep CLI.

**Comment by michael-crawford** [comment]
I ran
```PowerShell
dotnet nuget add source "https://api.nuget.org/v3/index.json" --name "nuget.org"
```
Then ran
```PowerShell
dotnet nuget list source
```
and got this:
```text
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
```

I next ran:
```PowerShell
dotnet tool install --global Azure.Bicep.RegistryModuleTool
```
and got this:
```text
You can invoke the tool using the following command: brm
Tool 'azure.bicep.registrymoduletool' (version '0.12.40') was successfully installed.
```

So, that seems to have solved the immediate problem. I won't have time to fully test that the installed tool works until later this week or next. I will update this ticket if I hit more issues.

In your response to your comments to my suggestion to improve `Publish-AzBicepModule` and add `Generate-AzBicepModule`, I feel you're describing internal details I should not need to even know, much less care about.

**How** you do this is up to you. **What** it looks like to me as a bicep developer who wants to publish modules which consist of sub-modules and embedded JSON data files is all I care about.

And today, I use that publish command to publish my modules - that is my interface to this functionality. The fact this publish CmdLet uses the Bicep CLI under the covers came as a surprise to me, as I thought it would just be creating and pushing up the equivalent of a container image, for example. But, if it validates as it's doing that, I can see the need. My point here is that I didn't need to know such implementation details, because my interface is the Azure Az.Resources module CmdLet.

Since you currently **have** such a CmdLet with a pretty clear name `Publish-AzBicepModule` - from me as a bicep consumer/publisher perspective, why would you not improve this to publish both single-file modules and more complex modules which conform to the rules outlined by `CONTRIBUTING` and created by the current `brm generate` functionality? Why split two near-identical use-cases across not just two tools, but two visible different technologies? That makes no sense at all, and will only create confusion in the long run.

I was not aware of this link. I installed the bicep tool to decompile bicep. AFAIK, I did not realize that in order to deploy a bicep-based deployment using a command like `New-AzResourceGroupDeployment`, I needed to have this bicep tool installed. I thought this command just accepted either format, and any validation would be done on the server end, or via bicep logic baked into the CmdLet itself. Which is my point, I shouldn't have to know this. I definitely should not have to install dotnet pre-requisites like I have to do with `brm` - I didn't have to do anything like that when installing the `bicep` tool, did I?

I really think that you should have these three commands as the **single** interface to publishing `bicep` modules into either a public or private registry:

* `Publish-AzBicepModule` - this should accept either a `-FilePath module.bicep` single-file module (current functionality), or a `-FilePath container.zip` multi-file module in some type of archive format like zip or tar.gz (replacement for separate `brm` functionality. It should know the difference automatically from examination of file format, but you could throw in a `-Format Archive` switch.
* `Generate-AzBicepModule` - this would generate the directory structure used for the archive format, and would be a user-friendly wrapper around the `brm generate` functionality. Ideally you would have some way to validate user changes to this structure made after generation, but that might be better in the next command...
* `Package-AzBicepModule` - this would take as input the `brm generate` directory structure, with user-modifications, and create the archive format used for complex modules in the improved `Publish-AzBicepModule` command. You could have `-DryRun` or `-Validate` switch on this to validate the module is valid without actually publishing it.

IMHO, either improve the `Publish-AzBicepModule` concept to handle both simple and complex bicep modules, or remove this functionality alltogether and make this functionality visible only within the `bicep` command itself, with additional verbs.

Thanks for reading!

**Comment by shenglol** [comment]
> IMHO, either improve the Publish-AzBicepModule concept to handle both simple and complex bicep modules, or remove this functionality alltogether and make this functionality visible only within the bicep command itself, with additional verbs.

This makes sense. Merging `brm` and the Bicep CLI would be the easiest solution. @alex-frankel created https://github.com/Azure/bicep-registry-modules/issues/209 to track it.

**Comment by alex-frankel** [comment]
Sorry for missing this other thread. @michael-crawford -- it is still not clear to me what is not working with `Publish-AzBicepModule`. Whether you are publishing to a private registry or the public registry, there is always only one entry-point file. The publish command does not care if that single file is itself calling other modules.

It looks like we can close this specific issue since we resolved the brm installation issue. Let's move the discussion to #209.
