### ISSUE TITLE
[AVM Module Issue]: Azure Container Apps CORS support

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/bicep-registry-modules#2012]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/container-app

### (Optional) Module Version

0.4.0

### Description

The module needs to support configuration of `CORS` on the Azure Container Apps.

This is a part of the ingress configuration.

The default behavior of the module causes some issues. 

`By default, requests made through the browser to a domain that doesn't match the page's origin domain are blocked.`

https://learn.microsoft.com/en-us/azure/container-apps/cors

**Comment by AlexanderSehr** [comment]
Hey @oZakari, once you have a moment, please take a look to triage the issue 💪

**Comment by oZakari** [comment]
Hey @BenjaminEngeset, sorry for the late response as just got back from being out of office. We can definitely incorporate this into the module. I won't be able to get to it until a couple of weeks, but if you're interested, you can also open a pull request with the changes as well.
