### ISSUE TITLE
[AVM Module Issue]: avm/res/network/virtual-network multiple addressPrefixes/enable ipv6

### ISSUE THREAD

**Issue by DeuxFils** [Azure/bicep-registry-modules#2020]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/virtual-network

### (Optional) Module Version

0.1.6

### Description

To enable ipv6 you have to provide multiple addressPrefixes. For example this bicep:

```
module virtualNetworkHub 'br/public:avm/res/network/virtual-network:0.1.6' = {
  name: 'virtualNetworkHubDeployment'
  params: {
    name: 'vnet-ipv6-test'
    addressPrefixes: [
      '10.189.200.0/21'
      '2001:DB8:200::/56'
    ]
    subnets: [
      {
        name: 'vsub-ipv6-test'
        addressPrefixes: [
          '10.189.200.0/24'
          '2001:DB8:200:1::/64'          
        ]
      }
    ]
  }
}
```
This results in the following error.

```
[...]Status Message: The template output 'subnetAddressPrefixes' is not valid: The language expression property 'addressPrefixes' doesn't exist, available properties are 'provisioningState, addressPrefix, serviceEndpoints, delegations,
privateEndpointNetworkPolicies, privateLinkServiceNetworkPolicies'[...]
```
It seem there is no way to enable ipv6 on the subnet. Notice ther is a (preview) which allows to have multiple addressPrefixes for a subnet. [Link](https://learn.microsoft.com/en-us/azure/virtual-network/how-to-multiple-prefixes-subnet).

**Comment by cloudchristoph** [comment]
As this is still a Preview Feature - [quote](https://learn.microsoft.com/en-us/azure/virtual-network/how-to-multiple-prefixes-subnet?tabs=powershell#:~:text=Multiple%20prefix%20support%20for%20Azure%20Virtual%20Network%20subnets%20is%20currently%20in%20public%20preview.):

> Multiple prefix support for Azure Virtual Network subnets is currently in public preview. 

...is it worth to implement this feature?

**Comment by DeuxFils** [comment]
The underlying bicep API has support for multiple addressPrefixes for a long time. I think the only usefull usecase till now is when you have one IPv4 and one IPv6 prefix. This is the way to enable IPv6 on the subnet.

In the future it is possible to have one or more IPv4 prefixes and optional one IPv6 range. I don't expect multiple IPv6 ranges are usefull.

I believe when this bug is fixed, multiple IPv4 prefixes are supported/implemented as well. Eventhough this is a preview feature.

**Comment by AlexanderSehr** [comment]
Hey @elbatane, please take a look when you can

**Comment by AlexanderSehr** [comment]
ping @elbatane

**Comment by elbatane** [comment]
Hi, thank you for open the issue. We will review and add this functionality. Thank you
