### ISSUE TITLE
[app/job]: change `secure` parameter to a custom type

### ISSUE THREAD

**Issue by ReneHezser** [Azure/bicep-registry-modules#2071]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/job

### Description

The `secrets` parameter is defined as an object and contains a `secureList` property. This should be changed to a custom type to improve syntax highlighting and get rid of the workaround introduced earlier.

#2070

**Comment by ReneHezser** [comment]
Waiting for merge of #2074

**Comment by AlexanderSehr** [comment]
Removing the `Needs: Triage` label to avoid a flood of comments ;)
