### ISSUE TITLE
[AVM Module Issue]: Urgent action required: Update your Azure API Management tooling to a supported management API version by 1 June 2024

### ISSUE THREAD

**Issue by dewolfs** [Azure/bicep-registry-modules#2075]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/api-management/service

### Description

Hi,

After deployment of APIM with diagnostic settings, we get a message in Azure Health Advisory:

> You're receiving this message because you're currently using one or more API versions prior to 2021-08-01 to configure or manage your Azure API Management services.
> 
> All API versions prior to 2021-08-01 will be retired starting 1 June 2024. These API versions will be disabled gradually and without further notice. The previously communicated date was 30 September 2023. You'll no longer be able to create or manage your API Management services using templates, tools, scripts, or programs that rely on a disabled API version.
> 
> Data plane operations, such as mediation of API requests in the gateway, remain unaffected by this change.
> 
> The API version may be embedded in deployment templates and tools that interact programmatically with API Management services.

More info: https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/api-version-retirement-sep-2023

The main.bicep config file contains the resource diagnostic settings with an API version prio to api-version 2021-08-01 which triggers the advisory alert.

https://github.com/Azure/bicep-registry-modules/blob/67c4156b2fec8c18116c2fe15791931708716666/avm/res/api-management/service/main.bicep#L468

Can we take this opportunity to upgrade all apim resources in this module to a more recent api-version ? ex: 2022-08-01

**Comment by tony-box** [comment]
@dewolfs thanks for the heads up. I have another PR right now #1989 that updates the core APIM service to the latest API. I Think I will combine this fix into that PR.
