### ISSUE TITLE
[AVM Module Issue]: PTN Module Role Assignment - No management Group

### ISSUE THREAD

**Issue by jkamping** [Azure/bicep-registry-modules#2076]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/ptn/authorization/role-assignment

### Description

I am trying to deploy the patern module for the role assigments in my MSDN subscription but this subscription is missing a management group. When trying to deploy the role to a subscription I have to scope the module to a management group that doensn't exist in my enviroment and change the scope is not possible.

Can this module be applied to enviroment where there is no management group?

**Comment by arnoldna** [comment]
@jkamping - Thanks for providing feedback.  All subscriptions should have at least the "Tenant Root Group" management group by default.  I would check that the account you are logging in with has the appropriate permissions. Make sure that you are logging with an account that has the "Global Administrator" role.

**Comment by jkamping** [comment]
@arnoldna even the Tenant Root Group was missing but the subscription is a old own. I created the Tenant Root Group now and assigned Owner permissions for my account and I can deploy the module now
