### ISSUE TITLE
[AVM Question/Feedback]: What is the strategy for AVM bicep modules to keep up with resource API Version updates?

### ISSUE THREAD

**Issue by alpersilistre** [Azure/bicep-registry-modules#2077]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi team,

We have been using Azure ARM JSON templates for many years and recently monitoring the status of Bicep and AVM initiative. We are a cloud team provides application teams a ready to use templates. We have been doing this with Azure ARM JSON templates, but we now want to use AVM bicep in the future.

My question is, how AVM team is keeping up with resource API versions? There are some important Azure resources that we want to deploy with AVM bicep, but respective AVM modules currently do not target newest versions.

Let me give some examples.

## Key Vault

Supported API version for Microsoft.KeyVault/vaults is 2022-07-01 in the AVM module: https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/key-vault/vault/README.md#resource-types

However, the latest Azure resource API version is 2023-07-01: https://learn.microsoft.com/en-us/azure/templates/microsoft.keyvault/allversions
AVM is 3 versions behind in this case.

## API Management

Supported API version for Microsoft.ApiManagement/service is 2021-08-01 in the AVM module: https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/api-management/service/README.md#resource-types

In this case, the latest Azure resource API version is 2023-05-01-preview: https://learn.microsoft.com/en-us/azure/templates/microsoft.apimanagement/allversions
It is 6 versions behind.

---

These are just two examples, but there are version gaps in other important resources as well.

I want to learn what is the strategy here. Is there a roadmap for keeping up with API versions? I'm not expecting the team to keep up with the latest version all the time, as that would be hard to achieve; I understand that. But I would like see what is the roadmap or next suppported version will be to better understand the strategy here. Or will upgrading to the newest version be prioritized if there is a security update? For example, sometimes we see recommendations to upgrade to a later API version in Azure Defender for Cloud.

Thank you.

**Comment by alpersilistre** [comment]
Hi @ChrisSidebotham, thank you for the response. I understand that the older version can be the latest - 5. Otherwise, it will not pass the static validation test.

Regarding opening an issue, if we see a major gap between the latest API version and the latest support AVM module (let's say the version is no bigger than 5, but it might be a couple of years old resource API), can we create an issue on this repo to request a new version? Because I understand that you want to follow a reactive approach here, and I would like to act accordingly.

**Comment by ChrisSidebotham** [comment]
@alpersilistre - Absolutely, if you require the API Version updated, please raise an issue. The module owner can either pick this up if they are not already working on it. :)

**Comment by alpersilistre** [comment]
> @alpersilistre - Absolutely, if you require the API Version updated, please raise an issue. The module owner can either pick this up if they are not already working on it. :)

Thanks 👍

**Comment by ChrisSidebotham** [comment]
I will now close this issue as we have no actionable items directly from this issue log
