### ISSUE TITLE
[AVM Module Issue]: Virtual Machine Module has issues with linuxConfiguration patchMode

### ISSUE THREAD

**Issue by kevin-381ecc2e** [Azure/bicep-registry-modules#2081]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.4.2

### Description

When deploying a Linux VM the deployment results in an error on the linuxConfiguration and specifically the patchMode.

I've set the patchMode parameter to 'ImageDefault' as defined by the manual and the template. Unfortunately the template still fails because a condition doesn't seem to be right. It appears that the automaticByPlatformSettings value is getting filled even when patchMode is set to 'ImageDefault'.

Error message:
```json
{
    "code": "InvalidParameter",
    "target": "linuxConfiguration.patchSettings.automaticByPlatformSettings",
    "message": "AutomaticByPlatformSettings cannot be set if the PatchMode is not 'AutomaticByPlatform'."
}
```

**Comment by AlexanderSehr** [comment]
Hey @rahalan, please take a look at your earliest convenience and triage the issue💪

**Comment by rahalan** [comment]
@kevin-381ecc2e thanks for bringing it up. Will look into it.
