### ISSUE TITLE
[AVM Module Issue]: nicConfigurations Use an existing PIP and network AVM module

### ISSUE THREAD

**Issue by darrenFrowen** [Azure/bicep-registry-modules#2083]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.4.2

### Description

Hi,

Due to publicIpNameSuffix and nicSuffix being required properties for nicConfigurations, is there a way i can reference existing outputs of Public IP and NICs created from AVM network interface and public IP address modules?

Regards

**Comment by darrenFrowen** [comment]
Thank you On 28 May 2024, at 20:01, avm-team-linter[bot] ***@***.***> wrote:﻿
@darrenFrowen, thanks for submitting this issue for the avm/res/compute/virtual-machine module!
ImportantA member of the @Azure/avm-res-compute-virtualmachine-module-owners-bicep or @Azure/avm-res-compute-virtualmachine-module-contributors-bicep team will review it soon!

**Comment by AlexanderSehr** [comment]
Hey @rahalan, please take a look at your earliest convenience 💪

**Comment by rahalan** [comment]
@darrenFrowen Thank you. I will look into it how to solve that.

**Comment by rahalan** [comment]
@darrenFrowen for NICs you can already define a custom name, instead of the prefix. For the PIP, there is a PR open, that will give you the same possibility (define a custom name, instead of a prefix). Does that solve your issue?

**Comment by darrenFrowen** [comment]
Hi,Sorry I have just returned from A/L will refresh my memory on Monday and get back to you then.Regards On 7 Jun 2024, at 17:01, Rainer Halanek ***@***.***> wrote:﻿
@darrenFrowen for NICs you can already define a custom name, instead of the prefix. For the PIP, there is a PR open, that will give you the same possibility (define a custom name, instead of a prefix). Does that solve your issue?

**Comment by darrenFrowen** [comment]
@rahalan i have just reviewed the template and sure enough it does allow custom NIC name, apologies for my confusion. As for the PR if that provides the same logic then yes that will solve my issue. is there any way i can view that PR do you have the link?

**Comment by darrenFrowen** [comment]
Hi @rahalan,

I see you have closed with fix in #2264 . However i have tested the custom name with the following. As you can see the publicIpNameSuffix is commented out and enablePublicIP set to true, this results in a failure as the true setting still expects the Suffix which means it ignore the name: property. 

If i set the enablePublicIP set to false assuming there is an existing public IP and setting the name, this also fails but this time

'The language expression property 'publicIpNameSuffix' doesn't exist, available properties are 'name'.' (Code:InvalidTemplate)   CorrelationId: 7ae3b01c-254b-4d07-9586-ad4dd4a0b4c2

          enablePublicIP: true
          ipConfigurations: [
            {
              name: 'ipconfig-untrust'
              subnetResourceId: subnetUntrustId
              pipConfiguration: {
                // publicIpNameSuffix: ''
                name: 'pip-s-${hubPrefix}-${vmName.name}'

**Comment by darrenFrowen** [comment]
Hi @rahalan, i have just revisited and  i can now see the version 0.5.0 available re-enable the custom PIP name and IP Protection and all went in fine thanks. There must be quite a big delay in the linter API version being avaialbe.


![image](https://github.com/Azure/bicep-registry-modules/assets/16030060/f530df36-3822-4150-81f6-fc5f8fece49f)
