### ISSUE TITLE
[AVM Module Issue]:  Please Update virtual-machine module nic-configuration.bicep for new public IP module 0.4.1

### ISSUE THREAD

**Issue by darrenFrowen** [Azure/bicep-registry-modules#2085]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.4.2

### Description

Hi,

Public IP Address AVM module has been recently updated to allow DDoS IP Protection, this now means that ddosProtectionPlan is not a required parameter. New version is 0.4.1 nic-configuration.bicep is using 0.4.0. This was implemented as part of the following pull request.

https://github.com/Azure/bicep-registry-modules/pull/2006

![image](https://github.com/Azure/bicep-registry-modules/assets/16030060/5e601eb6-8414-4046-9274-a82530dada65)

**Comment by rahalan** [comment]
@darrenFrowen thank you. I will investigate

**Comment by darrenFrowen** [comment]
Thank youOn 4 Jun 2024, at 15:46, Rainer Halanek ***@***.***> wrote:﻿
@darrenFrowen thank you. I will investigate

**Comment by darrenFrowen** [comment]
@rahalan any update on this one please?

**Comment by darrenFrowen** [comment]
Hi @rahalan,

I can clearly see that the module for the public IP address is now at 0.4.1 as follows.

module networkInterface_publicIPAddresses 'br/public:avm/res/network/public-ip-address:0.4.1'

which should support the following configuration without specifying the DDoS Plan ID.

                ddosSettings: {
                  protectionMode: 'Enabled'
                }

However when i execute the deployment it fails with the following error. 

Deployment template validation failed: 'The provided value    
     | for the template parameter 'ddosSettings' is not valid. A non-null value for the property 'ddosProtectionPlan' must be provided.
