### ISSUE TITLE
Enable usage of `brm` as a single-file executable so there is no .NET requirement

### ISSUE THREAD

**Issue by alex-frankel** [Azure/bicep-registry-modules#209]
*Created out of #192* 

It would be great to ship `brm` as a self-contained binary (or better yet as part of the `bicep` CLI). This will allow us to expose the generation and validation capabilities more broadly. You can imagine a command like:

```
az bicep publish --generate ...
```

**Comment by ChrisSidebotham** [comment]
Dear @alex-frankel, Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

As part of this transition, the new AVM CI environment is replacing the existing CI formerly leveraged within the Bicep Registry Modules (BRM) repository. As a result of this, issues and features related to the existing BRM CI will be closed. If you think your issue still needs addressing, please raise a new issue related to the AVM CI, [here](https://aka.ms/BRM/AVMQuestionFeedback).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
