### ISSUE TITLE
[AVM Module Feature]:  Microsoft.Web/sites support API Kind

### ISSUE THREAD

**Issue by bgreen-aiacontracts** [Azure/bicep-registry-modules#2090]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### (Optional) Module Version

0.3.2

### Description

My organization deploys Azure app services using a kind of API.  Support for this in AVM would be a nice additional.  I currently utilize avm for web apps, and function apps but have to write out the full bicep for API.

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy, please take a look when you get the chance. Busy modue this is 😄
