### ISSUE TITLE
[AVM Module Issue]: Sql Database not working for SKU DataWarehouse

### ISSUE THREAD

**Issue by solita-johan-kitti** [Azure/bicep-registry-modules#2105]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/sql/server

### (Optional) Module Version

DataWarehouse sku do not supportbackupShortTermRetentionPolicies

### Description

If the AVM is used for a database with SKU DataWarehouse the deployment will fail even if the backupShortTermRetentionPolicies parameter is set to {} in the database module the usage of 
`module database_backupShortTermRetentionPolicy 'backup-short-term-retention-policy/main.bicep' `
should probably have an if check not to set the backupLongTermRetentionPolicy id the backupLongTermRetentionPolicy is empty.

Error: 
"This feature is not available for the selected database's edition (DataWarehouse). (Code: FeatureDisabledOnSelectedEdition)"

**Comment by bryansan-msft** [comment]
@solita-johan-kitti can you provide a code example of the error?
