### ISSUE TITLE
[AVM Module Issue]: avm web/sites is missing acrUseManagedIdentityCreds properties

### ISSUE THREAD

**Issue by dibcar** [Azure/bicep-registry-modules#2106]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/site

### Description

The lastest version of web/site for siteConfig parameter is missing acrUseManagedIdentityCreds and acrUserManagedIdentityID properties.

**Comment by tsc-buddy** [comment]
@dibcar Thanks for logging this - You should have no problems accessing those properties. The siteConfig parameter expects an object to allow to you provide what ever properties and config you wish. 

I will run a some quick tests this week, and post any updates here.

**Comment by tsc-buddy** [comment]
Just runs some tests - both are usable on the latest version of the module.

**Comment by dibcar** [comment]
My bad, i don't know how I looked at it but you're right, the object is passed as is to the api. We can close this issue, thanks.
