### ISSUE TITLE
Telemetry gathering guidance for contributors

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#215]
As per https://github.com/Azure/bicep-registry-modules/pull/214#discussion_r1042189610

---

Some module contributors are gathering deployment telemetry in their modules.

I think we should guide contributors who have this in their modules to do so consistently so consumers of the bicep registry are familiar with both the activity and the parameter they need to provide to opt out.

It would be great if we can provide clear, consistent guidance for;
1. Parameter Name
2. Default value

We'll likely need to add a "Telemetry tracking" section to this repos README.md too.

**Comment by jtracey93** [comment]
I think taking this forward also it would be great to get some telemetry provided from the registry itself. 

e.g. how many times a module has been pulled, split by version pulled also

**Comment by shenglol** [comment]
> I think taking this forward also it would be great to get some telemetry provided from the registry itself.
> 
> e.g. how many times a module has been pulled, split by version pulled also

The registry telemetry data is available today since we are using MCR 🙂.

/cc @alex-frankel.

**Comment by alex-frankel** [comment]
Shenglong is right. I think the work that needs to happen is to display that telemetry somewhere publicly.

**Comment by ChrisSidebotham** [comment]
Dear @REPLACE_WITH_AUTHOR, Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

As part of this transition, the new AVM CI environment is replacing the existing CI formerly leveraged within the Bicep Registry Modules (BRM) repository. As a result of this, issues and features related to the existing BRM CI will be closed. If you think your issue still needs addressing, please raise a new issue related to the AVM CI, [here](https://aka.ms/BRM/AVMQuestionFeedback).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
