### ISSUE TITLE
[AVM Module Issue]: CosmosDB continuous backup and serverless capacity not working

### ISSUE THREAD

**Issue by jorik90** [Azure/bicep-registry-modules#2189]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/document-db/database-account

### (Optional) Module Version

0.5.4

### Description

I try to create an CosmosDB account with serverless capacity and continuous backup. This does not seem to be working with AVM. Using Bicep CLI v0.27.1.

The following Bicep creates a CosmosDB with AVM (incorrectly) and directly with Bicep (correctly):

main.bicep
```bicep
targetScope = 'subscription'

@minLength(1)
@description('Primary location for all resources')
param location string = 'westeurope'

resource resourceGroup 'Microsoft.Resources/resourceGroups@2021-04-01' existing = {
  name: 'jorik-l-we-rg'
}

module cosmosDb 'br/public:avm/res/document-db/database-account:0.5.4' = {
  scope: resourceGroup
  name: 'cosmosdb'
  params: {
    name: 'jorikavmcosmos-o-we-cosmosdb'
    locations: [
      {
        failoverPriority: 0
        locationName: 'westeurope'
        isZoneRedundant: false
      }
    ]
    capabilitiesToAdd: [
       'EnableServerless'
    ]
    backupPolicyType: 'Continuous'
    backupPolicyContinuousTier: 'Continuous7Days'
  }
}

module cdb 'cosmosdb.bicep' = {
  scope: resourceGroup
  name: 'cdb'
}
```

cosmosdb.bicep
```bicep
resource symbolicname 'Microsoft.DocumentDB/databaseAccounts@2023-11-15' = {
  name: 'joriknietavmcosmos-o-we-cosmosdb'
  location: 'westeurope'
  kind: 'GlobalDocumentDB'
  properties: {
    backupPolicy: {
      type: 'Continuous'
      continuousModeProperties: {
        tier: 'Continuous7Days'
      }
    }
    capabilities: [
      {
        name: 'EnableServerless'
      }
    ]
    capacity: {
      totalThroughputLimit: 4000
    }
    databaseAccountOfferType: 'Standard'
    enableFreeTier: false
    locations: [
      {
        failoverPriority: 0
        isZoneRedundant: false
        locationName: 'westeurope'
      }
    ]
  }
}

```

![Schermafbeelding 2024-06-04 163047](https://github.com/Azure/bicep-registry-modules/assets/157545/80310279-a41c-4c33-b781-2732fb4e694b)
![Schermafbeelding 2024-06-04 163105](https://github.com/Azure/bicep-registry-modules/assets/157545/09cae25b-1fda-4a1f-9aa9-49e8de6cf4ed)

### (Optional) Correlation Id

e8f9993f-d7b1-4292-bb29-e1c7d276b122

**Comment by bryansan-msft** [comment]
Hello @jorik90 try adding at least 1 database to see the continuous backup configured

**Comment by dmusic** [comment]
Why is it mandatory to have at least on database created during provisioning of CosmosDB Account to set Serverless capability:

  ((!empty(sqlDatabases) || !empty(mongodbDatabases) || !empty(gremlinDatabases) || !empty(tables))
    ? {
        ....
        capabilities: capabilities
        ....
      }
    : {}),

At least capabilities property should be set accordingly to capacity mode.
