### ISSUE TITLE
[AVM Module Issue]: Support Entra ID authentication with Microsoft Cache for Redis

### ISSUE THREAD

**Issue by deckerbd** [Azure/bicep-registry-modules#2190]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cache/redis

### (Optional) Module Version

0.3.2

### Description

Hey there! 👋 Long time user, first time caller.

Went to create a new Redis instance using the new [Entra ID authentication support](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-whats-new#microsoft-entra-id), but the deployment ended up failing when providing `'aad-enabled': 'true'` in the `redisConfiguration` parameter. The error cites Microsoft Entra Authentication is supported only for requests with minimum API version 2023-05-01-preview, which makes sense as the current module is using 2022-06-01.

Now that Entra ID for cache authentication is out in GA, can this use case be supported? 🙏

**Comment by hundredacres** [comment]
PR: https://github.com/Azure/bicep-registry-modules/pull/2194
