### ISSUE TITLE
[AVM Module Issue]: How to retrieve a Managed Environment static IP?

### ISSUE THREAD

**Issue by arnaud-tincelin** [Azure/bicep-registry-modules#2197]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/app/managed-environment

### Description

I am following the Azure documentation

> If you don't plan to use a custom domain, create a private DNS zone that resolves the Container Apps environment's default domain to the static IP address of the Container Apps environment. You can use [Azure Private DNS](https://learn.microsoft.com/en-us/azure/dns/private-dns-overview) or your own DNS server. If you use Azure Private DNS, create a private DNS Zone named as the Container App environment’s default domain (<UNIQUE_IDENTIFIER>.<REGION_NAME>.azurecontainerapps.io), with an A record. The A record contains the name *<DNS Suffix> and the static IP address of the Container Apps environment.

The module has an output `defaultDomain` but I cannot find an output using the `properties.staticIp` value?

**Comment by hundredacres** [comment]
PR: https://github.com/Azure/bicep-registry-modules/pull/2265
