### ISSUE TITLE
[AVM Module Issue]: Postgres v16 not in allowed list

### ISSUE THREAD

**Issue by coolhome** [Azure/bicep-registry-modules#2203]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/db-for-postgre-sql/flexible-server

### (Optional) Module Version

latest

### Description

```bice[
@allowed([
  '11'
  '12'
  '13'
  '14'
  '15'
])
@description('Optional. PostgreSQL Server version.')
param version string = '15'
```

This should support 16.

**Comment by AlexanderSehr** [comment]
Hey @josearper, please take a look when you get the chance

**Comment by josearper** [comment]
I'm working on this one now.

**Comment by sam-bryant** [comment]
Thanks.  Also looking for version 16.

**Comment by DanGiffen** [comment]
Hi guys,

https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/db-for-postgre-sql/flexible-server

I'm not seeing 16 as available, please update. Thanks Dan

![image](https://github.com/user-attachments/assets/fd4d7114-6f73-4d25-b2b7-d0c1f3ae623e)
![image](https://github.com/user-attachments/assets/bda5412e-3183-497f-8c28-d6eff8251ed7)
