### ISSUE TITLE
[AVM Module Issue]: Update Redis version to 2024-03-01. 

### ISSUE THREAD

**Issue by jachin84** [Azure/bicep-registry-modules#2204]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/cache/redis

### (Optional) Module Version

0.3.2

### Description

When attempting to deploy a Redis cache using version 0.3.2 with the EntraID Auth enabled I get the following error:
```
Microsoft Entra Authentication is supported only for requests with minimum API version 2023-05-01-preview. Please update the API version for the request URL to 2023-05-01-preview or later versions and then retry the request.
```

To repo just set:
```json
redisConfiguration: {
"aad-enabled": true
}
```

The fix is to update the Redis resource to apiVersion  `2022-06-01`.

**Comment by hundredacres** [comment]
PR: https://github.com/Azure/bicep-registry-modules/pull/2194
