### ISSUE TITLE
[AVM Module Issue]: ACA AVM should allow the creation of container apps without ingress

### ISSUE THREAD

**Issue by mosabami** [Azure/bicep-registry-modules#2205]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/container-app

### Description

One of the important reason for using container apps is to be able to easily create microservice applications that can communicate with themselves using its internal network. This allows customers to build applications where only a subset of the microservices can be accessed via ingress for security, cost and other reasons. The current AVM doesnt allow creation of those ingressless container-apps.

**Comment by oZakari** [comment]
Thanks @mosabami, will work on getting this incorporated hopefully this month.
