### ISSUE TITLE
[Module Proposal]: Creating Event Grid System Topic

### ISSUE THREAD

**Issue by jashjain211** [Azure/bicep-registry-modules#2260]

**Comment by matebarabas** [comment]
@jashjain211, the Event Grid System Topic Bicep module is already available, here: https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/event-grid/system-topic

For the list of all available modules, please see the AVM Module Index pages: https://aka.ms/AVM/ModuleIndex

To propose a new module (Bicep or Terraform), please use the module proposal template (https://aka.ms/AVM/ModuleProposal) or select the "New AVM Module Proposal 📝" option on the New issue page.
