### ISSUE TITLE
[Module Proposal]: Azure Database for PostgreSQL - Flexible Server

### ISSUE THREAD

**Issue by sunilthorat09** [Azure/bicep-registry-modules#227]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Creating a new base module for PostgreSQL Flexible Server Database similar to the ACR as described [here](https://github.com/Azure/bicep-registry-modules/issues/166).
Regarding the module path, looking for input on the naming conventions used here if my suggestion is not suitable. Thanks!

### Module path

database/postgresql-flexible-server

### Describe the module

This module will allow to create [PostgreSQL Flexible Server ](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/overview) resource.

**Comment by alex-frankel** [comment]
@sunilthorat09 - while the proposal is approved, we need someone from internal MS to contribute the PR.

**Comment by thomasriley** [comment]
@alex-frankel  - I was speaking with @sunilthorat09 the other day about this proposal and it is actually no longer required. Unless there is a requirement for this from another team right now, it might be worth closing this one as there will not be a PR forthcoming in the near future?

(FYI - @sunilthorat09 is actually internal via Team Nuance - appears Sunil has not yet joined in Azure org yet).
