### ISSUE TITLE
[AVM Question/Feedback]: Customize deployment history workflow

### ISSUE THREAD

**Issue by sebassem** [Azure/bicep-registry-modules#2302]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

In the ALZ sub-vending pattern module, we need to have this workflow to run on a custom management group as it generates lots of deployments.

**Comment by matebarabas** [comment]
@Azure/avm-core-team-technical-bicep folks, when you have a chance, please take a look. Thanks!

**Comment by AlexanderSehr** [comment]
We can certainly do that via a runtime parameter. 

I'd be curious though @jtracey93, how did you handle the mgmt-group deployment limit in ALZ-Bicep?
