### ISSUE TITLE
[Bug Report]: Documentation implies HelmParams but code requires HelmAppParams

### ISSUE THREAD

**Issue by imagiro69** [Azure/bicep-registry-modules#231]
### Module path

/modules/deployment-scripts/aks-run-helm

### Bicep version

0.13.1

### Describe the bug

The **README.md** on line 109 suggests that the field in the HelmApp object should be HelmParams, however the code in **aks-run-helm.bicep** looks for **helmAppParams** on the **app** object.

The readme is also not clear on line 26, about possible values in the helmApps array.

### To reproduce

{
        helmApp: 'bitnami/contour'
        helmAppName: 'contour-ingress'
        **helmParams**: '--version 7.7.1 --namespace ingress-basic --create_namespace --set envoy.kind=deployment --set contour.service.externalTrafficPolicy=cluster'
      }

Found using **az deployment**

**Comment by aristosvo** [comment]
@imagiro69 This will be fixed when #212 is merged 🎉

**Comment by ChrisSidebotham** [comment]
Dear @imagiro69 , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
