### ISSUE TITLE
[AVM Module Issue]: Storage Account networkAcls bypass if `defaultAction: 'Allow'`

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/bicep-registry-modules#2310]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### (Optional) Module Version

0.9.0

### Description

#878 had a PR #951 to set `bypass` to some value if `defaultAction: 'Deny'`, but the same problem remains if setting `defaultAction: 'Allow'`.

As discussed from this comment: <https://github.com/Azure/bicep-registry-modules/issues/878#issuecomment-2158846625>. Please add a workaround for fixing this with `defaultAction: 'Allow'` too. @AlexanderSehr had a suggestion here: <https://github.com/Azure/bicep-registry-modules/issues/878#issuecomment-2158890513>.

**Comment by AlexanderSehr** [comment]
Hey @fblix,
I'll create a quick PR.
