### ISSUE TITLE
[AVM Module Issue]: Microsoft.Web/connections, need parameterValueSet for deploying service bus type API Connection

### ISSUE THREAD

**Issue by DJHaose** [Azure/bicep-registry-modules#2338]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/connection

### (Optional) Module Version

0.1.0

### Description

Using Chrome developer tool to see the payload sent in JSON when creating an API connection that's service bus type. Similar to this Q&A https://learn.microsoft.com/en-us/answers/questions/1427460/how-to-paramatize-service-bus-managed-identity-in 

We need either an additional properties parameter or a parmeterValueSet parmeter. Currently there are customParameterValues, nonSecretParameterValues and parameterValues non of them fulfils that parameterValueSet under properties.

```javascript
{
  "type": "Microsoft.Web/connections",
  "apiVersion": "2016-06-01",
  "name": "[parameters('connections_servicebus_name')]",
  "location": "[parameters('location')]",
  "kind": "V2",
  "properties": {
      "api": {
          "id": "[concat('/subscriptions/', parameters('subscriptionId'), '/providers/Microsoft.Web/locations/', parameters('location'), '/managedApis/servicebus')]"
      },
      "parameterValueSet": {
          "name": "managedIdentityAuth",
          "values": {
              "namespaceEndpoint": {
              "value": "[concat('sb://', parameters('servicebus_namespace'), '.servicebus.windows.net/')]"
              }
          }
      },
      "displayName": "[parameters('connections_servicebus_name')]"
  }
}
```

**Comment by matebarabas** [comment]
This module is currently orphaned: https://github.com/Azure/Azure-Verified-Modules/issues/767

**Comment by ReneHezser** [comment]
Hi @DJHaose,
if it is just the missing parameter, we can implement it. I'd like to add an example of a Service Bus connection to the documentation. Would you mind providing a complete example of your scenario?

**Comment by ReneHezser** [comment]
A request to add the property has already been created here: https://github.com/Azure/bicep-types-az/issues/1812
