### ISSUE TITLE
[Bug Report]: Image creation purchase plan information error

### ISSUE THREAD

**Issue by mpr555** [Azure/bicep-registry-modules#2359]
### Image creation purchase plan information error

When using Microsoft.compute/galleries/images, the part of the code that inputs Plan information is incorrect.  As this causes an error in the portal when using a Microsoft image.  If you try and deploy a Vm from the compute gallery you get a validation error that there is no plan name.

When deploying it has the below in the arm template that you can download before creating the resource.

```
purchasePlan: {}
```
But as it's a Microsoft image there is no plan information.  If you delete that part and then rerun the script it validates and will then let you proceed.

This is the code that is causing the issue.
```
    purchasePlan: {
      product: !empty(productName) ? productName : null
      name: !empty(planName) ? planName : null
      publisher: !empty(planPublisherName) ? planPublisherName : null
    }
```
I think it needs to be something like this or similar so that it does not pass any plan information

```
purchasePlan: !empty(purchasePlan) ? purchasePlan : null
```

### To reproduce

This is run from a bicep solution that uses azure image builder to build a custom image that then puts that image into the compute gallery.

**Comment by AlexanderSehr** [comment]
Hey @ReneHezser,
just migrated the issue from CARML as an effort we're triving in the background for issues that may still be relevant. Please take a look when you can :)

**Comment by ReneHezser** [comment]
Sorry I missed this one. Will look at it today.

**Comment by AlexanderSehr** [comment]
If the case @ReneHezser (and the issue makes sense), the first step should be to remove the `Needs: Triage` label as it will stop the bot from commenting :)
