### ISSUE TITLE
[Question/Feedback from Discussions] Extend Databricks module

### ISSUE THREAD

**Issue by eriqua** [Azure/bicep-registry-modules#2360]
### Discussed in https://github.com/Azure/ResourceModules/discussions/3088

<div type='discussions-op-text'>

<sup>Originally posted by **Ulveno** April  4, 2023</sup>
Hello, 

Awesome work with all the modules. I was testing the Databricks module but it looks like there are missing properties params. 
</div>

CC: @Ulveno

**Comment by AlexanderSehr** [comment]
Hey @clintgrove,
please note that we're currently working on migration the still relevant issues from the original CARML modules over to AVM. This one is for a module that's owned by you.

There is not much in the description, but at least a few parameter seems to be missing (unless they're read-only). Please triage when you have a moment :)

![image](https://github.com/Azure/bicep-registry-modules/assets/5365358/ff7f0b95-3bdd-4dc4-8eb0-0c2ece780a1f)

**Comment by clintgrove** [comment]
Noted, I will have a look as soon as I can.

**Comment by clintgrove** [comment]
I am getting answers from Product group about these parameters. I suspect that none of them will add value to our current deployment code.

authorizations
uiDefinitionUri
 
And these below might just be read only and CANNOT be set at deployment 
createdBy
managedDiskIdentity
storageAccountIdentity
updatedBy

**Comment by AlexanderSehr** [comment]
thanks for checking @clintgrove .

As chatted about, I suspect the best course of action will be to add them as properties (not parameters), but outcommented like
```bicep
{
  (...)
  // createdBy: createdBy // Read-only 
```
