### ISSUE TITLE
using shared private dns zone that exist in resource group A in module scoped in resource group B 

### ISSUE THREAD

**Issue by azurecorner** [Azure/bicep-registry-modules#2363]
### Description

**Bicep version**
Bicep CLI version 0.17.1 (https://github.com/Azure/bicep/commit/d423d618828004879984cb4efedda2cdc6c2c66c)

**Describe the bug**
I would like to reference an existing private dns zone (created in another ressource group) when creating private endpoint module
But it seems that it is not possible to reference a private dns zone by id and reource group or name and reource group
To Reproduce
```bicep
resource privateDnsZone 'Microsoft.Network/privateDnsZones@2020-06-01' existing = { 
  name: privateDnsZoneName **// resource group here** 
}
```
Because the module is used with resource group scope , it cannot find the private dns zone that exist in another resource group

```bicep
module keyvaultPrivateEndpoint 'modules/private_endpoint.bicep' = {
  scope: resourceGroup(rgDemo)
  name: privateEndpoint_KvName
  params: {
    location: location
    privateEndpointName: privateEndpoint_KvName
    privateDnsZoneName: privateDnsZoneName
    pvtEndpointDnsGroupName: pvtEndpointDnsGroupName
    virtualNetworkId: vnet.outputs.id
    privateLinkConnexionService_kvName: privateLinkConnexionService_kvName
    privateDnsZonevirtualNetworkLinks_kvName: privateDnsZonevirtualNetworkLinks_kvName
    subnetId: '${vnet.outputs.id}/subnets/${subnetName}'
    privateLinkServiceId: keyvault.outputs.id
  }

  dependsOn: [
    vnet
    keyvault
  ]
}
```
When running the code at subscription level using

`az deployment sub create --location eastus --template-file main.bicep --parameters location="eastus"`

I have the following issue

`Private Dns Zone group /subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/rg-workshop/providers/Microsoft.Network/privateEndpoints/pe-kv-demo/privateDnsZoneGroups/mydnsgroupname has invalid private dns zone ids`

because it cannot find the private dns zone in the scoped resource group

## Additional context
You can find the all code here https://github.com/azurecorner/azure-bicep-workshop

**Comment by AlexanderSehr** [comment]
Hey @segraef,
please note that I just migrated this issue over from CARML. As this should still be relevant, it would be great if you could take a look. I'm not entirely sure if it is something that can be solved in the module though as the only 'child' we deploy is the Zone-Group, and not the zones themselves that are provided using a resourceId. I'd hence have expected it would already allow to use zones from other RGs.

**Comment by AlexanderSehr** [comment]
Hey @segraef, could you please triage this issue :)

**Comment by segraef** [comment]
Already implemented see https://github.com/Azure/bicep-registry-modules/blob/be45580c2e0d562e1c457ba2839fa79f04d0bafe/avm/res/network/private-endpoint/tests/e2e/max/main.test.bicep#L71.
