### ISSUE TITLE
[Bug Report]: Elastic Pool minCapacity not set causes error 'The service level objective "S2M50" does not support the min capacity '0''

### ISSUE THREAD

**Issue by zydio** [Azure/bicep-registry-modules#2365]
### Describe the bug

BICEP deployments of Elastic Pools using CARML modules started to fail in the last few days, for what looks like an ARM (server side) issue, as we are using either v0.8.0 or v0.10.0 CARML official release and also without changing anything we started getting the error.

Modifying **modules\Microsoft.Sql\servers\elasticPools\deploy.bicep** to send a value of null for `properties.minCapacity` (not `properties.perDatabaseSettings.minCapacity` which works) solves the problem.

Note that it is currently impossible to send a null value for `properties.minCapacity` when the Elastic Pool is created when defining it with the properties of `modules\Microsoft.Sql\servers\deploy.bicep` because this file defaults the parameter to 0 when not provided (which causes the original error) and **modules\Microsoft.Sql\servers\elasticPools\deploy.bicep** would anyway set a default of 2 (inconsistent with the behavior of the other module) which is equally not accepted by ARM.

### To reproduce

Run a deployment with an Elastic Pool, using CARML >= 0.8.0 and <= 0.10.0

### Code snippet

```Bicep
module sqlServer 'CARML/modules/Microsoft.Sql/servers/deploy.bicep' = {
  scope: resourceGroup('issue-with-minCapacity-rg')
  name: '${uniqueString(deployment().name)}-SqlServer'
  params: {
    location: 'westeurope'
    name: 'issue-with-minCapacity-sql'
    administratorLogin: 'adminForTicket'
    administratorLoginPassword: 'An1P@sswordYouL1ke'
    minimalTlsVersion: '1.2'
    elasticPools: [{
      name: 'issue-with-minCapacity-ep'
      skuName: 'StandardPool'
      skuTier: 'Standard'
      skuCapacity: 50
      maxSizeBytes: 50*1024*1024*1024
      databaseMinCapacity: 10
      databaseMaxCapacity: 50
      maintenanceConfigurationId: '${subscription().id}/providers/Microsoft.Maintenance/publicMaintenanceConfigurations/SQL_WestEurope_DB_1'
    }]
    databases: [{
      // An Elastic database in a Pool
      name: 'issue-with-minCapacity-db'
      skuName: 'ElasticPool'
      skuTier: 'Standard'
      skuCapacity: 0
      maxSizeBytes: 30*1024*1024*1024
      zoneRedundant: false
      elasticPoolId: '${subscription().id}/resourceGroups/issue-with-minCapacity-rg/providers/Microsoft.Sql/servers/issue-with-minCapacity-sql/elasticPools/issue-with-minCapacity-ep'
      requestedBackupStorageRedundancy: 'Local'
    }]
  }
```

### Relevant log output

```Shell
The service level objective "S2M50" does not support the min capacity '0'
```

**Comment by AlexanderSehr** [comment]
Hey @bryansan-msft,
please note that I just migrated this issue from CARML (was we're working through all module issues on that end). As this may still be relevent, please take a look and triage/close the issue :)

**Comment by AlexanderSehr** [comment]
Hey @peterbud,
that's essentially the aspect to figure out. As described initially, this issues was migrated from CARML as the module originated from its code base. If you'd consider the issue to not be relevant anymore (presumably because it was fixed), then feel free to go ahead and close the issue 💪 From a maintainer perspective, we just migrated the issues to ensure they're properly addressed and not just dropped because the codebase was migrated to a different repository 😉

**Comment by peterbud** [comment]
I have tried to repro the issue with the current module (pls not there is no `minCapacity` set!), and as expected the following bicep test script has been successfully deploying the resources, so I think we can close this issue.

```bicep
module testDeployment '../../../main.bicep' = [
  for iteration in ['init', 'idem']: {
    scope: resourceGroup
    name: '${uniqueString(deployment().name, resourceLocation)}-test-${serviceShort}-${iteration}'
    params: {
      name: '${namePrefix}${serviceShort}001'
      location: resourceLocation
      administratorLogin: 'adminUserName'
      administratorLoginPassword: password
      elasticPools: [
        {
          name: 'issue-with-minCapacity-ep'
          sku: {
            name: 'StandardPool'
            tier: 'Standard'
            capacity: 50
          }
          maxSizeBytes: 50 * 1024 * 1024 * 1024
          perDatabaseSettings: {
            minCapacity: '10'
            maxCapacity: '50'
          }
          zoneRedundant: false
        }
      ]
      databases: [
        {
          name: 'issue-with-minCapacity-db'
          sku: {
            name: 'ElasticPool'
            tier: 'Standard'
            capacity: 0
          }
          maxSizeBytes: 30 * 1024 * 1024 * 1024
          zoneRedundant: false
          elasticPoolResourceId: '${resourceGroup.id}/providers/Microsoft.Sql/servers/${namePrefix}${serviceShort}001/elasticPools/issue-with-minCapacity-ep'
          requestedBackupStorageRedundancy: 'Local'
        }
      ]
    }
  }
]


```
