### ISSUE TITLE
[Feature Request]: Add Firewall Rules to `synapse/workspace`

### ISSUE THREAD

**Issue by Jackmt9** [Azure/bicep-registry-modules#2372]
### Description

I'd like to request that firewall rules be created alongside synapse workspace module. 

('Microsoft.Synapse/workspaces/firewallRules@2021-06-01')

**Comment by AlexanderSehr** [comment]
Migrated the issue from CARML. Please note that the module is currently orphaned (ref: https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/)

**Comment by Ralph101** [comment]
Should be solved in this linked PR: #1189

**Comment by AlexanderSehr** [comment]
Closing as duplicate of #1189
