### ISSUE TITLE
[Bug Report]: Microsoft.Network/vpnGateways/connections] `ConnectionBandwidth` property has been deprecated

### ISSUE THREAD

**Issue by chris5287** [Azure/bicep-registry-modules#2375]
### Describe the bug

It appears the `ConnectionBandwidth` property has been deprecated, but the ARM docs haven't been updated here: https://docs.microsoft.com/en-us/azure/templates/microsoft.network/vpngateways/vpnconnections?tabs=bicep#vpnconnectionproperties

This means deployments fail and there is no way to use the module as it has a default value in the bicep file :(

### To reproduce

https://github.com/Azure/ResourceModules/blob/80c29bd5fef1d522354b801b6bb59106e74ad67c/modules/Microsoft.Network/vpnGateways/connections/deploy.bicep#L38

https://github.com/Azure/ResourceModules/blob/80c29bd5fef1d522354b801b6bb59106e74ad67c/modules/Microsoft.Network/vpnGateways/connections/deploy.bicep#L76

### Code snippet

```Bicep
module vpnc 'main/modules/Microsoft.Network/vpnGateways/connections/deploy.bicep' = {
  name: '${deployment().name}_vpnc'
  params: {
    name: 'vpnGatewayConnection'
    vpnGatewayName: 'vpnGateway'
    remoteVpnSiteResourceId: 'remoteVpnSiteResourceId'
    vpnLinkConnections: [...]
  }
}
```

### Relevant log output

```json
{
    "status": "Failed",
    "error": {
        "code": "VpnConnectionPropertyIsDeprecated",
        "message": "Update request for VpnConnection /subscriptions/....../resourceGroups/..../providers/Microsoft.Network/vpnGateways/..../vpnConnections/.... contains deprecated property ConnectionBandwidth. Please use corresponding VpnSiteLinkConnection property instead.",
        "details": []
    }
}
```

**Comment by AlexanderSehr** [comment]
Hey @fabmas,
I just migrated this issue from CARML. Please take a look an triage. Maybe it's not relevant anymore :)

**Comment by AlexanderSehr** [comment]
Hey @fabmas, please take a moment to triage this issue if you can 💪

**Comment by fabmas** [comment]
Hey, sorry for the delay. I'm currently restructuring the entire module introducing new UDTs. I'll take care of this issue in the next release of the module.

**Comment by AlexanderSehr** [comment]
Hey @fabmas,
thanks. Just note that the CI's automation (bot) will continue to comment and ping you until the labels `Needs: Triage` and `Status: Response Overdue` are removed 😉

**Comment by fabmas** [comment]
This issue is no more relevant.
