### ISSUE TITLE
[PSRule] Fix Rule Azure.VM.AMA

### ISSUE THREAD

**Issue by fabmas** [Azure/bicep-registry-modules#2377]
Solve PSRule error AZR-000345: failed Azure.VM.AMA. Use Azure Monitor Agent for collecting monitoring data.

https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.VM.AMA/
To deploy virtual machines that pass this rule:

- Deploy an extension sub-resource Microsoft.Compute/virtualMachines/extensions.
- Set properties.publisher to Microsoft.Azure.Monitor.
- Set properties.type to AzureMonitorWindowsAgent (Windows) or AzureMonitorLinuxAgent (Linux).

**Comment by AlexanderSehr** [comment]
Hey @rahalan,
just migrated this issue from CARML. Please take a look if it's still relevant and triage :)

**Comment by rahalan** [comment]
Already fixed in AVM
