### ISSUE TITLE
[Feature Request]: Align NAT Gateway Public IP implementation with e.g. Bastion & Azure Firewall

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/bicep-registry-modules#2378]
### Description

The implementation of the NAT Gateway Public IP differs a lot from the other resources which introduces quite some inconsistency. 

This is partly rooted in the fact that the NAT Gateway can have multiple Public IPs & alternative multiple Public IP Prefixes.

We should anyways align the approach and, for example, allow the user to either specify an array of Public IPs, or provide the configuration to create multiple Public IPs (- the same for prefixes).

**Comment by AlexanderSehr** [comment]
Hey @fabmas,
I just migrated this issue from CARML. Please take a look if it's still relevant and triage :)

**Comment by fabmas** [comment]
Hi @AlexanderSehr 
The module appears to be updated with the correct Public IP implementation version. I have included a test case that demonstrates the method for utilizing an existing Public IP by referencing its resourceID. The PR for the update is #3341
