### ISSUE TITLE
[Feature Request]: enable MultipleWriteLocations feature

### ISSUE THREAD

**Issue by gbabbar** [Azure/bicep-registry-modules#2379]
### Description

Do we have capability in DocDB module to enable "MultipleWriteLocations" feature ?
I am creating cosmosDB with mongodb API enabled

**Comment by AlexanderSehr** [comment]
Hey @bryansan-msft,
I just migrated this issue from CARML. Please take a look if it's still relevant and triage :)

**Comment by AlexanderSehr** [comment]
Hey @bryansan-msft , please take a moment to triage this issue if you can 💪
