### ISSUE TITLE
Difference in module domain-service main.bicep between tagged Github and uploaded main.bicep (as source) from public repository 

### ISSUE THREAD

**Issue by orhanmaden** [Azure/bicep-registry-modules#2384]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/aad/domain-service

### (Optional) Module Version

0.2.0

### Description

When I check the tagged version in GitHub for the domain-service version 0.2.0 and compare it to the `main.bicep` in the uploaded tar file from the public repository, I notice a difference.

To get the tagged version from GitHub, use the following link: https://github.com/Azure/bicep-registry-modules/blob/avm/res/aad/domain-service/0.2.0/avm/res/aad/domain-service/main.bicep

To retrieve the tar file containing `main.bicep`, save it to disk, open it, and compare the contents, use the following command:
```sh
curl --location 'https://mcr.microsoft.com/v2/bicep/avm/res/aad/domain-service/blobs/sha256:38fafc15518bef7d7d4f29fc87844809d58ccf3f0f164e1e4bbd41f2de260071' \
--header 'Accept: application/vnd.oci.image.manifest.v1+json' \
--output domain-service.0.2.0.tar
```

The difference is as follow:

**GitHub version:**
```bicep
name: '46d3xbcp.res.aad-domainservice.${replace('-..--..-', '.', '-')}.${substring(uniqueString(deployment().name, location), 0, 4)}'
```

**Public registry version:**
```bicep
name: '46d3xbcp.res.aad-domainservice.${replace('0.2.0', '.', '-')}.${substring(uniqueString(deployment().name, location), 0, 4)}'
```

How can this happen?

**Comment by ReneHezser** [comment]
Hi @orhanmaden,
you have a good eye ;-)
The change from the placeholder to the actual version is done in a script during the publishing process here: https://github.com/Azure/bicep-registry-modules/blob/7dbe7476e40ac8bf2964c87ac41614b02b999d52/avm/utilities/pipelines/publish/Publish-ModuleFromPathToPBR.ps1#L69

This is how it is supposed to be. No need to worry.
