### ISSUE TITLE
[PSRule] Fix Rule Azure.VM.DiskCaching

### ISSUE THREAD

**Issue by fabmas** [Azure/bicep-registry-modules#2399]
| RECOMMEND:
    | Check disk caching is configured correctly for the workload.

    | REASON:
    | - Path properties.storageProfile.osDisk.caching: Is set to 'ReadOnly'.

    | HELP:
    | - https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.VM.DiskCaching/

**Comment by AlexanderSehr** [comment]
Hey @rahalan,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by rahalan** [comment]
Already fixed with AVM
