### ISSUE TITLE
Setting `IsEnabled` via ARM has no effect on `Microsoft.Automation/automationAccounts/softwareUpdateConfigurations`

### ISSUE THREAD

**Issue by loopfish** [Azure/bicep-registry-modules#2402]
Tested in "[Microsoft.Automation/automationAccounts/softwareUpdateConfigurations](https://learn.microsoft.com/en-us/azure/templates/microsoft.automation/2019-06-01/automationaccounts/softwareupdateconfigurations?pivots=deployment-language-arm-template)",  "apiVersion": "2019-06-01" with ARM `New-AzResouceGroupDeployment`

The documentation states:
`isEnabled` "Gets or sets a value indicating whether this schedule is enabled." `bool`

There is no `enabled` property on the "[Microsoft.Automation/automationAccounts/schedules](https://learn.microsoft.com/en-us/azure/templates/microsoft.automation/2019-06-01/automationaccounts/schedules?pivots=deployment-language-arm-template)" resource for this to effect.

The only way to actually enable/disable a `softwareUpdateConfiguration` is via the UI. Setting `IsEnabled` with ARM template deployment has no effect.

Example:

ARM template RG deployment output: 
![image](https://user-images.githubusercontent.com/39245344/195787072-281b8f09-615b-4286-aeff-a15b6cf0d8f8.png)

Actual resultant setting in Portal UI:
![image](https://user-images.githubusercontent.com/39245344/195787206-268e7b8e-3a7a-4ffd-8529-47c01921062e.png)

**Comment by AlexanderSehr** [comment]
Hey @elanzel,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by elanzel** [comment]
Updated API version to 2023-05-15-preview, the scheduling is enabled
![Immagine 2024-06-21 153521](https://github.com/Azure/bicep-registry-modules/assets/56406644/4e389157-04d2-44c0-afab-13a3a7551931)
