### ISSUE TITLE
[Bug Report]: Missing properties for Compute/Gallery for Bicep when creating images

### ISSUE THREAD

**Issue by Binimow** [Azure/bicep-registry-modules#2403]
### Describe the bug

When trying to create a Compute/Gallery with images in array, the properties "isAcceleratedNetworkSupported" and "isHibernateSupported" aren't passed.

They exist as parameters for Compute/Gallery/Image but when comes the moment to create images from Compute/Gallery the properties are just not passed.

It is a fairly simple bug to solve, as a lot of the stuff surrounding the solution is already in place.

### To reproduce

Deploy a Compute/Gallery via Bicep with an image array specifying isAccelereatedNetworkSupported to true.

You will that the property is not applied!

I believe the explanation of this bug is quite simple. The Compute/Gallery main.json doesn't pass the property.

![Screenshot 2024-04-26 at 9 25 49 AM](https://github.com/Azure/ResourceModules/assets/43762065/df0d4936-a84f-4de8-b2e8-0445ee35ebf3)

galleries_images is missing the params for "isAcceleratedNetworkSupported" and "isHibernateSupported".

### Code snippet

```Bicep
param galImages = [
  {
    hyperVGeneration: 'V2'
    maxRecommendedMemory: 16
    maxRecommendedvCPUs: 8
    minRecommendedMemory: 4
    minRecommendedvCPUs: 2
    isAcceleratedNetworkSupported: true
    name: 'xrserver-devkit'
    offer: 'xrserver-devkit'
    osState: 'Generalized'
    securityType: 'TrustedLaunch'
    osType: 'Linux'
    publisher: 'example'
    sku: 'xrserver_devkit'
  }
  {
    hyperVGeneration: 'V2'
    maxRecommendedMemory: 16
    maxRecommendedvCPUs: 8
    minRecommendedMemory: 4
    minRecommendedvCPUs: 2
    isAcceleratedNetworkSupported: true
    name: 'xrserver-scaleset'
    offer: 'xrserver-scaleset'
    securityType: 'TrustedLaunch'
    osState: 'Generalized'
    osType: 'Linux'
    publisher: 'example'
    sku: 'xrserver_scaleset'
  }
]

module gallery '../../modules/compute/gallery/main.bicep' = {
  name: '${uniqueString(deployment().name, location)}-dev-cgcom'
  params: {
    name: galName
    location: location
    enableDefaultTelemetry: true
    images: galImages
    roleAssignments: [
      {
        principalIds: [
          galUserAssignedIdentity.outputs.principalId
        ]
        principalType: 'ServicePrincipal'
        roleDefinitionIdOrName: 'Reader'
      }
    ]
    lock: ''
  }
}
```

**Comment by AlexanderSehr** [comment]
Hey @ReneHezser,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)
