### ISSUE TITLE
[Bug Report]: Databricks Workspace test hardcoded value for AzureDatabricks Enterprise app object ID

### ISSUE THREAD

**Issue by tyconsulting** [Azure/bicep-registry-modules#2407]
### Describe the bug

The Object ID for the AzureDatabricks Enterprise app is hardcoded [HERE](https://github.com/Azure/ResourceModules/blob/main/modules/databricks/workspace/tests/e2e/max/dependencies.bicep#L94). This value is different in each tenant. Therefore it should be tokenized in the [settings.yml](https://github.com/Azure/ResourceModules/blob/main/settings.yml) file

### To reproduce

When the repo is forked, the databricks pipeline will fail out of the box because this Object Id is incorrect.
![image](https://github.com/Azure/ResourceModules/assets/11845994/c887bee9-2151-4370-a60a-60001e052242)

**Comment by AlexanderSehr** [comment]
Just migrated this issue from CARML and it's still very much relevant in AVM. 

However - the implementation changed slightly in that we moved the value into the `main.test.bicep` file to make it more obvious and easier to maintain (as opposed to be hidden away in some nested dependencies file). Ideally we'd be able to fetch the value, but MSIs don't have the permissions to fetch Entra ID information.

To this end, I don't think we can actually solve it - unless we'd add it as a secret to the environment. But as it's very test specific, I'm not sure that's a good idea either.

One last thought: I guess what we could think about is introducing a general task to the deployment pipeline that fetches IDs we know we need and makes them available as tokens. This would take care of that issue, even though it would require new code for every other ID we need (- like the 2 or 3 we know of today). It should be implemented in a way that the value is only fetched if a specific resource type (e.g. in this case for databricks) is targeted to not waste runtime.
The caveat: The service principal would need to be able to fetch this kind of information. However, I do believe this is possible by default.

@eriqua / @ChrisSidebotham what are your thoughts?

**Comment by donheerschap** [comment]
@AlexanderSehr I encountered this as well when creating the PR for Databricks. It might be overengineering but using readEnvironmentVariable will fix this issue, will prevent having to change any current CI, and will not cause any backwards compability issues as we can keep the default:

```bicep
databricksApplicationObjectId: readEnvironmentVariable('databricksApplicationObjectId', '711330f9-cfad-4b10-a462-d82faa92027d') // Tenant-specific 'AzureDatabricks' Enterprise Application Object Id
```

Anyone in their FORK can set their env variable in the settings (or locally on their machine) without having to change this while developing and change it back last commit to let the test pass on main here.
https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository

**Comment by AlexanderSehr** [comment]
Tagging @clintgrove for awareness

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr I encountered this as well when creating the PR for Databricks. It might be overengineering but using readEnvironmentVariable will fix this issue, will prevent having to change any current CI, and will not cause any backwards compability issues as we can keep the default:
> 
> ```bicep
> databricksApplicationObjectId: readEnvironmentVariable('databricksApplicationObjectId', '711330f9-cfad-4b10-a462-d82faa92027d') // Tenant-specific 'AzureDatabricks' Enterprise Application Object Id
> ```
> 
> Anyone in their FORK can set their env variable in the settings (or locally on their machine) without having to change this while developing and change it back last commit to let the test pass on main here. https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository

Hey @donheerschap,
it's fundamentally a good idea, but I'm not sure how well GH will play with this as I believe one has to pass secrets explicitely to make them available. 
I can't recall right now where I commented it, but somewhere I was suggesting a more generic approach that adds a few lines of code to the deploymentValidation action which looks for secrets with a certain prefix and passes them into the deployment as `secure()` `main.test.bicep` parameters (if the given template has such a parameter). This would also mean we don't need any additional changes to the CI (after this change of course) and would not have 'magic values' in the templates (i.e., values that are referenced but where it's hard to know where they actually came from as there was no parameter etc.).
Thoughts?

**Comment by clintgrove** [comment]
@AlexanderSehr  I think we actually completed this right? Its the keyvault idea and storing this OBjectID in there, everyone who deploys has to have their own keyvalut with this app id set there. So we can close this?

**Comment by AlexanderSehr** [comment]
That is true. Thanks for calling this out @clintgrove. Closing...

@donheerschap, the solution we implemented is defined [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/custom-ci-secrets/).
