### ISSUE TITLE
[Bug Report]: Error when deployment `app/managed-environment` without providing role assignments in `parameter.json`

### ISSUE THREAD

**Issue by Marc013** [Azure/bicep-registry-modules#2409]
### Describe the bug

Using module 'modules/app/**managed-environment**' throws exception '_Object reference not set to an instance of an object._' when NOT providing parameter `roleAssignments`.

### To reproduce

Create parameters file without parameter `roleAssignments` and run the deployment.

**Comment by AlexanderSehr** [comment]
Hey @hundredacres,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by hundredacres** [comment]
Pretty sure this can be closed. We've got clean pipeline runs for defaults, which has no roleAssignments being used.
