### ISSUE TITLE
[Feature Request]: Enable geo-replication for Redis cache.

### ISSUE THREAD

**Issue by Meertman** [Azure/bicep-registry-modules#2411]
### Description

A Redis cache supports the setup of geo-replication via bicep through the use of the linked server bicep resource: https://learn.microsoft.com/en-us/azure/templates/microsoft.cache/redis/linkedservers?pivots=deployment-language-bicep

Adding this to the bicep module for deployment of a Redis cache would be a welcome addition.

However the usage of the linked server and a private endpoint proves to be a bit difficult as you cannot add a private link to a Redis cache that is geo-replicated. You first need to remove the geo-replication, then add the link and then re-enable the geo-replication. As documented here: https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-geo-replication

Specifically:
> Private links can't be added to caches that are already geo-replicated. To add a private link to a geo-replicated cache: 1. Unlink the geo-replication. 2. Add a Private Link. 3. Last, relink the geo-replication.

**Comment by AlexanderSehr** [comment]
Hey @hundredacres,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by hundredacres** [comment]
Working on some tests to validate this functionality.

**Comment by Meertman** [comment]
@hundredacres, does this also work with private endpoints enabled? In the past I ran into issues with this? (and even created a GitHub issue on bicep for this: https://github.com/Azure/bicep-types-az/issues/1937)
