### ISSUE TITLE
[Feature Request]: add module for ADF Linked Services

### ISSUE THREAD

**Issue by tyconsulting** [Azure/bicep-registry-modules#2414]
### Description

currently there is no module for ADF Linked Services resource https://docs.microsoft.com/en-us/azure/templates/microsoft.datafactory/factories/linkedservices?pivots=deployment-language-bicep

**Comment by AlexanderSehr** [comment]
Hey @clintgrove,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by clintgrove** [comment]
I am working on this, due to raise PR today or tomorrow 25th june 2024
