### ISSUE TITLE
[Feature request from discussions] Container App Secrets to env variable missing

### ISSUE THREAD

**Issue by eriqua** [Azure/bicep-registry-modules#2415]
### Discussed in https://github.com/Azure/ResourceModules/discussions/2995

<div type='discussions-op-text'>

<sup>Originally posted by **cwp-michaell** March 14, 2023</sup>
The container app module seems to be missing the ability to pass the secrets from the container app to the individual container.
Currently I can pass a list to 
````
@description('Optional. The secrets of the Container App.')
@secure()
param secrets object = {}`
````
Which is referenced here 
````
var secretList = !empty(secrets) ? secrets.secureList : []
````
The `secretList` is then referenced at the container app level with `secrets: secretList` but I should then be able to pass these to the `template: env:` of the individual container from the container app secrets.</div>

**Comment by AlexanderSehr** [comment]
Hey @oZakari,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by oZakari** [comment]
Thanks @AlexanderSehr, I will take a deeper look at this in July.
