### ISSUE TITLE
[Feature Request]: MS Insights webtest tags

### ISSUE THREAD

**Issue by eriqua** [Azure/bicep-registry-modules#2416]
### Description

Improve the module `tags` implementation. 

The module requires formatted tags to keep the link between the webtest and its app insight dependency.
Currently the tags parameter object is required and must be passed as input in a specific format.

In a next iteration we may take care of implementing the required tag in the specific format, to improve the module usability.
For example, we could add an input array of hidden links to implement in union with additional tags that users may want to apply.

**Comment by AlexanderSehr** [comment]
Hey @JFolberth,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by JFolberth** [comment]
Closing as the tag parameter is optional; however, appInsightResourceId is required and this value is used to populate a variable to store the hidden tag and apply to the web test.
