### ISSUE TITLE
[Bug Report]: CosmosDB Account for MongoDB with server version 4.2 can't be created via the existing module (modules/document-db/database-accounts)

### ISSUE THREAD

**Issue by SavaMihai** [Azure/bicep-registry-modules#2417]
### Describe the bug

I'm trying to deploy a CosmosDB Account for MongoDB by using the module reference but it fails to create the desired state added in the parameters like Serverless and with server version 4.2 instead it creates a Cosmos DB Account with Provisioned throughput

### To reproduce

Create a bicep file to deploy a Cosmos DB Account for MongoDB using the latest reference module from the GitHub Repository modules/document-db/database-accounts

### Code snippet

```Bicep
module spsCosmosDb './bicep/modules/document-db/database-accounts/main.bicep' = {
  name: '${uniqueString(deployment().name, location)}-spsCosmosDb'
  scope: resourceGroup(sharedResourceGroupName)
  params: {
    name: spsCosmosDbName
    location: location
    capabilitiesToAdd: [
      'EnableServerless'
      'EnableMongo'
    ]
    enableFreeTier: false
    defaultConsistencyLevel: 'Eventual'
    databaseAccountOfferType: 'Standard'
    serverVersion: '4.2'
    locations: [
      {
        locationName: location
        failoverPriority: 0
        isZoneRedundant: false
      }
    ] 
  }
  dependsOn: [
    sharedResourceGroup
  ]
}
```

**Comment by AlexanderSehr** [comment]
Hey @bryansan-msft ,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by AlexanderSehr** [comment]
Just a quick update on this, @bryansan-msft has been out of office (and still is) which is why the issue has not been triaged yet. Stay tuned :)

**Comment by bryansan-msft** [comment]
In the current latest module version to specify the serverVersion you need to at least define one mongo database. This module takes an approach where you need to at least specify one database of any type (gremlin, sql, mongo, etc) to know which parameter read and use. 

https://github.com/Azure/bicep-registry-modules/blob/8490793291adea6a4a61035f6bb9df654b513d50/avm/res/document-db/database-account/main.bicep#L273-L280
