### ISSUE TITLE
[Bug]: consumption/budget - add parameter for thresholdType

### ISSUE THREAD

**Issue by dibcar** [Azure/bicep-registry-modules#2423]
### Description

The module consumption/budget have the properties thresholdType hardcoded to 'Actual' and can't be used for forecast notifications.

**Comment by AlexanderSehr** [comment]
Hey @segraef ,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by AlexanderSehr** [comment]
Hey @segraef, please take a moment to triage this issue if you can 💪

**Comment by segraef** [comment]
Thanks @AlexanderSehr, having a look at it now.
