### ISSUE TITLE
[Feature Request]: Module Microsoft.Web/sites - include vnetRouteAllEnabled and vnetImagePullEnabled properties

### ISSUE THREAD

**Issue by shawntmeyer** [Azure/bicep-registry-modules#2424]
### Description

Team,

I see these properties are enabled on Slots but this is also configurable at the site resource. https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites?pivots=deployment-language-bicep#siteproperties

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy ,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by tsc-buddy** [comment]
Hi There - These settings are available in the main site component of the module. I shall go ahead and close this issue. Thanks.
