### ISSUE TITLE
[Feature Request]: Send App Service logs to Blob Storage with sasUrl

### ISSUE THREAD

**Issue by vienleidl** [Azure/bicep-registry-modules#2431]
### Description

There should be an option for enabling the App Service logs and sending to the Blob Storage with sasUrl. The related Bicep file is https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/web/site/main.bicep

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy ,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by tsc-buddy** [comment]
Hi There - Thanks for logging this issue. We shall triage this wc 15th July.

**Comment by tsc-buddy** [comment]
Hi - There is a new submodule for use that allows this now. Thanks All.
