### ISSUE TITLE
[Feature Request]: Provide a workaround for setting secure environment variables in Azure Container Instances module

### ISSUE THREAD

**Issue by KamilWiecek** [Azure/bicep-registry-modules#2433]
### Description

Currently if we provide _containers_ object parameter it value is shown in deployment history. 
I'm wondering if we could implement a workaround that will replace placeholders in containers object based on mapping provided in another additional parameter of type @secure().

**Comment by AlexanderSehr** [comment]
Hey @JPEasier ,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by JPEasier** [comment]
Hi, 
for the containers object we use at the momenmt a custom type object.
secure definitions are marked as secure but not the entry object.
``` bicep
@description('Optional. The environment variables to set in the container instance.')
    environmentVariables: {
      @description('Required. The name of the environment variable.')
      name: string

      @description('Optional. The value of the secure environment variable.')
      @secure()
      secureValue: string?

      @description('Optional. The value of the environment variable.')
      value: string?
    }[]?
```

so the current version of the AVM module supports your request 👍
