### ISSUE TITLE
[Feature Request]: support audit-settings from sql server module

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/bicep-registry-modules#2434]
### Description

It would be nice (and natural) if the module https://github.com/Azure/ResourceModules/tree/main/modules/Microsoft.Sql/servers supported defining the audit-settings:
https://learn.microsoft.com/en-us/azure/templates/microsoft.sql/servers/auditingsettings?pivots=deployment-language-bicep

**Comment by AlexanderSehr** [comment]
Hey @bryansan-msft ,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by jikuja** [comment]
This has been partially fixed on https://github.com/Azure/bicep-registry-modules/commit/4f24c09ba9f1b17ae2916afaea841f94d84e90d8

Current module supports:
* setting Microsoft.Sql/servers/auditingSettings only on server level
* setting Microsoft.Insights/diagnosticSettings only on database level

Looks like when I searched for existing tickets I missed those which have been migrated from [Azure/ResourceModules](https://github.com/Azure/ResourceModules) Ticket of mine: https://github.com/Azure/bicep-registry-modules/issues/3377

@AlexanderSehr @emichellecarter Is there something wrong with this ticket metadata?

**Comment by AlexanderSehr** [comment]
Hey @jikuja,
this issue has been migrated from a different respository and not assigned to an owner as the module did not have an owner at the time. As such, nobody actually did properly review the ticket and the automation did apparently not pick it up when the module finally did get an owner.
Thank you for raising this. From the original ticket it sounds like we could close at least this issue as 'done' as it's possible to set diagnostic settings both on the server, as well as the individual databases. Now, your issue touches on a special database and how to set diagnostic settings on that. I'd hence say that's a seperate issue, be it related.
