### ISSUE TITLE
[Feature Request]: Support Container Instance deployment to private network 

### ISSUE THREAD

**Issue by KamilWiecek** [Azure/bicep-registry-modules#2437]
### Description

Extend current Azure Container Instances module to support deploying container groups in private networks.

_ipAddressType_ parameter has no impact and it has confusing description:

> Specifies if the IP is exposed to the public internet or private VNET. - Public or Private.

We miss _subnetId_ that should be used if _ipAddressType_ parameter is set to  _'Private'_.

**Comment by AlexanderSehr** [comment]
Hey @JPEasier ,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by JPEasier** [comment]
allready implemented in the AVM module
