### ISSUE TITLE
Set default values to a secure value - Network Watchers

### ISSUE THREAD

**Issue by elanzel** [Azure/bicep-registry-modules#2442]
All default values should comply with a security baseline, e.g. [NIST 800](https://docs.microsoft.com/en-us/azure/governance/policy/samples/nist-sp-800-53-r5)

The [build-in policies](https://github.com/Azure/azure-policy) of Azure can be used as a reference.

The task would be to scan over each of the following policies and make sure, that the module is per default complying to them.

The following policies are the NIST 800 ones:
\built-in-policies\policyDefinitions\Network\NetworkWatcher_Enabled_Audit.json

**Comment by AlexanderSehr** [comment]
Hey @segraef ,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by segraef** [comment]
`networkWatchers` complies with https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Network/NetworkWatcher_Enabled_Audit.json as well as all other policies.
https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/Network/NetworkWatcherFlowLog_Enabled_Audit.json only applies it a resource is given, hence the flowLogs property of the `networkWatchers` is optional.
