### ISSUE TITLE
[Feature Request]: Module virtual-network-gateways defaults to Basic public IP sku for non-AV vpn gateway skus

### ISSUE THREAD

**Issue by ThojoUno** [Azure/bicep-registry-modules#2443]
### Description

When selecting non "AZ" vpn gateway skus, module defaults to Basic public IP address sku. Request update to module to allow selection of Standard public IP address sku regardless of vpn gateway sku selected. Basic public IP address skus are being retired 9/1/2025, and Standard public IP address skus are recommended for production workloads.

**Comment by fabmas** [comment]
Hi, sorry for the late response. I'll investigate on this issue asap.

**Comment by fabmas** [comment]
Issue addressed in another request.
