### ISSUE TITLE
Set default values to a secure value - API 

### ISSUE THREAD

**Issue by elanzel** [Azure/bicep-registry-modules#2450]
All default values should comply with a security baseline, e.g. [NIST 800](https://docs.microsoft.com/en-us/azure/governance/policy/samples/nist-sp-800-53-r5)

The [build-in policies](https://github.com/Azure/azure-policy) of Azure can be used as a reference.

The task would be to scan over each of the following policies and make sure, that the module is per default complying to them.

The following policies are the NIST 800 ones:

\built-in-policies\policyDefinitions\API for FHIR\HealthcareAPIs_EnableByok_Audit.json
\built-in-policies\policyDefinitions\API for FHIR\HealthcareAPIs_PrivateLink_Audit.json

**Comment by AlexanderSehr** [comment]
I just migrated this issue from CARML. However, as the module is orphaned, triaging it may take a while...

**Comment by AlexanderSehr** [comment]
Hey @arnoldna, thanks for checking. I guess that means this issue can be closed `'As not planned'` ?

**Comment by arnoldna** [comment]
Currently not planned.
