### ISSUE TITLE
[AVM Module Issue]: unable to create `'Microsoft.Web/sites/config'` `'logs'`  resources

### ISSUE THREAD

**Issue by ksstott** [Azure/bicep-registry-modules#2463]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### Description

The current `br/public:avm/res/web/site` module does not support configuring logs and instead we need to write bicep similar to this:
```bicep
module site 'br/public:avm/res/web/site:0.3.7' = {
  name: 'webapp-123'
  params: {
    kind: 'app,linux,container'
    name: 'webapp-123'
    serverFarmResourceId: serverfarm.outputs.resourceId
}

resource logs 'Microsoft.Web/sites/config@2022-09-01' = {
  name: 'webapp-123/logs'
  dependsOn: [
    site
  ]
  properties: {
    httpLogs: {
      fileSystem: {
        enabled: true
        retentionInMb: 100
        retentionInDays: 7
      }
    }
    applicationLogs: {
      fileSystem: {
        level: 'Off'
      }
    }
  }
}
```

**Comment by tsc-buddy** [comment]
Hi There - Thanks for logging this issue. We shall triage this wc 8th July.

**Comment by tsc-buddy** [comment]
Hey @ksstott  - A submodule has recently been added for this. Thanks for logging.
