### ISSUE TITLE
[AVM Module Issue]: Add additional owner to Storage Account Module Bicep

### ISSUE THREAD

**Issue by ChrisSidebotham** [Azure/bicep-registry-modules#2468]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/storage/storage-account

### Description

add `ktremain` as primary module owner and keep `fblix` as secondary owner.

**Comment by ChrisSidebotham** [comment]
@matebarabas - for awareness

**Comment by ktremain** [comment]
Completed
