### ISSUE TITLE
[authorization/role-assignment]:  Setting a scope

### ISSUE THREAD

**Issue by ppons1997** [Azure/bicep-registry-modules#2488]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/ptn/authorization/role-assignment

### (Optional) Module Version

0.1.0

### Description

The Scope "resource group" and "subscription" are not valid for this module. Permitted scopes: "managementGroup"

While the metadata claims that all scopes are possible.

**Comment by arnoldna** [comment]
@ppons1997 - Thanks for reaching out. I agree that the working in the metadata sounds a little confusing. We will look at what we can do to provide some clarification. The module is designed to make the role assignment at the management group, subscription or resource group level. The deployment scope for the Bicep code will be at the Management Group. The module looks for the addition of the subscription or the subscription and resource group parameters to determine where the role needs to be set at. 

Here is a little code snippet that would make the role assignment at the resource group level. 

`module roleAssignment 'br/public:avm/ptn/authorization/role-assignment:0.1.0' = {
  name: '${uniqueString(deployment().name)}-test-${serviceShort}'
  params: {
    principalId: nestedDependencies.outputs.managedIdentityPrincipalId
    roleDefinitionIdOrName: '/providers/Microsoft.Authorization/roleDefinitions/c2f4ef07-c644-48eb-af81-4b1b4947fb11'
    principalType: 'ServicePrincipal'
    location: resourceLocation
    subscriptionId: subscriptionId
    resourceGroupName: resourceGroup.outputs.name
  }
}`

If you remove the resourceGroupName parameter then the role assignment would take place at the subscription level. And subsequently if you remove the subscriptionID then the role assignment would take place at the management group level.
