### ISSUE TITLE
[AVM Module Issue]: ERROR: The target scope "managementGroup" does not match the deployment scope "resourceGroup"

### ISSUE THREAD

**Issue by ksks200** [Azure/bicep-registry-modules#2519]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/ptn/authorization/role-assignment

### Description

When running the pipeline and specifying the resourcename and subscriptionID the below error is encountered:

"ERROR: The target scope "managementGroup" does not match the deployment scope "resourceGroup""

This indicates that the module for resourcegroup assignment is being run but since the managementgroup is specified as targetscope, it is failing.

**Comment by arnoldna** [comment]
@ksks200 Thanks for submitting an issue. 

When you run a deployment for this module you must deploy it at a management group scope and not at a subscription or resource group scope. For example, the Azure CLI command would be something like: 

`az deployment mg create --management-group-id testmg --name rollout01 --location WestUS \
            --template-file azuredeploy.json`

If you are still getting errors then I would need to see an example of your code and how you are running your deployments. Thanks.

**Comment by ksks200** [comment]
thank you @arnoldna and @AlexanderSehr . Change it to az deployment mg worked.
