### ISSUE TITLE
[AVM Module Issue]: `Microsoft.Web/sites/config` does not support the `name` property value as `web` or `logs` and the `kind` property value as `string`.

### ISSUE THREAD

**Issue by Menghua1** [Azure/bicep-registry-modules#2537]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### (Optional) Module Version

0.3.8

### Description

In `sites/config` resource, please support the `name` property value as `web` and the `kind` property value as `string`.

Related `azd` code links: 

- https://github.com/Azure/azure-dev/blob/main/templates/todo/common/infra/bicep/app/apim-api.bicep#L105

- https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/host/appservice.bicep#L103

CC: @jongio

**Comment by tsc-buddy** [comment]
Hey @Menghua1 - thanks for opening this. Have you had trouble setting values for the apiManagementConfig property and others within the siteConfig parameter?

**Comment by Menghua1** [comment]
> Hey @Menghua1 - thanks for opening this. Have you had trouble setting values for the apiManagementConfig property and others within the siteConfig parameter?

Yes, we have created a PR https://github.com/Azure/bicep-registry-modules/pull/2548 to fix it, please review it.
