### ISSUE TITLE
[AVM Module Issue]: avm/res/container-service/managed-cluster/main.bicep uses Open Service Mesh which has been archived

### ISSUE THREAD

**Issue by daveinci** [Azure/bicep-registry-modules#2546]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/container-service/managed-cluster

### Description

Open Service Mesh has been archived. Current API version 2024-02-01 of the Bicep template reference doesn't support OSM and uses the serviceMeshProfile/Istio addon instead.

**Comment by JPEasier** [comment]
hi @daveinci, 
we are working on a new release with latest api version and will remove that.

thanks for pointing out 🚀
