### ISSUE TITLE
[AVM Module Issue]: deploying a sub with all resource providers throws error in rg "rsg-australiasoutheast-ds | Deployments" The sku Sku: Standard_ZRS, Kind: StorageV2 is not available in zone. (Code: SkuUnavailableInZone

### ISSUE THREAD

**Issue by NirajCricket** [Azure/bicep-registry-modules#2549]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/ptn/lz/sub-vending

### (Optional) Module Version

module subVending 'br/public:avm/ptn/lz/sub-vending:0.1.0' = {

### Description

Hi @jtracey93 , mate as we discussed earlier, the resource providers are giving some pain in passing the build, this item always fails, and it is part of the resource group it creates, looks like something wrong in the module to find this storagev2 thingy, can you help to fix this?

[AVM Module Issue]: While creating the susbcription via bicep and json parameter, the Resource providers, defaults create a networkwatcher and rsg-australiasoutheast-ds  resource group. The resource group rsg-australiasoutheast-ds fails my azuredevops pipeline, and the deployment error shows in the rg of rsg-australiasoutheast-ds as {"code":"SkuUnavailableInZone","message":"The sku Sku: Standard_ZRS, Kind: StorageV2 is not available in zone."} . How can I exclude the creation of rg "{"code":"SkuUnavailableInZone","message":"The sku Sku: Standard_ZRS, Kind: StorageV2 is not available in zone."}" when I al deploying a sub with all resourceproviders . or how can we fix this storage error. 
![deployment fail-error](https://github.com/Azure/bicep-registry-modules/assets/35249470/310c18c6-a2bb-4ed2-96ca-601ab58d386b)
![main parameter json](https://github.com/Azure/bicep-registry-modules/assets/35249470/a5e9811a-c898-4df3-8668-c9b40e2e44de)
![main bicep](https://github.com/Azure/bicep-registry-modules/assets/35249470/119efea5-21ae-40f1-9272-746ab5d6fb86)

**Comment by sebassem** [comment]
We are submitting a PR to change the storage account SKU to avoid those kind of issues. To use the module without registring any resource providers, you have to provide and empty object for the `resourceProviders` parameters; Example: 

resourceProviders: {}

**Comment by jtracey93** [comment]
@NirajCricket, @sebassem has created a fix for this in a PR and we have just approved so you will need to upgrade to the latest version of the module which will be available in a few hours in the registry as version 0.1.1

**Comment by NirajCricket** [comment]
did I miss, it means the version for sub will be  0.1.2, so replace this module subVending 'br/public:avm/ptn/lz/sub-vending:0.1.0' with module subVending 'br/public:avm/ptn/lz/sub-vending:0.1.2' ?

**Comment by NirajCricket** [comment]
> We are submitting a PR to change the storage account SKU to avoid those kind of issues. To use the module without registering any resource providers, you have to provide and empty object for the `resourceProviders` parameters; Example:
> 
> resourceProviders: {}

I want to register all the resource providers but this storage v2 ZRS issues is causing issue.

**Comment by sebassem** [comment]
> did I miss, it means the version for sub will be 0.1.2, so replace this module subVending 'br/public:avm/ptn/lz/sub-vending:0.1.0' with module subVending 'br/public:avm/ptn/lz/sub-vending:0.1.2' ?

Correct

**Comment by sebassem** [comment]
> > We are submitting a PR to change the storage account SKU to avoid those kind of issues. To use the module without registering any resource providers, you have to provide and empty object for the `resourceProviders` parameters; Example:
> > resourceProviders: {}
> 
> I want to register all the resource providers but this storage v2 ZRS issues is causing issue.

After updating the module, you shouldn't face this problem
