### ISSUE TITLE
[AVM Module Issue]: adding private.endpoint on an existing privateLinkService fails, GroupId cannot be empty.

### ISSUE THREAD

**Issue by gherik** [Azure/bicep-registry-modules#2554]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/private-endpoint

### (Optional) Module Version

0.4.1

### Description

When adding a private endpoint on an existing privateLinkService (loadbalancer -> VM), the AVM module fails because the GroupId is an empty array.

**Error**
`
              "additionalInfo": null,
              "code": "DeploymentOutputEvaluationFailed",
              "details": null,
              "message": "The template output 'groupId' is not valid: The language expression property array index '0' is out of bounds..",
              "target": "groupId"
`

**Bicep code snipit**
```
resource privateLinkService 'Microsoft.Network/privateLinkServices@2023-11-01' existing =  {
  name: privateLinkServiceName
}

module privateEndpoint_avm 'br/public:avm/res/network/private-endpoint:0.4.1' =  {
  name: 'privateEndpoint_avm'
  params: {
    name: privateEndpointName
    location: location
    subnetResourceId: subnet.id
    customNetworkInterfaceName: customNetworkInterfaceName
    privateLinkServiceConnections: [
      {
        name: privateEndpointName
        properties: {
          groupIds: []
          privateLinkServiceId: privateLinkService.id
        }
      }
    ]
  }
}
```

I have tried an empty string in the array, but ARM does not accept that, gives error: 

`Private link service connection /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/privateEndpoints/xxx/privateLinkServiceConnections/xxx has the following group Id(s): . Group Ids are not valid when connecting to a third party resource (/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/privateLinkServices/xxx).`

I have validated that an empty array value is correct for this setup, creating via the Portal a deployment and checking the inputs (after successful deployment), the value of the parameter targetSubResource is an empty array. That parameter is the GroupId.

**Comment by johnlokerse** [comment]
@segraef / @AlexanderSehr I would like to pick this up. We can go two ways here:
* We can make groupId optional in the UDT in the private endpoint resource main bicep;
* Or we can add the private endpoint resource to the [private-link-service](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/network/private-link-service/main.bicep) resource main bicep.

If we go for bullet 1 it can be confusing since most users of this module require groupId. What do you guys think?

**Comment by AlexanderSehr** [comment]
Ney @johnlokerse & @gherik,
thanks for bringing this up. We may need to rely on @segraef (and or @jtracey93) for this as I'm not sure I fully grasp the root of the error (which may just be due to my limited know how in the area). My understanding was that the `groupIds` parameter is always required for private link service connections and that Azure would throw an error if you don't provide a value for it.

**Comment by johnlokerse** [comment]
@AlexanderSehr Yes, this was new for me too. I thought `groupId` was required as well. Well... it is required but it depends on how you deploy it. It is not enforced to define `groupId` but when you refer to a resource other than private link service in the `privateLinkServiceId` it breaks because it expects a groupId. (tested!)

When you use a private link service then `groupId` does not have to be defined see msdocs: https://learn.microsoft.com/en-us/azure/private-link/create-private-link-service-bicep?tabs=CLI

Below two deployments, both using a resource definition not using the AVM module:
* First is without groupId trying to couple it with a key vault **[error]**
* Second also without groupId and coupled to a private link service **[success]**

<img width="1425" alt="image" src="https://github.com/Azure/bicep-registry-modules/assets/3514513/de5ba874-a453-4718-bdc9-577f302a24bc">

**Comment by gherik** [comment]
Hi John,

The error message is about "The template output 'groupId' is not valid:”, so I saw that the last change was adding an output for the groupId. So I tested with an older version (0.3.3) and that one works (with an empty array for groupId).
(BTW, did I mentioned that the private end point resource is created successfully with version 0.4.1, but you get the error message)

My thought is to have a conditional output

Answering your questions;
1. Making it optional in the UDT is the same behaviour when using the microsoft bicep resource, to me that makes sense. I have tested a deployment for a storage blob and leaving the groupId empty, this gives an ARM error: is missing required parameter 'group Id’. (expected behaviour). So this would not be confusing.

2. Adding the private endpoint resource to the private-link service introduces the challenge on creating the private end point according to naming convention.


On 1 Jul 2024, at 11:15, John ***@***.***> wrote:



@segraef<https://github.com/segraef> / @AlexanderSehr<https://github.com/AlexanderSehr> I would like to pick this up. We can go two ways here:

  *   We can make groupId optional in the UDT in the private endpoint resource main bicep;
  *   Or we can add the private endpoint resource to the private-link-service<https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/network/private-link-service/main.bicep> resource main bicep.

If we go for bullet 1 it can be confusing since most users of this module require groupId. What do you guys think?

**Comment by AlexanderSehr** [comment]
> Hi John, The error message is about "The template output 'groupId' is not valid:”, so I saw that the last change was adding an output for the groupId. So I tested with an older version (0.3.3) and that one works (with an empty array for groupId). (BTW, did I mentioned that the private end point resource is created successfully with version 0.4.1, but you get the error message) My thought is to have a conditional output Answering your questions; 1. Making it optional in the UDT is the same behaviour when using the microsoft bicep resource, to me that makes sense. I have tested a deployment for a storage blob and leaving the groupId empty, this gives an ARM error: is missing required parameter 'group Id’. (expected behaviour). So this would not be confusing. 2. Adding the private endpoint resource to the private-link service introduces the challenge on creating the private end point according to naming convention.

Hey @gherik, you're correct in that latest ARM will tell you that something is missing. I guess the hope is just that we 'shift left' as far as possible, enabling users to not make errors to begin with (as opposed to building their solution just to have Azure tell them they can start over 😄). But naturally, this should only be done if it's not blocking anything else, as it is in your case. If bad comes to worse, we'll declare the property as 'Conditional' and update the module where required. @segraef what's your take as the owner?

Regarding the output, spot-on. It is already conditional, but as it always assumes a `groupId` to be there, it's not 'conditional' enough. Ref:
```bicep
@description('The group Id for the private endpoint Group.')
output groupId string = !empty(privateEndpoint.properties.manualPrivateLinkServiceConnections)
  ? privateEndpoint.properties.manualPrivateLinkServiceConnections[0].properties.groupIds[0]
  : privateEndpoint.properties.privateLinkServiceConnections[0].properties.groupIds[0]
```

**Comment by segraef** [comment]
[Testing](https://github.com/Azure/bicep-registry-modules/actions/runs/9772766577/job/26978118787), bear with me.

**Comment by segraef** [comment]
[This](https://github.com/Azure/bicep-registry-modules/actions/runs/9790068729) seems to work, let me know what you think.

**Comment by segraef** [comment]
Replied to your comments @johnlokerse, it looks good for now. There is one more thing we need to test now which is to see if `properties.ipConfigurations.groupId` accepts an [empty string ](https://github.com/Azure/bicep-registry-modules/pull/2605/files#diff-209befc0446138e2a7ad6cab2787ecd7cfeec33c1d308d216a8658c8fc7437eeR70)`''` when a private IP is used.

**Comment by segraef** [comment]
[Works](https://github.com/Azure/bicep-registry-modules/actions/runs/9803119988/job/27068845230), put #2605 into review, @AlexanderSehr if you have some time to review, thanks mate.

**Comment by gherik** [comment]
@segraef, how do I test your code? (still trying to become familiar with this Github environment)

**Comment by segraef** [comment]
> @segraef, how do I test your code? (still trying to become familiar with this Github environment)

The workflow automatically runs [here](https://github.com/Azure/bicep-registry-modules/actions/runs/9869471200) and how to get familiar with the environment you can read [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/).

**Comment by AlexanderSehr** [comment]
> > @segraef, how do I test your code? (still trying to become familiar with this Github environment)
> 
> The workflow automatically runs [here](https://github.com/Azure/bicep-registry-modules/actions/runs/9869471200) and how to get familiar with the environment you can read [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/).

We're also working on a CI documentation that would go into the AVM website, but as it's only me that's working on it, it will take a while longer to land 😄
