### ISSUE TITLE
[AVM Module Issue]: avm/res/insights/scheduled-query-rule implement "alertDisplayName" property

### ISSUE THREAD

**Issue by HRadingTwoday** [Azure/bicep-registry-modules#2560]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/insights/scheduled-query-rule

### (Optional) Module Version

0,1,4

### Description

Trying to convert from CARML module 'Microsoft.Insights.scheduledQueryRules' (version 1.3.0)
We are missing an optional 'alertDisplayName' parameter for the alert. Currently the "name" parameter is used as input for the Displayname.

for the resource It should implement the property:

displayName: !empty(alertDisplayName) ? alertDisplayName : name

**Comment by emichellecarter** [comment]
I will review the issue and work to make the change.
