### ISSUE TITLE
[AVM Module Issue]: Setting up 'AvailabilityZones' is not supported in Sku :'Developer'

### ISSUE THREAD

**Issue by dewolfs** [Azure/bicep-registry-modules#2561]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/api-management/service

### (Optional) Module Version

0.2.0

### Description

Hi,

I want to deploy an APIM instance in the SKU "Developer".  The Developer SKU defaults to 1 instance count.

When the following bicep code is used:

```
module apim 'br/public:avm/res/api-management/service:0.2.0' = {
  name: 'apim9999'
  params: {
    name: 'testapim9999'
    publisherEmail: publisherEmail
    publisherName: publisherName
    virtualNetworkType: 'Internal'
    subnetResourceId: subnetRef.id
    location: location
    sku: 'Developer'
    ....
  }
}
```

i get the error:

> [{"code":"NotSupported","message":"Setting up 'AvailabilityZones' is not supported in Sku :'Developer'.

If I look at the module, the SKU parameter will always be 2 if I choose Developer. But technically that's not possible ?!

https://github.com/Azure/bicep-registry-modules/blob/c58ce674ad0876a44fc44983f1bb03b300b76eb7/avm/res/api-management/service/main.bicep#L85
https://github.com/Azure/bicep-registry-modules/blob/c58ce674ad0876a44fc44983f1bb03b300b76eb7/avm/res/api-management/service/main.bicep#L224

How to proceed to deploy APIM with the Developer SKU ?

**Comment by dhayes-ccl** [comment]
I'm having the same problem, 
The AVM flavour fails to deploy with an Availability Zones error, the direct resource version deploys properly 

var subnetResourceId = resourceId(networkResourceGroup,'Microsoft.Network/virtualNetworks/subnets', vnetName, subnetName)
var uniqueId = uniqueString(resourceGroup().id, 'apim')
module apim 'br/public:avm/res/api-management/service:0.2.0' = {
  name: 'apimDeployment'
  params: {
    name: 'apim-apim${uniqueId}'
    publisherEmail: 'xxx'
    publisherName: 'xxx'
    sku:'Developer'
    skuCount:1
    subnetResourceId: subnetResourceId
    virtualNetworkType:'Internal'
    zones:null
    additionalLocations:null
    disableGateway:true
  }
}

// resource apimService 'Microsoft.ApiManagement/service@2021-01-01-preview' = {
//   name: 'apim-apim${uniqueId}'
//   location: resourceGroup().location
//   sku: {
//     name: 'Developer'
//     capacity: 1
//   }
//   properties: {
//     publisherEmail: 'xxx'
//     publisherName: 'xxx'
//     virtualNetworkType: 'Internal'
//     virtualNetworkConfiguration: {
//       subnetResourceId: subnetResourceId
//     }
//   }
// }

**Comment by tony-box** [comment]
Sorry for that, folks--definitely a bug. I am almost done with a fix and will be making a PR shortly.

**Comment by IngerMathilde** [comment]
Hi! Thanks for the fix! I see that it is still a problem in the latest available version 0.2.1. Any ETA when a new version will be released with this fix?

**Comment by dhayes-ccl** [comment]
@IngerMathilde  this worked for me, I think the key was setting the zones and additional locations to [] explicitly. Hope this helps you
module apimService 'br/public:avm/res/api-management/service:0.2.1' = {
  name: 'apim-${apimName}-${uniqueId}'
  params: {
    name: 'apim-${apimName}-${uniqueId}'
    location: location
    sku: skuName
    skuCount: skuCount
    virtualNetworkType: 'Internal'
    subnetResourceId: subnetResourceId
    hostnameConfigurations: ( deployHostNames ? allHostNameConfigurations:gatewayHostNameConfigurations)
    publisherEmail: publisherEmail
    publisherName: publisherName
    zones: []
    additionalLocations: []
    diagnosticSettings: [
      {
        name: 'LogAnalytics'
        workspaceResourceId: lawWorkspaceId
        logCategoriesAndGroups: [
          {
            categoryGroup: 'allLogs'
          }
        ]
        metricCategories: [
          {
            category: 'AllMetrics'
          }
        ]
      }
    ]
    policies: [
      {
        format: 'xml'
        value: replace(policy, '\${apimDeveloperPortalUrl}', developerPortalUrl)
      }
    ]
    managedIdentities: {
      systemAssigned: false
      userAssignedResourceIds: [
        uai.id
      ]
    }
  }
}

**Comment by tony-box** [comment]
@dhayes-ccl @IngerMathilde interesting... the test deployment for a Developer SKU deploys successfully using only the required params:

``` 
module testDeployment '../../../main.bicep' = [
  for iteration in ['init', 'idem']: {
    scope: resourceGroup
    name: '${uniqueString(deployment().name, resourceLocation)}-test-${serviceShort}-${iteration}'
    params: {
      name: '${namePrefix}${serviceShort}001'
      location: resourceLocation
      publisherEmail: 'apimgmt-noreply@mail.windowsazure.com'
      publisherName: '${namePrefix}-az-amorg-x-001'
      sku: 'Developer'
    }
  }
]
```

I'm not sure why explicitly setting the `skuCount` would then require an empty array for `zones` and `additionalLocations`. I am going to test a quick fix to default those two arrays to `[]` instead of `null` to see if that results in the desired behavior of setting `skuCount`

**Comment by tony-box** [comment]
@dhayes-ccl @IngerMathilde sorry--I just realized you two are using `skuCount` which was deprecated with the last minor update `0.2.0`. The new param name is called `skuCapacity` which better aligns with the actual definition of what that parameter modifies.

Regardless, I am testing out using empty arrays instead of null arrays to see if that removes any issues if you explicitly set the `skuCapacity` to 1

**Comment by IngerMathilde** [comment]
@dhayes-ccl  thanks this helped. Had zones and additionalLocations set to null and not empty strings. @tony-box  I am quite new to using azure verified modules, but If I look at the tag associated with the last release (https://github.com/Azure/bicep-registry-modules/blob/avm/res/api-management/service/0.2.1/avm/res/api-management/service/main.bicep), it is not up to date with main. That is why I was wondering if we needed a 0.2.2 version.

**Comment by tony-box** [comment]
@IngerMathilde @dewolfs PR raised to fix the issue. deployment was successful when I set the `skuCapacity` to 1 for the developer sku without setting `zones` or `additionalLocations` params.
