### ISSUE TITLE
[AVM Module Issue]: dns-zone nameServers output

### ISSUE THREAD

**Issue by lopf** [Azure/bicep-registry-modules#2563]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/dns-zone

### (Optional) Module Version

0.3.0

### Description

We would like to get the `nameServers` property in the module output in order to create NS delegation records in another zone.

**Comment by ChrisSidebotham** [comment]
Apologies for the delay in picking this up, will get this updated and published this week
