### ISSUE TITLE
[AVM Module Issue]: Machine Learning Module should add the creation of `Microsoft.MachineLearningServices/workspaces/connections`

### ISSUE THREAD

**Issue by Menghua1** [Azure/bicep-registry-modules#2575]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/machine-learning-services/workspace

### Description

Please add the creation of `Microsoft.MachineLearningServices/workspaces/connections`.

For example (azd):

- https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/ai/hub.bicep#L69

CC: @jongio

**Comment by AlexanderSehr** [comment]
Hey @Menghua1, thanks for the issue.
The request makes absolute sense, hence I removed the 'Needs: Triage' label. However, as the module currently has no owner that would automatically be assigned to this issue, it may take a moment for the community to work on it. If you're up for the task you can of course also create the contribution yourself. 💪

**Comment by matebarabas** [comment]
Good news, this module just got a new owner! @cecheta, can you please look into this issue? Thanks!

CC: @ross-p-smith as secondary owner

**Comment by cecheta** [comment]
Thanks for raising this, we'll look into this in due course

**Comment by cecheta** [comment]
Hi @Menghua1 , it looks like `Microsoft.MachineLearningServices/workspaces/endpoint` is deprecated now? I receive this error:

```json
{
  "status": "Failed",
  "error": {
    "code": "DeploymentFailed",
    "target": "/subscriptions/***/resourceGroups/rg-dev/providers/Microsoft.Resources/deployments/main",
    "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
    "details": [
      {
        "code": "ValidationError",
        "message": "Endpoint resources are no longer supported, and have been migrated to connections. Please delete this resource and re-create it as a connection.",
        "details": []
      }
    ]
  }
}
```

Would it be ok to update the issue to just include connections?

**Comment by Menghua1** [comment]
@jongio Any ideas about [above comments](https://github.com/Azure/bicep-registry-modules/issues/2575#issuecomment-2218198443)? Could we consider only including `connections`?

**Comment by jongio** [comment]
> @jongio Any ideas about [above comments](https://github.com/Azure/bicep-registry-modules/issues/2575#issuecomment-2218198443)? Could we consider only including `connections` in AVM?

Please track down where this module is being use, who added it to infra/core, and then figure out a path forward.

**Comment by Menghua1** [comment]
> > @jongio Any ideas about [above comments](https://github.com/Azure/bicep-registry-modules/issues/2575#issuecomment-2218198443)? Could we consider only including `connections` in AVM?
> 
> Please track down where this module is being use, who added it to infra/core, and then figure out a path forward.

We did not find repo to use this module and @wbreza added this module to infra/core.

During the test, it looks like `Microsoft.MachineLearningServices/workspaces/endpoint` is deprecated now. Do you have any ideas about this?@wbreza

**Comment by jtracey93** [comment]
@jongio, from the comments/chat here from @Menghua1 it looks like this one is maybe not needed, can you and the team confirm? 

#RR

**Comment by jongio** [comment]
Let's see what @wbreza says.

**Comment by wbreza** [comment]
`endpoints` are no longer supported and all new deployments must be migrated to `connections`.  An example of this after a migration can be found in the [AZD AI Studeio Starter template](https://github.com/Azure-Samples/azd-aistudio-starter/blob/main/infra/core/ai/hub.bicep#L62)

**Comment by jongio** [comment]
@Menghua1 we can close this.

**Comment by Menghua1** [comment]
> @Menghua1 we can close this.

This issue cannot be closed yet, because not only is the `endpoints` missing, but also a `connections` is missing. I removed the unsupported `endpoints` and updated the description.

**Comment by Menghua1** [comment]
@cecheta I've updated the issue to include only the `connections`.

**Comment by jtracey93** [comment]
@cecheta are you able to provide an ETA on resolution for adding this to the module for @jongio, please?

Thanks

Jack

**Comment by cecheta** [comment]
I will start looking at it now, however I am also working on the new `avm/ptn/ai-platform/baseline` module, and I am on leave for ~2 weeks from the start of August.

Hopefully this will be implemented before the end of August.
