### ISSUE TITLE
[AVM Module Issue]: MySQL Flexible Server Module should add the output `mysqlServer.properties.fullyQualifiedDomainName`

### ISSUE THREAD

**Issue by Menghua1** [Azure/bicep-registry-modules#2576]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/db-for-my-sql/flexible-server

### Description

Please add the output `mysqlServer.properties.fullyQualifiedDomainName`.

For example (azd):
https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/mysql/flexibleserver.bicep#L65

CC: @jongio

**Comment by v-xuto** [comment]
@hundredacres  We have created a PR for this issue. Please review.
- PR link: https://github.com/Azure/bicep-registry-modules/pull/2606

**Comment by AlexanderSehr** [comment]
Hey @hundredacres, please take a moment to triage this issue if you can 💪

**Comment by hundredacres** [comment]
I've opened a bug here: https://github.com/Azure/bicep/issues/14594

Appears to be an issue when passing a maintenanceWindow object, which is a WAF required setting.

**Comment by AlexanderSehr** [comment]
> I've opened a bug here: [Azure/bicep#14594](https://github.com/Azure/bicep/issues/14594)
> 
> Appears to be an issue when passing a maintenanceWindow object, which is a WAF required setting.

Hey @hundredacres, and this only happens when adding the output requested in this issue?

**Comment by hundredacres** [comment]
@AlexanderSehr If we just add the requested output and remove the maintenanceWindow object from the default and WAF tests, then we're green again. But the maintenanceWindow object is required by WAF, so not having the param present causes a Pester test to fail. If there's a way to bypass a specific WAF test, we could merge this change and wait for a response to my bug.

**Comment by hundredacres** [comment]
@AlexanderSehr The pipeline from this PR fails cause the maintenanceWindow object is missing from the default test, which throws this Pester error

`Error: AZR-000431: ***dfmsfsmin001 failed Azure.MySQL.MaintenanceWindow. Configure a customer-controlled maintenance window for Azure Database for MySQL servers.`

**Comment by AlexanderSehr** [comment]
Hey @hundredacres,
thanks for the input. Just got a bit confused as this issue doesn't mention anything about the `maintenanceWindow`, but looking at the PR I saw now that you're referring to the PSRule tests. Will reply on the PR then instead :)
