### ISSUE TITLE
[AVM Module Issue]:  deployment error shows in the rg of rsg-australiasoutheast-ds as {"code":"SkuUnavailableInZone","message":"The sku Sku: Standard_ZRS, Kind: StorageV2 is not available in zone."} . How can I exclude the creation of rg "{"code":"SkuUnavailableInZone","message":"The sku Sku: Standard_ZRS, Kind: StorageV2 is not available in zone."}" when I al deploying a sub with all resourceproviders . or how can we fix this storage error. 

### ISSUE THREAD

**Issue by NirajCricket** [Azure/bicep-registry-modules#2588]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/ptn/lz/sub-vending

### (Optional) Module Version

module subVending 'br/public:avm/ptn/lz/sub-vending:0.1.0' = {

### Description

{"code":"DeploymentFailed","target":"/subscriptions/6222387f-22a9-4ce6-ab15-aae74edbdb31/resourceGroups/rsg-australiasoutheast-ds/providers/Microsoft.Resources/deployments/lz-vend-ds-stg-create-xawbly67trsvg","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"SkuUnavailableInZone","message":"The sku Sku: Standard_ZRS, Kind: StorageV2 is not available in zone."}]}

### (Optional) Correlation Id

rsg-australiasoutheast-ds | Deployments while creating this rg it throws error

**Comment by sebassem** [comment]
I fix was submitted for this issue, please see this [issue](https://github.com/Azure/bicep-registry-modules/issues/2549). You need to update your module version to the latest

**Comment by NirajCricket** [comment]
which module I need to upgrade to 0.1.2 ? 

here is my main.bicep file

targetScope = 'managementGroup'
param subscriptionAliasEnabled bool
param subscriptionDisplayName string
param subscriptionAliasName string
param subscriptionBillingScope string
param subscriptionWorkload string
param subscriptionManagementGroupAssociationEnabled bool
param subscriptionManagementGroupId string
param subscriptionTags object
param resourceProviders object
param location string

module subVending 'br/public:avm/ptn/lz/sub-vending:0.1.0' = {
  name: 'subVendingDeployment'
  params: {
    subscriptionAliasEnabled: subscriptionAliasEnabled
    resourceProviders: resourceProviders
    subscriptionBillingScope: subscriptionBillingScope
    subscriptionAliasName: subscriptionAliasName
    subscriptionDisplayName: subscriptionDisplayName
    subscriptionManagementGroupAssociationEnabled: subscriptionManagementGroupAssociationEnabled
    subscriptionManagementGroupId: subscriptionManagementGroupId
    subscriptionTags: subscriptionTags
    subscriptionWorkload: subscriptionWorkload
    deploymentScriptLocation: location
  }
}

**Comment by NirajCricket** [comment]
Hi @sebassem  it seems the module version has fixed the job, 
module subVending 'br/public:avm/ptn/lz/sub-vending:0.1.2' = {
  name: 'subVendingDeployment'
  params: {
