### ISSUE TITLE
[AVM Module Issue]:   "registerResourceProviders": "[take(format('lz-vend-ds-create-{0}', is not ending and this job continues to run more than 35min, hence have to cancel it.

### ISSUE THREAD

**Issue by NirajCricket** [Azure/bicep-registry-modules#2592]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/ptn/lz/sub-vending

### (Optional) Module Version

module subVending 'br/public:avm/ptn/lz/sub-vending:0.1.2' = {

### Description

The Job   "registerResourceProviders": "[take(format('lz-vend-ds-create-{0}', uniqueString(parameters('subscriptionId'), parameters('deploymentScriptResourceGroupName'), parameters('deploymentScriptName'), deployment().name)), 64)]",

which is in my case is lz-vend-ds-create-wydd6ykdfcfki under resource group 
rsg-australiasoutheast-ds is not finishing, it is kind a loop or not sure but keeps running for more that 35min, hence have to cancel the job, is it expected or some other issue.

 registerResourceProviders: take(
    'lz-vend-ds-create-${uniqueString(subscriptionId, deploymentScriptResourceGroupName, deploymentScriptName, deployment().name)}',
    64
  )
![image](https://github.com/Azure/bicep-registry-modules/assets/35249470/9c75890a-588c-4389-97c0-8bb497673894)
![resourceprovider deployment never ending-from modules of avm](https://github.com/Azure/bicep-registry-modules/assets/35249470/b81ba3a5-a2eb-4718-bb89-1ba22739e966)
![resourceprovider deployment never ending](https://github.com/Azure/bicep-registry-modules/assets/35249470/2a69aa03-a757-4670-9831-d8b9604c5d3c)

### (Optional) Correlation Id

rsg-australiasoutheast-ds | Deployments while creating this rg it throws error
```[tasklist]
### Tasks
```

**Comment by NirajCricket** [comment]
Hi @sebassem and @jtracey93 , thanks for fixing previous issue in storagev2 ZRS, this is also part of same rg, which never finish , the resourceproviders tasks deployment is like running in a loop, not sure but not finishing in 35min, I am gonna run one more time and see.

**Comment by sebassem** [comment]
can you share your module parameters ?

**Comment by sebassem** [comment]
@NirajCricket can you check the resource providers status in the portal and let us know what you see there ?

**Comment by sebassem** [comment]
@NirajCricket can you check the resource providers status in the portal and let us know what you see there ?

**Comment by jtracey93** [comment]
#RR

**Comment by sebassem** [comment]
Closing for no response
