### ISSUE TITLE
[Module Proposal]: Azure Managed Grafana

### ISSUE THREAD

**Issue by vlahane** [Azure/bicep-registry-modules#260]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Why is the module needed?
We require a base module for managing Azure Managed Grafana instances and one is not currently available in the public registry. It will follow the same concept of the existing modules in bicep-registry-modules repository. 

The intent of the module is to focus specifically on the Azure Managed Grafana it will support features like private endpoint and management of Grafana configurations.

### Module path

observability/grafana

### Describe the module

Proposed module will allow user to provision managed Grafana instance quicky.

**Comment by vlahane** [comment]
Hi @alex-frankel any thoughts on managed grafana module. ?

**Comment by dciborow** [comment]
leaving myself some notes for this one.
```bicep
resource symbolicname 'Microsoft.Dashboard/grafana@2022-08-01' = {
  name: 'string'
  location: 'string'
  tags: {
    tagName1: 'tagValue1'
    tagName2: 'tagValue2'
  }
  sku: {
    name: 'string'
  }
  identity: {
    type: 'string'
    userAssignedIdentities: {}
  }
  properties: {
    apiKey: 'string'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    deterministicOutboundIP: 'string'
    grafanaIntegrations: {
      azureMonitorWorkspaceIntegrations: [
        {
          azureMonitorWorkspaceResourceId: 'string'
        }
      ]
    }
    publicNetworkAccess: 'string'
    zoneRedundancy: 'string'
  }
}
resource symbolicname 'Microsoft.Dashboard/grafana/privateEndpointConnections@2022-08-01' = {
  name: 'string'
  parent: resourceSymbolicName
  properties: {
    groupIds: [
      'string'
    ]
    privateEndpoint: {}
    privateLinkServiceConnectionState: {
      actionsRequired: 'string'
      description: 'string'
      status: 'string'
    }
  }
}
resource symbolicname 'Microsoft.Dashboard/grafana/privateLinkResources@2022-08-01' existing = {
  name: 'string'
}
```

**Comment by vlahane** [comment]
> Hi @alex-frankel any thoughts on managed grafana module. ?

@alex-frankel  @shenglol  please check this proposal, thanks! 😃

**Comment by shenglol** [comment]
I wonder if it makes sense to use the module group `observability`.

**Comment by vlahane** [comment]
observability makes more sense to me as well, ref: https://radar.cncf.io/2020-09-observability. I will update path in issue with `observability/grafana`
