### ISSUE TITLE
[AVM Module Issue]: CDN Profile Module should add the output `cdnEndpoint.outputs.name`, `cdnEndpoint.outputs.id`, `cdnEndpoint.outputs.uri`

### ISSUE THREAD

**Issue by NanaXiong00** [Azure/bicep-registry-modules#2610]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cdn/profile

### Description

Please add the output `cdnEndpoint.outputs.name`, `cdnEndpoint.outputs.id`, `cdnEndpoint.outputs.uri`.

For example (azd):

- https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/networking/cdn-endpoint.bicep#L51
- https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/networking/cdn-endpoint.bicep#L50
- https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/networking/cdn-endpoint.bicep#L52

CC: @jongio

**Comment by gbeaud** [comment]
Ok I will look into this 👍

**Comment by v-xuto** [comment]
PR for this issue: https://github.com/Azure/bicep-registry-modules/pull/2675

**Comment by v-xuto** [comment]
PR https://github.com/Azure/bicep-registry-modules/pull/2675 fix this issue. We will close it.
