### ISSUE TITLE
[AVM Module Issue]: Cognitive Services Module should add the output `account.properties.endpoints`

### ISSUE THREAD

**Issue by NanaXiong00** [Azure/bicep-registry-modules#2611]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cognitive-services/account

### Description

Please add the output `account.properties.endpoints`.

For example (azd):

- https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/ai/cognitiveservices.bicep#L54

CC: @jongio

**Comment by ilhaan** [comment]
@NanaXiong00 Thanks for submitting this. I will take a look at adding this next week.

**Comment by jtracey93** [comment]
@ilhaan, just checking in on how you are getting on with this ask as @jongio and team require this for some azd dependencies on AVM 👍 

Can you provide us an update and rough ETA?

Thanks

**Comment by donheerschap** [comment]
@jongio @jtracey93  just checking, you only need the raw output of the properties.endpoints right? I saw in most kinds of cognitive services these are just replica's of the single endpoint output, but for OpenAI there are some differences.

**Comment by jtracey93** [comment]
@NanaXiong00 & @jongio to answer here :)

**Comment by jongio** [comment]
THe raw typed output makes sense to me.

**Comment by v-xuto** [comment]
Related to PR: https://github.com/Azure/bicep-registry-modules/pull/2735
