### ISSUE TITLE
[AVM Module Issue]:  Resource Role Assignment

### ISSUE THREAD

**Issue by darrenFrowen** [Azure/bicep-registry-modules#2612]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/ptn/authorization/resource-role-assignment

### (Optional) Module Version

0.1.0

### Description

I have the following configuration i have been testing with, on the right we have my main.bicep currently scoped at subscription as i am deploying multiple resource groups and their resources. I have a module for a role assignment scoped to a resource group. My goal is to assign a vaults service principle the Contributor role to the Private DNS Zone Resource Group. On the left  we have the module showing a working resource roleAssignments template 19-26 and a non working AVM module 9-17. 

I seem to be going around in a circle of failures between using the 'resource-role-assignment' and the 'role-assignment' AVM modules.

1. If i use the 'resource-role-assignment'  AVM Module IntelliSense forces me to use the 'resourceId' parameter. If i define the resourceId and run the deployment it fails consistently with "The resource namespace 'subscriptions' is invalid.
     | (Code:InvalidResourceNamespace)".

2. If i then move to use any one of the AVM 'role-assignment'  '(Resource Group scope)' or '(Resource Group)' i then see IntelliSense error if the AVM template example is placed in the main.bicep i see this error. "Scope "subscription" is not valid for this module. Permitted scopes: "managementGroup".bicep(BCP134)". Or if i place the AVM template example is placed in the module itself i see this error. "Scope "resourceGroup" is not valid for this module. Permitted scopes: "managementGroup".bicep(BCP134)". 

ultimately i am trying to understand why where using the resource template this works fine scoped at the resource group assigns the role correctly on the resource group but any of the templates fail either subscription scope name space is incorrect or i am forced to use management group as the scope. 

![image](https://github.com/Azure/bicep-registry-modules/assets/16030060/b027546d-2924-4e6f-8b51-4af6600bfd2e)

### (Optional) Correlation Id

7f0852bd-509e-4a0a-9d9a-a5adf4f0a9df

**Comment by peterbud** [comment]
You should set the scope of your module to the appropriate resource group when using the resource-role-assignment module

Can you try the following:

```diff
module avmRoleassignment 'br/public:avm/ptn/authorization/resource-role-assignment:0.1.0' = {
  name: 'roleAssignmentDeployment'
+ scope: resourceGroup(...)
  params: {
    ....
  }
}
```

**Comment by darrenFrowen** [comment]
Hi @peterbud,

Just tried direct in my main.bicep on the right and in my sub module on the left both fail with the same error. The resource namespace 'subscriptions' is invalid.      
     | (Code:InvalidResourceNamespace)

![image](https://github.com/Azure/bicep-registry-modules/assets/16030060/1ae56a09-5197-4f54-b8a4-c9da297f4f04)

**Comment by peterbud** [comment]
What is your targetScope for both file? Can you share a minimal example which produces the error you describe (full code pls)? Also would be great instead of picture, you would share code.

Also look at the test bicep files which are successfully running in CI:
https://github.com/Azure/bicep-registry-modules/blob/main/avm/ptn/authorization/resource-role-assignment/tests/e2e/defaults/main.test.bicep

The test file's targetScope is a subscription, and the resource-role-assignment module's scope is a resourceGroup, which has been created.

So far I cannot repro your issue.

**Comment by darrenFrowen** [comment]
Hi Peter, Will share the code tomorrow morning, thanks for the quick response. On 7 Jul 2024, at 14:40, Peter Budai ***@***.***> wrote:﻿
What is your targetScope for both file? Can you share a minimal example which produces the error you describe (full code pls)? Also would be great instead of picture, you would share code.
Also look at the test bicep files which are successfully running in CI:
https://github.com/Azure/bicep-registry-modules/blob/main/avm/ptn/authorization/resource-role-assignment/tests/e2e/defaults/main.test.bicep
The test file's targetScope is a subscription, and the resource-role-assignment module's scope is a resourceGroup, which has been created.
So far I cannot repro your issue.

**Comment by darrenFrowen** [comment]
Hi @peterbud, please see below my code as requested.I am calling an existing Virtual Network resource group Id and an output from my backupvault for its system assigned identity. 

### main.bicep: _This is my main.bicep File which calls a sub module roleAssignmets.bicep_


targetScope = 'subscription'

```bicep
@description('Deploy Role Assignment at the specified scope')
param principalId string
param roleDefinitionId string
param principalType string
param scope string

@description('This is the existing Hub Virtual Network Resource Group')
resource hubVirtualNetworkServicesRg 'Microsoft.Resources/resourceGroups@2021-01-01' existing = {
  name: 'rg-${hubPrefix}-network'
}

@description('This is the built-in Contributor role. See https://docs.microsoft.com/azure/role-based-access-control/built-in-roles#contributor')
resource contributorRoleDefinition 'Microsoft.Authorization/roleDefinitions@2018-01-01-preview' existing = {
  scope: subscription()
  name: 'b24988ac-6180-42a0-ab88-20f7382dd24c'
}

@description('This is the required vault Role assignment for Virtual Network Resource Group')
module backupVaultVnetRgRoleAssignment './modules/templates/roleAssignmets.bicep' = if (vaultVnetRoleUpdate) {
  name: 'backupVaultVnetRgRoleAssignment'
  scope: hubVirtualNetworkServicesRg
  dependsOn: [
    sharedBackupVault
  ]
  params: {
    principalId: sharedBackupVault.outputs.vaultSystemAssignedMIPrincipalId
    roleDefinitionId: contributorRoleDefinition.id
    principalType: 'ServicePrincipal'
    scope: hubVirtualNetworkServicesRg.id
  }
}
```

### roleAssignmets.bicep: _I am successfully using this sub module to deploy role assingnment for a storage account resourceId but in this instance i need to taget the resource group_

```bicep
@description('Deploy Role Assignment at the specified scope')
param principalId string
param roleDefinitionId string
param principalType string
param scope string

@description('This AVM role assignment "fails" for Contributor Role on the RG Scope')
module avmRoleAssignment 'br/public:avm/ptn/authorization/resource-role-assignment:0.1.0' = {
  name: 'roleAssignmentDeployment'
  scope: resourceGroup()
  params: {
    principalId: principalId
    roleDefinitionId: roleDefinitionId
    resourceId: resourceGroup().id
  }
}
```

**Comment by peterbud** [comment]
I see now your issue. You are trying to assign a contributor role to a _resource group_. 

That won't work with this module. 

As the description says: "This module deploys a Role Assignment for a specific resource."

Resource Group != Resource

**Comment by darrenFrowen** [comment]
Hi Peter,Yes I suspected that was the case so as you can see from my below initial updated I tried the resource group and the resource group scope options but both errored with different issues. I am just trying to understand which I should be using when my main.bicep is scoped at subscription level.If i then move to use any one of the AVM 'role-assignment' '(Resource Group scope)' or '(Resource Group)' i then see IntelliSense error if the AVM template example is placed in the main.bicep i see this error. "Scope "subscription" is not valid for this module. Permitted scopes: "managementGroup".bicep(BCP134)". Or if i place the AVM template example is placed in the module itself i see this error. "Scope "resourceGroup" is not valid for this module. Permitted scopes: "managementGroup".bicep(BCP134)".ultimately i am trying to understand why where using the resource template this works fine scoped at the resource group assigns the role correctly on the resource group but any of the templates fail either subscription scope name space is incorrect or i am forced to use management group as the scope.On 8 Jul 2024, at 14:05, Peter Budai ***@***.***> wrote:﻿
I see now your issue. You are trying to assign a contributor role to a resource group.
That won't work with this module.
As the description says: "This module deploys a Role Assignment for a specific resource."
Resource Group != Resource
