### ISSUE TITLE
[AVM Module Issue]: ApiManagement Loggers should depend upon NamedValues

### ISSUE THREAD

**Issue by mikejonestechno** [Azure/bicep-registry-modules#2617]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/api-management/service

### (Optional) Module Version

0.2.0

### Description

Loggers have a credential parameter normally used for the AppInsights instrumentation key, however credentials can also reference namedValues. 

However the AVM attempts to generate the loggers and namedValues in parallel module deployments which causes deployment failures if a logger depends on a namedValue that does not yet exist, for example:

```AppInsights_InstrumentationKey (Code: ValidationError, Target: One or more Properties ['{0}'] specified are missing.)```

Propose updating the `main.bicep` so that the loggers module depends upon the namedValues module so that logger credentials can use namedValues. 

**Background**

Every AVM bicep deployment containing AppInsights or other loggers will automatically generate namedValues - _creating duplicated namedValues on every deployment_. 

I believe this is a 'known issue' in underlying APIM resource provider:
https://github.com/Azure/bicep/issues/7368
https://github.com/Azure/azure-powershell/issues/12228
https://www.kenmuse.com/blog/connecting-apim-and-appinsights-using-bicep/

The only available workaround is to manually define named values for instrumentation keys rather than using auto-generated values.

**Proposed Change**

File: [/avm/res/api-management/service/main.bicep#L428](https://github.com/Azure/bicep-registry-modules/blob/6bfef3b5819d4a8c750f41e0b0d76c2943f6afd1/avm/res/api-management/service/main.bicep#L428)

Replace existing:
```
module service_loggers 'loggers/main.bicep' = [
  for (logger, index) in loggers: {
    name: '${uniqueString(deployment().name, location)}-Apim-Logger-${index}'
    params: {
      name: logger.name
      apiManagementServiceName: service.name
      credentials: contains(logger, 'credentials') ? logger.credentials : {}
      isBuffered: contains(logger, 'isBuffered') ? logger.isBuffered : true
      loggerDescription: contains(logger, 'loggerDescription') ? logger.loggerDescription : ''
      loggerType: contains(logger, 'loggerType') ? logger.loggerType : 'azureMonitor'
      targetResourceId: contains(logger, 'targetResourceId') ? logger.targetResourceId : ''
    }
  }
]
```

with additional `dependsOn` :
```
module service_loggers 'loggers/main.bicep' = [
  for (logger, index) in loggers: {
    name: '${uniqueString(deployment().name, location)}-Apim-Logger-${index}'
    params: {
      name: logger.name
      apiManagementServiceName: service.name
      credentials: contains(logger, 'credentials') ? logger.credentials : {}
      isBuffered: contains(logger, 'isBuffered') ? logger.isBuffered : true
      loggerDescription: contains(logger, 'loggerDescription') ? logger.loggerDescription : ''
      loggerType: contains(logger, 'loggerType') ? logger.loggerType : 'azureMonitor'
      targetResourceId: contains(logger, 'targetResourceId') ? logger.targetResourceId : ''
    }
    dependsOn: [
      service_namedValues
    ]
  }
]
```

**Comment by tony-box** [comment]
@mikejonestechno thank you for the submission. Good catch--it's hard for me to test each possible permutation of the APIM module due to its complexity. I have a PR open right now that hasn't been approved yet--I think I can easily sneak this change into that PR.
