### ISSUE TITLE
[AVM CI Environment Issue]: `Set-AVMModule` creates `main.bicep` in wrong directory, overflow error

### ISSUE THREAD

**Issue by cecheta** [Azure/bicep-registry-modules#2637]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

When I use the `Set-AVMModule` to generate documentation and build the Bicep, it generates a `main.bicep` file in the wrong directory. If I try to re-run it, I receive an error `InvalidOperation: The script failed due to call depth overflow.`

Steps to reproduce:

* Launch devcontainer/Codespace
* Open `pwsh` terminal
* Run (as an example): 
```pwsh
. .\avm\utilities\tools\Set-AVMModule.ps1
Set-AVMModule -ModuleFolderPath .\avm\res\aad\domain-service
```

There is now a new `main.bicep` file at `/workspaces/bicep-registry-modules/avm/res/aad/domain-service/aad/domain-service/main.bicep`

Logs:
```
VERBOSE: Added file [/workspaces/bicep-registry-modules/avm/res/aad/domain-service/aad/domain-service/main.bicep]
Building [avm/res/aad/domain-service/main.bicep]                                                                        
Generating readme for [avm/res/aad/domain-service/main.bicep] 
```

* Run `Set-AVMModule -ModuleFolderPath avm/res/aad/domain-service` again

Logs:
```
InvalidOperation: The script failed due to call depth overflow.
```

I don't have much experience with PowerShell so I'm not sure if I'm simply running the script incorrectly

**Comment by AlexanderSehr** [comment]
Hey @cecheta,
thanks for raising this. I'll take a look as soon as I can.

**Comment by AlexanderSehr** [comment]
Hey @cecheta,
sadly, I cannot reproduce the issue. I wonder if it is something codespaces-specific. I've never used them so I don't know what makes them 'different'. Can you reproduce the issue locally?
If not, I guess the next step would then be to try and debug the script in a Codespace instance. For that I'd need to find out how to use them first though 😄

**Comment by cecheta** [comment]
I couldn't reproduce this when running PowerShell locally, so this seems to only be an issue when using a devcontainer

**Comment by AlexanderSehr** [comment]
Found the reason. One line in that code is hardcoded to Windows. Will open a PR to fix
