### ISSUE TITLE
[AVM Module Issue]: managedEnvironments is missing certificateKeyVaultProperties setting in customDomainConfiguration

### ISSUE THREAD

**Issue by robvangeloven** [Azure/bicep-registry-modules#2642]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/managed-environment

### (Optional) Module Version

0.5.1

### Description

The module is missing a way to set the [certificateKeyVaultProperties ](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/managedenvironments?pivots=deployment-language-bicep#certificatekeyvaultproperties)for a custom domain. Is it possible to add this? Or are you perhaps open to a PR for this?

**Comment by AlexanderSehr** [comment]
Hey @hundredacres,
please take a look at the issue when you can :)
That being said, @robvangeloven, contibutions are always welcome. I'd be suprised if @hundredacres would take offense 😄

**Comment by hundredacres** [comment]
Wouldn't take offense at all. Happy to get contributions from others!

**Comment by AlexanderSehr** [comment]
In either case @hundredacres, I'd recommend to remove the Triage Label to stop the automation from haunting you 😉

**Comment by robvangeloven** [comment]
> @robvangeloven do you want to work on a PR yourself, or do you want me to pick this up?

So sorry, I completely missed your reply!

I made a PR, since this is my first PR to this repo it's probably not complete yet: https://github.com/Azure/bicep-registry-modules/pull/2719

One issue I had is running Set-AVMModule.ps1 seemed to do nothing

**Comment by AlexanderSehr** [comment]
> > @robvangeloven do you want to work on a PR yourself, or do you want me to pick this up?
> 
> So sorry, I completely missed your reply!
> 
> I made a PR, since this is my first PR to this repo it's probably not complete yet: #2719
> 
> One issue I had is running Set-AVMModule.ps1 seemed to do nothing

Hey @robvangeloven, did you dot-source the script before invoking the `Set-AVMModule` function as documented? Note it's **not** just a script, but wraps a function 😉
