### ISSUE TITLE
[AVM Module Issue]: avm/ptn/security/security-center - AMA/MMA support

### ISSUE THREAD

**Issue by jikuja** [Azure/bicep-registry-modules#2665]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/ptn/security/security-center

### Description

#  Microsoft.Security/workspaceSettings | AMA vs MMA

Is `Microsoft.Security/workspaceSettings` for AMA or MMA?

I think this should be optional resource: https://techcommunity.microsoft.com/t5/microsoft-defender-for-cloud/microsoft-defender-for-cloud-strategy-and-plan-towards-log/ba-p/3883341

# Current documentation

IMO documentation should better than
* autoProvision parameter - `Optional. Describes what kind of security agent provisioning action to take. - On or Off.`
  * What does this enable?
* workspaceResourceId -  `Required. The full resource Id of the Log Analytics workspace to save the data in`
  *  Which data?

# AMA

Not sure if AMA support is good for this module. Some defender features might require it but MMA/AMA should be optional.

**Comment by tony-box** [comment]
@jikuja it looks like this is specifically for Log Analyitics Agent target workspaces. So it would be for MMA. I'm hesitant to create a new module to support this when it is EOL and will be deprecated in August of this year. 

I can however add the module `microsoft.security/settings` https://learn.microsoft.com/en-us/azure/templates/microsoft.security/settings?pivots=deployment-language-

This will allow enablement of Microsoft Defender for Endpoint (WDATP) as well as sentinel and MCAS

**Comment by jikuja** [comment]
What is deprecation plan on pattern module level to remove access to MMA?

What are the plans to enable AMA on pattern module or should it be done by customers' policy assignments or per VM deployment?

Related issue: avm.res.compute.virtual-machine module's AMA-specific code IMHO does not really work. 

Is there any public AMA migrations plans on AVM?

**Comment by tony-box** [comment]
@jikuja

**What is deprecation plan on pattern module level to remove access to MMA?**
I am unsure on this from the AVM perspective. If MMA is being deployed through other AVM resources, I am guessing we would need to coordinate those resources to start using AMA at some point in the future. Keep in mind, MMA is not going to stop working on Aug 31st, instead it will stop being supported and support will slowly phase out of new product releases. According to the [AMA Migration page](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration), MMA ingestion will stop working on Feb 1, 2025.

**What are the plans to enable AMA on pattern module or should it be done by customers' policy assignments or per VM deployment?**
I believe this should be done per resource, or via Policy. It's up to each use case's requirements.

**Related issue: avm.res.compute.virtual-machine module's AMA-specific code IMHO does not really work.**
If this doesn't work properly, can you please open a bug for that module? That module owner can take a look and try to address it. Although maybe this is better conversation for the whole AVM team to tackle so we are unified on an approach for the MMA -> AMA deprecation.

**Is there any public AMA migrations plans on AVM?**
Not that I am aware of. Please see the [AMA Migration page](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration) for more info on migration, though. @matebarabas

**Comment by jtracey93** [comment]
From an AVM perspective the MMA agent, if in a module today, will remain for a while. Reason being is that whilst August 2024 is the date of deprecation of MMA, it will still exist in a lot of environments past this date as folks migrate to AMA.

In the case of Microsoft Defender for Cloud (MDFC), MMA is not to be used going forward and instead migrate to new methods as per: https://learn.microsoft.com/en-us/azure/defender-for-cloud/prepare-deprecation-log-analytics-mma-agent

But in summary MDFC for Servers moves to an experience that doesnt require AMA and MDFC for SQL Servers on VMs does require AMA, due to throughput of logs requirement etc.
