### ISSUE TITLE
[AVM Module Issue]:  createDsStorageAccount: take(     'lz-vend-ds-stg-create-${uniqueString(subscriptionId, --Storageaccount name already exists

### ISSUE THREAD

**Issue by NirajCricket** [Azure/bicep-registry-modules#2690]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/ptn/lz/sub-vending

### (Optional) Module Version

module subVending 'br/public:avm/ptn/lz/sub-vending:0.1.2' = {

### Description

Hi @sebassem @jtracey93, it seems when u run the bicep template to create another subscription, and it vend the rame resource group for networking, then it uses the same storage account name as per the parameters in wrapper module, and that throws error in deployment as name already exists, can we fix it?
https://github.com/Azure/bicep-registry-modules/blob/main/avm/ptn/lz/sub-vending/modules/subResourceWrapper.bicep
 createDsStorageAccount: take(
    'lz-vend-ds-stg-create-${uniqueString(subscriptionId, deploymentScriptResourceGroupName, deploymentScriptLocation, deploymentScriptStorageAccountName, deployment().name)}',
    64
  )
}
Error:
The storage account named stgdstwcs is already taken. (Code: StorageAccountAlreadyTaken)
![deployment error-storageaccount name already exists](https://github.com/Azure/bicep-registry-modules/assets/35249470/32bf2ca4-ba29-4d3a-9600-5b6a75861fe9)
![deployment error-storageaccount name already exists fromgithub](https://github.com/Azure/bicep-registry-modules/assets/35249470/3963ec84-574d-4d05-8a50-979f760d7a85)

### (Optional) Correlation Id

rsg-australiasoutheast-ds | Deployments while creating this rg it throws error

**Comment by NirajCricket** [comment]
Hi @sebassem  r u referring me to change it here for each time I do a new subscription deployment?

https://github.com/Azure/bicep-registry-modules/blob/d0d07663f75a71099d3ef2683c028e2ce9b3dfec/avm/ptn/lz/sub-vending/modules/subResourceWrapper.bicep#L255

the issue is I am deploying the subscription module and this is part of vending modules in which it creates the default resource groups and try to deploy the storage account in those resource group, and subscription deployment doesn't have parameter defined for storage account.
![Uploading deployment error-storageaccount.jpg…]()

**Comment by sebassem** [comment]
@NirajCricket It appears you deployed the module multiple times with the same parameters without cleaning up the old deployments. You can either delete the existing deployment or [customize the name of the storage account](https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/lz/sub-vending#parameter-deploymentscriptstorageaccountname) based on your preferred naming convention.

**Comment by sebassem** [comment]
Closing with last comment. @NirajCricket please feel free to reachout if this is not resolved
