### ISSUE TITLE
[AVM Module Issue]: Metric alert with multiple scopes of type WebtestLocationAvailabilityCriteria fails with multiple scopes

### ISSUE THREAD

**Issue by guidemetothemoon** [Azure/bicep-registry-modules#2693]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/insights/metric-alert

### (Optional) Module Version

0.1.3

### Description

I've discovered a weird issue with AVM for Metric Alerts that doesn't happen if I declare metric alert resource with Bicep explicitly, i.e. without using the AVM.

This error happens when I'm using metric alert of type `'Microsoft.Azure.Monitor.WebtestLocationAvailabilityCriteria'` with **multiple** scopes being set, which in my case are Web Test resource ID and Application Insights resource ID. Main error message is: "**Alert scope is invalid.**"

Bicep AVM code that FAILS looks like this:

```
module metricAlert 'br/public:avm/res/insights/metric-alert:0.1.3' = {
  name: 'maDeployment-${deploymentTimestamp}'
  scope: metricAlertResourceGroup
  params: {
    alertDescription: 'Response time alert'
    enabled: true
    severity: 3
    name: metricAlertName
    location: 'global'
    windowSize: 'PT5M'
    evaluationFrequency: 'PT1M'
    alertCriteriaType: 'Microsoft.Azure.Monitor.WebtestLocationAvailabilityCriteria'
    targetResourceRegion: resourceLocation
    targetResourceType: 'Microsoft.Insights/webtests'
    criterias: [
      {
        componentId: appInsightsResourceId
        failedLocationCount: 3
        webTestId: webtestResourceId
      }
    ]
    actions: [
      actionGroupResourceId
    ]
    scopes: [
      webtestResourceId
      appInsightsResourceId
    ]
    tags: union(resourceTags, {
      'hidden-link:${appInsightsResourceId}': 'Resource'
      'hidden-link:${webtestResourceId}': 'Resource'
    })
  }
}
```

Bicep resource WITHOUT AVM that WORKS looks like this:

```
resource metricAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: metricAlertName
  location: alertLocation
  tags: union(resourceTags, {
    'hidden-link:${appInsightsResourceId}': 'Resource'
    'hidden-link:${webtestResourceId}': 'Resource'
  })
  properties: {
    description: 'Response time alert'
    enabled: true
    severity: 3
    autoMitigate: true
    windowSize: 'PT5M'
    evaluationFrequency: 'PT1M'
    targetResourceRegion: resourceLocation
    targetResourceType: 'Microsoft.Insights/webtests'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.WebtestLocationAvailabilityCriteria'
      componentId: appInsightsResourceId
      failedLocationCount: 3
      webTestId: webtestResourceId
    }
    actions: [
      {
        actionGroupId: actionGroupResourceId
      }
    ]
    scopes: [
      webtestResourceId
      appInsightsResourceId
    ]
  }
}
```

This is the error message:

```
New-AzSubscriptionDeployment : 1:06:41 PM - The deployment 'wtSubDeploymentc6f2f9b9' failed with error(s). Showing 3 out of 3 error(s).
Status Message: Alert scope is invalid. Activity ID: 7ce8ceb2-0c71-43ef-813e-51167c918fc8. (Code:BadRequest)
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage
details. (Code: DeploymentFailed)
 - {
  "code": "BadRequest",
  "message": "Alert scope is invalid. Activity ID: 7ce8ceb2-0c71-43ef-813e-51167c918fc8."
} (Code:BadRequest)
Status Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage
details. (Code: DeploymentFailed)
 - The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'. (Code: ResourceDeploymentFailure)
   - At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.
(Code: DeploymentFailed)
     - {
  "code": "BadRequest",
  "message": "Alert scope is invalid. Activity ID: 7ce8ceb2-0c71-43ef-813e-51167c918fc8."
} (Code:BadRequest)
CorrelationId: 0bbb1ed9-cbcb-4b61-81f4-d3b7805573d0
At line:1 char:1
+ New-AzSubscriptionDeployment -Location $subscriptionLocation -Name "w ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzDeployment], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureSubscriptionDeploymentCmdlet
```

I followed the README for the AVM to implement the properties as shown in the examples in the file. 

One thing I noted is the description for [targetResourceRegion and targetResourceType properties](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/insights/metric-alert#parameter-targetresourceregion). In AVM documentation it states that "**Required if alertCriteriaType is MultipleResourceMultipleMetricCriteria.**". But according to the [REST API documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/metricalerts?pivots=deployment-language-bicep#metricalertproperties) it also states that these properties are also required when multiple scopes are provided: "**Mandatory if the scope contains a subscription, resource group, or more than one resource.**". - Which I assume would also fall under all alert types and not only `MultipleResourceMultipleMetricCriteria`? If that's the case, current statement in AVM documentation may be easy to misinterpret.

### (Optional) Correlation Id

0bbb1ed9-cbcb-4b61-81f4-d3b7805573d0

**Comment by AlexanderSehr** [comment]
Hey @kijunkang, I just assigned the issue to you as the module owner. Please take a look at your earliest convenice to at least triage the issue (and remove the `Needs: Triage Label`)

**Comment by kijunkang** [comment]
> Hey @kijunkang, I just assigned the issue to you as the module owner. Please take a look at your earliest convenice to at least triage the issue (and remove the `Needs: Triage Label`)

Thank you @AlexanderSehr, I will start looking into this issue.

**Comment by kijunkang** [comment]
Hi @guidemetothemoon We identified the issue and currently working on it.
