### ISSUE TITLE
[AVM Module Issue]: ACA service add-ons + Service binds

### ISSUE THREAD

**Issue by weikanglim** [Azure/bicep-registry-modules#2696]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/container-app

### Description

The container-app AVM module is missing the ability to set [serviceBinds](https://github.com/Azure/azure-dev-pr/blob/a7c3709705631b65c39249c11c82bfe7b69b92fa/templates/common/infra/bicep/core/host/container-app.bicep#L140) and [service](https://github.com/Azure/azure-dev-pr/blob/a7c3709705631b65c39249c11c82bfe7b69b92fa/templates/common/infra/bicep/core/host/container-app.bicep#L131). This would be needed for ACA add-ons and referencing add-ons.

**Comment by oZakari** [comment]
Hi @weikanglim, valid ask and will start working on this in early August.
