### ISSUE TITLE
[AVM Module Issue]: Unable to login to Postgres with default settings

### ISSUE THREAD

**Issue by weikanglim** [Azure/bicep-registry-modules#2697]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/db-for-postgre-sql/flexible-server

### Description

Setting just `administratorLogin` and `administratorLoginPassword` doesn't allow logging in with the admin password.

For example, using the [defaults](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/db-for-postgre-sql/flexible-server#example-1-using-only-defaults) specified in the README:
```bicep
module flexibleServer 'br/public:avm/res/db-for-postgre-sql/flexible-server:<version>' = {
  name: 'flexibleServerDeployment'
  params: {
    // Required parameters
    name: 'dfpsfsmin001'
    skuName: 'Standard_B2s'
    tier: 'Burstable'
    // Non-required parameters
    administratorLogin: 'adminUserName'
    administratorLoginPassword: '<administratorLoginPassword>'
    geoRedundantBackup: 'Enabled'
    location: '<location>'
  }
}
```

The administrator login is actually disabled.

Current workaround: What is needed is to also provide the parameter `passwordAuth`:

```bicep
module flexibleServer 'br/public:avm/res/db-for-postgre-sql/flexible-server:<version>' = {
  name: 'flexibleServerDeployment'
  params: {
    // Required parameters
    name: 'dfpsfsmin001'
    skuName: 'Standard_B2s'
    tier: 'Burstable'
    // Non-required parameters
    administratorLogin: 'adminUserName'
    administratorLoginPassword: '<administratorLoginPassword>'
    passwordAuth: 'Enabled' // passwordAuth is required, otherwise the admin login will be rejected.
    geoRedundantBackup: 'Enabled'
    location: '<location>'
  }
}
```

**Comment by AlexanderSehr** [comment]
Hey @josearper , please take a moment to triage this issue if you can 💪
