### ISSUE TITLE
[AVM Module Issue]: PIP zones breaks network connectivity when not using zones.

### ISSUE THREAD

**Issue by drewmacphee** [Azure/bicep-registry-modules#2702]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.5.3

### Description

When trying to create a vm with zone = 0 and an availability set the following error occurs while trying to update an existing publicIP:
"pip has an existing availability zone constraint NoZone and the request has availability zone constraint 1, 2, 3, which do not match. Zones cannot be added/updated/removed once the resource is created. The resource cannot be updated from regional to zonal or vice-versa."

However if a new public ip is used the zone value seems to be incorrectly set to an array [1,2,3] resulting in broken network connectivity on the VM. Manually replacing the public ip fixes the connectivity issues. Exporting the Public IP template shows the odd zone value somehow being set to the full array.  

This looks to stem from lines 64 - 67 of https://github.com/Azure/bicep-registry-modules/blob/avm/res/compute/virtual-machine/0.5.3/avm/res/compute/virtual-machine/modules/nic-configuration.bicep

Zones is optional on public ips and if the zone isn't provided it should not be set. Those lines seem to be setting it to all allowed values.

Sample of the exported template:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "publicIPAddresses_vmname_pip_name": {
            "defaultValue": "vnamne-pip",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Network/publicIPAddresses",
            "apiVersion": "2023-11-01",
            "name": "[parameters('publicIPAddresses_vmname_pip_name')]",
            "location": "eastus",
            "sku": {
                "name": "Standard",
                "tier": "Regional"
            },
            "zones": [
                "1",
                "2",
                "3"
            ],
            "properties": {
                "ipAddress": "1.1.1.1",
                "publicIPAddressVersion": "IPv4",
                "publicIPAllocationMethod": "Static",
                "idleTimeoutInMinutes": 4,
                "dnsSettings": {
                    "domainNameLabel": "vmname",
                    "fqdn": "vmname.eastus.cloudapp.azure.com"
                },
                "ipTags": [],
                "ddosSettings": {
                    "protectionMode": "VirtualNetworkInherited"
                }
            }
        }
    ]
}
```

**Comment by rahalan** [comment]
@drewmacphee thank you. I will look into it

**Comment by drewmacphee** [comment]
@rahalan While I was looking for a workaround I've also noticed that you can't provide an existing PublicIP.
Providing publicIPAddressResourceId ignores it, since we're no longer providing pipConfiguration. 

        publicIPAddressResourceId: contains(ipConfiguration, 'pipConfiguration')
          ? resourceId(
              'Microsoft.Network/publicIPAddresses',
              contains(ipConfiguration.pipConfiguration, 'name')
                ? ipConfiguration.pipConfiguration.name
                : '${virtualMachineName}${ipConfiguration.pipConfiguration.publicIpNameSuffix}'
            )
          : null

While you're in there maybe it would be a good to have it so providing publicIPAddressResourceId directly ignores pipConfiguration and uses whatever pip you've created elsewhere.

Thanks!

**Comment by rahalan** [comment]
@drewmacphee PR #3336 will add the possibility to use existing PIPs. Regarding the zones, you can always override it, just specify zones: [] if you do not want zone redundancy.
