### ISSUE TITLE
[AVM Module Issue]: Make privateDnsZoneConfigs names configurable

### ISSUE THREAD

**Issue by cecheta** [Azure/bicep-registry-modules#2717]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/private-endpoint

### (Optional) Module Version

0.4.3

### Description

As part of https://github.com/Azure/Azure-Verified-Modules/issues/1150, the private DNS zone config names require a specific name, different to the one supplied by the module, otherwise AI studio does not work correctly. The names should be configurable.

**Comment by cecheta** [comment]
Attempted to implement this in #2718 , keeping it backwards-compatible

**Comment by segraef** [comment]
Will be closed by #2718.
