### ISSUE TITLE
[Module Proposal]: Azure Event Hubs

### ISSUE THREAD

**Issue by sumit-salunke** [Azure/bicep-registry-modules#272]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

we require a base module for manage azure event clusters, event hub namespace and event hubs and one is not currently available in the public registry. 

### Module path

data/event-hub

### Describe the module

This module will allow for provisioning and management of Azure event hub, in line with a similar experience as using azure portal/cli.

If there is a recommendation for a more relevant module path, Please let me know

**Comment by Gordonby** [comment]
dupe of #246 ?

**Comment by sumit-salunke** [comment]
Closing it as https://github.com/Azure/bicep-registry-modules/issues/246 already approved
