### ISSUE TITLE
[AVM Module Issue]: ACA should allow pulling secrets from keyvault in addition to providing them directly

### ISSUE THREAD

**Issue by mosabami** [Azure/bicep-registry-modules#2721]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/container-app

### Description

ACA bicep module allows user to pull secrets for ACA from keyvault as opposed to providing it as text in the Bicep module directly. This AVM only allows the latter. we need it to also allow the former. You can find here the base bicep resource allows it here:
https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-bicep#secret where the secret can be pulled from keyvault by providing the keyvault url

**Comment by oZakari** [comment]
As discussed over teams, will complete by early August at the latest.
