### ISSUE TITLE
[AVM Module Issue]: `avm/res/databricks/workspace` Firewall support for workspace storage account

### ISSUE THREAD

**Issue by donheerschap** [Azure/bicep-registry-modules#2753]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/databricks/workspace

### Description

When having Databricks in an isolated workload where policies disable public access to resources it will break databricks because the workspace storage account is created default with public access.

According to these docs, [firewall support](https://learn.microsoft.com/en-us/azure/databricks/security/network/storage/firewall-support#serverless) & [serverless private link](https://learn.microsoft.com/en-us/azure/databricks/security/network/serverless-network-security/serverless-private-link), this is possible in the 2024-05-01 API with `defaultStorageFirewall: 'Enabled'`

**Comment by donheerschap** [comment]
@clintgrove I believe I already have a working example, I can fit the required properties and resources this weekend. I suggest the private endpoints for the workspace storage account are created from this module aswell.

**Comment by clintgrove** [comment]
Can I assume that you are going offer your idea up and raise a PR or would you like us to investigate to see if this is something we should add if needed?

**Comment by donheerschap** [comment]
@clintgrove I will raise a pr.
