### ISSUE TITLE
[AVM Module Issue]: Configure App Service Logs (sites/config Config-Logs)

### ISSUE THREAD

**Issue by corey-stidston** [Azure/bicep-registry-modules#2765]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### Description

Please expose parameters to configure App service logging on an App service. Here is the relevant documentation - [Microsoft.Web sites/config 'logs'](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-logs?pivots=deployment-language-bicep#enabledconfig). Thank you 😄

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy, please triage the issue when you have a moment 💪

**Comment by tsc-buddy** [comment]
Hey There - You should be able to do this via _logsConfiguration_ parameter. This was added in the most recent version of the module.
