### ISSUE TITLE
[Module Proposal]: Unreal Cloud DDC

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#277]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Make it easier for Game Developers to deploy the set of resources required to run Unreal Cloud DDC on Azure.

### Module path

azure-gaming/unreal-cloud-ddc

### Describe the module

This uses AKS, CosmosDB, and Azure Storage to host the DDC assets of a developer in the cloud which can be used by other members of the game studio.

**Comment by dciborow** [comment]
https://github.com/Azure/bicep-registry-modules/pull/276

**Comment by ChrisSidebotham** [comment]
Dear @dciborow , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
