### ISSUE TITLE
[AVM Module Issue]: Missing Traffic Selector Policies

### ISSUE THREAD

**Issue by marshalexander99** [Azure/bicep-registry-modules#2791]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/connection

### (Optional) Module Version

0.1.2

### Description

Despite the flag being available for usePolicyBasedTrafficSelectors there is no option to configure the traffic selectors in the module

**Comment by rahalan** [comment]
**@marshalexander99, thanks for submitting this issue for the `avm/res/network/connection` module!**

> [!IMPORTANT]
> A member of the @Azure/avm-res-network-connection-module-owners-bicep or @Azure/avm-res-network-connection-module-contributors-bicep team will review it soon!

**Comment by AlexanderSehr** [comment]
Hey @fabmas, please triage the issue when you have a moment 💪

**Comment by fabmas** [comment]
The property TrafficSelectoryPolicies has been added to the module and the corresponding PR is the following: #3057
