### ISSUE TITLE
[AVM Module Issue]: resource-group omits `managedBy` which makes migrating to AVM impossible

### ISSUE THREAD

**Issue by snelis** [Azure/bicep-registry-modules#2795]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/resources/resource-group

### (Optional) Module Version

0.2.4 (latest)

### Description

The module identifies that the managedBy propery is immutable, yet it does not make it configurable.

`// managedBy: managedBy // removed due to immutable string, only used for managed resource groups`

Since CARML used to set it to an empty string by default, you end up with the property:

`"managedBy": "",`

AVM then tries to deploy without this property and you get this error:

`The managed by property of the resource group cannot be changed from its current value ''`

Can we make this configurable so i can configure it to an empty string?

**Comment by segraef** [comment]
Hi @snelis thanks for bringing this up, have you thought about raising a PR for this?

**Comment by snelis** [comment]
Yes, but have not found time to look into this further, for now i stuck with CARML to avoid being blocked.

**Comment by segraef** [comment]
I'd like to understand your use case in a bit more detail. The reason we removed the `managedBy` parameter is because it's only used by managed resource groups. See correspondence https://github.com/Azure/ResourceModules/pull/4351#issuecomment-1849515975.

**Comment by snelis** [comment]
We come from the CARML, they transition into AVM.

The latest tag that was in use is 0.11.1 which is here
https://github.com/Azure/ResourceModules/blob/v0.11.1/modules/resources/resource-group/main.bicep

This tag deploys resource groups *with* the `managedBy` property.
It must be a string in that module, and default is `''`

Therefore we now have resourcegroups with this property already in place (as an empty string).
So when i use the new AVM module that does not implement this property at all, i get this error from ARM.
> The managed by property of the resource group cannot be changed from its current value ''

So this makes me unable to transition this module from CARML into AVM because they are incompatible with each other.

**Comment by segraef** [comment]
@snelis, just fyi I have this on my backlog.

**Comment by segraef** [comment]
@snelis did you try using the resource group resource and setting the `managedBy` parameter?

**Comment by segraef** [comment]
Since the parameter was removed due to the decision of immutable string issues in CARML and before moving into AVM, we are not going to reintroduce the parameter again. We recommend using the generic [resource group](https://learn.microsoft.com/en-us/azure/templates/microsoft.resources/resourcegroups?pivots=deployment-language-bicep) resource and setting the `managedBy` parameter or reference an [existing resource group](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/existing-resource) to enable you to transition to AVM.

**Comment by snelis** [comment]
It's immutable, so yes i can use the generic resource group to maintain it's current value, but i wont be able to transition into AVM.
I will have to keep using this generic resource group instead forever.
Not a big problem.

**Comment by Grant-Rc** [comment]
Hello all,

After logging the same issue I found this as a closed issue, 

 https://github.com/Azure/ResourceModules/issues/4555 

We have just transitioned to AVM for all our code and in testing phase, If nothing is to change is the only solution to use resource deployment in the root bicep or a custom module?
