### ISSUE TITLE
[Module Proposal]: Azure Image Builder

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#280]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

The [Azure Image Builder](https://learn.microsoft.com/en-us/azure/virtual-machines/image-builder-overview?tabs=azure-powershell) service facilitates customised VM image creation for storage in an [Azure Compute Gallery](https://learn.microsoft.com/en-us/azure/virtual-machines/azure-compute-gallery).
It's quite obtuse to use, and we can make it much easier by building on top of Azure Marketplace images and running the VM Build for the user.

Azure Image Builder and the Compute Gallery are leveraged by a wide varierty of Azure Services like VM's, Azure Virtual Desktop, Azure Dev Box, Windows 365 etc.

The intent would be to included in the GitHub directory powershell Chocolately scripts that could be used to represent common personas;
1. Azure Developer
2. Cloud Native Developer
3. etc

### Module path

image-builder/windows

### Describe the module

It will be a productionised version of this bicep file https://github.com/Gordonby/Devcenter/blob/ade/bicep/aib.bicep

It will accept parameters to take ;
- Azure Marketplace base image reference (eg. Windows 11 or Windows Server 2022)
- An array of powershell script references to apply to the image
- An existing Azure Compute Gallery
- New image name details
- Optional flag to create role assignments needed for use by [Azure Dev Box](https://azure.microsoft.com/en-us/products/dev-box/)

After a definition has been created, DeploymentScripts will be used to start the build process.

**Comment by ChrisSidebotham** [comment]
Dear @Gordonby , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, module proposals for new, non-AVM modules will no longer be accepted and we encourage you to propose a new AVM module, which you can file here: Module Proposal, [here](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
