### ISSUE TITLE
[Module Collection]: Dedicated Azure Resource Bicep Modules

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#281]
### Module Collection

This collects the work for the various dedicated resource modules proposed.

- [x] #235 
  - [x] #254
- [x] #244
  - [x] #252 
- [x] #245 
  - [x] #253 
- [x] #246 
  - [ ] #296 
- [x] #247
  - [x]  #251 
- [x] #248
- [x] #250 
- [x] #259 
  - [x] #267 
  - [ ] #310 
- [x] #260 
- [x] #287 
  - [ ] #308 
- [x] #302 
  - [ ] #309 
- [x] #306

**Comment by ChrisSidebotham** [comment]
Closing this as partially completed/stale
