### ISSUE TITLE
[AVM Module Issue]: db-for-postgre-sql/flexible-server missing properties (autoGrow, iops ...) in storage configuration

### ISSUE THREAD

**Issue by MichielVanHerreweghe** [Azure/bicep-registry-modules#2839]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/db-for-postgre-sql/flexible-server

### Description

At this point in time it is not possible to configure the storage properties (autoGrow, iops, throughput, tier and type). This is possible as seen in the Microsoft Bicep resource documentation (https://learn.microsoft.com/en-us/azure/templates/microsoft.dbforpostgresql/flexibleservers?pivots=deployment-language-bicep)

**Comment by AlexanderSehr** [comment]
Hey @josearper, could you please take a look and triage the issue? :) 
Sounds relatively straight forward to me

**Comment by arnoldna** [comment]
@MichielVanHerreweghe - Thanks for opening this issue. With Azure Verified Modules we have specifications around our use of preview features. https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-sfr1---category-composition---preview-services

There have been two "preview" versions of the API released in 2023. As I dove into the documentation, I noticed that Premium SSD v2 is still in preview (https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-storage#premium-ssd-v2-throughput). This makes me a little cautious in implementing all of the "storage" options outlined in the API at this time. I would like to have a conversation with the product group to see if I can get a sense of it/when they are going to move from the preview version to something more permanent.

**Comment by arnoldna** [comment]
After conversing with the product group I am going to hold off on adding any storage related preview features to the module until the new features become GA. Currently, the preview features do not support high availability. It is estimated that support will come in the beginning of 2025.
