### ISSUE TITLE
Fix module table refresh pipeline

### ISSUE THREAD

**Issue by shenglol** [Azure/bicep-registry-modules#284]
The module table refresh workflow doesn't work anymore because of the company wise policy blocking PRs from being created by GitHub actions. We may need to use a GitHub pages site to show the module table and enable auto re-publish when the main branch is updated.

**Comment by dciborow** [comment]
@shenglol , i think we could fix this by using a PAT with the specific permissions instead of the GITHUB_TOKEN. Looks like I am going to want that PAT to get the shell script static analysis working well too, so maybe we are stacking up enough reasons to go forward with it now?

**Comment by shenglol** [comment]
Done via https://github.com/Azure/bicep-registry-modules/pull/311.
