### ISSUE TITLE
[AVM Module Issue]: Support autorotation for customer managed key in storage account

### ISSUE THREAD

**Issue by thasimongyldendal** [Azure/bicep-registry-modules#2842]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/storage/storage-account

### Description

Currently if specifying a customer managed key it defaults to an explicit version (either specified in the AVM-module or using latest if not specified). From [/res/storage/storage-account/main.bicep](https://github.com/Azure/bicep-registry-modules/blob/89d0d1cd823161ee7b21bd9ab29b8bd9d94e7a3d/avm/res/storage/storage-account/main.bicep#L365) 
```bicep
  keyvaultproperties: !empty(customerManagedKey)
          ? {
              keyname: customerManagedKey!.keyName
              keyvaulturi: cMKKeyVault.properties.vaultUri
              keyversion: !empty(customerManagedKey.?keyVersion ?? '')
                ? customerManagedKey!.keyVersion
                : last(split(cMKKeyVault::cMKKey.properties.keyUriWithVersion, '/'))
            }
          : null
```

This leads to autorotation of the encryption key being disabled on the created storage account: 
![image](https://github.com/user-attachments/assets/40fd2e4f-91cd-46bd-b3d1-65fea8537acd)

It should be possible to not specify the keyversion to have automated key rotation work as desired. I believe when you use the resource directly and don't specify a keyversion automated rotation is supported.

**Comment by AlexanderSehr** [comment]
Hey @thasimongyldendal,
thanks for raising this issue. Have you been able to confirm that autorotation is enabled when not specifying a version? If so, we should update the AVM spec and update this as well as other modules to allow users to specify that they want auto-rotation enabled (e.g., by specifying as such in the interface / as a value).

**Comment by thasimongyldendal** [comment]
Hello @AlexanderSehr
I have confirmed that not specifying a keyversion gives you automatic key rotation.

I used this bicep code to confirm it: 
```bicep
resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  kind: 'StorageV2'
  name: name
  location: resourceGroup().location
  sku: {
    name: sku
  }
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentity.id}' : {}
    }
  }
  properties: {
    encryption: {
      keyvaultproperties: { //Here I did not set the keyversion property
        keyname: keyName
        keyvaulturi: keyVaultUri 
      }
      identity: {
        userAssignedIdentity: managedIdentity.id
      }
      keySource: 'Microsoft.Keyvault'
    }
  }
}
```

And the result in the portal: 
![image](https://github.com/user-attachments/assets/c06bc4b2-219f-4c2c-9c2e-6be549b827ff)

**Comment by AlexanderSehr** [comment]
I'll see to create a PR once the new RBAC schema was roled out to the storage account module via #2008 to avoid conflicts

**Comment by AlexanderSehr** [comment]
> Is there any updates on this? We've just spotted this issue and need to make a decision on whether to move to a custom module for storage accounts depending on time scales.

Hey @Dekor86,
I took a closer look just recently. As this may have an impact on the spec (which in turn would affect all modules with CMK) I want to have collect the feedback from the core team before going ahead and changing the implementation. 
The alternatives would be to either
- Remove the KeyVersion autofetch completely, leaving it up to the module owner to either require that parameter (if it is required by the Resource Provider), or to default to `null` (as asked for above)
- Or to add another boolean switch that enables/disables the functionality that would automatically fetch the latest version at deployment time for the user

There's a call happening this Thursday that I hope will bring a decision after which we can then go ahead and implement the change. It may take until next week to release the update though.

**Comment by AlexanderSehr** [comment]
The decision is unfortunately still pending as we did not come to an agreement yet and are still discussing how to fix the issue

**Comment by AlexanderSehr** [comment]
Closing as per #3853
