### ISSUE TITLE
[AVM Module Issue]: avm/res/compute/virtual-machine AMA support

### ISSUE THREAD

**Issue by jikuja** [Azure/bicep-registry-modules#2843]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine

### Description

Current virtual machine resource template MMA support is implemented by changing extension name, publisher and type properties. This approach is missing:

* Data Collection Rules(DCR)
* Data Collection Rule association(DCRA)

Also current implementation is setting workspaceKey as protectedSettings even LAW linkage is done by DCR.

Template documentation does not mention anything about DCRs and DCRAs.

# The Fix

* Resource template should not use inputs that are for legacy MMA extension
* It should be possible to pass multiple DCRA configuration as parameters

# Security

I was wondering if this should be security-typed issue because falase sense of security...

**Comment by jikuja** [comment]
Misleading change happened ealier on ResourceModules -repository: https://github.com/Azure/ResourceModules/pull/3938/files#diff-ea64a3e8858890c0add5dac6bdb2ae82d6a78761b4db0e231a84f632d30cb153L571-L585

**Comment by rahalan** [comment]
@jikuja thanks for bringing it up. I will investigate.

**Comment by rahalan** [comment]
@jikuja will be fixed in PR #3116
