### ISSUE TITLE
[AVM Module Issue]: VNET peering not following WAF-naming

### ISSUE THREAD

**Issue by john-fox-maule** [Azure/bicep-registry-modules#2860]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/network/virtual-network

### (Optional) Module Version

0.1.8

### Description

Naming of peerings is not following recommend abbreviations according to https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations#networking recommend abbreviation is **peer** 

![peer](https://github.com/user-attachments/assets/d0f102ae-8dad-432a-9c11-60ca91b03767)
![actual peers](https://github.com/user-attachments/assets/b85865bc-414d-413c-809b-5044bb80adfd)
![main](https://github.com/user-attachments/assets/307d0592-c568-4e8c-99ab-bdc53b382ed5)

**Comment by AlexanderSehr** [comment]
Hey @john-fox-maule,
I guess the best would be to add the `peer-` prefix to the existing name? E.g. `peer-vnet1-vnet2` & `peer-vnet2-vnet1`
Subjectively, I think it's nice to be able to see from where to where the peering is pointing to.

**Comment by john-fox-maule** [comment]
Hey
Yes the peer- should be a prefix in my opinion, however i dont see the point in having the local vnet name listed first it wil always be the same (from where), if you look in the portal you always have the local vnet name, if you list all via scripting it is easy to combine anyway.

**Comment by AlexanderSehr** [comment]
> Hey Yes the peer- should be a prefix in my opinion, however i dont see the point in having the local vnet name listed first it wil always be the same (from where), if you look in the portal you always have the local vnet name, if you list all via scripting it is easy to combine anyway.

Fair point. I was more thinking along the lines of an error message (e.g., via a policy violation) related to the peering where I would not have the VNET name in front of me. But it's a detail. :)
