### ISSUE TITLE
[AVM Module Issue]: avm/res/insights/data-collection rule does not support AgentSettings DCR

### ISSUE THREAD

**Issue by jikuja** [Azure/bicep-registry-modules#2864]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/insights/data-collection-rule

### Description

avm/res/insights/data-collection module does not support [AgentSettings DCR](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-manage?tabs=azure-resource-manager#configure)

To support this existing paramters must be changed and property should be created conditionally => complicated.

**Comment by krbar** [comment]
@jikuja thanks for reporting, I will look into it.
