### ISSUE TITLE
[Module Proposal]: Azure Data Explorer Clusters [Kusto/clusters]

### ISSUE THREAD

**Issue by vlahane** [Azure/bicep-registry-modules#287]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We require a base module for managing KustoClusters and one is not currently available in the public registry. It will follow the concept of existing modules in bicep-registry-modules repo.

We will be needing this bicep module to provision Kusto Clusters.

### Module path

storage/data-explorer

### Describe the module

This module will allow for provisioning and management of KustoClusters (Azure Data Explorer Clusters), in line with a similar experience as using Azure Portal/CLI. Including support for Private endpoint, Diagnostic Settings,etc

module name we can also make as `data-analytics/data-explorer-clusters ` let's me know if any suggestions for module path.

**Comment by dciborow** [comment]
for module path, how about 'storage/data-explorer'?

Here is the output from my prototype GPT model based on the issue.

### main.bicep
```bicep
@description('Deployment Location')
param location string

@description('Name of the Kusto Cluster. Must be unique within Azure.')
param name string = 'kusto${uniqueString(resourceGroup().id, subscription().id)}'

@description('The SKU of the Kusto Cluster.')
param sku string = 'Dev(No SLA)_Standard_D11_v2'

@description('The number of nodes in the Kusto Cluster.')
param numberOfNodes int = 1

@description('The version of the Kusto Cluster.')
param version string = 'latest'

@description('The tags of the Kusto Cluster.')
param tags object = {}

resource kustoCluster 'Microsoft.Kusto/clusters@2020-02-15' = {
  name: name
  location: location
  sku: {
    name: sku
  }
  properties: {
    numberOfNodes: numberOfNodes
    version: version
    tags: tags
  }
}

@description('The ID of the created or existing Kusto Cluster. Use this ID to reference the Kusto Cluster in other Azure resource deployments.')
output id string = kustoCluster.id
```


### Summary
This Bicep module creates a Kusto Cluster with the specified number of nodes and version.

### Description
Azure Data Explorer is a fast, fully managed data analytics service for real-time analysis on large volumes of data streaming from applications, websites, IoT devices, and more. Azure Data Explorer clusters are the fundamental resource in Azure Data Explorer. A cluster is a collection of compute resources that host databases and tables.

This Bicep module allows users to create or use existing Kusto Clusters with options to control the number of nodes and version. The output of the module is the ID of the created or existing Kusto Cluster, which can be used in other Azure resource deployments.

### Examples
#### Example 1
This example creates a new Kusto Cluster with a unique name in the East US region using the default Kusto Cluster configuration settings. The module output is the ID of the created Kusto Cluster, which can be used in other Azure resource deployments.
```bicep
module kustoCluster 'br/public:data-analytics/kusto-clusters:0.0.1' = {
  name: 'mykustocluster'
  params: {
    location: 'eastus'
  }
}

output kustoClusterID string = kustoCluster.outputs.id
```
#### Example 2
This example creates a new Kusto Cluster with the name "mykustocluster" in the "myresourcegroup" resource group located in the East US region. The Kusto Cluster is configured to use a specific version and number of nodes. The module output is the ID of the created or existing Kusto Cluster, which can be used in other Azure resource deployments.
```bicep
param location string = 'eastus'
param name string = 'mykustocluster'
param newOrExisting string = 'new'
param resourceGroupName string = 'myresourcegroup'
param version string = 'latest'
param numberOfNodes int = 1

module kustoCluster 'br/public:data-analytics/kusto-clusters:0.0.1' = {
  name: 'mykustocluster'
  params: {
    location: location
    name: name
    newOrExisting: newOrExisting
    resourceGroupName: resourceGroupName
    version: version
    numberOfNodes: numberOfNodes
  }
}

output kustoClusterID string = kustoCluster.outputs.id
```

### test.bicep
```bicep
/*
Write deployment tests in this file. Any module that references the main
module file is a deployment test. Make sure at least one test is added.
*/

param location string = resourceGroup().location

//Prerequisites
// module prereq 'prereq.test.bicep' = {
//   name: 'test-prereqs'
//   params: {
//     location: location
//   }
// }

//Test 0. 
module test0 '../main.bicep' = {
  name: 'test0'
  params: {
    location: location
  }
}
```

**Comment by shenglol** [comment]
On second thought, what about changing the path to `data/data-explorer`? `storage` makes me think that it's related to `Microsoft.Storage`.

**Comment by vlahane** [comment]
should we go with `kusto/data-explorer` ?

**Comment by shenglol** [comment]
Actually `kusto` might be even better since that matches the RP name. @dciborow thoughts?

**Comment by vlahane** [comment]
@shenglol  should we also plan for other module to move to their respective RP groups like `compute/container-registry` rename it to `container-registry/registry` or `container-registry/acr` ?

**Comment by vlahane** [comment]
Hi @shenglol  @dciborow  Should we follow below naming for all of our module, any thoughts?

https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations

Syntax:
```
category + abbreviation
```
Example:

|Resource | Old Path|  New Path|
| --------- | -------- | ------- |
| Container registry | compute/container-registry  | containers/cr    |
| Azure Data Explorer cluster | storage/data-explorer | analytic-iot/dec     |
| Virtual network | network/virtual-network    | networking/vnet    |
| Availability set | compute/availability-set |	compute-web/avail |
| Function app | compute/function-app |	compute-web/func |

**Comment by alex-frankel** [comment]
Renaming modules is a breaking change, so I would prefer we keep the existing convention for now. `compute` is meant to be a category for all variety of computing services including resources like ACI or Functions.

**Comment by shenglol** [comment]
We never had an official discussion about the naming convention the module groups, but after reading @alex-frankel's [comment in the Cosmos DB module PR](https://github.com/Azure/bicep-registry-modules/pull/251#issuecomment-1502185799), I start to realize that it makes sense to let module group names be at a higher level of abstraction and match the industry standard terms people use when dealing with cloud architecture. I'll make sure to document that in CONTRIBUTE.md and the issue template. I think we can keep the group name `storage` for this module.

Regarding changing group names for existing modules, like @alex-frankel said, it should be avoided because it's a breaking change, plus the fact that we don't have a way to mark modules as deprecated.

**Comment by alex-frankel** [comment]
>plus the fact that we don't have a way to mark modules as deprecated.

Related to https://github.com/Azure/bicep/issues/3505

**Comment by vlahane** [comment]
looks like OCI spec don't supporting yet, proposal still open  "OCI Image Deprecation: vendor support." 
`https://github.com/opencontainers/image-spec/pull/903`
