### ISSUE TITLE
[AVM Module Issue]: Construct event hub(s) app settings for `avm/res/web/site`

### ISSUE THREAD

**Issue by donheerschap** [Azure/bicep-registry-modules#2870]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### Description

When wanting to use event hub bindings app settings need to be created for the event hub. As you can't pass calculated properties to a module it needs to be constructed inside the module (similar to azureWebJobsValues and appInsights)

Acceptance:

- Can pass 1 or more event hub resource IDs
- Constructs the connection string for app settings
- Can determine to use identity authentication instead of connection string for each event hub (similar to azurewebjobsstorage see [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-python#identity-based-connections)

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy, please triage when you get the chance :)

**Comment by tsc-buddy** [comment]
Hey @donheerschap thanks for logging this. I've just got back from vacation so will triage and look into this some more WC 12/8

**Comment by pankajagrawal16** [comment]
Hi @donheerschap 

I was looking at this issue, wont it be possible to pass and set event hub related app settings via `appSettingsKeyValuePairs` parameter from the module ? Or am i missing something here ?

 I am but unsure about the part where you wrote:
> As you can't pass calculated properties to a module it needs to be constructed inside the module
