### ISSUE TITLE
[AVM Module Issue]: Allow standalone deployment of access policies

### ISSUE THREAD

**Issue by stewartadam** [Azure/bicep-registry-modules#2899]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/key-vault/vault

### Description

Key Vault module supports creation of access policies at creation time, but there should also be a way to create access policies standalone.

One example would be a App Service that needs to read secrets from Key Vault via environment variables using Managed Identity -- we have to create the key vault and app service first, then the access policy tying the two together separately once both exist.

**Comment by AlexanderSehr** [comment]
Hey @stewartadam,
a fair ask, and very true for so many resources. 
That being said, the currently structure of AVM does not cater to this feature as a standalone top-level module. Instead, the direction this is going is torward publishing child-modules alongside their parents as we used to in CARML. 

This has actually been requested a few times as you can see here
- https://github.com/Azure/bicep-registry-modules/issues/1390
- https://github.com/Azure/bicep-registry-modules/issues/1933
- https://github.com/Azure/Azure-Verified-Modules/issues/578
- https://github.com/Azure/Azure-Verified-Modules/issues/747

I'll say again that this is a valid ask and I really hope we'll be manage to work around the background processes that currently prevent us from implementing this feature. But for the time being, I'll close this as a duplicate of the above.

However - if you disagree, of course feel free to re-open the issue 💪

**Comment by stewartadam** [comment]
@AlexanderSehr thanks for the details and sharing the current prioritization. All those issues are closed however - how are we tracking progress towards this ask? Particularly since, as you mention, many users are facing it.

**Comment by AlexanderSehr** [comment]
Hey @stewartadam, we do track it as an item on an internal ADO that contains a range of tasks for the CI. However, I for transparency reasons, we should probably also have an item here in GitHub... I'll add it to my todo list
