### ISSUE TITLE
[Bug Report]: Feature request: deployment script, create KV certificate -> set validity

### ISSUE THREAD

**Issue by charlyinalbon** [Azure/bicep-registry-modules#297]
### Module path

/modules/deployment-scripts/create-kv-certificate

### Bicep version

3.0 (of the module)

### Describe the bug

This is no bug, but a feature request.
With Azure CLI one can specify the validity of the certificate: https://learn.microsoft.com/en-us/cli/azure/keyvault/certificate?view=azure-cli-latest#az-keyvault-certificate-create 

--validity: Number of months the certificate is valid for. Overrides the value specified with --policy/-p.

However, with this module this is not possible. It just takes the default value of 12 months. 

The feature request is to add the validity as parameter to the module.

### To reproduce

It is a feature request.

### Code snippet

```Bicep
-
```

### Relevant log output

```Shell
-
```

**Comment by dciborow** [comment]
Looks like this was easy. Will look to have this merged in once we get our PR tests back up and running.
