### ISSUE TITLE
[AVM Module Issue]: Search service publicNetworkAccess value casing is inconsistent with other modules

### ISSUE THREAD

**Issue by stewartadam** [Azure/bicep-registry-modules#2984]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/search/search-service

### Description

The key `publicNetworkAccess` is used on many Azure services and most other AVM modules are standardizing around CamelCase values `Enabled` or `Disabled`, but this module is inconsistent and requires `enabled` or `disabled`.

**Comment by krbar** [comment]
Hi @stewartadam, after consultation with the core team, we will align this with the other modules.
