### ISSUE TITLE
[AVM Module Issue]: avm/res/network/front-door-web-application-firewall-policy old API version and missing types

### ISSUE THREAD

**Issue by anderseide** [Azure/bicep-registry-modules#2988]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/front-door-web-application-firewall-policy

### Description

The API version for avm/res/network/front-door-web-application-firewall-policy is old, resulting in deployment error when configuring setting the javascriptChallengeExpirationInMinutes policy setting.

**Comment by AlexanderSehr** [comment]
Hey @PaulJohnston88,
it has been a while. Could you please triage the issue and give a rough estimate when you may or may not be able to address it? 💪 
To triage the issue, you either close it (if it does not make sense to you), or you remove the 'Needs Triage' & 'Reponse' labels and add a commment 🚀
