### ISSUE TITLE
[AVM Module Issue]: web/site is missing option for container app environment

### ISSUE THREAD

**Issue by jhueppauff** [Azure/bicep-registry-modules#3012]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### Description

Hi, 

for function apps running in container apps environment the module is missing the option to specify the kind : "functionapp,linux,container,azurecontainerapps" and to specify managedEnvironmentId instead of serverFarmResourceId

```
resource functionApp 'Microsoft.Web/sites@2023-12-01' = {
  name: functionName
  location: location
  kind: 'functionapp,linux,container,azurecontainerapps'
  properties: {
    managedEnvironmentId: containerAppEnvironment.outputs.resourceId
    siteConfig: {
      linuxFxVersion: 'DOCKER|mcr.microsoft.com/azure-functions/dotnet8-quickstart-demo:1.0'
      appSettings: [
        {
          name: 'FUNCTIONS_EXTENSION_VERSION'
          value: '~4'
        }
        {
          name: 'AzureWebJobsStorage'
          value: 'DefaultEndpointsProtocol=https;AccountName=${functionStorageName};EndpointSuffix=core.windows.net'
        }
      ]
    }
  }
}
```

**Comment by tsc-buddy** [comment]
Hey @jhueppauff  - thanks for logging this. We shall triage it WC 12/08.

**Comment by pankajagrawal16** [comment]
@jhueppauff this should be available now. Give it a try

**Comment by pankajagrawal16** [comment]
@jhueppauff Just following up if you managed to try it out ?

**Comment by tsc-buddy** [comment]
Closing this following the release of the feature. :) thanks all.
