### ISSUE TITLE
[Module Proposal]: Azure Database for PostgreSQL - Single Server

### ISSUE THREAD

**Issue by OmegaVVeapon** [Azure/bicep-registry-modules#302]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

While we are aware that Postgresql Single Server is currently [on the retirement path](https://learn.microsoft.com/en-us/azure/postgresql/single-server/whats-happening-to-postgresql-single-server), Postgresql Flexible Server currently has no support for Private Endpoints which is a requirement for us.

Therefore, we'll need a Bicep module for this.

### Module path

database/postgresql-single-server

### Describe the module

This module will allow to create [PostgreSQL Single Server ](https://learn.microsoft.com/en-us/azure/postgresql/single-server/overview-single-server) resource.

**Comment by dciborow** [comment]
I grabbed this issue to test out an Open AI GPT-3 model I have been tuning to help with Bicep. Here is what the engine has proposed to help get started with this module.


### main.bicep
```bicep
@description('Deployment Location')
param location string

@description('Name of the PostgreSQL Server. Must be unique within Azure.')
param name string = 'ps${uniqueString(resourceGroup().id, subscription().id)}'

@description('ID of the subnet where the PostgreSQL Server will be deployed, if virtual network access is enabled.')
param subnetID string = ''

@description('Toggle to enable or disable virtual network access for the PostgreSQL Server.')
param enableVNET bool = false

@description('Toggle to enable or disable zone redundancy for the PostgreSQL Server.')
param isZoneRedundant bool = false

@description('PostgreSQL Server Version. Use "9.6" for PostgreSQL 9.6 and "10" for PostgreSQL 10.')
param version string = '9.6'

var networkAcls = enableVNET ? {
  defaultAction: 'Deny'
  virtualNetworkRules: [{ id: subnetID }]
} : {}

resource postgresqlServer 'Microsoft.DBforPostgreSQL/servers@2017-12-01' = {
  name: name
  location: location
  sku: {
    name: version == '9.6' ? 'B_Gen5_2' : 'B_Gen5_4'
    tier: version == '9.6' ? 'Basic' : 'Basic_G5'
    capacity: 1
  }
  properties: {
    administratorLogin: 'admin'
    administratorLoginPassword: password()
    sslEnforcement: true,
    publicNetworkAccessEnabled: false,
    enableAutomaticFailover: false,
    isZoneRedundant: isZoneRedundant,
    networkAcls: networkAcls,
  }
}

@description('The ID of the created or existing PostgreSQL Server. Use this ID to reference the PostgreSQL Server in other Azure resource deployments.')
output id string = postgresqlServer.id
```
### Summary
This Bicep module creates a PostgreSQL Server with zone-redundancy, virtual network access, and TLS version.

### Description
PostgreSQL is a powerful, open source object-relational database system that is designed to be highly available and scalable.
It is a fully managed service that provides high availability and disaster recovery capabilities for databases.
PostgreSQL is designed to be highly available and scalable, with high availability and disaster recovery capabilities for databases.

This Bicep module allows users to create or use existing PostgreSQL Server with options to control redundancy, access, and security settings. Zone-redundancy allows data to be stored across multiple Availability Zones, increasing availability and durability. Virtual network rules can be used to restrict or allow network traffic to and from the PostgreSQL Server. Encryption and TLS settings can be configured to ensure data security.

The module supports both PostgreSQL 9.6 and 10, allowing users to choose the version that best suits their needs. The output of the module is the ID of the created or existing PostgreSQL Server, which can be used in other Azure resource deployments.

### Examples
#### Example 1
This example creates a new PostgreSQL Server with a unique name in the East US region using the default PostgreSQL Server configuration settings. The module output is the ID of the created PostgreSQL Server, which can be used in other Azure resource deployments.
```bicep
module postgresqlServer 'br/public:database/postgresql-single-server:0.0.1' = {
  name: 'mypostgresqlserver'
  params: {
    location: 'eastus'
  }
}

output postgresqlServerID string = postgresqlServer.outputs.id
```
#### Example 2
This example creates a new PostgreSQL Server with the name "mypostgresqlserver" in the "myresourcegroup" resource group located in the East US region. The PostgreSQL Server is configured to use zone-redundancy and virtual network access. The module output is the ID of the created or existing PostgreSQL Server, which can be used in other Azure resource deployments.
```bicep
param location string = 'eastus'
param name string = 'mypostgresqlserver'
param newOrExisting string = 'new'
param resourceGroupName string = 'myresourcegroup'
param isZoneRedundant bool = true

module postgresqlServer 'br/public:database/postgresql-single-server:0.0.1' = {
  name: 'mypostgresqlserver'
  params: {
    location: location
    name: name
    newOrExisting: newOrExisting
    resourceGroupName: resourceGroupName
    isZoneRedundant: isZoneRedundant
  }
}

output postgresqlServerID string = postgresqlServer.outputs.id
```

### test.bicep
```bicep
/*
Write deployment tests in this file. Any module that references the main
module file is a deployment test. Make sure at least one test is added.
*/

param location string = resourceGroup().location

//Prerequisites
// module prereq 'prereq.test.bicep' = {
//   name: 'test-prereqs'
//   params: {
//     location: location
//   }
// }

//Test 0. 
module test0 '../main.bicep' = {
  name: 'test0'
  params: {
    location: location
  }
}
```

**Comment by shenglol** [comment]
> While we are aware that Postgresql Single Server is currently [on the retirement path](https://learn.microsoft.com/en-us/azure/postgresql/single-server/whats-happening-to-postgresql-single-server), Postgresql Flexible Server currently has no support for Private Endpoints which is a requirement for us.

@alex-frankel what do you think?

**Comment by dciborow** [comment]
I also found this module I previously created. I'll have a PR up for this one next.

```
@description('Server Name for Azure database for PostgreSQL')
param serverName string = 'psql${uniqueString(resourceGroup().id)}'

@description('Database administrator login name')
@minLength(4)
param administratorLogin string

@description('Database administrator password')
@minLength(8)
@secure()
param administratorLoginPassword string

@description('Azure database for PostgreSQL compute capacity in vCores (2,4,8,16,32)')
param skuCapacity int = 2

@description('Azure database for PostgreSQL sku name ')
param skuName string = 'GP_Gen5_2'

@description('Azure database for PostgreSQL Sku Size ')
param skuSizeMB int = 51200

@description('Azure database for PostgreSQL pricing tier')
param skuTier string = 'GeneralPurpose'

@description('Azure database for PostgreSQL sku family')
param skuFamily string = 'Gen5'

@description('PostgreSQL version')
@allowed([
  '9.5'
  '9.6'
  '10'
  '11'
])
param postgresqlVersion string = '11'

@description('Location for all resources.')
param location string = resourceGroup().location
param tags object = {
  'aia-industry': 'industry'
  'aia-solution': 'solution'
  'aia-version': '0.0'
}

@description('PostgreSQL Server backup retention days')
param backupRetentionDays int = 7

@description('Geo-Redundant Backup setting')
param geoRedundantBackup string = 'Disabled'

@description('Name of the VNet')
param vnetName string = 'vnet${uniqueString(resourceGroup().id)}'

@description('Resource group name of the VNET if using existing one.')
param vnetResourceGroupName string = resourceGroup().id

@description('Name of the subnet')
param subnetName string = 'subnet${uniqueString(resourceGroup().id)}'
param vnetEnable bool = false()

var firewallrules = {
  batch: {
    rules: [
      {
        Name: 'AllowAzureServices'
        StartIpAddress: '0.0.0.0'
        EndIpAddress: '0.0.0.0'
      }
    ]
  }
}

resource serverName_resource 'Microsoft.DBforPostgreSQL/servers@2017-12-01' = {
  tags: tags
  name: serverName
  location: location
  sku: {
    name: skuName
    tier: skuTier
    capacity: skuCapacity
    size: skuSizeMB
    family: skuFamily
  }
  properties: {
    createMode: 'Default'
    version: postgresqlVersion
    administratorLogin: administratorLogin
    administratorLoginPassword: administratorLoginPassword
    storageProfile: {
      storageMB: skuSizeMB
      backupRetentionDays: backupRetentionDays
      geoRedundantBackup: geoRedundantBackup
    }
  }
}

resource serverName_AllowSubnet 'Microsoft.DBforPostgreSQL/servers/virtualNetworkRules@2017-12-01' = if (vnetEnable) {
  parent: serverName_resource
  name: 'AllowSubnet'
  properties: {
    virtualNetworkSubnetId: resourceId(vnetResourceGroupName, 'Microsoft.Network/virtualNetworks/subnets', vnetName, subnetName)
    ignoreMissingVnetServiceEndpoint: true
  }
}

@batchSize(1)
resource serverName_firewallrules_batch_rules_Name 'Microsoft.DBforPostgreSQL/servers/firewallRules@2017-12-01' = [for i in range(0, length(firewallrules.batch.rules)): {
  name: '${serverName}/${firewallrules.batch.rules[i].Name}'
  location: location
  properties: {
    startIpAddress: firewallrules.batch.rules[i].StartIpAddress
    endIpAddress: firewallrules.batch.rules[i].EndIpAddress
  }
  dependsOn: [
    serverName_resource
  ]
}]

output id string = serverName_resource.id

```

**Comment by dciborow** [comment]
> > While we are aware that Postgresql Single Server is currently [on the retirement path](https://learn.microsoft.com/en-us/azure/postgresql/single-server/whats-happening-to-postgresql-single-server), Postgresql Flexible Server currently has no support for Private Endpoints which is a requirement for us.
> 
> @alex-frankel what do you think?

I might have misunderstood the original request. I was going to pull together a tmeplate for PSQL flexible. Having a bicep template for the service won't make a difference if it is retired :-(.

**Comment by alex-frankel** [comment]
@omegavveapon -- do you know when single server is planned to be retired? And do you know when flexible server plans to support private endpoint?

**Comment by OmegaVVeapon** [comment]
> @OmegaVVeapon -- do you know when single server is planned to be retired? And do you know when flexible server plans to support private endpoint?

It's in the linked documentation but I'll gladly put it here.

> Single Server is on the retirement path and is scheduled for retirement by March 28, 2025.

Additionally

> As part of this retirement, we no longer support creating new single server instances from the Azure portal beginning November 30, 2023. If you need to create single server instances to meet business continuity needs, you can continue to use Azure CLI.

Ref: https://learn.microsoft.com/en-us/azure/postgresql/single-server/whats-happening-to-postgresql-single-server

> And do you know when flexible server plans to support private endpoint?

I do not unfortunately. I heard an estimate internal of "sometime in the next 6 months" but I have no source to back that up so take it with a grain of salt. Perhaps someone from the Azure Postgresql team could weigh in on the roadmap?

---

My two cents is that we _should_ have a public Bicep module for Postgresql Single Server and link the documentation above in the `README` as we have a commitment to support it for 2 more years.

We already have an in-house Bicep module for Postgresql Single Server that is field-tested and that we used to stand up the dbs for our environment so I don't expect this to be _too_ much work... just need to productize it for general consumption.

**Comment by shenglol** [comment]
> My two cents is that we should have a public Bicep module for Postgresql Single Server and link the documentation above in the README as we have a commitment to support it for 2 more years.

Agree. 2 years of support seems fine. My only suggestion is to change the module group name to the plural form:

 - `databases/postgresql-single-server`

**Comment by shenglol** [comment]
As discussed in https://github.com/Azure/bicep-registry-modules/pull/251#issuecomment-1502185799, we'll use `storage` as the group name for database and other storage related modules.
