### ISSUE TITLE
[AVM Module Issue]: Search Service module to output Private Endpoint IP(s)

### ISSUE THREAD

**Issue by aheinenwbmi** [Azure/bicep-registry-modules#3022]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/search/search-service

### Description

The private endpoint module outputs the IP address of the private endpoint NIC but the search service module which calls that private endpoint module doesnt output the IP address of the private endpoint NIC. It would be nice to have that output so I can create an A record for that IP address without having to call the private endpoint as an existing resource in my bicep file after the search service deploys.

**Comment by krbar** [comment]
@aheinenwbmi I will add an output `privateEndpoints` with the properties of the private endpoints, which are available as outputs of the `avm/res/network/private-endpoint` module, like: name, resourceId, groupId, customDnsConfig, networkInterfaceIds.
I hope this helps.
