### ISSUE TITLE
[AVM Module Issue]: Key Vault Diagnostic setting in portal doesn't match AVM module

### ISSUE THREAD

**Issue by Gossef** [Azure/bicep-registry-modules#3050]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/key-vault/vault

### (Optional) Module Version

0.7.0

### Description

In the portal, the diagnostic setting categories for Key Vaults are:
* Audit Logs
* Azure Policy Evaluation Details

However, in the AVM module the category "Audit Logs" or "AuditLogs" isn't accepted, as it should be AuditEvent.

This makes it difficult to easily copy these settings to the AVM Module's configuration as the documentation doesn't necessarily list all options either.

**Comment by AlexanderSehr** [comment]
Hey @Gossef,
thank you for the issue. You're raising a good point that we actually tried to address in the preceeding CARML modules. There, we tried to provide up-to-date `@allowed([...])` lists for logs & metrics. When transitioning to AVM we dropped those however.
That begs the question as to 'why?'. And the simple answer is unfortunately maintainability.
For one, these allowed list has always be up to date as it's not allowed to contain wildcards. That means, when we had an allowed list it could only set what's in the allowed ist. However, if the RP added new categories, you would not be able to use them unless the module is updated.
We tried to solve that issue in return with some automation. That is, try to fetch the allowed values from whatever documentation we could find and create an issue (or even an automated PR) to update the list. That, in theory, was great as it would keep that timeframe where something is missing small - but - we never found a reliable source. We experimented with some automation using those 2 urls:
 - https://raw.githubusercontent.com/MicrosoftDocs/azure-docs/main/articles/azure-monitor/essentials/metrics-supported.md
 - https://raw.githubusercontent.com/MicrosoftDocs/azure-docs/main/articles/azure-monitor/essentials/resource-logs-categories.md 
but even those often either had too many or too few categories. And now, both links don't work anymore.

If you happen to know a reliable source to fetch these options from (without the need to have the resource deployed first and then fetch it from the portal), I think we'd have a strong case of adding the feature again. 

Your request makes absolute sense afterall.

I hope the above provided some insights. 💪

**Comment by AlexanderSehr** [comment]
To bring this issue to a close:
I just checked the network trace when setting a diagnostic setting on a key vault:
![Image](https://github.com/user-attachments/assets/4373d92b-2928-4486-9dc3-838956eb4018)
with the payload looking like this
```json
{
    "id": "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/my-rg/providers/Microsoft.KeyVault/vaults/my-vault/providers/microsoft.insights/diagnosticSettings/testSetting",
    "name": "testSetting",
    "properties": {
        "logs": [
            {
                "category": "AuditEvent",
                "categoryGroup": null,
                "enabled": true,
                "retentionPolicy": {
                    "days": 0,
                    "enabled": false
                }
            },
            {
                "category": "AzurePolicyEvaluationDetails",
                "categoryGroup": null,
                "enabled": true,
                "retentionPolicy": {
                    "days": 0,
                    "enabled": false
                }
            }
        ],
        "workspaceId": "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/my-rg/providers/Microsoft.OperationalInsights/workspaces/my-law",
        "logAnalyticsDestinationType": "AzureDiagnostics"
    }
}
```

So it appears the naming you'd need to set when deploying the setting with IaC is
| Display Name | Technical name |
| - | - |
| Audit Logs | AuditEvent |
| Azure Policy Evaluation Details | AzurePolicyEvaluationDetails |

As stated in my earlier comment, I'm not aware of a very reliable source when it comes to these settings - aside the documentation of the corresponding resource provider like [this one](https://learn.microsoft.com/en-us/azure/key-vault/general/monitor-key-vault-reference#supported-resource-logs-for-microsoftkeyvaultvaults).
