### ISSUE TITLE
[AVM Module Issue]: Log Analytics Workspace option only works globally

### ISSUE THREAD

**Issue by Gossef** [Azure/bicep-registry-modules#3051]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/operational-insights/workspace

### (Optional) Module Version

0.4.0

### Description

In order to use the Log Analytics Workspace itself for its own diagnostic settings, you can use this parameter:
useDeployedWorkspaceForDiagnosticSettings

However that sets all diagnostic settings to point to this workspace. In our scenario we write all logs to a storage account and only a small selection (for example metrics) to the Log Analytics Workspace. This is now not possible, since without this setting we cannot reference the workspace itself and with the setting everything goes to the Workspace (as well as the storage account)

**Comment by krbar** [comment]
@Gossef thanks for reporting this. I will discuss it with the team and come up with a fix
