### ISSUE TITLE
[AVM Module Issue]: Public IP in `virtual-network-gateway` module missing properties 

### ISSUE THREAD

**Issue by johnlokerse** [Azure/bicep-registry-modules#3061]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/network/virtual-network-gateway

### (Optional) Module Version

latest

### Description

Currently, I am busy building a platform landing zone using AVM modules. This landing zone requires a virtual network gateway, so I decided to use this AVM module. The module also deploys the necessary Public IP resource, but it is missing properties such as the DNS domain label, which I need.

Although it’s easy to add these properties to the template, we might need to consider a different approach. According to the documentation, a resource module should not deploy external dependencies. It depends on how we view the module; the Public IP resource is required for the virtual network gateway but is also an external dependency.

As a suggestion, I would recommend using the required Public IP resourceId parameter route. This approach enforces that the Public IP resource must be provided through a parameter. If we want to keep the Public IP and gateway together, we should expose every Public IP property and offer the user the option to provide a resourceId as an alternative to "bring your own IP".

Tagging @AlexanderSehr @fabmas

**Comment by AlexanderSehr** [comment]
Personally, I'd suggest to apply the same approach we did/should for several other modules that may or must use a public IP. For example:
- Azure Bastion
- Load Balancer
- Azure Firewall
- VM
- VMSS
- etc.

The approach: Either you provide a resource Id of an existing Public IP - OR - you provide the properties needed to create set public IP in the module. For that, the module needs an input object and reference to the Public IP AVM module to which it passes the provided inputs. As an example:

https://github.com/Azure/bicep-registry-modules/blob/be99668fb424576c0f073f1d5ac98d9db268539f/avm/res/network/bastion-host/main.bicep#L133C88-L150

**Comment by jtracey93** [comment]
@fabmas, any updates here?

**Comment by fabmas** [comment]
@jtracey93 the pull request is awaiting review before it can be merged.
