### ISSUE TITLE
[AVM Module Issue]: Need additionalPortMappings support for Container app Bicep module

### ISSUE THREAD

**Issue by nitinitare** [Azure/bicep-registry-modules#3062]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/container-app

### Description

I need to do additional port mapping for container app but I don't see that property in AVM module. I am not sure why additionalPortMappings ingress property is not added to module.

**Comment by nitinitare** [comment]
@hundredacres could you please look into it.

**Comment by oZakari** [comment]
Hey @nitinitare, I can work on this next week. If you need the capability sooner, you also have the option of submitting a PR and referencing this issue as well.

**Comment by nitinitare** [comment]
@oZakari Thanks for the update. I can wait till next week.
