### ISSUE TITLE
[AVM Module Issue]: Container app Managed environment module missing property peerTrafficConfiguration

### ISSUE THREAD

**Issue by nitinitare** [Azure/bicep-registry-modules#3063]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/app/managed-environment

### Description

I need to enable encryption for peer to peer traffic. But I don't see peerTrafficConfiguration property in the Module.

**Comment by hundredacres** [comment]
PR here: https://github.com/Azure/bicep-registry-modules/pull/3068
