### ISSUE TITLE
[AVM Module Issue]: Container app environment is set to internal but still it doesn't set container app ingress traffic limited to VNET

### ISSUE THREAD

**Issue by nitinitare** [Azure/bicep-registry-modules#3064]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/app/managed-environment

### Description

As per the documentation if we set container apps environment to internal it should limit the container app traffic to VNET. But when I am using the AVM module it always set limited to container apps environment. Also there are no explicit property in the container app module to change it.

**Comment by hundredacres** [comment]
@nitinitare can you show me the code you're using?

**Comment by hundredacres** [comment]
@nitinitare Are you referring to this setup as well: https://learn.microsoft.com/en-us/azure/container-apps/ingress-overview

**Comment by nitinitare** [comment]
@hundredacres Please find below code

module managedEnvironment 'br/public:avm/res/app/managed-environment:0.7.0' = {
  name: 'managedEnvironmentDeployment'
  scope: resourceGroup(resourceGroupName)
  params: {
    // Required parameters
    logAnalyticsWorkspaceResourceId: logAnalyticsWorkspaceResourceId
    name: managedEnvironmentName
    // Non-required parameters
    location: location
    tags: tags
    managedIdentities: {
      systemAssigned: true
    }
    infrastructureSubnetId: '/subscriptions/${subscription().subscriptionId}/resourceGroups/${vnetResourceGroupName}/providers/Microsoft.Network/virtualNetworks/${vnetName}/subnets/${subnetName}'
    internal: true
    peerTrafficEncryption: true
    zoneRedundant: zoneRedundant
    workloadProfiles: workloadProfiles
    appInsightsConnectionString: appInsightsConnectionString
    openTelemetryConfiguration: {
      logsConfiguration: {
        destinations: [
          'appInsights'
        ]
      }
      tracesConfiguration: {
        destinations: [
          'appInsights'
        ]
      }
    }
  }
}


module containerApp 'br/public:avm/res/app/container-app:0.4.0' = {
  name: 'containerAppDeployment'
  scope: resourceGroup(resourceGroupName)
  params: {
    // Required parameters
    name: containerAppName
    containers: containers
    environmentId: managedEnvironment.outputs.resourceId
    // Non-required parameters
    location: location
    registries: [
      {
        identity: 'system'
        server: '${containerRegistryName}.azurecr.io'
        username: containerRegistryName
      }
    ]
    ingressTargetPort: 443
    ingressAllowInsecure: false
    ingressExternal: false
    //lock: lock
    managedIdentities: managedIdentities
    secrets: caSecrets
    tags: tags
  }
}

**Comment by hundredacres** [comment]
@nitinitare Update the app module and flip the flag to true and ingress traffic will be open to the VNET

```
module containerApp 'br/public:avm/res/app/container-app:0.9.0' = {
  name: 'containerAppDeployment'
  scope: resourceGroup(resourceGroupName)
  params: {
    // Required parameters
    name: containerAppName
    containers: containers
    environmentResourceId: managedEnvironment.outputs.resourceId
    // Non-required parameters
    location: location
    ingressTargetPort: 443
    ingressAllowInsecure: false
    ingressExternal: true
    //lock: lock
    managedIdentities: {
      userAssignedResourceIds: [
        managedIdentity.id
      ]
    }
    secrets: {
      secureList: [
        {
          name: 'containerappstoredsecret'
          value: myCustomContainerAppSecret
        }
        {
          name: keyVaultSecretName
          keyVaultUrl: keyVaultSecret.properties.secretUri
          identity: managedIdentity.id
        }
      ]
    }
    tags: tags
  }
}
```

**Comment by nitinitare** [comment]
@hundredacres Thanks for your response, will give it a try and update this issue.

**Comment by nitinitare** [comment]
closing as issue addressed
