### ISSUE TITLE
feat: Unable to Deploy Function App from IDE Due to Missing ipSecurityRestrictions Configuration

### ISSUE THREAD

**Issue by vishal-1908** [Azure/bicep-registry-modules#3065]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### Description

**Description:**

I encountered an issue while attempting to deploy an Azure Function App from my IDE. The deployment fails due to the function app's public network access being disabled. This issue arises when a private endpoint is configured for the function app, resulting in the absence of `ipSecurityRestrictions` settings.

**Reproduction Steps:**
1. Set up a Function App with a private endpoint inside Virtual Network in Azure using AVM.
2. Attempt to deploy the Function App from an IDE (e.g., Visual Studio, Visual Studio Code, etc.).
3. Will get Error 403 - Forbidden

**Expected Behavior:**
The function app should be deployable from the IDE, with the appropriate `ipSecurityRestrictions` in place.

**Actual Behavior:**
The deployment is blocked because public network access is disabled, and `ipSecurityRestrictions` are missing from `avm/res/web/site:version`. This configuration issue can currently only be resolved by manually adding `ipSecurityRestrictions` via the Azure portal.

**Workaround:**
Manually add the required `ipSecurityRestrictions` configuration through the Azure portal to enable public network access for the deployment.

**Impact:**
This issue prevents developers from deploying function apps directly from their IDEs when a private endpoint is configured, disrupting the development workflow.

**Suggested Solution:**
Provide a mechanism to automatically add `ipSecurityRestrictions` in the module when the public network access is to be allowed for certain IPs via AVM.

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy & @pankajagrawal16, just assigned you to the issue. Please triage it when you have a moment :)

**Comment by pankajagrawal16** [comment]
Hi @vishal-1908 

I looked through the issue, and i have a question. 

Currently module accepts `siteConfig` as an object, so you can basically pass the module any properties supported as part of siteconfig to the module which offcourse inclused `ipSecurityRestriction` and `scmIpSecurityRestriction` as well. 

Have you tried passing these configuration inside siteConfig ? as document [here ](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites?pivots=deployment-language-bicep#siteconfig)

Please confirm.
