### ISSUE TITLE
[AVM Module Issue]: Docker Hub Rate Limit

### ISSUE THREAD

**Issue by ARMSGit** [Azure/bicep-registry-modules#3069]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/ptn/deployment-script/import-image-to-acr

### (Optional) Module Version

0.2.0

### Description

When using the import-image-to-acr script to import images from Docker Hub, the deployment fails with 429 response code with body/error description "You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limits"

The CLI (az acr import) supports using docker hub credentials and imports into Azure Container Registry successfully.

**Comment by ReneHezser** [comment]
I was out, sorry. Will look into this.

**Comment by ReneHezser** [comment]
Hey @ARMSGit 
I've added the option to authenticate to the source registry. Tested with a private docker hub image and it worked perfectly. In a while the new version should be available for you to use it.
