### ISSUE TITLE
[AVM Module Issue]: Improve (fix) naming on Virtual Wan Hub Connections

### ISSUE THREAD

**Issue by noopman** [Azure/bicep-registry-modules#3085]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/ptn/lz/sub-vending

### Description

The naming of Virtual Wan Hub Connections is based on a guid. It looks incredibly ugly in the list of connections. Real world example: _vhc-48b529d4-e9c0-5a89-87d8-a413512e103f_

I propose:

* Make much better names for the connection using the vnet name as part of the connection name by default!
* Consider allowing the connection name to be an optional parameter!

Here is the exact location in code where the [virtualWanHubConnectionName](https://github.com/Azure/bicep-registry-modules/blob/main/avm/ptn/lz/sub-vending/modules/subResourceWrapper.bicep#L298C1-L298C44) is set.

`var virtualWanHubConnectionName = 'vhc-${guid(virtualHubResourceIdChecked, virtualNetworkName, virtualNetworkResourceGroupName, virtualNetworkLocation, subscriptionId)}'`

Instead we could have 'cn' for connection and the name could be as simple as this:

`var virtualWanHubConnectionName = 'cn-${virtualNetworkName}'`

**Comment by sebassem** [comment]
Thanks for submitting this issue, we are looking into how to better handle this
