### ISSUE TITLE
[AVM Module Issue]: Add support for rest of the Workspace properties.

### ISSUE THREAD

**Issue by iliyansi** [Azure/bicep-registry-modules#3087]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/databricks/workspace

### Description

When I try to deploy data bricks workspace and configure default catalog I don't see such parameter while on resource api there is `defaultCatalog` property of type DefaultPropertiesCatalog object which sets initialName and InitialType of that catalog. There is also missing parameter  for `enhancedSecurityCompliance` property and `authorization`.

**Comment by clintgrove** [comment]
Hi. I am busy working on a fix for this. It will take about another week

**Comment by clintgrove** [comment]
hi @iliyansi I have completed some work on this. PR is now open. One thing to note is that you cannot currently set the catalog name, the Resource Provider does not currently allow it. The thing you can set is whether its a HiveMetastore or a UnityCatalog. See how I have implemented it in the MAX version of the databricks deployment
