### ISSUE TITLE
[AVM Question/Feedback]: Bicep module vs Json parameter file 

### ISSUE THREAD

**Issue by abhiramani-git** [Azure/bicep-registry-modules#3091]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hi
I am seeing all examples have Bicep module vs Json parameter file . i want to use json parameter files but what exact bicep file do i create to pass my json parameter. because current bicep file is hardcoded to all values anyways.
i am trying to find quick way to run one example copy paste bicep,copy paste json parameter file and run command

am i missing something?

for example i have taken this json from from Virtual machine example. can you please help me what exact bicep code i write to pass this json parameter file for virtual machine?

```
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    // Required parameters
    "adminUsername": {
      "value": "localAdminUser"
    },
    "imageReference": {
      "value": {
        "offer": "0001-com-ubuntu-server-jammy",
        "publisher": "Canonical",
        "sku": "22_04-lts-gen2",
        "version": "latest"
      }
    },
    "name": {
      "value": "cvmlinmin"
    },
    "nicConfigurations": {
      "value": [
        {
          "ipConfigurations": [
            {
              "name": "ipconfig01",
              "pipConfiguration": {
                "name": "pip-01"
              },
              "subnetResourceId": "<subnetResourceId>"
            }
          ],
          "nicSuffix": "-nic-01"
        }
      ]
    },
    "osDisk": {
      "value": {
        "caching": "ReadWrite",
        "diskSizeGB": 128,
        "managedDisk": {
          "storageAccountType": "Premium_LRS"
        }
      }
    },
    "osType": {
      "value": "Linux"
    },
    "vmSize": {
      "value": "Standard_DS2_v2"
    },
    "zone": {
      "value": 0
    },
    // Non-required parameters
    "disablePasswordAuthentication": {
      "value": true
    },
    "location": {
      "value": "<location>"
    },
    "publicKeys": {
      "value": [
        {
          "keyData": "<keyData>",
          "path": "/home/localAdminUser/.ssh/authorized_keys"
        }
      ]
    }
  }
}
```

**Comment by AlexanderSehr** [comment]
Hey @abhiramani-git,
when using a JSON parameter file, you'd just store that file somewhere and then pass it into the deploying cmdlet alongside the reference to the template you want to deploy. Let's take your VM example above. To use it
1. Store it as a JSON file (e.g., vm.parameters.json)
2. Invoke `New-AzResourceGroupDeployment -TemplateParameterFile '<pathToFile>/vm.parameters.json' -TemplateFile '<pathToVMModuleFolder>/main.bicep' -ResourceGroupName 'my-rg'`
Alternatively, you can also reference the `main.json` file. The cmdlet should be fine with both. Also, there may be a way to do the same using `Az CLI` commands, but I'd not know the command from the top of my head.

One other note regarding the JSON parameter file example. While it is directly rendered from the actual deployments we're performing in the CI to validate the module, they cannot be used 1:1 (but almost). Every time you see something like `<heyThere>`  you have to add a value (e..g, `"subnetResourceId": "<subnetResourceId>"`) and make sure that reference also exists :) In case of the VM module for example, you have to create the VNET before deploying the VM module into it.

I hope the above helps :)
