### ISSUE TITLE
[AVM Module Issue]: Option to create ED25519 or RSA SSH keys to be added

### ISSUE THREAD

**Issue by humblejay** [Azure/bicep-registry-modules#3095]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/ssh-public-key

### Description

Azure now provides option to create ED25519 SSH Keys in addition to the regular RSA keys. The portal support for this is described [here](https://learn.microsoft.com/en-us/azure/virtual-machines/ssh-keys-portal). The current version of avm/res/compute/ssh-public-key module needs to be updated to have option to create either ED25519 or RSA keys.

**Comment by ChrisSidebotham** [comment]
PR in draft awaiting test tenant provisioning
