### ISSUE TITLE
[AVM Testing Workflows]: Custom Secrets in AVM E2E Pipeline - Azure Stack HCI Modules

### ISSUE THREAD

**Issue by mbrat2005** [Azure/bicep-registry-modules#3101]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

In order to deploy an Azure Stack HCI cluster, an App Registration and client secret credential is currently required (until managed identity is supported). This is a blocker for the HCI cluster and related resource modules. We have looked into options to dynamically create this App Registration, but Deployment Scripts require excessive permissions for the GitHub action credential and Bicep MS Graph support doesn't allow creating secret credentials. 

This has left passing an existing App Registration ID and secret through GitHub secrets to the E2E pipeline during execution. However, this doesn't appear possible today without modifying the template workflows. 

This impacts these proposed modules: avm/res/azure-stack-hci/ cluster, virtual-hard-disk, virtual-machine-instance, network-interface. Others, which have yet to be proposed related to AKS and SDN on HCI, as well as pattern modules would also be blocked.

**Comment by matebarabas** [comment]
@AlexanderSehr, I transferred the issue to BRM as suggested. Can you please link any related, already existing issues to it? If I'm not mistaken this is already being discussed and the solution is being developed somewhere. Can you please confirm? Thanks!

CC: @mbrat2005

**Comment by AlexanderSehr** [comment]
Hey @mbrat2005, the custom-inputs/secrets feature was merged just recently via this PR #3015 and is documented [here](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/custom-ci-secrets/). If you agree, then I'd suggest to close the issue as completed :)

**Comment by mbrat2005** [comment]
Amazing, thanks for all the work @AlexanderSehr! 

For the documentation piece, a quick section detailing the steps to be taken before attempting a PR to upstream main would be good--I'm assuming that we (module owners) need to provide you (maintainers) with the list of secrets to be added to the upstream key vault and any related configuration for those secret's target resources/identities?

**Comment by AlexanderSehr** [comment]
> e documentation piece, a quick section detailing the steps to be taken before attempting a PR to upstream main would be good--I'm assuming that we (module owners) need to provide you (maintaine

That's correct. @jtracey93 actually just called this out today and we added a disclaimer on top of the [docs](https://azure.github.io/Azure-Verified-Modules/contributing/bicep/bicep-contribution-flow/custom-ci-secrets/). It's not perfect, but a start. 

That being said, if there is any special configuration needed, I'd further suggest to add something to the test parameter's description, or add a comment in the test case that you could point in the PR to. This would help any potential contributor to set to module to replicate the setup too 💪

**Comment by mbrat2005** [comment]
@AlexanderSehr Giving this a test run today, it seems that the CI secrets solution may need something to work with PSRules, which expects parameters to have values or default values when it expands the bicep files. 

Does that sound right to you? Do you think the param values need to be added to the module files before the PSRules testing runs? If so, I could see if I can get that working following the other CI variable code...

**Comment by AlexanderSehr** [comment]
Hey @mbrat2005,
dang sorry, I thought I added that remark to the docs. Just opened this [PR](https://github.com/Azure/Azure-Verified-Modules/pull/1374/files) to add the missing piece.
In short, you have to provide a default value (an empty string is enough) for the new parameter. This is because PSRule wants to expand the template and hence needs a value for every parameter. We intend to slightly alter the implementation in the future as there is an alternative way to do this (i.e., defining defaults in the PSRule configuration), that it's currently not working for us. We did however already create an issue for it and it will likely be fixed sooner than later.
Until then we'll make due with the default value and then update the approach on behalf of the owners later :)

**Comment by mbrat2005** [comment]
Great, thanks! I'll try that

**Comment by mbrat2005** [comment]
Tested again and a default blank value workaround works.
