### ISSUE TITLE
[AVM Module Issue]: The property "privateDnsZoneGroupName" is not allowed on objects of type "params". Permissible properties include "privateDnsZoneGroup".

### ISSUE THREAD

**Issue by e-kve** [Azure/bicep-registry-modules#3124]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### Description

We have made a local copy of the storage-account module and changed the relevant paths. We then get the following errors:

Error BCP104: The referenced module has errors.
C:\bicep\avm\res\storage\storage-account\main.bicep(536,7) : Error BCP037: The property "privateDnsZoneGroupName" is not allowed on objects of type "params". Permissible properties include "privateDnsZoneGroup".
C:\bicep\avm\res\storage\storage-account\main.bicep(537,7) : Error BCP037: The property "privateDnsZoneResourceIds" is not allowed on objects of type "params". Permissible properties include "privateDnsZoneGroup".

**Comment by AlexanderSehr** [comment]
Hey @e-kve,
could you let me know which version of the Private Endpoint module you're referencing? Could it be that it is 0.7 or newer? If so, the PE interface changed (which is implemented in exactly the location your error message mentions):
https://github.com/Azure/bicep-registry-modules/blob/8e5729753f9a887bda5c000e63eec8e3086abeb8/avm/res/storage/storage-account/main.bicep#L536-L537

@krbar is actually currently working on updating all AVM modules to use that latest interface, changing for example
```bicep
privateDnsZoneGroupName: privateEndpoint.?privateDnsZoneGroupName
privateDnsZoneResourceIds: privateEndpoint.?privateDnsZoneResourceIds
``` 
to 
```bicep 
privateDnsZoneGroup: privateEndpoint.?privateDnsZoneGroup
```

**Comment by e-kve** [comment]
Thanks for your reply.
We used v0.7 of the Private Endpoint module. Will retry with the latest version of relevant modules.

**Comment by AlexanderSehr** [comment]
Sounds good. Then this is definitely the reason. The interface simply changed :) Please apply the necessary updates and try again 💪

**Comment by e-kve** [comment]
The issue is solved in the latest version. Thanks.
