### ISSUE TITLE
[AVM Module Issue]: DevTest Lab Network - Optional parameter sharedPublicIpAddressConfiguration is not optional

### ISSUE THREAD

**Issue by HexagonSam** [Azure/bicep-registry-modules#3126]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/dev-test-lab/lab

### (Optional) Module Version

0.3.1

### Description

Using AVM DevTest Lab module, the parameter sharedPublicIpAddressConfiguration should be optional, but reports error if omitted:

Error: Code=InvalidTemplate; Message=Deployment template
     | validation failed: 'The provided value for the template parameter
     | 'virtualnetworks[0].subnetOverrides[0]' is not valid. A non-null value
     | for the property 'sharedPublicIpAddressConfiguration' must be provided,
     | but the property was null or missing.

Deploying a DevTest Lab using a bicep resource of the same API version does not require this parameter.

If the parameter is supplied, it enables the Enable shared public IP option for the subnet which is not the desired configuration.

**Comment by HexagonSam** [comment]
Using module version 0.3.2

This is still not working for me. The documentation still says this is optional, but if I still get the error if omitted:

13:04:38 - Error: Code=InvalidTemplate; Message=Deployment template
     | validation failed: 'The provided value for the template parameter
     | 'virtualnetworks[0].subnetOverrides[0]' is not valid. A non-null value
     | for the property 'sharedPublicIpAddressConfiguration' must be provided,
     | but the property was null or missing.

The updated documentation contains an error about the parameter type. It requires an object, but says valid options are a string type:

[sharedPublicIpAddressConfiguration](https://github.com/Azure/bicep-registry-modules/issues/3126#parameter-subnetoverridessharedpublicipaddressconfiguration)	object	The permission policy of the subnet for allowing public IP addresses (i.e. Allow, Deny)).

Which give the error:

13:16:29 - Error: Code=InvalidTemplate; Message=Deployment template
     | validation failed: 'The provided value for the template parameter
     | 'virtualnetworks[0].subnetOverrides[0].sharedPublicIpAddressConfiguration' is not valid. Expected a value of type 'Object', but received a value of type 'String'.

Am I missing something on how to disable this setting?

**Comment by HexagonSam** [comment]
Ahmed,

This was an issue on my side. I updated my bicep file, but forgot to publish it to the template spec, so it wasn’t really updated for the Deployment Stack.

Still getting my process down for the move from Blueprints to TemplateSpecs/Deployment Stacks.

Thanks for all your assistance.

Side question, how are we supposed to know to use 0.3.2, as the official version still seems to be 0.3.0. I just used trial and error.

Regards,
Sam

From: Ahmad Abdalla ***@***.***>
Date: Monday, September 9, 2024 at 8:44 AM
To: Azure/bicep-registry-modules ***@***.***>
Cc: WILLIAMS Samuel H (Sam) ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/bicep-registry-modules] [AVM Module Issue]: DevTest Lab Network - Optional parameter sharedPublicIpAddressConfiguration is not optional (Issue #3126)
This email is not from Hexagon’s Office 365 instance. Please be careful while clicking links, opening attachments, or replying to this email.


@HexagonSam<https://github.com/HexagonSam> let me have a look deeply into this. I've added additional test scenarios for vnet properties to validate it. Will come back to you. Thanks

**Comment by HexagonSam** [comment]
This was an error on my side, forgot to publish my updated bicep file to the template spec. Works now leaving this parameter out.

**Comment by ahmadabdalla** [comment]
@HexagonSam I did quick check to see the latest published version

![image](https://github.com/user-attachments/assets/31fc3ca7-1897-465d-b269-6a2ce4ddf7fc)

Which has been created as a tag as well: See https://github.com/Azure/bicep-registry-modules/releases/tag/avm%2Fres%2Fdev-test-lab%2Flab%2F0.3.2

@Azure/avm-core-team-technical-bicep Is their specific time on when would be the latest release tag for a module available on the Bicep Registry?

**Comment by AlexanderSehr** [comment]
The @ahmadabdalla,
the module is available and can be used right after publishing. It's the VSCode extension that unfortunately needs some time to catch up as it caches the module versions instead of loading them each time. I don't know how long it waits but I think already restarting VSCode should do the trick if you want the dropdown to refresh. But again, you don't actually need the cache to refresh to reference the module. If you just set the version you want, Bicep will work with it.
