### ISSUE TITLE
[AVM Module Issue]: Missing support for disabling outbound access

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/bicep-registry-modules#3152]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/virtual-network

### (Optional) Module Version

0.2.0

### Description

Can support for disabling default outbound access be added?

We have created a rule for this in PSRule, but the AVM module does not have support for this feature currently.

https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/default-outbound-access

**Comment by AlexanderSehr** [comment]
Hey @elbatane, could you take a look at this? 🚀

**Comment by AlexanderSehr** [comment]
Hey @BenjaminEngeset,
it appears I may have accidently implemented this feature about a month ago (#3105). My bad for not updating this issue. Will close it :)
