### ISSUE TITLE
[AVM Module Issue]: db-for-postgre-sql private deployment no publicNetworkAccess param

### ISSUE THREAD

**Issue by DanGiffen** [Azure/bicep-registry-modules#3166]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/db-for-postgre-sql/flexible-server

### (Optional) Module Version

0.2.0

### Description

Unable to deploy a private server, get a conflict config error if vnet integration and private dns configured in the template. publicNetworkAccess param on latest api https://learn.microsoft.com/en-us/azure/templates/microsoft.dbforpostgresql/flexibleservers?pivots=deployment-language-bicep not available for the avm module https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/db-for-postgre-sql/flexible-server/main.bicep
![image](https://github.com/user-attachments/assets/3c012070-e440-4b4b-b4ed-1855a64b00a6)
![image](https://github.com/user-attachments/assets/e860cabe-e587-410c-b353-df0300ee1083)

**Comment by arnoldna** [comment]
The currently deployed API version does not support public endpoints. We will need to upgrade the API version to make this feature available.

**Comment by xdawxd** [comment]
@arnoldna is there any ETA for this? My team is looking forward to the API update.
