### ISSUE TITLE
[AVM Module Issue]: should migrationToken be secure?

### ISSUE THREAD

**Issue by tonybaloney** [Azure/bicep-registry-modules#3172]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Security Bug

### Module Name

avm/res/cognitive-services/account

### Description

I've noticed that the cognitive services account AVM module has parameter `migrationToken` which is not marked as secure. https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cognitive-services/account/main.bicep#L105-L106 I can't find documentation anywhere on what this parameter is (other than "migration token") so I can't work out if this is supposed to be a secure value. There

**Comment by ilhaan** [comment]
Good question. @jceval any thoughts?

**Comment by AlexanderSehr** [comment]
> Good question. @jceval any thoughts?

I tend to strongly agree 👀

**Comment by jceval** [comment]
I

> Quote reply

Yes - I think it should be a secure value. Given that it may contain sensitive information required for migration processes, it should indeed be treated as a secure value. This ensures that the token is not exposed in plain text within your deployment scripts or logs.
