### ISSUE TITLE
[AVM Module Issue]: Unable to set value 'inboundIpAddressOverride'

### ISSUE THREAD

**Issue by kevin-381ecc2e** [Azure/bicep-registry-modules#3176]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/hosting-environment

### (Optional) Module Version

0.1.1

### Description

When deploying an App Service Environment with Private VNET Integration you can provide an 'inboundIpAddressOverride' to pick a custom Ip within the subnet. However when deploying the module to Azure we receive the following error: 

```
Operation not supported: Cannot set or change Custom Inbound IP Address on Updates.
```

It seems that in the module first the appServiceEnvironment is being created on the following line https://github.com/Azure/bicep-registry-modules/blob/119f1cdf9437bfb392a53519f560884be395a021/avm/res/web/hosting-environment/main.bicep#L153

And afterwards the networkConfiguration gets deployed 'as an Update' on line
https://github.com/Azure/bicep-registry-modules/blob/119f1cdf9437bfb392a53519f560884be395a021/avm/res/web/hosting-environment/main.bicep#L174

The Azure Portal mentions that it is not allowed to set the custom IP after the App Service Environment is deployed.
I think it's necessary to include the network configuration in the  'appServiceEnvironment' resource to make this work.

**Comment by tsc-buddy** [comment]
Thanks @kevin-381ecc2e - we shall triage this and take a look into it. I can confirm we are seeing similar behavior out of nowhere, so will look into why as no new ASE module versions have been published.
