### ISSUE TITLE
[Module Proposal]: Log Analytics workspaces

### ISSUE THREAD

**Issue by vlahane** [Azure/bicep-registry-modules#318]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We require a base module for managing Log Analytics workspaces.
will follow the concept of existing modules in bicep-registry-modules repo.

We will be needing this bicep module to provision Log Analytics workspaces for storing log data.

### Module path

storage/log-analytics-workspace

### Describe the module

This module will be used to provision azure Log Analytics workspaces, ref: https://learn.microsoft.com/en-us/azure/azure-monitor/logs/data-platform-logs#log-analytics-workspaces.

**Comment by shenglol** [comment]
Mind changing the module path to `storage/log-analytics-workspace`?
