### ISSUE TITLE
[AVM Module Issue]: DurableTask.AzureStorage: If at least one Azure Storage service URI is specified, BlobServiceUri, QueueServiceUri, and TableServiceUri must all be provided.

### ISSUE THREAD

**Issue by brgsstm** [Azure/bicep-registry-modules#3207]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/site

### Description

When using this AVM to deploy a function app and when using 'storageAccountUseIdentityAuthentication: true', it automatically creates 2x app settings: AzureWebJobsStorage__accountName and AzureWebJobsStorage__blobServiceUri.

This works fine when deploying standard (non-durable) functions to the function app, however when you deploy a durable function, the runtime presents the below error:

DurableTask.AzureStorage: If at least one Azure Storage service URI is specified, BlobServiceUri, QueueServiceUri, and TableServiceUri must all be provided.

If AzureWebJobsStorage__blobServiceUri is removed, the runtime succeeds.

This can be worked around by adding the queue/table endpoints to the provided parameters, but I would prefer to see this logic added to the AVM.

**Comment by tsc-buddy** [comment]
Hey @brgsstm - thanks for logging this. We shall triage this week and schedule work. In the mean time if you have a workaround code snippet that can speed up the process, feel free to share.
