### ISSUE TITLE
[Feature Request]: Private DNS for network module/virtual-network

### ISSUE THREAD

**Issue by arashwanns** [Azure/bicep-registry-modules#323]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

To create dns zones and link it to the virtual network
https://learn.microsoft.com/en-us/azure/dns/private-dns-privatednszone
https://learn.microsoft.com/en-us/azure/dns/private-dns-virtual-network-links

### Module path

https://github.com/Azure/bicep-registry-modules/tree/main/modules/network/virtual-network

### Describe the module

Network Module

**Comment by djsly** [comment]
> It should be part of the Private DNS Zone module not virtual network module.
> 
> https://learn.microsoft.com/en-us/azure/templates/microsoft.network/privatednszones/virtualnetworklinks?pivots=deployment-language-bicep

the point here is that a private DNS zone by itself doesn't do anything, you must link it to a vnet. 

so the idea was that since it goes hand in hand with a vnet. maybe we could combine them.  Also, when using private endpoints, users are obligated to create the matching private dns zones. we figured maybe passing a list of private dns zone name that they would want to be created and attached to their VNET would make it easier.

**Comment by ChrisSidebotham** [comment]
Dear @arashwanns , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
