### ISSUE TITLE
[AVM Module Issue]: NetworkInterface not found while deploying storage account

### ISSUE THREAD

**Issue by timdhaeyer** [Azure/bicep-registry-modules#3235]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### (Optional) Module Version

0.13.0

### Description

When creating a new storage account for the first time I get the following error.
`The Resource 'Microsoft.Network/networkInterfaces/nic-pe-stwe1760dc28-blob' under resource group 'rg-we-1760-d-c-19' was not found`

Private Endpoints and NIC's are provided as an input parameter so they should get created by AVM.
The strangest thing is that the NIC is actually created and my deployment runs without errors the 2nd time. Without any changes.
Has anybody seen this behavior before.

### (Optional) Correlation Id

8771952f-7ab0-49da-8b04-3e8fdb018f53

**Comment by ktremain** [comment]
Let me see if i can re-create this issue in my test sub - is there anything else about your configuration that i might need to know in order for the test to be valid?

**Comment by timdhaeyer** [comment]
I will close the issue. While reviewing my code to give you more information, I found out that I made the mistake myself. I will need to make a workaround to solve this. Sorry for bothering you with this
