### ISSUE TITLE
[AVM Module Issue]: Virtual Machine - Support for premium SSD v2 disks

### ISSUE THREAD

**Issue by juang903** [Azure/bicep-registry-modules#3252]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### (Optional) Module Version

0.7.0

### Description

Add support for premium SSD v2 disks and the ability to specify IOPS and throughput configuration.

**Comment by rahalan** [comment]
@juang903 thanks for sharing. I will look into it

**Comment by rahalan** [comment]
@juang903 PR #3770 will add this
