### ISSUE TITLE
[AVM Module Issue]: DevTest Lab storage account configuration issue

### ISSUE THREAD

**Issue by Sam-Williams-Admin** [Azure/bicep-registry-modules#3258]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/dev-test-lab/lab

### (Optional) Module Version

0.3.2

### Description

When creating a DevTest Lab with the AVM module, the storage account created is configured with the public network access set to "Enabled from selected virtual networks and IP addresses", and no networks are selected. When creating a DevTest Lab from the portal this setting is set to "Enabled from all networks". With the AVM settings, artifacts will fail to install because they can't be copied to the lab storage account blob container.

I have not found any parameters to set this configuration. I don't even find anything in the bicep file for the lab that appears to be related to this at all. Not sure why/how the AVM module is setting this option.

**Comment by Sam-Williams-Admin** [comment]
@ahmadabdalla, 

I'm waiting on resolution of this issue to start the migration of >600 DevTest Labs from ARM/blueprints to AVM/deploymentstacks. Any assistance appreciated. I'm available if we need to debug.

**Comment by ahmadabdalla** [comment]
@Sam-Williams-Admin apologies for the delay, if the desired outcome is to set it public, then there is a parameter called 'isolateLabResources', which is a property of the DevTestLab resource. Setting this to 'Enabled' will set the storage account and Key vault to allow public network access. Please give it a shot and let me know the outcome. Thanks 🙏🏻

**Comment by Sam-Williams-Admin** [comment]
@ahmadabdalla that resolved the issue. I've never had to set that one before, but I understand why you are defaulting security type settings as strict as possible.

Is there a way within the AVM module that you can configure this to enable, but still allow access to pull artifacts from GitHub/AzDo repos? Would be good to have this enabled, but have an exception of some sort for what you want/need.

This resolves the immediate issue.

**Comment by ahmadabdalla** [comment]
@Sam-Williams-Admin I'm glad that worked for you. Regarding your question, and as you mentioned we're focusing on secure defaults where applicable. I would prefer to not introduce additional logic that can add complexity to the module as you can also supply your own storage account and not use the default one created by DevTest Lab. So then we can have contradicting configs where if public is desired but the custom storage account is configured differently. The simplest is to set this parameter to 'Disabled'. Let me know please if you have other ideas, more than welcome to consider. Thanks again
