### ISSUE TITLE
[AVM Module Issue]: particular key vault resource access to a function app

### ISSUE THREAD

**Issue by nitinitare** [Azure/bicep-registry-modules#3265]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/web/site

### Description

I have a key vault resource created via bicep avm module and then I am creating a Function app using bicep AVM module. 

I want the "Key Vault Secrets User" permission for function app on the key vault. But I am not sure How to get it done. On portal if we go to managed identity role assignment we get the option to select a key vault scope and select a particular scope. Similar way how to get it done via AVM module.

![image](https://github.com/user-attachments/assets/e3bdebcb-2b3a-463f-9675-9c3ab12b7e4c)

**Comment by pankajagrawal16** [comment]
@nitinitare , How is keyvault created? Are you using module for keyvault as well? You can achieve this via https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/key-vault/vault#parameter-roleassignments of keyvault module

**Comment by nitinitare** [comment]
@pankajagrawal16 I will be creating multiple function apps which will need key vault access. So the problem i am facing is to get the function app system assigned principal id and passing it to the key vault role assignment module. 

Key vault will be created before function apps. And I want to avoid manual steps. So was looking for a way for role assignment in function app itself where for ex I can say assign Key Vault Secrets User permission to the current function app for this key vault.
