### ISSUE TITLE
[Module Proposal]:  Redis Enterprise

### ISSUE THREAD

**Issue by vlahane** [Azure/bicep-registry-modules#327]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We require a base module for managing Redis Enterprise.
will follow the concept of existing modules in bicep-registry-modules repo.

We will be needing this bicep module for some of our applications storing cache.

### Module path

storage/redis-enterprise

### Describe the module

This module will be used to provision azure Redis Enterprise. 
Ref: https://learn.microsoft.com/en-us/azure/templates/microsoft.cache/redisenterprise?pivots=deployment-language-bicep

**Comment by ChrisSidebotham** [comment]
Dear @vlahane , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, module proposals for new, non-AVM modules will no longer be accepted and we encourage you to propose a new AVM module, which you can file here: Module Proposal, [here](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
