### ISSUE TITLE
[AVM Module Issue]: bastionHosts module is not on the latest API version

### ISSUE THREAD

**Issue by sebassem** [Azure/bicep-registry-modules#3308]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/bastion-host

### Description

The module is on an old API version which is missing multiple properties

**Comment by krbar** [comment]
@sebassem thanks for reporting, I will look into it.
