### ISSUE TITLE
[AVM Module Issue]: update TLS versions to supported values `avm/res/storage/storage-account`

### ISSUE THREAD

**Issue by JulianHayward** [Azure/bicep-registry-modules#3313]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/storage/storage-account

### Description

https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/storage/storage-account#parameter-minimumtlsversion
https://learn.microsoft.com/en-us/azure/storage/common/transport-layer-security-configure-migrate-to-tls2
as discussed with Felix @fblix

**Comment by ReneHezser** [comment]
Hi @JulianHayward,
Could you specify the question of this issue? I don't get what should be done :-(

**Comment by fblix** [comment]
@ReneHezser its about this post: https://techcommunity.microsoft.com/t5/azure-storage-blog/tls-1-0-and-1-1-support-will-be-removed-for-new-amp-existing/ba-p/4026181

Basically, the allowedValues fields just need to be updated.
