### ISSUE TITLE
[AVM Module Issue]: web/serverfarm Flex Consumption

### ISSUE THREAD

**Issue by jonnywinter** [Azure/bicep-registry-modules#3316]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/serverfarm

### Description

When deploying an app service plan for Flex Consumption (preview), you are not required to enter 'skuCapacity' - as per the [Microsoft Article](https://learn.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code?tabs=bicep%2Cwindows%2Cdevops&pivots=flex-consumption-plan). Can you change it so that skuCapacity is not required or provide a response on what is needed for a FC1 like the below (code from MS link) -

```bicep
resource flexFuncPlan 'Microsoft.Web/serverfarms@2023-12-01' = {
  name: planName
  location: location
  tags: tags
  kind: 'functionapp'
  sku: {
    tier: 'FlexConsumption'
    name: 'FC1'
  }
  properties: {
    reserved: true
  }
}
```

**Comment by tsc-buddy** [comment]
This has been addressed in 0.10 today. Thanks all.
