### ISSUE TITLE
[AVM Module Issue]: Cannot specify displayName for service/products, service/subscriptions

### ISSUE THREAD

**Issue by timatbuild** [Azure/bicep-registry-modules#3328]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/api-management/service

### Description

Hi,

My question is about service/products and service/subscriptions:
Why can't I specify a displayName that is different from the resource name?
The name params accepted by the submodules are used for both name and displayName properties, so we are stuck with the more technical names our solution requires us to use, for both name and displayName, as we cannot specify a human readable one as displayName...
For service/apis however this is supported...

**Comment by tony-box** [comment]
@timatbuild thanks for the submission. I just raised a PR that adds displayName to some modules that had it missing.
