### ISSUE TITLE
[AVM Module Issue]: `avm/res/web/hosting-environment` - certain versions reaching end of life

### ISSUE THREAD

**Issue by matebarabas** [Azure/bicep-registry-modules#3337]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/hosting-environment

### Description

Hi @tsc-buddy,
 
As it's been communicated here, some versions of the Azure resource used in your module have been retired. Please see more details here: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/post-retirement-action-for-app-service-environment-v1-v2-logic/ba-p/4233407
 
Please make sure that 
1. your module is aligned with these changes (I think it already is, but please check and confirm) 
2. you have the following blurb added to the `Notes` section of your module's readme.md (Feel free to also include a pointer to the public announcement linked above.):
    "Certain versions of this Azure resource reached their end of life. The latest version of this module only includes supported versions of the resource. All unsupported versions have been removed from the related parameters."
3. you have the following blurb added to the related parameter's description:
    "Certain versions of this Azure resource reached their end of life. The latest version of this module only includes supported versions of the resource. All unsupported versions have been removed from this parameter."
 
Thank you!

**Comment by tsc-buddy** [comment]
I can confirm its only allowing v3, I shall updates the notes on readme as requested. Thanks @matebarabas

**Comment by matebarabas** [comment]
Thanks, @tsc-buddy! Please link the PR to this issue once you have it, so it self-closes. Thanks again!
