### ISSUE TITLE
[AVM Module Issue]: `avm/res/api-management/service` - certain versions reaching end of life

### ISSUE THREAD

**Issue by matebarabas** [Azure/bicep-registry-modules#3338]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/api-management/service

### Description

Hi @tony-box,
 
As it's been communicated here, some versions of the Azure resource used in your module have been retired. Please see more details here: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/post-retirement-action-for-app-service-environment-v1-v2-logic/ba-p/4233407
 
Please make sure that 
1. your module is aligned with these changes (it might already be, but I didn't see the parameter value called out in the article above, so please check and confirm) 
2. you have the following blurb added to the `Notes` section of your module's readme.md (Feel free to also include a pointer to the public announcement linked above.):
    "Certain versions of this Azure resource reached their end of life. The latest version of this module only includes supported versions of the resource. All unsupported versions have been removed from the related parameters."
3. you have the following blurb added to the related parameter's description:
    "Certain versions of this Azure resource reached their end of life. The latest version of this module only includes supported versions of the resource. All unsupported versions have been removed from this parameter."
 
Thank you!

**Comment by tony-box** [comment]
@matebarabas it appears that using a newer version of the APIM ARM API will default to deploying a stv2 APIM sku. There isn't an explicit parameter to define what APIM sku to deploy: https://learn.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet?tabs=stv1#prerequisites

I have cross referenced a few other places and it seems that in the past, (see https://techcommunity.microsoft.com/t5/azure-paas-blog/compute-platform-versions-for-azure-api-management-service/ba-p/2836971) to get a stv2 SKU, you had to deploy APIM with a certain set of networking requirements. But the latest APIs will always deploy a v2 SKU. I can do a little more digging to validate this. It's not documented very well.

**Comment by matebarabas** [comment]
Thanks, @tony-box, for looking into this! When your research is concluded, please still consider adding the above blrub to the over `Notes` section of the readme.md - I understand though, that it seems there isn't any parameter to add the same blurb to, but I still believe it might be worth to clarify that this module only supports the latest version/tier/family/sku. Thanks!

**Comment by tony-box** [comment]
Confirmed from engineering that the stv1 should no longer be deployable using bicep. I've added text to the notes section of the Readme.md file in #3342

**Comment by matebarabas** [comment]
Thanks for the fix/update, @tony-box!
