### ISSUE TITLE
[AVM Module Issue]: Feature Request-LAW-Need capability to add onboardingStates extension resource 

### ISSUE THREAD

**Issue by oZakari** [Azure/bicep-registry-modules#3340]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/operational-insights/workspace

### Description

Can we have the capability to add Microsoft.SecuirtyInsights/onboardingStates (which is an extension resource) to the log analytics workspace resource module. This is primarily a requirement needed for onboarding the log analytics workspace to sentinel.

We currently use [this approach in ALZ-Bicep](https://github.com/Azure/ALZ-Bicep/blob/main/infra-as-code/bicep/modules/logging/logging.bicep#L641C1-L645C2) for reference so it would just need to be an empty resource declaration that we could use to scope to the LAW.

**Comment by krbar** [comment]
@oZakari Thanks for reporting, I will take look at it.
