### ISSUE TITLE
[AVM Module Issue]: Unable to create management IP using standard SKU in `avm/res/network/azure-firewall`

### ISSUE THREAD

**Issue by johnlokerse** [Azure/bicep-registry-modules#3368]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/azure-firewall

### (Optional) Module Version

latest

### Description

I tried to use the module `avm/res/network/azure-firewall` to setup an Azure Firewall including a management IP and `AzureFirewallManagementSubnet` so I could get forced tunneling up and running. I didn't get it to work using a `Standard` SKU, and looking at the module in the current state it does not support this using a SKU other than `Basic`.

I would like to implement support for Standard and Premium SKU, so I went with this approach:
* Introduced a parameter called `forcedTunneling` with the `bool` type with standard value `false`
* Updated `requiresManagementIp` so it checks the following:

```bicep
var requiresManagementIp = azureSkuTier == 'Basic' || azureSkuTier == 'Standard' && forcedTunneling || azureSkuTier == 'Premium' && forcedTunneling ? true : false
```

The above changes worked for me and allowed me to deploy an Azure Firewall with `Standard` SKU and it created the management IP. Am I missing something, or would you like to see another approach @hundredacres ?

**Comment by hundredacres** [comment]
@johnlokerse Thanks for the submission. I implemented the fix as suggested with a minor change to the way we do the logic for requiresManagementIp. Let me know if that works for you.

**Comment by johnlokerse** [comment]
> @johnlokerse Thanks for the submission. I implemented the fix as suggested with a minor change to the way we do the logic for requiresManagementIp. Let me know if that works for you.

@hundredacres That looks even better! Thanks 💪🏼

**Comment by johnlokerse** [comment]
Any news on this @hundredacres?
