### ISSUE TITLE
[Module Proposal]: API published through API Management

### ISSUE THREAD

**Issue by BernieWhite** [Azure/bicep-registry-modules#338]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

There is no existing module available in the public registry, but is common deployed by customers developing their own APIs.

### Module path

apim/api

### Describe the module

Deploy a version REST API from a provided Open API spec with optional:
- Policy
- OAuth configuration
- App Insights diagnostic logs

**Comment by ChrisSidebotham** [comment]
Dear @BernieWhite , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, module proposals for new, non-AVM modules will no longer be accepted and we encourage you to propose a new AVM module, which you can file here: Module Proposal, [here](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
