### ISSUE TITLE
[AVM Module Issue]: avm/ptn/lz/sub-vending default storage account name too short

### ISSUE THREAD

**Issue by janegilring** [Azure/bicep-registry-modules#3384]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/ptn/lz/sub-vending

### (Optional) Module Version

0.1.5

### Description

The vending module fails from time to time due to the storage account created for the Deployment Script already exists.
As there are 4 random characters in the current version, increasing this to a higher number would probably help mitigate these random issues.

**Comment by sebassem** [comment]
This has been resolved
