### ISSUE TITLE
[Module Proposal]: DNS zones 

### ISSUE THREAD

**Issue by vlahane** [Azure/bicep-registry-modules#340]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

DNS zones/Public DNS zone we are using for domain management, but plan is to use bicep modules. 
Module will support necessary Record types like A,CNAME,NS initially later we can add all other Types based on input and requirements. 

### Module path

network/dns-zone

### Describe the module

API "type": "Microsoft.Network/dnszones".
ref: 
- https://learn.microsoft.com/en-us/azure/dns/dns-get-started-bicep?tabs=CLI
- https://learn.microsoft.com/en-us/azure/dns/dns-getstarted-portal

**Comment by shenglol** [comment]
I'd suggest changing using the module path `network/dns-zone`.
