### ISSUE TITLE
[AVM Module Issue]: Virtual Network creation with subnets and peerings is throwing an "updating state" error.

### ISSUE THREAD

**Issue by joerygrolleman** [Azure/bicep-registry-modules#3405]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/virtual-network

### Description

When creating a virtual network with subnets and network peering for the first time, it causes an error: Resource is in Updating state and the last operation that updated/is updating the resource is PutSubnetOperation.

**Comment by jtracey93** [comment]
@elbatane are you able to take a look into this?

**Comment by elbatane** [comment]
HI @jtracey93, someone from the Core team will look at it. Thanks
