### ISSUE TITLE
[AVM CI Environment Issue]:  Add AVM Static Validation Test To Ensure `enableTelemetry` is always passed to any called AVM modules (exc. Utility Modules)

### ISSUE THREAD

**Issue by jtracey93** [Azure/bicep-registry-modules#3504]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Add AVM Static Validation Test To Ensure `enableTelemetry` is always passed to any called AVM modules (exc. Utility Modules)

- [x] Also add to the Specification - @ReneHezser is handling update SFR4 as we speak

**Comment by ReneHezser** [comment]
PR is open https://github.com/Azure/Azure-Verified-Modules/pull/1519

**Comment by eriqua** [comment]
@jtracey93 @AlexanderSehr @ReneHezser this looks a duplicate of #2977 
Would you agree to close it?

**Comment by jtracey93** [comment]
it is, but PR is in, so we should be able to close both soon

**Comment by jtracey93** [comment]
Ah actually the PR does not include a test . Happy for you to close whichever one you see fit to do so

**Comment by AlexanderSehr** [comment]
Closing this one as the other has a bit more detail + we should not fundamentally exclude utility modules - but only exclude modules that, in general, don't implement the telemetry parameter. Reason being: If a utility module uses a deployment script - it would actually implement our telemetry deployment 😉
