### ISSUE TITLE
[AVM Module Issue]: Databricks Workspace Feature Request - Security and Compliance

### ISSUE THREAD

**Issue by awood86** [Azure/bicep-registry-modules#3515]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/databricks/workspace

### (Optional) Module Version

0.8.1

### Description

Could the Enhanced Security Compliance definition be added please?

**https://learn.microsoft.com/en-us/rest/api/databricks/workspaces/create-or-update?view=rest-databricks-2024-05-01&tabs=HTTP#enhancedsecuritycompliancedefinition**

**Comment by clintgrove** [comment]
Working on this now, PR raised in draft
