### ISSUE TITLE
[AVM Module Issue]: Unable to provision PYTHON|3.11 web app

### ISSUE THREAD

**Issue by rukasakurai** [Azure/bicep-registry-modules#3546]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/site

### (Optional) Module Version

0.9.0

### Description

While I believe that the way to provision a PYTHON|3.11 web app is to specify the linuxFxVersion, when I try to apply the bicep, I get the error `The parameter LinuxFxVersion has an invalid value.`

#### Code
```bicep
module webAppModule 'br/public:avm/res/web/site:0.9.0' = {
  name: 'webAppModule'
  params: {
    kind: 'app,linux'
    name: webAppName
    serverFarmResourceId: appServicePlanModule.outputs.resourceId
    location: location
    siteConfig: {
      linuxFxVersion: 'PYTHON|3.11'
    }
  }
}
```

#### Error Message
```
ERROR: deployment failed: error deploying infrastructure: deploying to resource group:

Deployment Error Details:
BadRequest: The parameter LinuxFxVersion has an invalid value.
- The parameter LinuxFxVersion has an invalid value.
```

#### How to reproduce error
I created a public repository with sample code that can be used to reproduce the error.
```
git clone https://github.com/rukasakurai/python-hello-world-azure-web-apps
cd python-hello-world-azure-web-apps
git checkout d0d65ce72c4f8e2be17e844681d440a736a08f81
azd provision
```

### (Optional) Correlation Id

TraceID: e0bd2c0a5049ae6fc72847dfa55102f4

**Comment by rukasakurai** [comment]
The issue was that I hadn't set the `kind` of the App Service Plan to `Linux`:
https://github.com/rukasakurai/python-hello-world-azure-web-apps/commit/643480c8d675ce7e1da56c2e31b8e71eb8982f28#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4R19

Closing the issue because it was an issue in my code, not the code in this repository.

**Comment by tsc-buddy** [comment]
All good @rukasakurai  - thanks for using our module.
