### ISSUE TITLE
[AVM Module Issue]: `avm.res/cognitive-services/account` deployments is missing new settings

### ISSUE THREAD

**Issue by peterbud** [Azure/bicep-registry-modules#3549]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cognitive-services/account

### Description

Current module only considers `model`, `raiPolicyName` and `sku`, however at the [current API](https://learn.microsoft.com/en-us/azure/templates/Microsoft.CognitiveServices/accounts/deployments?pivots=deployment-language-bicep#deploymentproperties) there are other important settings, like `versionUpgradeOption` or `scaleSettings`, which would be nice to add.

**Comment by AlexanderSehr** [comment]
Hey @jceval & @ilhaan,
Please triage the issue when you get the chance 🙂

**Comment by peterbud** [comment]
This has been open for 2 months without response. Should I submit a PR for this myself?

**Comment by AlexanderSehr** [comment]
> This has been open for 2 months without response. Should I submit a PR for this myself?

Hey @peterbud, I'll ping the owners internally

**Comment by jceval** [comment]
@peterbud @AlexanderSehr - looking into this

**Comment by peterbud** [comment]
Hi @jceval, I was looking for the `versionUpgradeOption` primarily, and just saw that there are other params which are not covered by the current module. If they are deprecated, then obviously no need to add them.

**Comment by jceval** [comment]
@peterbud changes coming in #4034 if you want to take a look.

**Comment by jceval** [comment]
@peterbud thanks for the patience on this issue. Changes have been merged to main in PR #4034
