### ISSUE TITLE
[AVM Module Issue]: Databricks Feature request customNetworkInterfaceName on DBFS storage

### ISSUE THREAD

**Issue by awood86** [Azure/bicep-registry-modules#3580]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/databricks/workspace

### (Optional) Module Version

0.8.3

### Description

Hi,

I don't think there's an option for the Storage account private endpoints to have a custom NIC name

@batchSize(1)
module storageAccount_storageAccountPrivateEndpoints 'br/public:avm/res/network/private-endpoint:0.7.1' = [
  for (privateEndpoint, index) in (storageAccountPrivateEndpoints ?? []): if (privateStorageAccount == 'Enabled') {
    name: '${uniqueString(deployment().name, location)}-workspacestorage-PrivateEndpoint-${index}'
    scope: resourceGroup(privateEndpoint.?resourceGroupName ?? '')
    params: {
      name: privateEndpoint.?name ?? 'pep-${_storageAccountName}-${privateEndpoint.service}-${index}'
      privateLinkServiceConnections: privateEndpoint.?isManualConnection != true
        ? [
            {
              name: privateEndpoint.?privateLinkServiceConnectionName ?? '${_storageAccountName}-${privateEndpoint.service}-${index}'
              properties: {
                privateLinkServiceId: _storageAccountId
                groupIds: [
                  privateEndpoint.service
                ]
              }
            }
          ]
        : null

Could this be added in? Unless I'm reading this wrong too.

Thanks

**Comment by clintgrove** [comment]
Hi. Sorry for late responses here. The customNetworkInterfaceName is present in the bicep template. I will spend some time Friday 1 Nov to go through this issue and see if its a simple fix or explanation of how to get it in

**Comment by clintgrove** [comment]
I had a look at this, the functionality is there, all you have to do in your deployment when call AVM bicep for Databricks is **add** (like I did when testing) this row in when and if you add "storageAccountPrivateEndpoints"

![Image](https://github.com/user-attachments/assets/4b5de33a-c1d6-4f08-985d-295a9609a530)

If you feel like we should add this in the WAF example (remembering that the example is just there for demonstration purposes, and you can call the AVM using this method https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/databricks/workspace#example-3-waf-aligned (and you would use this method and add the customNetworkInterfaceName: 'yourcustomnamehere'

**Comment by awood86** [comment]
@clintgrove thanks! I was putting the name in the wrong location 🤦‍♂️

![Image](https://github.com/user-attachments/assets/4f00bd77-f1a7-4404-934e-8f42e9de026d)
