### ISSUE TITLE
[AVM Module Issue]: SQL Server Database Geo Secondary replica bug with attaching to ElasticPool, SKU Name and Tier should be NULL instead of defaults

### ISSUE THREAD

**Issue by Bash-** [Azure/bicep-registry-modules#3581]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/sql/server

### Description

SQL Server Database Geo Secondary replica bug with attaching to ElasticPool, SKU Name and Tier should be NULL instead of defaults.

What I am doing: create a secondary SQL Server with databases in createMode: 'Secondary' and secondaryType: 'Geo' based on another SQL server. I am copying multiple databases and would like to make them part of an ElasticPool. 

Normally you would set this by providing skuTier: 'Standard' and skuName: 'ElasticPool' to the database properties and setting the elasticPoolId.
However, in case of a database with createMode 'Secondary' and using an ElasticPool it seems that the skuTier and skuName should not be filled (as it will take this from the original database?)

However, when I leave skuTier and skuName from the configuration, this module template falls back to default values of skuTier GeneralPurpose and skuName GP_Gen5_2.

I do not know exactly how it works with the secondary taking over skuTier and skuName, but I now had to work around this issue, hope someone can get it further.

**Comment by peterbud** [comment]
Hi @Bash- , thanks for raising the issue. 

Can you share the relevant part of your bicep file to be able to reproduce the error?

> Normally you would set this by providing skuTier: 'Standard' and skuName: 'ElasticPool' to the database properties and setting the elasticPoolId.

Are you sure there is an 'ElasticPool' SKU available? In which region? I run this to get the list of available SKUs, and I don't have such SKU:
```
az sql db list-editions -l westus2 -o table 
```

Maybe it depends on the given subscription?
