### ISSUE TITLE
[AVM CI Environment Issue]: Update readme to include nullable property to parameter usage

### ISSUE THREAD

**Issue by eriqua** [Azure/bicep-registry-modules#3593]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Update the readme utility to detail if a parameter is nullable (`nullable: true`) in the parameter usage section

**Comment by ReneHezser** [comment]
Could be included in #3456
