### ISSUE TITLE
[AVM Module Issue]:

### ISSUE THREAD

**Issue by bartmars** [Azure/bicep-registry-modules#3599]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/compute/virtual-machine

### Description

I'd like to request a feature for adding the userdata parameter when creating a virtual machine with this Bicep template. The current template already has provided the customdata parameter , but we use specific Azure Marketplace Images (Cisco ISE) that seem to require the userdata parameter. This parameter is not available (to my knowledge) in the current versions of this template. 

The reason why I'm asking is because Cisco ISE in Azure needs to do a cloud-init script after starting the VM, which seems to be only working with the userdata parameter. If the field is not set up, then the deployment of the server fails. 

This is my first time requesting a feature request, so if I'm missing something here please let me know.

**Comment by rahalan** [comment]
@bartmars thanks for the idea. Will look into it

**Comment by rahalan** [comment]
@bartmars will be added with PR #3756

**Comment by bartmars** [comment]
> [@bartmars](https://github.com/bartmars) will be added with PR [#3756](https://github.com/Azure/bicep-registry-modules/pull/3756)

That's great @rahalan, thanks!
