### ISSUE TITLE
[AVM Module Issue]: Add support for failoverGroups at `avm/res/sql/server`

### ISSUE THREAD

**Issue by brneu** [Azure/bicep-registry-modules#3609]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/sql/server

### Description

Request the SQL Server AVM support the failover groups provider in Bicep:
Microsoft.Sql/servers/failoverGroups

**Comment by peterbud** [comment]
Yes, there are quite a few modules under SQL Server which don't have yet support in the AVM. We'll tackle them in the future.

**Comment by AlexanderSehr** [comment]
> Yes, there are quite a few modules under SQL Server which don't have yet support in the AVM. We'll tackle them in the future.

Hey @peterbud,
please note that I removed the following tags on your behalf:
![Image](https://github.com/user-attachments/assets/63b56bbe-cbd1-4349-b019-4232e551d3ac)

As per the messages of the @microsoft-github-policy-service, you should modify them once your triaged an issue to stop it from notifying you that you should triage it 😉
