### ISSUE TITLE
[AVM Module Issue]: Signal R Service has no option for managed identity

### ISSUE THREAD

**Issue by riosengineer** [Azure/bicep-registry-modules#3618]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/signal-r-service/signal-r

### (Optional) Module Version

0.5.0

### Description

I cannot see any way in the current AVM module for the Signal R service to enable even a system assigned managed identity for the resource. 

I've checked the source code module and can only see reference to a delegated assigned identity, and so it appears there is no way to enable this from AVM at present. 

The module also appears to be orphaned and I am not sure this constitutes enough to be a 'security bug' but I would welcome the improvement to the module. 

Thanks

**Comment by ReneHezser** [comment]
@riosengineer in case you didn't get a notification otherwise, this one is done ;-)

**Comment by riosengineer** [comment]
> @riosengineer in case you didn't get a notification otherwise, this one is done ;-)

I did, deployed the update this morning 😎 thank you for your work on it. I was following the PR 🫡
