### ISSUE TITLE
[AVM Question/Feedback]: PolicyDefinition module migration from CARML

### ISSUE THREAD

**Issue by dibcar** [Azure/bicep-registry-modules#3619]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Hello, 

I would like to know why the CARML modules for policyDefinition have not been migrated to AVM and if they will be in a future release.

Thanks,

**Comment by AlexanderSehr** [comment]
Hey @dibcar,
great question. 💪  The answer of the status quo can be found in the current [role assignment](https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/authorization/role-assignment) and [policy assignment](https://github.com/Azure/bicep-registry-modules/blob/main/avm/ptn/authorization/policy-assignment/) modules you can find published to AVM: If you're referencing either module in your solution template you must always deploy them via the management group scope, even if you want to apply their magic to let's say the subscription level. 
The reason this is the case today, is that only top-level modules are published (e.g., key vault) - as opposed to CARML where the CI would also publish the child-modules as their own seperate instances (e.g., key vault keys). The latter had the charm that you could directly reference e.g. the [policy-definition-subscription](https://github.com/Azure/ResourceModules/blob/v0.11.1/modules/authorization/policy-definition/subscription/main.bicep) module in your deployment, when referencing a Private Bicep Registry or Template Specs.

Now, while we're trying to get the chid-module publishing working (you'd find many such asks in the issues of this repository), the more realistic scenario is that we'll get proper 'multi-scope' module support first. This feature is documented in this issue [859](https://github.com/Azure/bicep-registry-modules/issues/859#issuecomment-2320160505) and would essentially allow us to publish the nested scopes of e.g., the role assignment, policy assignment or policy defintion modules as their own top-level resource module.

Sure, we could also migrate the policy definition module as we did the policy assignment & role assignment ones, but I'd probably argue it would only provide so much added value over the native resource type implementation. Mind you, as opposed to most other resource modules, the authorization namespace modules have only very few added properties / logic compared to the native implementation.

Finally, I do not want to discourage you from suggesting the migration regardless. You can do this via [this issue form](https://github.com/Azure/Azure-Verified-Modules/issues/new?template=module_proposal.yml). I'd however propose to wait with the actual implementation until after the CI supports multi-scoped modules properly. 

I hope the above did provide the desired insights. If so, I'd suggest to close the issue in favor of a module proposal :)
