### ISSUE TITLE
[AVM Module Issue]: SearchService - Can't use `secretsExportConfiguration`

### ISSUE THREAD

**Issue by jolerasioo** [Azure/bicep-registry-modules#3636]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/search/search-service

### (Optional) Module Version

0.7.0

### Description

I copy-pasted the sample code to try [Default and deploying keys to azure key vault with](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/search/search-service#example-2-deploying-with-a-key-vault-reference-to-save-secrets) version 0.7.0 and the key vault object parameter is automatically flagged as `not permitted`. I went into the module and I see it's declare so I don't know exactly where the issue is. I just wanted to raise it for awareness or to be corrected if I missed something.

![Image](https://github.com/user-attachments/assets/5fb21911-0386-44fc-92f3-05d060e9a370)
![Image](https://github.com/user-attachments/assets/0e9fa060-8ac7-43ff-bdad-1f3e84da1d2b)

My code:
```
param location string = resourceGroup().location

param kvName string

param envName string = 'dev'

param aiSeachName string = 'ai-search-${uniqueString(resourceGroup().id)}-${envName}}'

@allowed([
  'free'
  'disabled'
  'standard'
])
@description('Configuration for semantic search, dependent on region and SKU')
param semanticSearchConfig string = 'free'

resource kv 'Microsoft.KeyVault/vaults@2024-04-01-preview' existing ={
  name: kvName
}

module searchService 'br/public:avm/res/search/search-service:0.7.0' = {
  name: 'searchServiceDeployment'
  params: {
    // Required parameters
    name: aiSeachName
    // Non-required parameters
    authOptions: {
      aadOrApiKey: {
        aadAuthFailureMode: 'http401WithBearerChallenge'
      }
    }
    disableLocalAuth: false
    location: location
    semanticSearch: semanticSearchConfig
    // issue gets flagged here
    secretsExportConfiguration: {
      keyVaultResourceId: kv.id
      primaryAdminKeyName: 'Primary-Admin-Key'
      secondaryAdminKeyName: 'Secondary-Admin-Key'
    }
  }
}

```

**Comment by jolerasioo** [comment]
Link with the sample I used: https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/search/search-service#example-2-deploying-with-a-key-vault-reference-to-save-secrets

**Comment by krbar** [comment]
@jolerasioo Could you please test with the version 0.7.1 or newer? I think the 0.7.0 didn't support `secretsExportConfiguration`.
