### ISSUE TITLE
[AVM Module Issue]: cannot set `ipTags` for `network/public-ip-address`

### ISSUE THREAD

**Issue by KLuuKer** [Azure/bicep-registry-modules#3652]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/public-ip-address

### (Optional) Module Version

0.6.0

### Description

I'm unable to configure `ipTags: [ { ipTagType: 'RoutingPreference', tag: 'Internet' } ]`
which is needed to set the routing preference to internet, instead of the normal azure network routing

https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/routing-preference-portal?tabs=azurepowershell

this is useful for certain cost savings when integrating with other cdn services

**Comment by krbar** [comment]
@KLuuKer thanks for reporting the issue, a module update is coming.
