### ISSUE TITLE
[AVM Module Issue]: main.bicep capped at Management Group scope while it should target all scopes.

### ISSUE THREAD

**Issue by KrazeyKami** [Azure/bicep-registry-modules#3659]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/ptn/authorization/role-assignment

### (Optional) Module Version

0.2.0

### Description

When trying to use the module to set a role on a resource group, I get the following error:
_Scope "resourceGroup" is not valid for this module. Permitted scopes: "managementGroup".bicep[BCP134]_

On inspection of the main.bicep, it has the targetscope capped at Management group.
The respective modules are having the correct scope though.

Currently working around this issue by d/l the module and referencing it from my own location.

**Comment by arnoldna** [comment]
There is an open issue related to this issue #2688.
