### ISSUE TITLE
[AVM Module Issue]: IPv6 support for `avm/res/network/public-ip-prefix`

### ISSUE THREAD

**Issue by cmezach** [Azure/bicep-registry-modules#3673]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/public-ip-prefix

### (Optional) Module Version

0.5.1

### Description

The module currently only supports Public IP prefixes, can you add support for IPv6 Public IP Prefixes?

**Comment by krbar** [comment]
@cmezach thanks for reporting it. Actually the timing was very good, I was just about to update this module. The PR is in review, see above.
