### ISSUE TITLE
[AVM Module Issue]: Boot Diagnostics has wrong parameter value

### ISSUE THREAD

**Issue by FallenHoot** [Azure/bicep-registry-modules#3713]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine-scale-set

### (Optional) Module Version

0.4.0

### Description

Unable to enable Boot Diagnostics, because parameter is configured wrong. It needs boolen, but requesting a string. After looking into it more deeply, the Microsoft best practice is to not include a storage account, but that can be optional. The  [learn docs](https://learn.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics) state that all you need is the enabled `true` or `false`

```
bootDiagnostics: {
          enabled: !empty(bootDiagnosticStorageAccountName)
          storageUri: !empty(bootDiagnosticStorageAccountName)
            ? 'https://${bootDiagnosticStorageAccountName}${bootDiagnosticStorageAccountUri}'
            : null
}
```

Feedback:
After looking into this for VMs and VMSS, I noticed this has the same issue. `bootDiagnosticEnabled ` needs to be a param to allow the users to decide if they should use the Microsoft best practice managed storage or the optional secure standalone storage account. 

Suggested fix:

```
@description('Optional. Enable boot diagnostics to use default managed or secure storage. Defaults to false.')
param bootDiagnosticEnabled bool = false

@description('Optional. The name of the boot diagnostic storage account. Provide this if you want to use your own storage account for security reasons instead of the recommended Microsoft Managed Storage Account.')
param bootDiagnosticStorageAccountName string?

@description('Optional. The URI of the boot diagnostic storage account.')
param bootDiagnosticStorageAccountUri string?

bootDiagnostics: {
  enabled: bootDiagnosticEnabled
  storageUri: !empty(bootDiagnosticStorageAccountName) ? 'https://${bootDiagnosticStorageAccountName}${bootDiagnosticStorageAccountUri}' : null
}

```

Happy to create a PR if needed.

**Comment by rahalan** [comment]
@FallenHoot , thank you. Please submit a PR!
