### ISSUE TITLE
[AVM Question/Feedback]: FinOpsToolKit/FinOpsHub Resource Naming Parameters Implementation

### ISSUE THREAD

**Issue by plaplainabf** [Azure/bicep-registry-modules#3740]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Within bicep-registry-modules/avm/ptn/finops-toolkit/finops-hub, it would be really useful if the module had parameters for the resource names. Most companies have their own naming standard in Azure and we have our own bicep naming standards module, so effectively we would want to get the storage account, key vault and data factory names from our own module then ideally pass it through to this module.

A quick look I believe the main.bicep would need updating and the keyvault.bicep would also need parameters implementing. This would make updates a lot easier as we could simply change the version of the bicep we're targeting.

Main.bicep should be relatively easy to update, just needs the following converting to parameters, a parameter creating for the key vault name. Also setting default values for the parameters to prevent current deployments breaking.
![Image](https://github.com/user-attachments/assets/563611a9-5b04-494f-83a8-e08fbe96850d)

The keyvault.bicep should just need a keyVaultName parameter defining and remove where keyVaultName is currently defined. Potentially adding in some logic to set a default name if no value is passed to prevent current deployments breaking.

**Comment by flanakin** [comment]
@plaplainabf can you create this suggestion in the FinOps toolkit repo where FinOps hubs is managed?

**Comment by plaplainabf** [comment]
Sorry about that @flanakin I've now posted it under that repo :)
https://github.com/microsoft/finops-toolkit/issues/1105
