### ISSUE TITLE
[AVM Module Issue]: slot app settings only applied if appSettingsKeyValuePairs not empty

### ISSUE THREAD

**Issue by umennel** [Azure/bicep-registry-modules#3744]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/site

### (Optional) Module Version

latest (0.11.1)

### Description

Slot app settings for storage account and app insights are not applied, unless other app settings are specified with `appSettingsKeyValuePairs`. 
I already looked at the source code and tracked down the issue:
In `bicep-registry-modules/tree/main/avm/res/web/site/main.bicep`:
```bicep
module app_appsettings 'config--appsettings/main.bicep' = if (!empty(appSettingsKeyValuePairs) || !empty(appInsightResourceId) || !empty(storageAccountResourceId)) {
```
In `bicep-registry-modules/tree/main/avm/res/web/site/main.bicep`:
```bicep
module slot_appsettings 'config--appsettings/main.bicep' = if (!empty(appSettingsKeyValuePairs)) {
```

The lines should be identical to have the same behavior for specifying slot app settings.

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy,
please triage this issue when you get the chance 🚀
