### ISSUE TITLE
[AVM Module Issue]: Ask for outboundIpAddresses as an output from Microsoft.Web/sites

### ISSUE THREAD

**Issue by wchigit** [Azure/bicep-registry-modules#3782]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### Description

Could the module output the outbound IPs of an app service, i.e. possibleOutboundIpAddresses in the app service property?

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy,
Please triage this issue when you get the chance 💪
