### ISSUE TITLE
feat: Subscription Vending - NRP issue

### ISSUE THREAD

**Issue by ReneHezser** [Azure/bicep-registry-modules#3783]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/ptn/lz/sub-vending

### Description

Sometimes the deployment will fail with ```"code": "SubscriptionNotRegistered", "message": "Subscription xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx is not registered with NRP."```.

Since the deployment script also uses networking to create a VNet (at least in my cases), should we wait or retry after the subscription has been created?

This happened in a customer environment, as well as in the GitHub action of the module.

**Comment by sebassem** [comment]
@ReneHezser 
I did some testing, and I think this problem was interment for the customer; Before the deployment script runs, a virtual network is created which automatically registers the Microsoft.Network resource provider as with any normal ARM/Bicep deployment.

**Comment by sebassem** [comment]
> I did some testing, and I think this problem was interment for the customer; Before the deployment script runs, a virtual network is created which automatically registers the Microsoft.Network resource provider as with any normal ARM/Bicep deployment.

@ReneHezser is it ok to close it with this answer ?

**Comment by ReneHezser** [comment]
Thanks @sebassem . We can close it.
