### ISSUE TITLE
[AVM Module Issue]: frontdoor not able to validate dns for custom domains

### ISSUE THREAD

**Issue by nitinitare** [Azure/bicep-registry-modules#3790]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/cdn/profile

### (Optional) Module Version

0.7.1

### Description

This module not adding the CNAME record and TXT record for custom domains. How to validate dns automatically using this AVM module. 
Also, It doesn't output the custom domain validation token and endpoint hostname.

**Please provide an example.**

**Comment by gbeaud** [comment]
@nitinitare thanks for raising this issue; it's already tracked under this issue which I will be working on [](https://github.com/Azure/bicep-registry-modules/issues/3371#issuecomment-2400156291)

If you're ok I will close this one and you can track the other one? Thanks

**Comment by nitinitare** [comment]
@gbeaud Not sure if these issues are related. That issue is for key vault but this one specifically for Azure Frontdoor service. And it's related to DNS validation. When we add a domain, we need TXT record for validation and also CNAME record for the  custom domain. And that's not happening form this cdnprofile module.

Would request to keep this open.

**Comment by gbeaud** [comment]
@nitinitare sorry for some reason the link was not pointing to the right page, here is the issue: https://github.com/Azure/bicep-registry-modules/issues/3371

I think it is exactly what you're asking for; providing TXT values as outputs of the module for DNS validation, right? If you agree we can close the present issue and you can track the other one 😊👍 thanks
