### ISSUE TITLE
[AVM Module Issue]: ipSecurityRestrictions Added to Web/Function Apps

### ISSUE THREAD

**Issue by awood-ops** [Azure/bicep-registry-modules#3844]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/site

### (Optional) Module Version

0.11.1

### Description

Hi,

Could the ipSecurityRestrictions as part of the Web Site config be added to the module?

Thanks

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy,
Please triage this issue when you get the chance 💪

**Comment by awood-ops** [comment]
Thanks @AlexanderSehr

**Comment by AlexanderSehr** [comment]
> Thanks [@AlexanderSehr](https://github.com/AlexanderSehr)

Let's rather thank @tsc-buddy ;) I merely merged his PR

**Comment by awood-ops** [comment]
> > Thanks [@AlexanderSehr](https://github.com/AlexanderSehr)
> 
> Let's rather thank @tsc-buddy ;) I merely merged his PR


Haha sorry just woke up. Thanks @tsc-buddy!
