### ISSUE TITLE
[AVM Module Issue]:

### ISSUE THREAD

**Issue by JWHolding** [Azure/bicep-registry-modules#3847]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/automation/automation-account

### Description

Provide support within the module for creating runtime environments

**Comment by o-l-a-v** [comment]
There is only a preview API for this at the moment AFAIK:

* <https://learn.microsoft.com/en-us/azure/automation/manage-runtime-environment>
  * <https://learn.microsoft.com/en-us/azure/automation/manage-runtime-environment?tabs=create-runtime-rest#create-runtime-environment>

No mention of runtime environments in Bicep doc:

* <https://learn.microsoft.com/en-us/azure/templates/microsoft.automation/2023-11-01/automationaccounts>

But mentioned in API spec for `2023-05-15-preview`:

* <https://github.com/Azure/azure-rest-api-specs/blob/main/specification/automation/resource-manager/Microsoft.Automation/preview/2023-05-15-preview/account.json>

**Comment by elanzel** [comment]
Hello @JWHolding and @o-l-a-v , thank you for the request and the additional information.
Evaluating the approach to take, as what you are asking is a preview feature.
I'll be back with info about the development of the feature as soon i get them,
thank you

**Comment by elanzel** [comment]
Runtime Environment for automation account is not in GA: https://learn.microsoft.com/en-us/azure/automation/runtime-environment-overview
Referring to https://azure.github.io/Azure-Verified-Modules/specs/bcp/res/#id-sfr1---category-composition---preview-services we're not planning to implement this feature at the moment
