### ISSUE TITLE
[AVM Module Issue]: New parameter for virtual-network-link

### ISSUE THREAD

**Issue by alphasteff** [Azure/bicep-registry-modules#3848]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/private-dns-zone

### (Optional) Module Version

0.6.0

### Description

Hello everyone
I don't know if you are already adding preview features. We have the problem with Private DNS zones, which can be solved with the new feature: resolutionPolicy

More info:
https://learn.microsoft.com/en-us/azure/dns/private-dns-fallback

I hope you find time to implement it soon.

**Comment by ChrisSidebotham** [comment]
@alphasteff - Apologies for the delay, a fix is in PR now.
