### ISSUE TITLE
[AVM Module Issue]: avm/res/network/azure-firewall - enhance documentation for parameter hubIPAddresses

### ISSUE THREAD

**Issue by janegilring** [Azure/bicep-registry-modules#3872]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/azure-firewall

### Description

The documentation for the following parameter should be improved:

Parameter | Type | Description
-- | -- | --
hubIPAddresses | object | IP addresses associated with AzureFirewall. Required if virtualHubId is supplied.

There are no information about the schema for the parameter, and looking at the Bicep code reveals no information about the expected syntax:
https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/network/azure-firewall/main.bicep#L296

In order to determine this, we had to lookup the [documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.network/azurefirewalls?pivots=deployment-language-bicep):

```
    hubIPAddresses: {
      privateIPAddress: 'string'
      publicIPs: {
        addresses: [
          {
            address: 'string'
          }
        ]
        count: int
      }
    }
```

**Comment by eriqua** [comment]
Related to the more general #3641
