### ISSUE TITLE
[AVM Module Issue]: Missing diagnostic settings option on Front Door CDN profile

### ISSUE THREAD

**Issue by jonclyde** [Azure/bicep-registry-modules#3876]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cdn/profile

### Description

Hi,

I am using the the CDN profile AVM module to deploy Azure Front Door and need to enable diagnostic settings to a log analytics workspace. I require logs/metrics to be saved but most importantly the WAF logs to allow tuning. 

I can't seem to see a way of doing this with the current version of module https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cdn/profile/main.bicep. 

Is this a feature that needs to be added? Are there any alternative methods for enabling diagnostics as a workaround?

Cheers

Jon

**Comment by gbeaud** [comment]
Hi @jonclyde, thanks for sharing this! The WAF policy for Front Door is in another module: [https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/network/front-door-web-application-firewall-policy](url) and Front Door itself is in yet another module: [https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/network/front-door](url)

On the Front Door resource there are already some options for diagnostic settings:

![Image](https://github.com/user-attachments/assets/953db741-933f-4a51-ab1f-9426f9d9432e)

Please have a look if the diagnostic settings meet your expectations and if not, you should raise a feature request on the other repo - hope this helps and please let me know if I can close the present issue 😊
