### ISSUE TITLE
[AVM Module Issue]: DataFactory Private Endpoint issue

### ISSUE THREAD

**Issue by kevin-381ecc2e** [Azure/bicep-registry-modules#3878]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/data-factory/factory

### (Optional) Module Version

0.6.2'

### Description

We're trying to provision DataFactories with Private Endpoints. However we're unable to provision a privateEndpoint with the groupId: 'portal'.
The template has a hardcoded groupId of 'dataFactory' under the privateLink configuration.

https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/data-factory/factory/main.bicep#L328.

I'm receiving the error:

```json
[
PrivateIPAddress: XXX.XXX.XXX.XXX, 
GroupId: portal, 
MemberName: portal
]
 and its missing these membernames/groupids requested by Private Link service [GroupId: dataFactory, MemberName: dataFactory]. Private Endpoint needs to be reconfigured with missing memberNames.
```

**Comment by clintgrove** [comment]
Hi @kevin-381ecc2e  please can you explain more about "portal" I am not aware of this type. Also can you share a bit of the code you have implemented to give us a better idea of what the issue is?

**Comment by krbar** [comment]
Hi @kevin-381ecc2e , thanks for the additional info! I believe your code will deploy successfully if you add:

```bicep
service: 'portal'
```
as a property of the second private endpoint. If this property is not set, the module defaults to using `dataFactory`.

Typically, we set a default service only in modules that support a single private endpoint type. In this case, we apparently overlooked the `portal` sub-resource. To address this, we will release a new module version that does not include a default service.
