### ISSUE TITLE
[AVM Module Issue]: Missing RetentionPolicy property in diagnosticSettings.logCategoriesAndGroups property of Logic App Workflow definition

### ISSUE THREAD

**Issue by julianportelli** [Azure/bicep-registry-modules#3886]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/logic/workflow

### (Optional) Module Version

0.4.0

### Description

The `retentionPolicy` property is missing under `diagnosticSettings.logCategoriesAndGroups` in the AVM module. According to the [official Azure documentation](https://learn.microsoft.com/en-us/azure/templates/Microsoft.Insights/2021-05-01-preview/diagnosticSettings?pivots=deployment-language-bicep#retentionpolicy), this property is a critical part of the `diagnosticSettings` resource schema and is required to configure retention settings for diagnostic logs.

---

## Expected Behavior  

The `diagnosticSettings.logCategoriesAndGroups` should include a `retentionPolicy` property to allow users to configure log retention settings.  

**Example Configuration:**

```bicep
logCategoriesAndGroups: [
  {
    category: 'YourCategory'
    categoryGroup: 'YourCategoryGroup'
    retentionPolicy: {
      enabled: true
      days: 30
    }
  }
]

### (Optional) Correlation Id

_No response_

**Comment by lsnoddy** [comment]
Investigating...

**Comment by AlexanderSehr** [comment]
Hey @lsnoddy,
Let me jump in here. @julianportelli, please note that this setting was deprecated in favor of a setting on the storage account's side where the logs would be stored. I'll try to find the corresponding docs and link them here (has been a while ago).

**Comment by julianportelli** [comment]
> Hey [@lsnoddy](https://github.com/lsnoddy), Let me jump in here. [@julianportelli](https://github.com/julianportelli), please note that this setting was deprecated in favor of a setting on the storage account's side where the logs would be stored. I'll try to find the corresponding docs and link them here (has been a while ago).
> 
> Edit: Here we go: [ref](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy?tabsportal). [@julianportelli](https://github.com/julianportelli), I'd advice to leverage the recommended lifecycle management. I'll go ahead and close this issue. However, if you feel the link does not address the issue, you're welcome to open it again 🙂

Hi @AlexanderSehr, thanks for finding the link for me and letting me know about this deprecation, as I was not aware of it.
