### ISSUE TITLE
[AVM Module Issue]:  br/public:avm/res/network/application-gateway-web-application-firewall-policy:0.1.1

### ISSUE THREAD

**Issue by gsuttie** [Azure/bicep-registry-modules#3891]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/application-gateway-web-application-firewall-policy

### (Optional) Module Version

0.1.1

### Description

"details":[{"code":"ApplicationGatewayWafPolicyJSChallengeCookieExpirationNotSupportedForAPIVersion","message":"Specified api-version 2022-11-01 does not meet the minimum required api-version 2023-11-01 for JSChallenge cookie expiration in Firewall Policy for resource

The polisy module refers to Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies@2022-11-01

Can this be updated to  2023-11-01?

**Comment by AlexanderSehr** [comment]
Hey @ilhaan,
Please triage the issue when you get the chance 💪

**Comment by ilhaan** [comment]
@gsuttie do we know for sure that the new version will address this issue? Do you have any docs showing this?
