### ISSUE TITLE
[AVM Module Issue]: wrong RBAC roles defined for Static Web App

### ISSUE THREAD

**Issue by zensqlmonitor** [Azure/bicep-registry-modules#3898]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/static-site

### Description

Hi,

proposed buit-roles are **not** all related to Static Web App but to App Service:
- [Web Plan Contributor ](https://github.com/Azure/bicep-registry-modules/blob/a2373345b7b2af6ef867c728616a3d59f5e40589/avm/res/web/static-site/main.bicep#L115)
- [Website Contributor](https://github.com/Azure/bicep-registry-modules/blob/a2373345b7b2af6ef867c728616a3d59f5e40589/avm/res/web/static-site/main.bicep#L119)

I tried to get the secret/token from a Static Web App using a managed identity and this requires the permission:: Microsoft.Web/staticSites/listSecrets/action

It looks that the service is still missing some standard RBAC role for Microsoft.Web/staticSites.
Could you please fix this.

**Comment by ChrisSidebotham** [comment]
Hi @zensqlmonitor,

Please can you provide more details, Website Contributor is used for Static Web Apps. Please see the listed available roles below, Regarding your SMID, Can you elaborate further

Job Roles:
![Image](https://github.com/user-attachments/assets/7de1812b-8838-4500-89e6-bfd0d7a5239f)

Privileged Roles:
![Image](https://github.com/user-attachments/assets/8f1d5d68-ce93-4ea1-9d1d-162d201a7866)

**Comment by ChrisSidebotham** [comment]
@zensqlmonitor - I see your point here, however removing the roles from the template is non-functional change. As the portal still shows 'Website Contributor' as a valid role for the Static Site we would not remove this at this time. 

As you stated though, there are no built in roles for the function you desire except for privileged roles. I am unsure what the expected next steps are here with this?

**Comment by zensqlmonitor** [comment]
@ChrisSidebotham It looks like the portal is wrong also. I suppose I have to open another ticket in the Azure support as you are not communicating between product teams at Microsoft. Correct? 
The Static Web Apps is a service provided for more than 3 years and still not any built-in RBAC roles ?

**Comment by ChrisSidebotham** [comment]
As this is more product support, I would say you are best to raise this via your support channel. From an AVM and Bicep PG point of view I believe there is nothing we can do here. I can remove the other role from the module, but it is purely a non-functional effect here as it does not affect the way the static site is used. 

And yes, you are correct, there is no 'job function' specific roles for the Static Apps at this point.

**Comment by zensqlmonitor** [comment]
Thanks @ChrisSidebotham
