### ISSUE TITLE
[AVM Module Issue]: Change @allowed values in "kind" to lowercase to match actual values

### ISSUE THREAD

**Issue by sajense** [Azure/bicep-registry-modules#3909]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/web/serverfarm

### Description

Current values allowed are using upper-case letters, which is causing a modify to happen at every run.
 ```
@description('Optional. Kind of server OS.')
@allowed([
  'App'
  'Elastic'
  'FunctionApp'
  'Windows'
  'Linux'
])
param kind string = 'App'
 ```
What-if output: 
 ```
  ~ Microsoft.Web/serverfarms/asp-xxx-xxx [2022-09-01]
    ~ kind:                                 "linux" => "Linux"
 ```
The ``allowed`` decorator is case-sensitive, so values must be fixed in the module
```
@description('Optional. Kind of server OS.')
@allowed([
  'app'
  'elastic'
  'functionapp'
  'windows'
  'linux'
])
param kind string = 'app'
```

It's not causing a functional issue, it's just kind of annoying always seeing this in every pipeline run.

**Comment by pankajagrawal16** [comment]
Hi @sajense Thanks for opening the issue. It makes sense. In order to be backward compatible, we can lowercase it inside module itself.
