### ISSUE TITLE
[AVM Module Issue]:

### ISSUE THREAD

**Issue by brettmillerb** [Azure/bicep-registry-modules#3913]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/automation/automation-account

### (Optional) Module Version

0.11.0

### Description

The Azure Modules List states that the latest version is `0.11.0` but this isn't available and the latest version is actually `0.9.1`

![Image](https://github.com/user-attachments/assets/e1fa7786-eea2-4a7d-8217-45fe4b7f7c52)

**Comment by elanzel** [comment]
Hi @brettmillerb there issue is related to your local deployment. 

As you can see in the following test, i referenced 'br/public:avm/res/automation/automation-account:0.11.0' and that is found
![Image](https://github.com/user-attachments/assets/2d46e250-1c9e-4182-90c7-d9c7fa0bdce3)

**Comment by brettmillerb** [comment]
Hi @elanzel 

I tried this again today and it seemed to work. I didn't change anything other than pull an earlier version first.

Not sure what the issue was but it appears to be working now 🤷‍♂

**Comment by elanzel** [comment]
Thank you for your feedback @brettmillerb and for closing the issue :-)
