### ISSUE TITLE
[AVM Module Issue]: how to enable endtoendtlsencrytion on function app

### ISSUE THREAD

**Issue by nitinitare** [Azure/bicep-registry-modules#3929]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/web/site

### (Optional) Module Version

0.12.0

### Description

How to enable end to end tls encryption on function app. I have tried adding property endToEndEncryptionEnabled: true in siteconfig but still it is set to false. Seems it is missing in module.

![Image](https://github.com/user-attachments/assets/211bb84f-c68a-4a9c-9fda-370005577f85)
learn more: https://techcommunity.microsoft.com/blog/appsonazureblog/end-to-end-e2e-tls-encryption-preview-on-linux-multi-tenant-app-service-resource/3976646

**Comment by AlexanderSehr** [comment]
Hey @tsc-buddy,
please review this issue and triage it when you can 💪
