### ISSUE TITLE
[AVM Module Issue]: Web/Sites

### ISSUE THREAD

**Issue by gsuttie** [Azure/bicep-registry-modules#3934]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/site

### Description

Is this setting just missing? 

endToEndEncryptionEnabled or am i missing something?

I see it in the docs but It doesnt seem to be working

https://learn.microsoft.com/en-us/azure/templates/microsoft.web/change-log/sites

Thanks
Gregor

**Comment by AlexanderSehr** [comment]
Hey @pankajagrawal16  & @tsc-buddy,
please triage this issue if possible (as per the comments). Thanks 💪
