### ISSUE TITLE
[Module Proposal]: Azure OpenAI

### ISSUE THREAD

**Issue by OmegaVVeapon** [Azure/bicep-registry-modules#398]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We require a base module to create Azure OpenAI instances.
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/overview

Like Speech Services, this is another cognitive service so it'll follow the path set by the module pending merge in https://github.com/Azure/bicep-registry-modules/issues/248

### Module path

cognitiveservices/openai

### Describe the module

Allows the provisioning and management of Azure OpenAI, including pricing plan selection and support for VNET integration via private endpoints.

**Comment by dciborow** [comment]
I'm aligned with this one.

@OmegaVVeapon , is this something you could propose? I'm happy to support you on this and help.

**Comment by OmegaVVeapon** [comment]
I'm closing this.
It was already completed as part of #404.
