### ISSUE TITLE
[Module Proposal]: Azure Content Moderator

### ISSUE THREAD

**Issue by OmegaVVeapon** [Azure/bicep-registry-modules#399]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We require a base module to create Azure Content Moderator instances.
https://learn.microsoft.com/en-us/azure/cognitive-services/content-moderator/overview

### Module path

cognitiveservices/content-moderator

### Describe the module

Allows the provisioning and management of Azure Content Moderator, including pricing plan selection and support for VNET integration via private endpoints.

**Comment by dciborow** [comment]
Will work on this one with @OmegaVVeapon  in parallel to #398

**Comment by OmegaVVeapon** [comment]
I'm closing this.
It was already completed as part of https://github.com/Azure/bicep-registry-modules/pull/404.
