### ISSUE TITLE
[Module Proposal]:  Azure Bing Resource 

### ISSUE THREAD

**Issue by tanujbhatia1708** [Azure/bicep-registry-modules#401]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We require a base module to create Azure Bing Resources.
https://learn.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-web-api-v7-reference

### Module path

cognitiveservices/bing-resource

### Describe the module

Allows the provisioning and management of Azure Bing Resource including pricing plan selection

**Comment by shenglol** [comment]
As suggested in https://github.com/Azure/bicep-registry-modules/pull/407#issuecomment-1619014411, we should consider change the module path to `ai/bing-search`.

**Comment by ChrisSidebotham** [comment]
Dear @tanujbhatia1708 , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, module proposals for new, non-AVM modules will no longer be accepted and we encourage you to propose a new AVM module, which you can file here: Module Proposal, [here](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
