### ISSUE TITLE
[Bug Report]: Auto generating new version isn't working as expected in fork-on-push-brm-generate workflow.

### ISSUE THREAD

**Issue by sunilthorat09** [Azure/bicep-registry-modules#437]
### Module path

/modules/

### Bicep version

0.18.4

### Describe the bug

Auto generation of new tag version isn't working as expected in `on push brm generate` workflow that runs in forked repo.

### To reproduce

GH action workflow link - https://github.com/sunilthorat09/bicep-registry-modules/actions/runs/5451970068/jobs/9918855928

In this workflow, the updated module is `ai/cognitiveservices` and under `bump version and push tag` step the previous version isn't correctly calculated. Its setting to `0.0.0` instead of latest available `1.0.2`.  

and next `update version` step updates incorrect version in readme.md file as seen in https://github.com/Azure/bicep-registry-modules/commit/ce222f039d08ee5e4496eff540790b2f355904d0.

**Comment by ChrisSidebotham** [comment]
Dear @sunilthorat09, Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
