### ISSUE TITLE
[Bug Report]: ai/cognitive-services fails deployment test

### ISSUE THREAD

**Issue by StephenWeatherford** [Azure/bicep-registry-modules#450]
### Module path

/modules/ai/cognitive-services

### Bicep version

Bicep CLI version 0.19.5 (87ca110fc0)

### Describe the bug

Blocks https://github.com/Azure/bicep-registry-modules/pull/433

See https://github.com/Azure/bicep-registry-modules/pull/433/checks?check_run_id=15217188020

[31;1mNew-AzResourceGroupDeployment: [31;1m9:06:59 PM - Error: Code=InvalidTemplateDeployment; Message=The template deployment 'main.test' is not valid according to the validation procedure. The tracking id is '36dc8f5f-095c-4fd2-add8-811d50378a55'. See inner errors for details.
[0m
[31;1mNew-AzResourceGroupDeployment: [31;1m9:06:59 PM - Error: Code=DeploymentModelNotSupported; Message=Creating account deployment is not supported by the model 'text-davinci-002'. This is usually because there are better models available for the similar functionality.
[0m
[31;1mNew-AzResourceGroupDeployment: [31;1mThe deployment validation failed[0m

### To reproduce

https://github.com/Azure/bicep-registry-modules/pull/433

**Comment by StephenWeatherford** [comment]
@omegavveapon

Not clear to me what the correct replacement is.

**Comment by OmegaVVeapon** [comment]
> @OmegaVVeapon
> Not clear to me what the correct replacement is.

Looked up the error you got from the RP and it seems like as of July 7th, it's `gpt-35-turbo`.
See: https://github.com/Azure-Samples/jp-azureopenai-samples/pull/47/files

I'll submit a PR to amend the example.

**Comment by ChrisSidebotham** [comment]
Dear @StephenWeatherford , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
