### ISSUE TITLE
Dependabot Support for Bicep Modules

### ISSUE THREAD

**Issue by dciborow** [Azure/bicep-registry-modules#452]
While Dependabot support for ARM api versions  would require a lot of unique work, supporting bicep modules should be much easier. 

Dependabot already has hooks for versioning based in a container registry. This is particularly how terraform is supported in Dependabot.

Users should be able to use dependabot for both our public modules, as well as private modules from their own container registry.

**Comment by macel94** [comment]
upvote x1000

please please please implement this

**Comment by ChrisSidebotham** [comment]
@dciborow / @shenglol - Should this live in the Bicep repo?
