### ISSUE TITLE
[Module Proposal]: Role assignments

### ISSUE THREAD

**Issue by shenglol** [Azure/bicep-registry-modules#48]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

It would be great to have a module to simplify role assignments.

### Module path

identity/role-assignment

### Describe the module

The module contains a role assignment resource. It takes an array of role definition IDs as a parameter to enable batch role assignments.

**Comment by wsmelton** [comment]
Not sure why this was closed but it is needed.

Modules being published are not consistent on whether they include assigning RBAC or not. Key Vault does, but the Storage Account module does not.

If you publish modules that include the RBAC/IAM baked in that is more to maintain on the module (in my view). Publishing a Role Assignment module puts the ownership on the user consuming it for assigning access to resources being deployed. (We are doing this in our private registry.)

If this is re-opened, please allow the user-friendly name of the role and do not make users lookup the IDs.

**Comment by alex-frankel** [comment]
I think the issue is that we need to finish https://github.com/azure/bicep/issues/2246 in order to make a module like this realistic. 

>If this is re-opened, please allow the user-friendly name of the role and do not make users lookup the IDs.

Agreed we should get this done. That is tracked here: https://github.com/Azure/bicep/issues/1895
