### ISSUE TITLE
[Bug Report]: Documentation for

### ISSUE THREAD

**Issue by alastairwigg** [Azure/bicep-registry-modules#526]
### Module path

/modules/storage/cosmos-db

### Bicep version

N/A

### Describe the bug

The README for the `/modules/storage/cosmos-db` gives incorrect examples for configuring private endpoints.

This syntax is incorrect, the format does not match the expected custom type -

Incorrect: 
```
privateEndpoints: {
      endpoint1: {
        subnetId: dependencies.outputs.subnetIds[0]
        isManualApproval: true
        groupId: 'Sql'
      }
      endpoint2: {
        subnetId: dependencies.outputs.subnetIds[1]
        privateDnsZoneId: dependencies.outputs.privateDNSZoneId
        groupId: 'Gremlin'
      }
    }
  }
```

Correct:
```
privateEndpoints: [
    {
      name: 'endpoint1'
      subnetId: dependencies.outputs.subnetIds[0]
      groupId: 'Sql'
    }
]
```
https://github.com/Azure/bicep-registry-modules/blob/2bfceaa924e59bea4d7783cc3e1354745f58955c/modules/storage/cosmos-db/README.md?plain=1#L399

### To reproduce

To reproduce try to configure a private endpoint as per the README

**Comment by ChrisSidebotham** [comment]
@alastairwigg - Have you checked out the AVM Module https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/document-db/database-account which uses a common interface accross all AVM Module for deploying private endpoints. 

Is we don't receive a response for 3 days I will close this issue :)

**Comment by ChrisSidebotham** [comment]
Dear @alastairwigg , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
