### ISSUE TITLE
[Module Proposal]: Azure Service Bus

### ISSUE THREAD

**Issue by OmegaVVeapon** [Azure/bicep-registry-modules#540]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We require a base module to create Azure Service Bus instances.
https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview

### Module path

storage/service-bus

### Describe the module

Allows the provisioning and management of Azure Service Bus, including the creation of Queues and Topic + Subscriptions.

**Comment by shenglol** [comment]
I'd suggest changing the module path to `messaging/service-bus`.

**Comment by OmegaVVeapon** [comment]
> I'd suggest changing the module path to `messaging/service-bus`.

Sounds good to me.

**Comment by ChrisSidebotham** [comment]
@OmegaVVeapon - [avm/res/servicebus/namespace](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/service-bus/namespace) has now been published by the AVM Team along with all child modules. does this suffice on this requirement?

**Comment by ChrisSidebotham** [comment]
Closing issue as Service Bus module has been published
