### ISSUE TITLE
Make enhancements to `generate-module-index-data.js

### ISSUE THREAD

**Issue by jtracey93** [Azure/bicep-registry-modules#543]
Now that  `generate-module-index-data.js` is working for AVM modules we should tidy and improve the file on the following points:

~~1. Remove the need for the if logic introduced in #542~~ Fixed by @shenglol 
~~2. Make the `generateModuleIndexData` more efficient for looping over BRM & AVM modules, instead of calling the same logic 3 times - make it DRYer~~ Fixed by @shenglol 
3. Make it handle errors (try, catch)
~~4. Make it handle modules larger than 1mb~~ Fixed by @jtracey93
5. Make it log an issue if the workflow fails for investigation

> https://dev.azure.com/CSUSolEng/Azure%20Verified%20Modules/_workitems/edit/32820

**Comment by ChrisSidebotham** [comment]
^ Bump

**Comment by jtracey93** [comment]
#1683 & #1533 fixes and closes this

**Comment by eriqua** [comment]
> #1683 & #1533 fixes and closes this

@jtracey93 @AlexanderSehr @matebarabas as this is in main (🎉 ) are we good to close it?

**Comment by jtracey93** [comment]
Yup :)
