### ISSUE TITLE
[Bug Report]: Cannot set all of the site configs, especially netFrameworkVersion

### ISSUE THREAD

**Issue by charper-work** [Azure/bicep-registry-modules#555]
### Module path

/modules/compute/function-app

### Bicep version

latest

### Describe the bug

There is no way to set the `netFrameworkVersion` within the siteconfig: 

properties: {
    siteConfig: {
      linuxFxVersion: enableDockerContainer ? 'DOCKER|${dockerImage}' : linuxFxVersion ?? null
      ftpsState: ftpsState
      minTlsVersion: minTlsVersion
    }

Unlike the AppSettings and ConnectionStrings, which you can extend.

### To reproduce

Create a bicep file.
Reference the public function-app module.
Try to set the netFrameworkVersion.

**Comment by charper-aim** [comment]
This also does not have `dotnet-isolated` as an allowed function worker runtime.

**Comment by ChrisSidebotham** [comment]
Dear @charper-work , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
