### ISSUE TITLE
[Modules Proposal]: ALZ (Azure Landing Zones) Modules

### ISSUE THREAD

**Issue by jtracey93** [Azure/bicep-registry-modules#57]
## Have you checked this module does not already exist in the registry?

Yes. Some overlap foreseen with VNET & Resource Group modules. However, our modules wrap these as are at a higher level than individual resources.

## Why is the module needed?

Help customers deliver the [ALZ (Azure Landing Zone)](https://aka.ms/alz) reference architecture using the Bicep modules from the [ALZ-Bicep repository](https://github.com/Azure/ALZ-Bicep), supported by CAE team (WW CSU).

This will form another consumption method to meet more customers where they want to consume the modules from as per https://github.com/Azure/ALZ-Bicep/wiki/ConsumerGuide

## Modules paths

| Module | Path |
| -------- | ----- |
| ALZ Management Groups | `alz/managementGroups` |
| ALZ Custom Role Definitions | `alz/customRoleDefinitions/customRoleDefinitions` |
| ALZ Custom Role Definition - Application Owner | `alz/customRoleDefinitions/cafApplicationOwnerRole` |
| ALZ Custom Role Definition - Network Management | `alz/customRoleDefinitions/csfNetworkManagementRole` |
| ALZ Custom Role Definition - Security Operations | `alz/customRoleDefinitions/cafSecurityOperationsRole` |
| ALZ Custom Role Definition - Subscription Owner | `alz/customRoleDefinitions/cafSubscriptionRole` |
| ALZ Hub Networking | `alz/hubNetworking` |
| ALZ Logging, Automation & Sentinel | `alz/logging` |
| ALZ Custom Policy Definitions | `alz/policy/definitions/customPolicyDefinitions` |
| ALZ Policy Assignment - Management Group | `alz/policy/assignments/policyAssignmentManagementGroup` |
| ALZ Policy Default Policy Assignments | `alz/policy/assignments/alzDefaults/alzDefaultPolicyAssignments` |
| ALZ Public IP | `alz/publicIp` |
| ALZ Resource Group | `alz/resourceGroup` |
| ALZ Role Assignments - Management Group | `alz/roleAssignments/roleAssignmentManagementGroup` |
| ALZ Role Assignments - Management Group Many | `alz/roleAssignments/roleAssignmentManagementGroupMany` |
| ALZ Role Assignments - Subscription | `alz/roleAssignments/roleAssignmentSubscription` |
| ALZ Role Assignments - Subscription Many | `alz/roleAssignments/roleAssignmentSubscriptionMany` |
| ALZ Spoke Networking | `alz/spokeNetworking` |
| ALZ Subscription Placement | `alz/subcriptionPlacement` |
| ALZ Virtual Network Peering | `alz/virtualNetworkPeering` |
| ALZ Virtual Network Peering with vWAN | `alz/vnetPeeringVwan`
| ALZ Virtual WAN Hub | `alz/vwanConnectivity`

## Describe the modules

As mentioned above this will form another consumption method to meet more customers where they want to consume the modules from as per https://github.com/Azure/ALZ-Bicep/wiki/ConsumerGuide to deploy the ALZ (Azure Landing Zone) architecture using the existing ALZ-Bicep modules.

**Comment by alex-frankel** [comment]
FYI @jtracey93 -- Shenlong and I discussed offline. You can go ahead and start opening the relevant PR(s) w/o creating individual issues.

If it is multiple PRs, just make sure the PR description does not use any of the keywords for closing the issue, otherwise it'll automatically close the issue too early.

**Comment by ChrisSidebotham** [comment]
@jtracey93 - Is this still required?

**Comment by jtracey93** [comment]
will be handled as part of future work
