### ISSUE TITLE
[Modules Proposal]: Sample - Serverless App Archetype

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#61]
# Have you checked this module does not already exist in the registry?

- [x] Yes

# Why is the module needed?

To expedite the creation of API applications that use a serverless pattern.
Tech stack targets FunctionApps for compute and CosmosDb for db storage.
Observability is implemented in various azure services.

# Module Paths

app/apim-cosmos-functionapp

# Describe the modules

The main module takes a GitHub repo url (and branch names) and does a full infra deployment, binding the slots to staging/production in the repo. 
- Azure APIM is deployed with an independent REDIS cache
- Web tests are created on internet accessible web/api endpoints for completeness.
- Application secrets are stored in Key Vault, and secrets are added securely in the CosmosDb module.
- 
![image](https://user-images.githubusercontent.com/17914476/161751273-98dd7bf9-9738-4f23-840a-d0a7bd9a534b.png)

It would be most of what is documented in this repo: https://github.com/Gordonby/AzureBicepServerlessAppStack

**Comment by alex-frankel** [comment]
I think we are hesitant to build out a library of samples like this. At this point, it is more appropriate to put samples in [azure-quickstart-templates](https://github.com/Azure/azure-quickstart-templates). Do you mind submitting this there?

There is a larger discussion about what we need to do with all of those samples. It might be worth considering if we can "mirror" the quickstart samples that have been ported to bicep to also be accessible via the registry.

**Comment by Gordonby** [comment]
> I think we are hesitant to build out a library of samples like this. At this point, it is more appropriate to put samples in [azure-quickstart-templates](https://github.com/Azure/azure-quickstart-templates). Do you mind submitting this there?
> 
> There is a larger discussion about what we need to do with all of those samples. It might be worth considering if we can "mirror" the quickstart samples that have been ported to bicep to also be accessible via the registry.

I'd actually imagine the QuickStart's leveraging this alongside a code repo to then create a full app deployment sample.

I'm happy keeping this idea on ice for the time being whilst the registry direction evolves 😸 . I acknowledge it's not the most straightforward set of modules 😆
