### ISSUE TITLE
DocumentDB: avm and setting implicit keyvault secrets for connection strings #611

### ISSUE THREAD

**Issue by jongio** [Azure/bicep-registry-modules#632]
In azd, we allow the user to pass a keyvault reference when creating a cosmos database. If they do provide one, then we set a keyvault secret that contains the connection string.

That way the user doesn't have to do that in their own bicep.

It's not necessary, but certainly makes for a seamless experience for users, so they don't have to think about doing so on their own.

You can see that in action here: https://github.com/Azure/azure-dev/blob/main/templates/common/infra/bicep/core/database/cosmos/cosmos-account.bicep#L34

It would be nice if avm did the same.

**Comment by matebarabas** [comment]
@jongio, this issue was transferred to the BRM repo, as it relates to a feature request to a module. Please note that the `avm/res/document-db/database-account` module is yet to be migrated from CARML. Since no module owner has volunteered to take care of this one yet, please expect delays in both the migration and the addition of the requested feature.

**Comment by AlexanderSehr** [comment]
> @jongio, this issue was transferred to the BRM repo, as it relates to a feature request to a module. Please note that the `avm/res/document-db/database-account` module is yet to be migrated from CARML. Since no module owner has volunteered to take care of this one yet, please expect delays in both the migration and the addition of the requested feature.

Plese note, a draft PR popped up in the meantime: https://github.com/Azure/bicep-registry-modules/pull/667

**Comment by bryansan-msft** [comment]
I'm picking up this issue as the module was already migrated and owner assigned

**Comment by jongio** [comment]
> I'm picking up this issue as the module was already migrated and owner assigned

Thanks, ping if you have any questions

**Comment by jongio** [comment]
@bryansan-msft - Do you have an ETA on this one?

**Comment by bryansan-msft** [comment]
@jongio There is a pull request already open that include this one #1407. It should be this week hopefully tomorrow
