### ISSUE TITLE
Add support to compile main.test.json from main.test.bicep with the Bicep registry module tool

### ISSUE THREAD

**Issue by BenjaminEngeset** [Azure/bicep-registry-modules#680]
It would be great to have the Bicep registry module tool able to compile `main.test.json` from `main.test.bicep` as it does with `main.json` from `main.bicep`.

There are some edge cases where this can be helpful when it comes to troubleshooting, as well not having to grant workflows access to a private Bicep container registry where anonymous access is not enabled.

**Comment by AlexanderSehr** [comment]
Wouldn't see any reason why not do add this with an optional switch flag. @ChrisSidebotham & @eriqua any suprising concerns from your side?

**Comment by ChrisSidebotham** [comment]
@BenjaminEngeset are you referring the current AVM Modules directory set up?

**Comment by ChrisSidebotham** [comment]
Closing as related to the BRM CI not AVM CI 

Dear @BenjaminEngeset , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

As part of this transition, the new AVM CI environment is replacing the existing CI formerly leveraged within the Bicep Registry Modules (BRM) repository. As a result of this, issues and features related to the existing BRM CI will be closed. If you think your issue still needs addressing, please raise a new issue related to the AVM CI, [here](https://aka.ms/BRM/AVMQuestionFeedback).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
