### ISSUE TITLE
[Module Proposal]: Azure CLI DeploymentScript Module - AKV Certs in AGW

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#69]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Split from #60

[DeploymentScripts](https://docs.microsoft.com/en-us/azure/templates/microsoft.resources/deploymentscripts?tabs=bicep) typically require several Azure resources to be deployed together to execute a meaningful deployment (ID, RBAC and the Script Itself). It lends itself to be in a registry because of this nature.

As well as serving as a meaningful module for customers, it will be directly leveraged in the [Azure/Aks-Construction repo](https://github.com/Azure/AKS-Construction) to reduce complexity in post-deployment automation steps;
- Using the AZ CLI to create self-signed certificates in an Azure Key Vault for use by an Azure Application Gateway Ingress Controller.

> DeploymentScripts are a powerful, yet underutilised resource in Arm, we need more living samples of this resource type being used. 

### Module path

deployment-scripts/create-agw-kv-certificate

### Describe the module

A single bicep file that will deploy a managed identity, apply rbac permissions on existing resources and run an Azure CLI script.

The Azure CLI script will
- Instruct KeyVault to create a self signed certificate based on its default certificate policy
- Add either a root **or** frontend certificate to an existing Application Gateway, referencing the KeyVault certificate

**Comment by alex-frankel** [comment]
FYI - @Gordonby can you make sure these deployment-scripts modules can be deployed a second time to ensure they are idempotent?

Created #77 to see if this can be built into our CI tests.
