### ISSUE TITLE
[Enhancement] Add custom removal for additional resources

### ISSUE THREAD

**Issue by MrMCake** [Azure/bicep-registry-modules#72]
The ResourceGroup removal logic used in this repo is already very detailed. However, there are a few more modules worth adding to the current [removal script](https://github.com/Azure/bicep-registry-modules/blob/main/scripts/azure-pipelines/Remove-TestResourceGroup.ps1).

For example
- KeyVault
- Cognitive Services
- API Management
- Log Analytics Workspaces

If we don't implement a corresponding logic, a 2nd test of e.g. a test file deploying a key vault will fail because it does not automatically recover deleted resources.

To speed things up, I'd suggest to re-use parts of the removal logic used in [CARML](https://github.com/Azure/ResourceModules/blob/main/utilities/pipelines/resourceRemoval/helper/Invoke-ResourcePostRemoval.ps1#L99) and align it to the structure used in the [Bicep-Registry-Modules](https://github.com/Azure/bicep-registry-modules/blob/main/scripts/azure-pipelines/Remove-TestResourceGroup.ps1) repository.

cc: @shenglol, @eriqua

**Comment by shenglol** [comment]
Thanks for sharing this!

**Comment by akata72** [comment]
Why not use azure/ResourceModules as the starting point for the public registry. It seems strange to start from «scratch» when most of the basic modules are already created. 😀😀

**Comment by alex-frankel** [comment]
We plan to re-use as much as possible. We are working closely with @MrMCake and the CARML team to get their content hosted in the registry. Both the `virtual-network` and `availability-set` modules come from CARML.
