### ISSUE TITLE
[AVM Module Issue]: `service-bus\namespaces` VNext Updates

### ISSUE THREAD

**Issue by ChrisSidebotham** [Azure/bicep-registry-modules#722]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/service-bus/namespace

### (Optional) Module Version

0.1

## Breaking Changes
 - N/A

## Feature Updates

- User Defined Types for Child Resources (Topics & Queues)
  - Add descriptions to UDT for Child parameters such as `audtoDeleteOnIdle` as written in the childs `readme.md` currently
- User Defined Type for Authorization Rules (Awaiting Bicep feature release for User Defined Functions)
- Subscription extension resource under topics as per #731 

## Fixes
- Topic creation blocked for standard SKU due to premium properties #726

**Comment by andlommy** [comment]
Any reason to have audtoDeleteOnIdle default to PT5M instead of not set or 0, that would mimic portal default behavior for topic creation?

**Comment by ChrisSidebotham** [comment]
Hi @andlommy - The module itself has been migrated from [CARML](https://aka.ms/carml). This configuration was set as default over a year ago by other members of the CARML contribution community. The `service-bus/namespace` module does not surface the description of child modules until we implement User Defined Types for child Modules (In this case we will expedite this for this module.) Which is largely dependant on the feature release from the Bicep Team for User Defined Functions & User Defined Type Imports. We will look to remove this default following discussion within the CARML Team. 

I will update here accordingly

**Comment by ChrisSidebotham** [comment]
@andlommy - The PR mentioned above applies a fix for this and the default has been changed to a nullable value. Therefore, a default is no longer set for the property `autoDeleteOnIdle` - I will now close this issue as the version has been increased.
