### ISSUE TITLE
[Module Proposal]: Azure CLI DeploymentScript Module - AKS Run Command

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#73]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Extension of #60 and #69 

[DeploymentScripts](https://docs.microsoft.com/en-us/azure/templates/microsoft.resources/deploymentscripts?tabs=bicep) typically require several Azure resources to be deployed together to execute a meaningful deployment (ID, RBAC and the Script Itself). It lends itself to be in a registry because of this nature.

As well as serving as a meaningful module for customers, it will be directly leveraged in the [Azure/Aks-Construction repo](https://github.com/Azure/AKS-Construction) to reduce complexity in post-deployment automation steps;

- Using the AZ CLI to leverage the [ AKS Run Command](https://azure.microsoft.com/en-gb/updates/general-availability-aks-run-command/) to install CertManager on the cluster
- Using the AZ CLI to leverage the [ AKS Run Command](https://azure.microsoft.com/en-gb/updates/general-availability-aks-run-command/) to install External-DNS on the cluster
- Using the AZ CLI to leverage the [ AKS Run Command](https://azure.microsoft.com/en-gb/updates/general-availability-aks-run-command/) to install a sample application (the Azure Vote App) on the cluster
- Using the AZ CLI to leverage the [ AKS Run Command](https://azure.microsoft.com/en-gb/updates/general-availability-aks-run-command/) to query the Kubernetes events for `Warnings`

### Module path

deployment-scripts/aks-run-command

### Describe the module

A single bicep file that will deploy a managed identity, apply rbac permissions on existing resources and run an Azure CLI script.

The Azure CLI script will

- Invoke the AKS Run Command, relaying the command it has been provided with

**Comment by alex-frankel** [comment]
FYI - @Gordonby can you make sure these deployment-scripts modules can be deployed a second time to ensure they are idempotent?

Created #77 to see if this can be built into our CI tests.
