### ISSUE TITLE
[AVM Module Issue]: service-bus\namespace\topic\subscriptions support

### ISSUE THREAD

**Issue by andlommy** [Azure/bicep-registry-modules#731]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/service-bus/namespace

### Description

Currently it's possible to create service bus namespace and topics using the AVM module.
Creating topic subscriptions, however, is not supported.
Topic with no subscriptions make little sense.
Using AVM module and manually creating subscriptions for a topic is challenging due to one-to-many namespace-topic-subscription fanout (a single namespace may have one or more topics, a single topic may have many subscriptions).
Request is to add support for Microsoft.ServiceBus/namespaces/topics/subscriptions resource creation as a child resource to Microsoft.ServiceBus/namespaces/topics, if topic property contains subscription sub-property

**Comment by ChrisSidebotham** [comment]
Hi @andlommy. 

Thanks for submitting this issue and I can certainly align this in #722 for future release. Can I also ask if you have been using this module in is previous form residing in CARML (https://aka.ms/carml) or have you picked up using this module natively to AVM?

**Comment by andlommy** [comment]
@ChrisSidebotham, neither CARML nor AVM have subscription resource support. We're using the AVM module

**Comment by ChrisSidebotham** [comment]
> @ChrisSidebotham, neither CARML nor AVM have subscription resource support. We're using the AVM module

Thanks for response. Just wanted to understand where your usage was - I will add this into the VNext updates for Service Bus module.
