### ISSUE TITLE
[AVM Question/Feedback]: Reuse of pipelines in fork 

### ISSUE THREAD

**Issue by MadCapMonster** [Azure/bicep-registry-modules#733]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I am looking to reuse the current pipelines to deploy the modules to our container registry however we don't want to do test deployments. there are two default values set in most module workflows  deploymentValidation and removeDeployment that we wish to disable, there seems to be logic to disable removeDeployment on the shared file but not used elsewhere however no logic or ability to disable deploymentValidation or documentation to reused the pipelines, could you please elaborate

**Comment by MadCapMonster** [comment]
I should add that this is on a sync not just running individual workflows

**Comment by AlexanderSehr** [comment]
Hey @MadCapMonster,
thanks for your question. Please note that the workflows in this repository are intended primarily for contributions into the Public Registry / it's repository. They're not optimized / designed for any other use.
That being said - I would recommend you take a look at the [CARML CI](https://aka.ms/carml) from which we're currently migrating the library from. Also there the workflows intend to do a full CI run - but - you could simply disable / remove the parts of the code you don't need. It's also better documented in its [Wiki](https://github.com/Azure/ResourceModules/wiki/The%20CI%20environment%20-%20Pipeline%20design).
You may need to perform a few adjustments here and there, but that CI's pupose was pretty much what you're asking for. Anybody should be able to take it and deploy it to their environment (be it Azure DevOps or GitHub) and use it for CARML/AVM modules or anything else to publish to a Private Bicep Registry / Template Specs / Azure DevOps Universal Packages. 
The CI we use for the AVM modules in this repository is actually a simplified version of the same. 

I hope that helped a bit. If you have additional questions, please let us know.

**Comment by AlexanderSehr** [comment]
Good day and a happy new year @MadCapMonster,
I'll go ahead and close this issue for now, hoping that my previous response was able to answer the raised question :) If not, please feel free to reopen it again.
