### ISSUE TITLE
[Module Proposal]: Bicep Template for MongoDB- vCore 

### ISSUE THREAD

**Issue by schandnani** [Azure/bicep-registry-modules#740]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Our team will be using this mongo Db for testing purpose. 

### Module path

storage/mongoDB-vCore

### Describe the module

Create an Azure Cosmos DB for MongoDB vCore cluster by using a Bicep template. 
https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/quickstart-bicep?tabs=azure-cli

**Comment by ChrisSidebotham** [comment]
Dear @schandnani , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
