### ISSUE TITLE
[AVM Module Issue]: Readme's reference CARML in cross-module references section

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/bicep-registry-modules#757]
e.g., 

![image](https://github.com/Azure/bicep-registry-modules/assets/5365358/22fab61b-d2bf-4b45-ad78-fedc524fef3c)

**Comment by eriqua** [comment]
@AlexanderSehr can this be closed?

**Comment by AlexanderSehr** [comment]
Looks like it, yes @eriqua . Thanks
