### ISSUE TITLE
[Bug Report]: AVM readme generator can't resolve external dependecies, if they are in sub-modules

### ISSUE THREAD

**Issue by rahalan** [Azure/bicep-registry-modules#764]
### Module path

/avm/res/compute/virtual-machine

### Bicep version

0.24.24

### Describe the bug

The AVM readme generator is able to show cross-referenced modules only, if they are referenced in the main.bicep file. If they re in a sub-module, they are not showing up on the readme.

![image](https://github.com/Azure/bicep-registry-modules/assets/61878316/24d16d75-6b79-4dfd-8874-1e56d33bf83f)

### To reproduce

Run the Set-ModuleReadme on the VM module (still in the branch users/rahalan/AlignVmToAVM2)

**Comment by AlexanderSehr** [comment]
Awaits #717 to have a valid test case

**Comment by AlexanderSehr** [comment]
Utility-focused issue and handled by linked PR.
