### ISSUE TITLE
[Bug Report]:  'aks-run-helm' test case are failed.  additional paramater needed

### ISSUE THREAD

**Issue by apc-kamezaki** [Azure/bicep-registry-modules#776]
### Module path

/modules/deployment-scripts/aks-run-helm

### Bicep version

0.24.24

### Describe the bug

test code did not succeed 'helm install' because of some reasons

- because command did not have required roles. It should be added 'rbacRolesNeeded' param to the template.
- typo of helm options (create_namespace) , it should be create-namespace

### To reproduce

Execute deployment-scripts/aks-run-helm/main.test.bicep and check the output of each test templates

### Code snippet

```Bicep
$ az deployment group create --resource-group ${RESOURCE_GROUP} --template-file main.test.bicep

```
```


### Relevant log output

```Shell
Result of 'sampleHelmChart'


"logs": "\"azure-marketplace\" has been added to your repositories\nHang tight while we grab the latest from your chart repositories...\n...Successfully got an update from the \"azure-marketplace\" chart repository\nUpdate Complete. ⎈Happy Helming!⎈\nError: query: failed to query with labels: secrets is forbidden: User \"6a2d0f68-1eb8-41e0-93d9-1754298c077d\" cannot list resource \"secrets\" in API group \"\" in the namespace \"default\": User does not have access to the resource in Azure. Update role assignment to allow access.\n",

```

Result of helmContour

```
"logs":"\"bitnami\" has been added to your repositories\nHang tight while we grab the latest from your chart repositories...\n...Successfully got an update from the \"bitnami\" chart repository\nUpdate Complete. ⎈Happy Helming!⎈\nError: unknown flag: --create_namespace\n",
```

Result of milvus

```
"logs":"\"milvus\" has been added to your repositories\nHang tight while we grab the latest from your chart repositories...\n...Successfully got an update from the \"milvus\" chart repository\nUpdate Complete. ⎈Happy Helming!⎈\nError: query: failed to query with labels: secrets is forbidden: User \"cbb0247f-5534-4f4a-884f-69e968eb0b00\" cannot list resource \"secrets\" in API group \"\" in the namespace \"default\": User does not have access to the resource in Azure. Update role assignment to allow access.\n",
```
```

**Comment by ChrisSidebotham** [comment]
Dear @apc-kamezaki , Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

For bugs or new features with existing modules in the `/modules` directory of this repository, we encourage you to first try the AVM equivalent module if available and if the module is lacking any features, you can file an [AVM Module Issue](https://aka.ms/AVM/Bicep/ModuleIssue). If the module is not available yet, you can file a new [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
