### ISSUE TITLE
[AVM Module Issue]: Deployment Script without storageAccountKey

### ISSUE THREAD

**Issue by jachin84** [Azure/bicep-registry-modules#812]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/resources/deployment-script

### Description

The deployment script resource allows specifying only a `storageAccountName` in `storageAccountSettings` rather than specifying both `storageAccountName` and `storageAccountKey`. This allows assigning access to the storage account using the user-assigned managed identity rather than using a `storageAccountKey`. This is described in [the documentation](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deployment-script-vnet).

Here is a basic example:
```bicep
param location string = resourceGroup().location
param userAssignedIdentityName string = 'id-d-jbh-deployment'
param storageAccountName string = 'stdjbhdeployment'
param peSubnetId string
param utcValue string = utcNow()

var peSubnetSplit = split(peSubnetId, '/')

resource userAssignedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' existing = {
  name: userAssignedIdentityName
}

resource vnet 'Microsoft.Network/virtualNetworks@2023-06-01' existing = {
  name: peSubnetSplit[8]
  scope: resourceGroup(peSubnetSplit[2], peSubnetSplit[4])

  resource subnet 'subnets' existing = {
    name: last(peSubnetSplit)
  }
}

resource deploymentScript 'Microsoft.Resources/deploymentScripts@2023-08-01' = {
  name: 'deploymentScript'
  location: location
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${userAssignedIdentity.id}': {}
    }
  }
  kind: 'AzurePowerShell'
  properties: {
    forceUpdateTag: utcValue
    azPowerShellVersion: '11.0'
    storageAccountSettings: {
      storageAccountName: storageAccountName
    }
    containerSettings:{
      subnetIds:[
        {
          id: vnet::subnet.id
        }
      ]
    }
    retentionInterval: 'PT1H'
    cleanupPreference: 'OnSuccess'
    scriptContent: '''
      Invoke-RestMethod -Uri 'https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/mslearn-arm-deploymentscripts-sample/appsettings.json' -OutFile 'appsettings.json'
      $storageAccount = Get-AzStorageAccount -ResourceGroupName 'rg-d-jbh-deployment' | Where-Object { $_.StorageAccountName -eq 'stdjbhdeployment' }
      $blob = Set-AzStorageBlobContent -File 'appsettings.json' -Container 'config' -Blob 'appsettings.json' -Context $storageAccount.Context -Force
      $DeploymentScriptOutputs = @{}
      $DeploymentScriptOutputs['Uri'] = $blob.ICloudBlob.Uri
      $DeploymentScriptOutputs['StorageUri'] = $blob.ICloudBlob.StorageUri
    '''
  }
}

output fileUri string = deploymentScript.properties.outputs.Uri

```

A possible fix might be something like (not tested but you get the idea):
```bicep
param enableManagedIdStorageAuthentication bool = false

...

resource storageAccount 'Microsoft.Storage/storageAccounts@2021-04-01' existing = if (!empty(storageAccountResourceId) && !enableManagedIdStorageAuthentication) {
  name: last(split((!empty(storageAccountResourceId) ? storageAccountResourceId : 'dummyAccount'), '/'))!
  scope: resourceGroup(split((!empty(storageAccountResourceId) ? storageAccountResourceId : '//'), '/')[2], split((!empty(storageAccountResourceId) ? storageAccountResourceId : '////'), '/')[4])
}

var storageAccountSettings = !empty(storageAccountResourceId) ? {
  storageAccountKey: enableManagedIdStorageAuthentication ? null : listKeys(storageAccount.id, '2023-01-01').keys[0].value
  storageAccountName: last(split(storageAccountResourceId, '/'))
} : null


```

**Comment by sebassem** [comment]
@jachin84 Thank you for submitting this issue. I looked at the code and if I understand the issue correctly, we already provide the storageAccountKey in the [storageAccountSettings](https://github.com/Azure/bicep-registry-modules/blob/10bc5a9d5fc41454fcdb407f34b087af6530c65c/avm/res/resources/deployment-script/main.bicep#L133) , the storageAccountKey property cannot be null as its a required property if we reference an existing storage account

**Comment by AlexanderSehr** [comment]
Hey @sebassem if you recall we talked about this before. It is seemingly possible to get it working but refused back in the day. Let's revisit it as per the provided example and see if we can find out what blocked us during the migration.

**Comment by jachin84** [comment]
`storageAccountKey` is definitely optional when using a managed identity. I'm using this in our deployments daily atm.

**Comment by sebassem** [comment]
> ```bicep
> param enableManagedIdStorageAuthentication bool = false
> ```
`var storageAccountSettings = !empty(storageAccountResourceId) ? {
  storageAccountKey: (storageAccount.properties.?allowSharedKeyAccess ?? true) ? listKeys(storageAccount.id, '2023-01-01').keys[0].value : null
  storageAccountName: last(split(storageAccountResourceId, '/'))
} : null`

I tried the above logic and it only works if the **allowSharedKeyAccess** property is null or true. If its set to false, it doesn't work.

_Access key was not specified for storage account 'depsbavmstrdscli'. Make sure to use the correct storage account access key_

**Comment by sebassem** [comment]
> Hey @sebassem if you recall we talked about this before. It is seemingly possible to get it working but refused back in the day. Let's revisit it as per the provided example and see if we can find out what blocked us during the migration.

`var storageAccountSettings = !empty(storageAccountResourceId) ? {
  storageAccountKey: (storageAccount.properties.?allowSharedKeyAccess ?? true) ? listKeys(storageAccount.id, '2023-01-01').keys[0].value : null
  storageAccountName: last(split(storageAccountResourceId, '/'))
} : null`

I tried the above logic and it only works if the **allowSharedKeyAccess** property is null or true. If its set to false, it doesn't work.

_Access key was not specified for storage account 'depsbavmstrdscli'. Make sure to use the correct storage account access key_

**Comment by jachin84** [comment]
I did some more testing on this today making only the following changes:

```bicep
var storageAccountSettings = !empty(storageAccountResourceId) ? {
  storageAccountKey: !empty(subnetResourceIds) ? null : listKeys(storageAccount.id, '2023-01-01').keys[0].value
  storageAccountName: last(split(storageAccountResourceId, '/'))
} : null
```

My reason was providing `subnetResourceIds` means the container app will be private and therefore the `storageAccountKey` is not required.  This seemed to work fine as long as the provided managed identity has `Storage File Data Privileged Contributor` on the Storage Account. 

A note on testing. Setting `Allow storage account key access` to `Disabled` won't work.
![image](https://github.com/Azure/bicep-registry-modules/assets/2740855/1e7230d1-4b58-4d8a-806c-19438e3b1851)

AFAIK you cannot access Azure files using a managed identity without using Storage Account Keys. My activity log shows a `List Storage Account Keys` as part of the deployment. I guess the resource provider is adding the Storage Account Key in the background which, now that I think about it, probably negates any changes needed to this module. Might be worth double checking with the owners of the deployment scripts resource provider.

**Comment by sebassem** [comment]
Thanks for the investigation @jachin84 , ideally we wanted to implement this change if customers are disabling the account keys but it seems we cannot workaround that. We can take this with PG to see if there are plans to do this

**Comment by AlexanderSehr** [comment]
Hey @jachin84 & @sebassem,
exactly, in order for the deployment script to use a storage account via private networking they always want to use a shared access key. Just checked a solution I published a while back that I updated with that feature and noticed I commented the same thing on the storage account property: 
  [`allowSharedKeyAccess: true // May not be disabled to allow deployment script to access storage account files`](https://github.com/Azure/DevOps-Self-Hosted/blob/cf942c7610051a5bfec3a93a38a4f4f50c785ef1/constructs/azureImageBuilder/templates/image.deploy.bicep#L276).
Yet I do not specify the `storageAccountKey` which it seemingly then requests automatically, if granted permissions to do so, which matches your description above @jachin84 . 
```bicep
    storageAccountSettings: !empty(storageAccountName) ? {
      storageAccountName: storageAccountName
    } : null
```
With that in mind, it would be great if we could update the module accordingly to not make the key required, mentioning in the parameter's description that if not required, the deployment script's MSI needs the permissions to automatically fetch the key intead.

**Comment by AlexanderSehr** [comment]
Hey @jachin84,
@sebassem implemented a few changes and attached a Pull Request to this issue. If you have a moment, feedback would be welcome :) . With the updated implementation, the module will only explicitely fetch the Storage Account's key in case NO subnet (i.e., private networking) is provided. If one is provided, it goes the implicit route and only passes `null` to the `storageAccountKey` property.
It's not perfect, but the only reasonable alternative would be to remove the storage account key fetch entirely and pass it in as an optional (secure) parameter.

**Comment by jachin84** [comment]
@AlexanderSehr looks good to me. Pulled locally and ran through a deployment. All working as expected.
