### ISSUE TITLE
[AVM Question/Feedback]:  roleAssignments param in resource-group module 

### ISSUE THREAD

**Issue by OlehGap** [Azure/bicep-registry-modules#815]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I probably misunderstood roleAssignments param in resource-group module
I want to create a resource group , set tags and grant certain permissions to the RG.

I have no problem with resource group tags and locks, but the roles are assigned on the subscription level not the RG. 

Do I use it incorrectly? wrong version? Sorry, I'm new to AVM/BRM

My code : 

```
module newRg 'br/public:avm/res/resources/resource-group:0.2.1' =  {
  name: '${deployment().name}.${rgName}'
  scope: subscription()
  params: {
    name: rgName
    location: rgLocation
    tags: newTags
    lock: {
      kind: lockKind
      name: '${rgName}-RG-lock-${lockKind}'
    }
    roleAssignments : rbac
  }
}
```

**Comment by OlehGap** [comment]
I guess, that's a bug. 
`resource resourceGroup_roleAssignments 'Microsoft.Authorization/roleAssignments@2022-04-01' = [for (roleAssignment, index) in (roleAssignments ?? []) 

...
`

should be moved to a nested module: nested_lock.bicep or a new one 

Similar module from [Azure Resource Manager QuickStart Templates](https://github.com/Azure/azure-quickstart-templates)

[subscription-deployments/create-rg-lock-role-assignment/main.bicep](https://github.com/Azure/azure-quickstart-templates/blob/master/subscription-deployments/create-rg-lock-role-assignment/main.bicep)

works as expected -- the role assigned on RG level.

**Comment by ChrisSidebotham** [comment]
@OlehGap - I have proposed a change via the PR linked to this thread - this resolves the issue and sets the role assignment scope to `/subscriptions/SUBSCRIPTIONID/resourcegroups/RESOURCEGROUPNAME` 
Pening approval from @Azure/avm-res-resources-resourcegroup-module-owners-bicep

**Comment by segraef** [comment]
> fix: roleassignemts in `avm-res-resources-resourcegroup` #823

Thanks for the fix, approved.
