### ISSUE TITLE
What is the benefit of using JSON ARM in cr when the scheme is br?

### ISSUE THREAD

**Issue by bengeset96** [Azure/bicep-registry-modules#82]
Hi project contributors and maintainers 😃 

What is the benefit of using JSON ARM for the cr (besides source of truth) when the scheme for the module is br (bicep registry)

Since main.json is being uploaded and not main.bicep ❓ 

And even more interesting since when calling on the JSON ARM module, you are allowed to use the same module definition as Bicep with same params syntax/upbuilding. 

Does that mean the json is being decompiled from ARM JSON to Bicep under the upload when using br scheme?

Would be interesting to know why and if users of Bicep should go for this direction instead rather than .bicep

**Comment by shenglol** [comment]
Bicep supports referencing a JSON template as module directly. We cannot publish the main Bicep files as module artifacts since module authors may create other Bicep files and reference them as local modules in a main Bicep file for a module.

**Comment by bengeset96** [comment]
Thank you @shenglol 

Makes sense!
