### ISSUE TITLE
[AVM Module Issue]: Storage Account networkAcls bypass

### ISSUE THREAD

**Issue by GodVenn** [Azure/bicep-registry-modules#878]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### (Optional) Module Version

0.5.0

### Description

Deployment fails with message 
`{"code":"RequestIsNotValidJson","message":"The request cannot be interpreted as valid Json: <Full json of deployment follows>`.
if deployment specifies `networkAcls` **without specifying the `bypass` parameter**.

Eventually i attempted to add that parameter just for testing and it worked, but this is undocumented, as the `bypass` parameter is not listed as required.

**Steps to reproduce:**
Deploy the module with networkAcls specified, without the `bypass` paramter, eg:
```bicep
module appStorage 'br/public:avm/res/storage/storage-account:0.5.0' = {
  name: '${uniqueString(deployment().name)}-storage'
  scope: resourceGroup()
  params: {
    name: storageAccountName
    skuName: 'Standard_LRS'
    networkAcls: {
      defaultAction: 'Deny'
      virtualNetworkRules: [
        {
          action: 'Allow'
          id: subnet.id
        }
      ]
    }
  }
}
```

**Comment by GodVenn** [comment]
@fblix 
Seems there is an issue in your assignment bot

**Comment by jtracey93** [comment]
@fblix are you also able to fix this one?

**Comment by fblix** [comment]
> @fblix are you also able to fix this one?

yep, gonna take a look as soon as I have some time.

**Comment by o-l-a-v** [comment]
This still fails with:

```bicep
networkAcls: {
  defaultAction: 'Allow'
}
```

The ARM template then shows `bypass: null`, which gives `RequestIsNotValidJson`.

**Comment by AlexanderSehr** [comment]
> This still fails using `br/public:avm/res/storage/storage-account:0.9.0` with:
> 
> ```bicep
> networkAcls: {
>   defaultAction: 'Allow'
> }
> ```
> 
> The ARM template then shows `bypass: null`, which gives `RequestIsNotValidJson`.
> 
> This issue seems related: [Azure/bicep-types-az#1334](https://github.com/Azure/bicep-types-az/issues/1334).

Hey @o-l-a-v,
thanks for bringing this up. One may be blown away by how consistent `null` is supported. I guess in your case the workaround would be to set 
```bicep
networkAcls: {
  bypass: 'None'
  defaultAction: 'Allow'
}
```
as annoying as it may be.

Begs however the question if either
- `bypass` should be mandatory OR
- if it should have a default value of e.g. `None` 

Just not setting it would be preferred, but that would require butchering the implementation even more. That is, instead of
```bicep
networkAcls: !empty(networkAcls)
  ? {
      resourceAccessRules: networkAcls.?resourceAccessRules
      bypass: networkAcls.?bypass
      defaultAction: networkAcls.?defaultAction ?? 'Deny'
      virtualNetworkRules: networkAcls.?virtualNetworkRules
      ipRules: networkAcls.?ipRules
    }
  : {
      // New default case that enables the firewall by default
      bypass: 'AzureServices'
      defaultAction: 'Deny'
    }
```

having
```bicep
networkAcls: !empty(networkAcls)
  ? union(
      {
        resourceAccessRules: networkAcls.?resourceAccessRules
        defaultAction: networkAcls.?defaultAction ?? 'Deny'
        virtualNetworkRules: networkAcls.?virtualNetworkRules
        ipRules: networkAcls.?ipRules
      },
      (contains(networkAcls!, 'bypass') ? { bypass: networkAcls.?bypass } : {})
    )
  : {
      // New default case that enables the firewall by default
      bypass: 'AzureServices'
      defaultAction: 'Deny'
    }
```

**Comment by o-l-a-v** [comment]
@AlexanderSehr: Yep, thanks, I've already worked around it. I vote for more buthering so the end users does not have to think about this.

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr: Yep, thanks, I've already worked around it. 😊 I vote for more butchering so the end users do not have to think about this.

I tend to agree. @o-l-a-v, could you do me a favor and open an issue for this? Ideally including the above suggestion. Commenting on the closed issue will only get us so far unfortunately.
