### ISSUE TITLE
sort order of param/vars/resources/outputs (etc)

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/bicep-registry-modules#88]
Should we standardize the ordering of the top level keywords in modules?  Thinking: 

- It's often easier to reason over when this is consistent...
- params/outputs define the contract, having that be easy to discern is useful
- should be easy to automate

**Comment by alex-frankel** [comment]
I agree we should standardize for params/outputs. Params should definitely all be declared at the top. Outputs could either be 2nd or last, but should also be grouped together.

I don't feel as strongly about the order of variables/resources.

Created this issue in bicep to track: https://github.com/Azure/bicep/issues/6602

**Comment by ChrisSidebotham** [comment]
Dear @bmoore-msft, Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

As part of this transition, the new AVM CI environment is replacing the existing CI formerly leveraged within the Bicep Registry Modules (BRM) repository. As a result of this, issues and features related to the existing BRM CI will be closed. If you think your issue still needs addressing, please raise a new issue related to the AVM CI, [here](https://aka.ms/BRM/AVMQuestionFeedback).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
