### ISSUE TITLE
[AVM Module Issue]: Support outboundType `userAssignedNATGateway` and `managedNATGateway`

### ISSUE THREAD

**Issue by coolhome** [Azure/bicep-registry-modules#897]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/container-service/managed-cluster

### Description

Support outboundType `userAssignedNATGateway` and `managedNATGateway`

https://learn.microsoft.com/en-us/azure/aks/nat-gateway

Before:
```bicep
@description('Optional. Specifies outbound (egress) routing method. - loadBalancer or userDefinedRouting.')
@allowed([
  'loadBalancer'
  'userDefinedRouting'
])
param outboundType string = 'loadBalancer'
```

After:
```bicep
@description('Optional. Specifies outbound (egress) routing method.') // Modification
@allowed([
  'loadBalancer'
  'userDefinedRouting'
  'managedNATGateway' // Added
  'userAssignedNATGateway' // Added
])
param outboundType string = 'loadBalancer'
```

**Comment by AlexanderSehr** [comment]
Thanks for picking this up @JPEasier & @ilhaan

**Comment by ilhaan** [comment]
Draft PR for this here: https://github.com/Azure/bicep-registry-modules/pull/992

**Comment by ilhaan** [comment]
PR no longer in draft and is ready for review: https://github.com/Azure/bicep-registry-modules/pull/992

**Comment by AlexanderSehr** [comment]
Linked the PR directly. This will automatically close this issue once the PR is merged (cc: @ilhaan)

**Comment by ilhaan** [comment]
PR comments have been reviewed and updates being pushed

**Comment by JPEasier** [comment]
Hi @coolhome, 
the PR provided by @ilhaan is now merged.

Thank you for your request!
