### ISSUE TITLE
[AVM Module Issue]: Unable to enable `diagnosticSettings` by category - missing `enabled` boolean on diagnosticSettingType

### ISSUE THREAD

**Issue by coolhome** [Azure/bicep-registry-modules#898]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

Other, as defined below...

### (Optional) Module Name if not listed above

Every module

### Description

It is not possible to use a category name and enable it via the **diagnosticSettingType** for **AVM all modules**.

It appears the `logCategoriesAndGroups[].enabled` defaults to false. I assume the same is true for `metricCategories[].enabled` There is not a property for setting `enabled` unless you take the defaults of AllMetrics/AllLogs.

```bicep
    diagnosticSettings: [
      {
        name: 'toLA'
        workspaceResourceId: '.../providers/microsoft.operationalinsights/workspaces/...'
        logCategoriesAndGroups: [
          {
            category: 'PostgreSQLFlexSessions'
          }
          {
            category: 'PostgreSQLFlexQueryStoreRuntime'
          }
          {
            category: 'PostgreSQLFlexQueryStoreWaitStats'
          }
        ]
      }
    ]
```

Results in the following:
![image](https://github.com/Azure/bicep-registry-modules/assets/700740/296713e9-dc37-46e3-9eaa-7b7923bb62d7)

**Comment by AlexanderSehr** [comment]
Hey @coolhome, thanks for raising this rather surprising issue. We'll try to reproduce and resolve the issue. I could swear this worked in the sense of 'enable' defaulted to true. But apparently not 👀

**Comment by ChrisSidebotham** [comment]
@AlexanderSehr  can we update the UDT to include `enabled: true` if catagory is not empty?

**Comment by AlexanderSehr** [comment]
Ok, so I was able to reproduce the issue with e.g. the KeyVault module using the following template:
```bicep
module kvlt 'br/public:avm/res/key-vault/vault:0.3.4' = {
  name: 'alsehrdiagkv-deployment'
  params: {
    name: 'alsehrdiagkvlt'
    location: 'WestEurope'
    enablePurgeProtection: false
    diagnosticSettings: [
      {
        name: 'customSetting'
        logCategoriesAndGroups: [
          {
            category: 'AzurePolicyEvaluationDetails'
          }
        ]
        storageAccountResourceId: '/subscriptions/<subId>/resourceGroups/core-rg/providers/Microsoft.Storage/storageAccounts/alsehrcloudshell'
      }
    ]
  }
}
```

If we'd fetch the diagnostic settings after via

```PowerShell
Get-AzDiagnosticSetting -ResourceId '/subscriptions/<subId>/resourceGroups/alsehdiagtest-rg/providers/Microsoft.KeyVault/vaults/alsehrdiagkvlt'
```

It returns

```
Location                    :
Tags                        :
StorageAccountId            :
/subscriptions/<subId>/resourceGroups/core-rg/providers/Microsoft.Storage/storageAccounts/alsehrcloudshell       
ServiceBusRuleId            :
EventHubAuthorizationRuleId :
EventHubName                :
Metrics
    TimeGrain       :
    Category        : AllMetrics
    Enabled         : True
    RetentionPolicy :

Logs
    Category        : AzurePolicyEvaluationDetails
    Enabled         : False
    RetentionPolicy :

WorkspaceId                 :
LogAnalyticsDestinationType : AzureDiagnostics
Id                          : /subscriptions/<subId>/resourcegroups/alsehdiagtest-rg/providers/microsoft.keyvaul 
t/vaults/alsehrdiagkvlt/providers/microsoft.insights/diagnosticSettings/customSetting
Name                        : customSetting
Type                        : Microsoft.Insights/diagnosticSettings
```

so yeah. as described by the author, 'Enabled` defaults to false ... for whatever reason. Will no look into how we can best change that.

**Comment by AlexanderSehr** [comment]
Reopening as only one of the two linked PRs was merged
