### ISSUE TITLE
should we add defaultValues of params to the readme for a module?

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/bicep-registry-modules#90]
Makes it really elegant to understand how the params work - knowing what a defaultValue is on a module is pretty important...  but this creates a maint issue.  We could automate any changes to a defaultValue must also acompany a readme change (or just automate that part of the readme (assuming we aren't already)).

could also help address this with tooling support...

**Comment by bengeset96** [comment]
Hi, not a Microsoft employee, but saw this issue and taught it was quite interesting.

Should be so. 

I was/still to this day have a problem around this issue with Bicep modules that are really consumable. 

Originally I taught it was smart to add much default values as this improves deployment success and complexity. I still believe so more than ever.

A normal consumer tends to just use = required-properties, so hence very important as they just want the module to work as is with minimal tweak and tune up. But then it is also important that consumer understand what is being deployed.. 

Specially on big orchestration module this can be painful. One thing is deploying it the first time and verifying and :shipit:. But if consumer have deployed this module before with great sucess and wants to do it again. Now new deployment and then consumer refers to newer version and gets a really unexpected behavior. Specially those who you don't notice before you are too late 🙅.

Default values should be called out in the description of the parameters for visibility and default values should also be documented in the readme. 

But doing these readme's manually is quite painful and timeconsuming. Prone to human mistakes as well. Does not help to have a great description for a default value in the module, when you have altered maybe the oposite in readme. It just ended up being major management overhead doing this manually, so before the tooling was released I was using own written pwsh script for generating readme's. But unstable, unfinished and needs manual work after it has been ran to fix certain things. 

![image](https://user-images.githubusercontent.com/99641908/164331914-4dd6d71b-fdb2-43bc-84a5-769d7a25602b.png)

I do believe blackbelt kungfu @shenglol can do something with the module tool?

**Comment by shenglol** [comment]
This is definitely a good suggestion. I can update the registry module tool to generate the information.

**Comment by Gordonby** [comment]
I think this is a good idea, i was going to do the PR a couple weeks back but never found time 🤣

**Comment by dciborow** [comment]
I'm looking at this doc thinking... "but what is the default?"
<img width="675" alt="image" src="https://user-images.githubusercontent.com/9027725/193702263-2b48c26d-32df-4831-9370-e0e4550233b8.png">

**Comment by ChrisSidebotham** [comment]
Dear @bmoore-msft, Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

As part of this transition, the new AVM CI environment is replacing the existing CI formerly leveraged within the Bicep Registry Modules (BRM) repository. As a result of this, issues and features related to the existing BRM CI will be closed. If you think your issue still needs addressing, please raise a new issue related to the AVM CI, [here](https://aka.ms/BRM/AVMQuestionFeedback).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
