### ISSUE TITLE
[AVM Module Issue]: App Services (microsoft.web/sites) application settings are incorrectly constructed

### ISSUE THREAD

**Issue by tyconsulting** [Azure/bicep-registry-modules#906]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/site

### Description

the module automatically populate the following App Settings:

1. AzureWebJobsStorage
2. AzureWebJobsDashboard
3. APPINSIGHTS_INSTRUMENTATIONKEY
4. APPLICATIONINSIGHTS_CONNECTION_STRING

* According to the documentation [HERE](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#appinsights_instrumentationkey), `APPINSIGHTS_INSTRUMENTATIONKEY` and `APPLICATIONINSIGHTS_CONNECTION_STRING` should not be used at the same time. when possible, use `APPLICATIONINSIGHTS_CONNECTION_STRING`.
* According to the documentation [HERE](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsstorage__accountname), `AzureWebJobsStorage` should only be used if the Shared Key Access is not disabled for the storage account. 
* According to the documentation [HERE](https://learn.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsdashboard), `AzureWebJobsDashboard` is deprecated.

**Comment by ChrisSidebotham** [comment]
@tsc-buddy - Is this something you are ok to look at as the module owner?

**Comment by dewolfs** [comment]
When Shared Key Access is disabled, `AzureWebJobsStorage` should be changed to `AzureWebJobsStorage__accountname`.
Documentation can be found [HERE](https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial#edit-the-azurewebjobsstorage-configuration).

**Comment by tyconsulting** [comment]
i already have updated code working in my environment. I will raise a PR in next few days

**Comment by tsc-buddy** [comment]
> @tsc-buddy - Is this something you are ok to look at as the module owner?

@ChrisSidebotham , yep, sure thing. I shall pick this up at somepoint next week.

**Comment by tyconsulting** [comment]
> > @tsc-buddy - Is this something you are ok to look at as the module owner?
> 
> @ChrisSidebotham , yep, sure thing. I shall pick this up at somepoint next week.

I already have the working code and I will raise a PR. once my existing PR on this module #925 is approved and merged :)

**Comment by tsc-buddy** [comment]
A review and deployment of the changes in the PR has been scheduled for 26/2/24 once I return back to work.
