### ISSUE TITLE
standardize the use of a newOrExisting pattern

### ISSUE THREAD

**Issue by bmoore-msft** [Azure/bicep-registry-modules#91]
when modules offer the capability to use existing resource or create new ones various information is required via params...  usually:

- some flag indicating new vs. existing
- resource name
- resource rg
- resource subId

Should we standardize the way these patterns are implemented?  Including things like:
- is the default new or existing?
- is the name of the flag param consistent (e.g. createNewMSI vs. useExistingMSI) if we pick a default seems we must do this as well
- should rg/sub params default to the current scope (resourceGroup().name, subscription().id)
- should the name have a defaultValue (which likely never works with existing but always works with new)
- should the name param and the rg/sub param be similarly named?  E.g.  managedIdentityName and then (managedIdentityResourceGroup vs. existingManagedIdentityResourceGroup)

**Comment by alex-frankel** [comment]
I think this is a dup of #68, but I will close that one since it has more detail.

**Comment by dciborow** [comment]
While this PR does not provide a specific standardization, it may be able to help shape what is required.
https://github.com/Azure/bicep-registry-modules/pull/172

# Input 
<img width="631" alt="image" src="https://user-images.githubusercontent.com/9027725/192911462-c82c0af5-4faa-4940-b4a8-985d5389f5cc.png">

# New
<img width="625" alt="image" src="https://user-images.githubusercontent.com/9027725/192911541-350b6e76-7638-4fc7-ad86-a2c2ccb09ff4.png">

# Existing
<img width="739" alt="image" src="https://user-images.githubusercontent.com/9027725/192911567-524fcf4e-bbcd-4f17-ac91-a796574aa88b.png">

# Output
<img width="630" alt="image" src="https://user-images.githubusercontent.com/9027725/192911590-087fb03e-0ba9-4d9e-9732-9ff8b881f120.png">


# Standardization

* When `none` is an option, `none` is default
```bicep
@allowed([ 'new', 'existing', 'none' ])
param newOrExisting<ResourceType> string = 'none'
```

### When `none` is not an option, `new` is default
```bicep
@allowed([ 'new', 'existing'])
param newOrExisting<ResourceType> string = 'new'
```

### Default Name Appends `Name` to <ResourceType>, where Default Value is a unique string
```bicep
param <ResourceType>Name string = '<ResourceType>${uniqueString(resourceGroup().id, subscription().id)}'
```bicep

**Comment by dciborow** [comment]
Have relocated the post into a PR to make it easier to collect feedback.
https://github.com/Azure/bicep-registry-modules/pull/173

**Comment by ChrisSidebotham** [comment]
Dear @bmoore-msft, Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

As part of this transition, the new AVM CI environment is replacing the existing CI formerly leveraged within the Bicep Registry Modules (BRM) repository. As a result of this, issues and features related to the existing BRM CI will be closed. If you think your issue still needs addressing, please raise a new issue related to the AVM CI, [here](https://aka.ms/BRM/AVMQuestionFeedback).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
