### ISSUE TITLE
[AVM Module Issue]: ResourceAccessRules on storage account

### ISSUE THREAD

**Issue by Jackmt9** [Azure/bicep-registry-modules#936]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/storage/storage-account

### Description

When creating a storage account, I'd like to have the ability to pass:
```bicep
"networkAcls": {
  "resourceAccessRules": [
    {
      (...)
    }
  ]
}
```

**Comment by Jackmt9** [comment]
@rahalan Is this your area of ownership?

**Comment by ChrisSidebotham** [comment]
@fblix - Are you able to take a look into this?

**Comment by fblix** [comment]
Will have a look as soon as I have some time.

**Comment by fblix** [comment]
Started to work on it.
