### ISSUE TITLE
[AVM Module Issue]: Selective Role Assignment Modification for Existing Storage Accounts

### ISSUE THREAD

**Issue by Jackmt9** [Azure/bicep-registry-modules#937]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/storage/storage-account

### Description

Description
Summary: Introduce a functionality within the storage account module (as well as others) that allows users to modify role assignments on existing storage accounts without requiring a full reconfiguration of the account settings. This feature is particularly essential for scenarios where the storage account is referenced by another service like Synapse, and role modifications are necessary post the initial creation.

Detailed Description:

Use Case: In cases where a storage account is created and subsequently referenced by a Synapse workspace, it becomes necessary to modify role assignments after the initial setup. Currently, altering role assignments requires calling the entire storage account module, involving reconfiguration of all settings, which is cumbersome and inefficient.
Proposed Solution: Implement a feature that enables calling the storage module with an option to solely update role assignments. This would streamline the process by allowing users to add or change roles without having to input all the other configurations again.
Expected Behavior:
Users should be able to call the storage module with a new parameter or method focused exclusively on role management.
This call would enable the addition, removal, or modification of roles associated with the storage account.
All other existing configurations of the storage account should remain unchanged unless explicitly specified by the user.
Benefits:
Enhanced flexibility and efficiency in managing role assignments for storage accounts.
Reduced risk of inadvertent configuration changes during role updates.
Better integration with services like Synapse, accommodating dynamic changes in role assignments post-initial setup.
Impact:

This feature would be a significant improvement for developers and administrators who manage cloud resources and require dynamic role management for storage accounts, especially in complex setups involving services like Synapse.

**Comment by AlexanderSehr** [comment]
> This issue couldn't be assigend to fblix, because no such users exists.

@rahalan

**Comment by fblix** [comment]
Gonna take a look at it. This may need a discussion with other module owners so the implementation can be re used by other modules as well. What do you think, @AlexanderSehr ?

**Comment by AlexanderSehr** [comment]
Hey @Jackmt9,
I understand where you're coming from, but I'm not yet convinced that would be a good idea for a resource module as its main purpose is to deploy a resource - and in addition deploy extensions (like RBAC).
Technically speaking I'm sure it's doable, but I'd be inclined to argue that it may be easier to implement the 'raw' role assignment instead of using a module. For example

```bicep
resource storageFileDataPrivilegedContributor 'Microsoft.Authorization/roleDefinitions@2022-04-01' existing = {
  name: '69566ab7-960f-475b-8e7c-b3118f30c6bd'
  scope: tenant()
}
resource storageFileSharePermissions 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid('storageFileDataPrivilegedContributorRole', managedIdentity.id, storageAccount.id)
  scope: storageAccount
  properties: {
    principalId: managedIdentity.properties.principalId
    roleDefinitionId: storageFileDataPrivilegedContributor.id
    principalType: 'ServicePrincipal'
  }
}
```

or 

```bicep
resource roleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
    name: guid('msi-${location}-${managedIdentity.id}-Reader-RoleAssignment')
    properties: {
        principalId: managedIdentity.properties.principalId
        roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'acdd72a7-3385-48ef-bd42-f606fba81ae7') // Reader
        principalType: 'ServicePrincipal'
    }
}
```

That's just my subjective take on it, so take it with a grain of salt. The opinion of others may very much differ. Anyhow, I assume there is a reason you'd rather want to use the module. So, could you please elaborate why the native role assignment would not be a good option? :)

**Comment by Jackmt9** [comment]
Hi @AlexanderSehr, I'd be happy to elaborate and discuss how I've altered this repository for my use. I'd love to come up with the optimal solution together. 

My actual use case is as follows: I've created a storage account followed by a function app. The function app is dependent on the storage account existing first. I need to grant the function app a role assignment on the storage account AFTER they have both been created. To do so, I have a few options:
1. I can call the storage account module again, pass in all configurations and add the role assignment.
2. I can call the 'raw' role assignment resource
3. We can have a storage-account/role-assignment module.

In the first scenario, I don't want to have to pass in all the configurations again, as it's possible that a configuration gets updated in the first creation and not the second. There is no single source of truth for all configurations. This will be a terrible approach.

In the second scenario, it is possible, however I dislike having to lookup the role id value, add it in, and comment out what the role name. It's possible that somebody updates the role assignment id without changing the commented name. There are more things that can go wrong with this approach. The other thing to consider is the 'name' of the resource. If the name is changed and the role assignment is attempting to re-create, the deployment will fail. I'll label this as a bicep bug or a silly feature. 

I like this third scenario. All modules have a /role-assignment/main where the role assignment logic is isolated. This way, when needed, a role assignment can be created without having to do so on resource creation. The main storage account logic should also be referencing this file for role assignments. This way, the role assignment logic lives in only one place but can also be referenced separately when needed.

Note that this shouldn't just apply to storage account - I believe this should apply to all resources. I'd love to hear your thoughts or if you have any alternative approaches not mentioned.

**Comment by Jackmt9** [comment]
Not to mention, we'd also be able to bulk-assign roles without having multiple resource statements:
```module modStorageRoleAssignments 'br/reference:carml/res/storage/storage-account/role-assignments/main:1.0' = {
  name: 'St-Role-${uniqueString(deployment().name)}'
  params: {
    name: functionApp.storageAccount.name
    roleAssignments: [
      {
        principalId: modFunctionApp.outputs.systemAssignedMIPrincipalId
        roleDefinitionIdOrName: 'Storage Queue Data Contributor'
      }
      {
        principalId: modFunctionApp.outputs.systemAssignedMIPrincipalId
        roleDefinitionIdOrName: 'Storage Table Data Contributor'
      }
      {
        principalId: modFunctionApp.outputs.systemAssignedMIPrincipalId
        roleDefinitionIdOrName: 'Storage Account Contributor'
      }
      {
        principalId: modFunctionApp.outputs.systemAssignedMIPrincipalId
        roleDefinitionIdOrName: 'Storage Blob Data Owner'
      }
    ]
  }
}```

**Comment by jtracey93** [comment]
Great conversation here.

I have to say I would probably agree with @AlexanderSehr here and do a separate roleAssignment call whether via a native/raw declaration or via another module just for role assignments, it doesn't really matter; the point is to make a separate resource/module call just for the role assignment post the other deployments or events happening.

Making it separate allows you to build it into the dependency graph/logic and you can influence it as you desire to occur at a specific time in the deployment.

Thats my input 👍

**Comment by Jackmt9** [comment]
@AlexanderSehr Let me add one more point here that I believe is crucial. The issue here lies when creating a role assignment for a resource in a different resource group than that being deployed.

My specific instance:
I have a key vault in one resource group and a data factory in another. The resource group with the key vault has to be deployed first. 
This means that we will need to create the keyvault, then the data factory, and immediately followed by a role assignment for data factory on keyvault.

The issue:
If we are going the route you suggested - direct resource role assignment call - we will have an issue. In order to deploy the role assignment, it needs to live in a module as it is in a different scope (different resource group). So the creation of the role assignment will anyways need to be referencing a module. Why not have it live in this library?

**Comment by Jackmt9** [comment]
I'll also reference issue #1211 here. This ticket is to handle the necessary role assignment within the module itself.

**Comment by Jackmt9** [comment]
Side-by-side here's what the code could look like (it becomes even messier if the storage account is outside the resource group).
![image](https://github.com/Azure/bicep-registry-modules/assets/58706647/a50bc722-1975-424b-966b-30afe927ba92)
![image](https://github.com/Azure/bicep-registry-modules/assets/58706647/bb5689bb-52f4-44b0-b939-2f3975afc3f3)

**Comment by ChrisSidebotham** [comment]
@AlexanderSehr / @fblix - Can you take a look at this?

**Comment by AlexanderSehr** [comment]
> @AlexanderSehr / @fblix - Can you take a look at this?

Hey @ChrisSidebotham as you can see above we did. It's not a storage account specific issue (as also pointed out by the author). We're still debating this and you're more than welcome to add your thoughts as well. I think @eriqua also wanted to take a look as time allows.

**Comment by Jackmt9** [comment]
I guess what I'm trying to highlight here is that in order to assign a role to a resource in a different scope, a module would need to be created anyways. Natively in bicep, if something is in a different scope - a module needs to be called. So I'd essentially have to copy and paste code from the AVM module and put it in it's own file elsewhere.

**Comment by peterbud** [comment]
Would it make sense maybe to resurrect this old, retired module? https://github.com/Azure/bicep-registry-modules/blob/main/modules/authorization/resource-scope-role-assignment/README.md

**Comment by AlexanderSehr** [comment]
> Would it make sense maybe to resurrect this old, retired module? https://github.com/Azure/bicep-registry-modules/blob/main/modules/authorization/resource-scope-role-assignment/README.md

Hey @peterbud,
that would be an option as a Pattern module I presume. However, we'd need to find an FTE to migrate an own it. @matebarabas, I presume it's retirement comes down to a similar situation as with the ACR-Import module?

By the way, for reference, [this](https://github.com/Azure/bicep-registry-modules/blob/ai/bing-resource/1.0.1/modules/authorization/resource-scope-role-assignment/README.md) would be a link to a tag when the module still existed.

**Comment by matebarabas** [comment]
Hi All,
@Jackmt9 / @peterbud, could you please file a [module proposal](https://aka.ms/avm/moduleproposal) for a pattern module with the following name `avm/ptn/authorization/resource-role-assignment`. Please reference this issue in the description of the proposal. As Alexander mentioned, we'll then try to find an FTE module owner who can migrate the old BRM version of this solution and make it AVM-compliant.

@peterbud, please also note that this retired module you're referring to is still published in the Public Bicep Registry, it's just not showing up through IntelliSense, but you can still leverage it by typing in its name and the version you'd like to use. See the [ARCHIVED.md](https://github.com/Azure/bicep-registry-modules/blob/main/modules/authorization/resource-scope-role-assignment/ARCHIVED.md) file for all available versions.

**Comment by peterbud** [comment]
Thanks for the feedback. I have opened a module proposal, and I'd be happy to contribute to create a AVM conform version of this module. In the meantime I can use the archived module, it just works fine.
