### ISSUE TITLE
[AVM Module Issue]: All modules that are calling the AVM Private Endpoint module do not cater for manual PE connections

### ISSUE THREAD

**Issue by tyconsulting** [Azure/bicep-registry-modules#946]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

Other, as defined below...

### (Optional) Module Name if not listed above

All modules calling the Private Endpoint module

### Description

In all the modules that are calling the PE module to create private endpoints, the configuration for `privateLinkServiceConnection` is hardcoded and `manualPrivateLinkServiceConnection` is an optional parameter. **HOWEVER**, these 2 properties are muturely exclusive. you can only have 1 or the other. you **CANNOT** have both.

When a PE should be automatically approved, the `privateLinkServiceConnection` should be used. Or, when a PE needs to be manually approved after it's created, then you must use `manualPrivateLinkServiceConnection`.

Here's an example (taken from the ACR module):
```
module registry_privateEndpoints 'br/public:avm/res/network/private-endpoint:0.3.2' = [for (privateEndpoint, index) in (privateEndpoints ?? []): {
  name: '${uniqueString(deployment().name, location)}-registry-PrivateEndpoint-${index}'
  params: {
    privateLinkServiceConnections: [
      {
        name: name
        properties: {
          privateLinkServiceId: registry.id
          groupIds: [
            privateEndpoint.?service ?? 'registry'
          ]
        }
      }
    ]
    name: privateEndpoint.?name ?? 'pep-${last(split(registry.id, '/'))}-${privateEndpoint.?service ?? 'registry'}-${index}'
    subnetResourceId: privateEndpoint.subnetResourceId
    enableTelemetry: privateEndpoint.?enableTelemetry ?? enableTelemetry
    location: privateEndpoint.?location ?? reference(split(privateEndpoint.subnetResourceId, '/subnets/')[0], '2020-06-01', 'Full').location
    lock: privateEndpoint.?lock ?? lock
    privateDnsZoneGroupName: privateEndpoint.?privateDnsZoneGroupName
    privateDnsZoneResourceIds: privateEndpoint.?privateDnsZoneResourceIds
    roleAssignments: privateEndpoint.?roleAssignments
    tags: privateEndpoint.?tags ?? tags
    manualPrivateLinkServiceConnections: privateEndpoint.?manualPrivateLinkServiceConnections
    customDnsConfigs: privateEndpoint.?customDnsConfigs
    ipConfigurations: privateEndpoint.?ipConfigurations
    applicationSecurityGroupResourceIds: privateEndpoint.?applicationSecurityGroupResourceIds
    customNetworkInterfaceName: privateEndpoint.?customNetworkInterfaceName
  }
}]
```
This will not work if manual PE connection is required.

Suggested change:

1. Extend the `privateEndpointType` type in each module and add a new boolean parameter called `manualConnection` or something similar. Set the default value to `false`
2. Update the logic in above code block based on `manualConnection` parameter. if it's `false`, then populate `privateLinkServiceConnections`, otherwise, if it's `true`, populate `manualPrivateLinkServiceConnections` instead

**Comment by segraef** [comment]
What about this?

```
    privateLinkServiceConnections: (!empty(privateEndpoint.?manualPrivateLinkServiceConnections) ? [] : [
      {
        name: name
        properties: {
          privateLinkServiceId: keyVault.id
          groupIds: [
            privateEndpoint.?service ?? 'vault'
          ]
        }
      }
    ])
    manualPrivateLinkServiceConnections: !empty(privateEndpoint.?privateLinkServiceConnections) ? [] : privateEndpoint.?manualPrivateLinkServiceConnections
```

```
module keyVault_privateEndpoints 'br/public:avm/res/network/private-endpoint:0.3.1' = [for (privateEndpoint, index) in (privateEndpoints ?? []): {
  name: '${uniqueString(deployment().name, location)}-KeyVault-PrivateEndpoint-${index}'
  params: {
    privateLinkServiceConnections: (!empty(privateEndpoint.?manualPrivateLinkServiceConnections) ? [] : [
      {
        name: name
        properties: {
          privateLinkServiceId: keyVault.id
          groupIds: [
            privateEndpoint.?service ?? 'vault'
          ]
        }
      }
    ])
    name: privateEndpoint.?name ?? 'pep-${last(split(keyVault.id, '/'))}-${privateEndpoint.?service ?? 'vault'}-${index}'
    subnetResourceId: privateEndpoint.subnetResourceId
    enableTelemetry: privateEndpoint.?enableTelemetry ?? enableTelemetry
    location: privateEndpoint.?location ?? reference(split(privateEndpoint.subnetResourceId, '/subnets/')[0], '2020-06-01', 'Full').location
    lock: privateEndpoint.?lock ?? lock
    privateDnsZoneGroupName: privateEndpoint.?privateDnsZoneGroupName
    privateDnsZoneResourceIds: privateEndpoint.?privateDnsZoneResourceIds
    roleAssignments: privateEndpoint.?roleAssignments
    tags: privateEndpoint.?tags ?? tags
    manualPrivateLinkServiceConnections: !empty(privateEndpoint.?privateLinkServiceConnections) ? [] : privateEndpoint.?manualPrivateLinkServiceConnections
    customDnsConfigs: privateEndpoint.?customDnsConfigs
    ipConfigurations: privateEndpoint.?ipConfigurations
    applicationSecurityGroupResourceIds: privateEndpoint.?applicationSecurityGroupResourceIds
    customNetworkInterfaceName: privateEndpoint.?customNetworkInterfaceName
  }
}]
```

By the way at some point we should think about giving the flexibility and freedom to choose names for `privateLinkServiceConnections.?name` and `privateEndpoint.?name` and support naming conventions by end users.

**Comment by AlexanderSehr** [comment]
> What about this @tyconsulting ?
> 
> ```
>     privateLinkServiceConnections: (!empty(privateEndpoint.?manualPrivateLinkServiceConnections) ? [] : [
>       {
>         name: name
>         properties: {
>           privateLinkServiceId: keyVault.id
>           groupIds: [
>             privateEndpoint.?service ?? 'vault'
>           ]
>         }
>       }
>     ])
>     manualPrivateLinkServiceConnections: !empty(privateEndpoint.?privateLinkServiceConnections) ? [] : privateEndpoint.?manualPrivateLinkServiceConnections
> ```
> 
> ```
> module keyVault_privateEndpoints 'br/public:avm/res/network/private-endpoint:0.3.1' = [for (privateEndpoint, index) in (privateEndpoints ?? []): {
>   name: '${uniqueString(deployment().name, location)}-KeyVault-PrivateEndpoint-${index}'
>   params: {
>     privateLinkServiceConnections: (!empty(privateEndpoint.?manualPrivateLinkServiceConnections) ? [] : [
>       {
>         name: name
>         properties: {
>           privateLinkServiceId: keyVault.id
>           groupIds: [
>             privateEndpoint.?service ?? 'vault'
>           ]
>         }
>       }
>     ])
>     name: privateEndpoint.?name ?? 'pep-${last(split(keyVault.id, '/'))}-${privateEndpoint.?service ?? 'vault'}-${index}'
>     subnetResourceId: privateEndpoint.subnetResourceId
>     enableTelemetry: privateEndpoint.?enableTelemetry ?? enableTelemetry
>     location: privateEndpoint.?location ?? reference(split(privateEndpoint.subnetResourceId, '/subnets/')[0], '2020-06-01', 'Full').location
>     lock: privateEndpoint.?lock ?? lock
>     privateDnsZoneGroupName: privateEndpoint.?privateDnsZoneGroupName
>     privateDnsZoneResourceIds: privateEndpoint.?privateDnsZoneResourceIds
>     roleAssignments: privateEndpoint.?roleAssignments
>     tags: privateEndpoint.?tags ?? tags
>     manualPrivateLinkServiceConnections: !empty(privateEndpoint.?privateLinkServiceConnections) ? [] : privateEndpoint.?manualPrivateLinkServiceConnections
>     customDnsConfigs: privateEndpoint.?customDnsConfigs
>     ipConfigurations: privateEndpoint.?ipConfigurations
>     applicationSecurityGroupResourceIds: privateEndpoint.?applicationSecurityGroupResourceIds
>     customNetworkInterfaceName: privateEndpoint.?customNetworkInterfaceName
>   }
> }]
> ```
> 
> By the way at some point we should think about giving the flexibility and freedom to choose names for `privateLinkServiceConnections.?name` and `privateEndpoint.?name` to support naming conventions by end users.

@segraef the implementation + the added ideas sound good to me. Let's make them happen.

**Comment by tyconsulting** [comment]
although this is probably the easiest fix, but imho, it's not the most user friendly option. @segraef like what you mentioned about how Terraform AzureRM provider implemented this, a boolean parameter indicating if it's manual connection or not is probably better from the end user's point of view.  to the users, it's a yes / no question.

This is how I did it in my local CARML fork:
PE type (added optiona booleanl `isManualConnection` optional string `manualConnectionRequestMessage`) :

```
type privateEndpointType = {
  @description('Optional. The name of the private endpoint.')
  name: string?

  @description('Optional. The location to deploy the private endpoint to.')
  location: string?

  @description('Optional. The service (sub-) type to deploy the private endpoint for. For example "vault" or "blob".')
  service: string?

  @description('Required. Resource ID of the subnet where the endpoint needs to be created.')
  subnetResourceId: string

  @description('Optional. The name of the private DNS zone group to create if privateDnsZoneResourceIds were provided.')
  privateDnsZoneGroupName: string?

  @description('Optional. The private DNS zone groups to associate the private endpoint with. A DNS zone group can support up to 5 DNS zones.')
  privateDnsZoneResourceIds: string[]?

  @description('Optional. Custom DNS configurations.')
  customDnsConfigs: {
    @description('Required. Fqdn that resolves to private endpoint ip address.')
    fqdn: string?

    @description('Required. A list of private ip addresses of the private endpoint.')
    ipAddresses: string[]
  }[]?

  @description('Optional. A list of IP configurations of the private endpoint. This will be used to map to the First Party Service endpoints.')
  ipConfigurations: {
    @description('Required. The name of the resource that is unique within a resource group.')
    name: string

    @description('Required. Properties of private endpoint IP configurations.')
    properties: {
      @description('Required. The ID of a group obtained from the remote resource that this private endpoint should connect to.')
      groupId: string

      @description('Required. The member name of a group obtained from the remote resource that this private endpoint should connect to.')
      memberName: string

      @description('Required. A private ip address obtained from the private endpoint\'s subnet.')
      privateIPAddress: string
    }
  }[]?

  @description('Optional. Application security groups in which the private endpoint IP configuration is included.')
  applicationSecurityGroupResourceIds: string[]?

  @description('Optional. The custom name of the network interface attached to the private endpoint.')
  customNetworkInterfaceName: string?

  @description('Optional. Specify the type of lock.')
  lock: lockType

  @description('Optional. Array of role assignment objects that contain the \'roleDefinitionIdOrName\' and \'principalId\' to define RBAC role assignments on this resource. In the roleDefinitionIdOrName attribute, you can provide either the display name of the role definition, or its fully qualified ID in the following format: \'/providers/Microsoft.Authorization/roleDefinitions/c2f4ef07-c644-48eb-af81-4b1b4947fb11\'.')
  roleAssignments: roleAssignmentType

  @description('Optional. Tags to be applied on all resources/resource groups in this deployment.')
  tags: object?

  @description('Optional. Enable/Disable usage telemetry for module.')
  enableTelemetry: bool?

  @description('Optional. If Manual Private Link Connection is required.')
  isManualConnection: bool?

  @description('Optional. A message passed to the owner of the remote resource with the manual connection request. Restricted to 140 chars.')
  manualConnectionRequestMessage: string?
}[]?
```
Calling the PE module:

```
module workspace_privateEndpoints 'br/public:avm/res/network/private-endpoint:0.3.3' = [for (privateEndpoint, index) in (privateEndpoints ?? []): {
  name: '${uniqueString(deployment().name, location)}-workspace-PrivateEndpoint-${index}'
  params: {
    privateLinkServiceConnections: !(privateEndpoint.?isManualConnection == true) ? [
      {
        name: name
        properties: {
          privateLinkServiceId: workspace.id
          groupIds: [
            privateEndpoint.?service ?? 'databricks_ui_api'
          ]
        }
      }
    ] : null
    name: privateEndpoint.?name ?? 'pep-${last(split(workspace.id, '/'))}-${privateEndpoint.?service ?? 'databricks_ui_api'}-${index}'
    subnetResourceId: privateEndpoint.subnetResourceId
    enableTelemetry: privateEndpoint.?enableDefaultTelemetry ?? enableReferencedModulesTelemetry
    location: privateEndpoint.?location ?? reference(split(privateEndpoint.subnetResourceId, '/subnets/')[0], '2020-06-01', 'Full').location
    lock: privateEndpoint.?lock ?? lock
    privateDnsZoneGroupName: privateEndpoint.?privateDnsZoneGroupName
    privateDnsZoneResourceIds: privateEndpoint.?privateDnsZoneResourceIds
    roleAssignments: privateEndpoint.?roleAssignments
    tags: privateEndpoint.?tags ?? tags
    manualPrivateLinkServiceConnections: privateEndpoint.?isManualConnection == true ? [
      {
        name: name
        properties: {
          privateLinkServiceId: workspace.id
          groupIds: [
            privateEndpoint.?service ?? 'databricks_ui_api'
          ]
          requestMessage: privateEndpoint.?manualConnectionRequestMessage ?? 'Manual approval required.'
        }
      }
    ] : null
    customDnsConfigs: privateEndpoint.?customDnsConfigs
    ipConfigurations: privateEndpoint.?ipConfigurations
    applicationSecurityGroupResourceIds: privateEndpoint.?applicationSecurityGroupResourceIds
    customNetworkInterfaceName: privateEndpoint.?customNetworkInterfaceName
  }
}]
```

**Comment by AlexanderSehr** [comment]
> although this is probably the easiest fix, but imho, it's not the most user friendly option. @segraef like what you mentioned about how Terraform AzureRM provider implemented this, a boolean parameter indicating if it's manual connection or not is probably better from the end user's point of view. to the users, it's a yes / no question.
> 
> This is how I did it in my local CARML fork: PE type (added optiona booleanl `isManualConnection` optional string `manualConnectionRequestMessage`) :
> 
> ```
> type privateEndpointType = {
>   @description('Optional. The name of the private endpoint.')
>   name: string?
> 
>   @description('Optional. The location to deploy the private endpoint to.')
>   location: string?
> 
>   @description('Optional. The service (sub-) type to deploy the private endpoint for. For example "vault" or "blob".')
>   service: string?
> 
>   @description('Required. Resource ID of the subnet where the endpoint needs to be created.')
>   subnetResourceId: string
> 
>   @description('Optional. The name of the private DNS zone group to create if privateDnsZoneResourceIds were provided.')
>   privateDnsZoneGroupName: string?
> 
>   @description('Optional. The private DNS zone groups to associate the private endpoint with. A DNS zone group can support up to 5 DNS zones.')
>   privateDnsZoneResourceIds: string[]?
> 
>   @description('Optional. Custom DNS configurations.')
>   customDnsConfigs: {
>     @description('Required. Fqdn that resolves to private endpoint ip address.')
>     fqdn: string?
> 
>     @description('Required. A list of private ip addresses of the private endpoint.')
>     ipAddresses: string[]
>   }[]?
> 
>   @description('Optional. A list of IP configurations of the private endpoint. This will be used to map to the First Party Service endpoints.')
>   ipConfigurations: {
>     @description('Required. The name of the resource that is unique within a resource group.')
>     name: string
> 
>     @description('Required. Properties of private endpoint IP configurations.')
>     properties: {
>       @description('Required. The ID of a group obtained from the remote resource that this private endpoint should connect to.')
>       groupId: string
> 
>       @description('Required. The member name of a group obtained from the remote resource that this private endpoint should connect to.')
>       memberName: string
> 
>       @description('Required. A private ip address obtained from the private endpoint\'s subnet.')
>       privateIPAddress: string
>     }
>   }[]?
> 
>   @description('Optional. Application security groups in which the private endpoint IP configuration is included.')
>   applicationSecurityGroupResourceIds: string[]?
> 
>   @description('Optional. The custom name of the network interface attached to the private endpoint.')
>   customNetworkInterfaceName: string?
> 
>   @description('Optional. Specify the type of lock.')
>   lock: lockType
> 
>   @description('Optional. Array of role assignment objects that contain the \'roleDefinitionIdOrName\' and \'principalId\' to define RBAC role assignments on this resource. In the roleDefinitionIdOrName attribute, you can provide either the display name of the role definition, or its fully qualified ID in the following format: \'/providers/Microsoft.Authorization/roleDefinitions/c2f4ef07-c644-48eb-af81-4b1b4947fb11\'.')
>   roleAssignments: roleAssignmentType
> 
>   @description('Optional. Tags to be applied on all resources/resource groups in this deployment.')
>   tags: object?
> 
>   @description('Optional. Enable/Disable usage telemetry for module.')
>   enableTelemetry: bool?
> 
>   @description('Optional. If Manual Private Link Connection is required.')
>   isManualConnection: bool?
> 
>   @description('Optional. A message passed to the owner of the remote resource with the manual connection request. Restricted to 140 chars.')
>   manualConnectionRequestMessage: string?
> }[]?
> ```
> 
> Calling the PE module:
> 
> ```
> module workspace_privateEndpoints 'br/public:avm/res/network/private-endpoint:0.3.3' = [for (privateEndpoint, index) in (privateEndpoints ?? []): {
>   name: '${uniqueString(deployment().name, location)}-workspace-PrivateEndpoint-${index}'
>   params: {
>     privateLinkServiceConnections: !(privateEndpoint.?isManualConnection == true) ? [
>       {
>         name: name
>         properties: {
>           privateLinkServiceId: workspace.id
>           groupIds: [
>             privateEndpoint.?service ?? 'databricks_ui_api'
>           ]
>         }
>       }
>     ] : null
>     name: privateEndpoint.?name ?? 'pep-${last(split(workspace.id, '/'))}-${privateEndpoint.?service ?? 'databricks_ui_api'}-${index}'
>     subnetResourceId: privateEndpoint.subnetResourceId
>     enableTelemetry: privateEndpoint.?enableDefaultTelemetry ?? enableReferencedModulesTelemetry
>     location: privateEndpoint.?location ?? reference(split(privateEndpoint.subnetResourceId, '/subnets/')[0], '2020-06-01', 'Full').location
>     lock: privateEndpoint.?lock ?? lock
>     privateDnsZoneGroupName: privateEndpoint.?privateDnsZoneGroupName
>     privateDnsZoneResourceIds: privateEndpoint.?privateDnsZoneResourceIds
>     roleAssignments: privateEndpoint.?roleAssignments
>     tags: privateEndpoint.?tags ?? tags
>     manualPrivateLinkServiceConnections: privateEndpoint.?isManualConnection == true ? [
>       {
>         name: name
>         properties: {
>           privateLinkServiceId: workspace.id
>           groupIds: [
>             privateEndpoint.?service ?? 'databricks_ui_api'
>           ]
>           requestMessage: privateEndpoint.?manualConnectionRequestMessage ?? 'Manual approval required.'
>         }
>       }
>     ] : null
>     customDnsConfigs: privateEndpoint.?customDnsConfigs
>     ipConfigurations: privateEndpoint.?ipConfigurations
>     applicationSecurityGroupResourceIds: privateEndpoint.?applicationSecurityGroupResourceIds
>     customNetworkInterfaceName: privateEndpoint.?customNetworkInterfaceName
>   }
> }]
> ```

Hey @tyconsulting I understand why this is implemented like this in TF given that it's conditions are ... limited. But I can't help but wonder why an extra boolean is a better experience. If somebody happens to impement manual service connections, isn't it a rather counter-intuitive to also need to enable them?

**Comment by tyconsulting** [comment]
> > although this is probably the easiest fix, but imho, it's not the most user friendly option. @segraef like what you mentioned about how Terraform AzureRM provider implemented this, a boolean parameter indicating if it's manual connection or not is probably better from the end user's point of view. to the users, it's a yes / no question.
> > This is how I did it in my local CARML fork: PE type (added optiona booleanl `isManualConnection` optional string `manualConnectionRequestMessage`) :
> > (...)
> > Calling the PE module:
> > (...)
> 
> Hey @tyconsulting I understand why this is implemented like this in TF given that it's conditions are ... limited. But I can't help but wonder why an extra boolean is a better experience. If somebody happens to impement manual service connections, isn't it a rather counter-intuitive to also need to enable them?

the user experience for auto vs manual connection is different in this case?

**Comment by tyconsulting** [comment]
what mean by different user experience is, if auto connection, then i don't even have to provide the `groupId` and the resource id of the `privateLinkServiceId`. but for manual connection, the user has to construct the complete payload. the payload between auto and manual is ALMOST identical (except for an additional string for request message for manual connection)

**Comment by AlexanderSehr** [comment]
> what I mean by different user experience is, if auto connection, then i don't even have to provide the `groupId` and the resource id of the `privateLinkServiceId`. but for manual connection, the user has to construct the complete payload. the payload between auto and manual is ALMOST identical (except for an additional string for request message for manual connection)

Ah gotcha, sorry. We'll have a discussion with the other maintainers to make sure everybody is in, then update the spec - and consequently the modules :) Thanks @tyconsulting

**Comment by tyconsulting** [comment]
> > what I mean by different user experience is, if auto connection, then i don't even have to provide the `groupId` and the resource id of the `privateLinkServiceId`. but for manual connection, the user has to construct the complete payload. the payload between auto and manual is ALMOST identical (except for an additional string for request message for manual connection)
> 
> Ah gotcha, sorry. We'll have a discussion with the other maintainers to make sure everybody is in, then update the spec - and consequently the modules :) Thanks @tyconsulting

you're welcome. for my current project, there's no difference which way you want to go, because we have developed an overlay module that consumes CARML / AVM. so customers don't actually directly call CARML / AVM modules to deploy resources. but for those who consume these modules directly, we need to think about the user experience.

**Comment by segraef** [comment]
> what I mean by different user experience is, if auto connection, then i don't even have to provide the `groupId` and the resource id of the `privateLinkServiceId`. but for manual connection, the user has to construct the complete payload. the payload between auto and manual is ALMOST identical (except for an additional string for request message for manual connection)

Agreed, adjusting interfaces via https://github.com/Azure/Azure-Verified-Modules/pull/621 and once approved by the team a global change to all modules. Thank you @tyconsulting.

**Comment by segraef** [comment]
Implementation in progress, see linked PRs.
