### ISSUE TITLE
[AVM Module Issue]: Add GroupId as additional output for the Private Endpoint module

### ISSUE THREAD

**Issue by tyconsulting** [Azure/bicep-registry-modules#953]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/private-endpoint

### Description

Add additional output for the Private Endpoint groupId:

something like this?

```
@description('The group Id for the private endpoint Group.')
output groupId string = !empty(privateEndpoint.properties.manualPrivateLinkServiceConnections) ?  privateEndpoint.properties.manualPrivateLinkServiceConnections[0].properties.groupIds[0] : privateEndpoint.properties.privateLinkServiceConnections[0].properties.groupIds[0]
```

When upstream modules call the PE module to create multiple PEs, it would be good to be able to identify what is each PE created for (i.e. storage account with multiple PEs such as blob, dfs, file, etc,)

Right now only the PE name and resource Id can be used to identify the PE. but if the names are generic (not being able to identify the PE type / groupId by name), it is difficult for users to leverage the output.

**Comment by segraef** [comment]
https://github.com/Azure/bicep-registry-modules/pull/954
