### ISSUE TITLE
Expand Array Outputs in Readme

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#96]
The outputs in the readme.md are autogenerated. Where one of the outputs is an array, it would be great to be able to expand it out.
Eg. For an array of objects, we could list the name and types used.

**Comment by shenglol** [comment]
Good idea!

**Comment by Gordonby** [comment]
This idea becomes more important when using UserDefinedTypes.
The `array` type abstracts valuable type information which is available.

**Comment by ChrisSidebotham** [comment]
Dear @Gordonby, Azure Verified Modules ([AVM](https://aka.ms/AVM)) will become the single Microsoft standard for Bicep modules. Transitioning to AVM, requests for new features or bug fixes will need to be submitted against the appropriate AVM module via [AVM Module Issues](https://aka.ms/AVM/Bicep/ModuleIssue). 

As part of this transition, the new AVM CI environment is replacing the existing CI formerly leveraged within the Bicep Registry Modules (BRM) repository. As a result of this, issues and features related to the existing BRM CI will be closed. If you think your issue still needs addressing, please raise a new issue related to the AVM CI, [here](https://aka.ms/BRM/AVMQuestionFeedback).

See this [informational notice](https://github.com/Azure/bicep-registry-modules?tab=readme-ov-file#%EF%B8%8F-upcoming-changes-%EF%B8%8F) for more details on the upcoming changes.

Thank you for your understanding!
