### ISSUE TITLE
[AVM Module Issue]: `Coginitive Services Deployments`

### ISSUE THREAD

**Issue by JFolberth** [Azure/bicep-registry-modules#964]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cognitive-services/account

### Description

Would be a sub module to support Open AI model deployments. I have some sample code: https://github.com/JFolberth/PDFgpt/blob/main/infrastructure/modules/openAI.module.bicep

Would need to be updated to adhere to the practices

**Comment by matebarabas** [comment]
@ilhaan, @JFolberth - based on the discussion we had, I've moved this issue to the BRM repo and converted it to an [AVM Module Issue]. @JFolberth please work with @ilhaan as a module owner to implement this feature in the `avm/res/cognitive-services/account` module as agreed. Thanks!

**Comment by segraef** [comment]
@JFolberth we talked about this but afaik this issue can be closed since we have deployments integrated already and as you can see with #2979 I've added a couple of more e2e as well to support examples.

**Comment by JFolberth** [comment]
Yeah I am good with closing this feature addition.
