### ISSUE TITLE
[AVM Module Issue]: consumption/budget thresholdType hardcoded to 'actual'

### ISSUE THREAD

**Issue by dibcar** [Azure/bicep-registry-modules#968]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/consumption/budget

### Description

The module consumption/budget have the properties thresholdType hardcoded to 'Actual' and can't be used for forecast notifications.

**Comment by AlexanderSehr** [comment]
Hey @segraef could you take a look at that please? Or provide a time line when you'd have time to have a look? Presumably, this is only a matter of adding a parameter that may have the current hardcoded value as a default, but still provide the flexiblity of setting something else.

**Comment by segraef** [comment]
Having a loook at it now.
