### ISSUE TITLE
[Module Proposal]: Storage Account

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/bicep-registry-modules#97]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We need a module to simplify Storage Account creation.

### Module path

storage/storageaccounts

### Describe the module

Taken from the [CARML](https://aka.ms/CARML) repository, the module contains a Storage Account resource. It sets default values for common properties and allows users to override them via parameters. It further inclused extension resources such as RBAC, diagnostic settings & locks. It further enables the user to deploy child resources such as containers, queues alongside a rich set of its properties (and their extensions).

**Comment by MrMCake** [comment]
[link](https://github.com/MrMCake/bicep-registry-modules/tree/users/alsehr/storageAccountModule/modules/storage/storage-account)

**Comment by AlexanderSehr** [comment]
Closing as the linked PR was closed as it was open for too long and eventually was outdated, compared to CARML upstream
