### ISSUE TITLE
[Module Proposal]: Managed Identity

### ISSUE THREAD

**Issue by AlexanderSehr** [Azure/bicep-registry-modules#98]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

We need a module to simplify Managed Identity creation.

### Module path

managed-identity/user-assigned-identities

### Describe the module

Taken from the [CARML](https://aka.ms/CARML) repository, the module contains a Managed Identity resource. It sets default values for common properties and allows users to override them via parameters. It further inclused extension resources such as RBAC & locks.

**Comment by MrMCake** [comment]
[link](https://github.com/MrMCake/bicep-registry-modules/tree/users/alsehr/msi/modules/managed-identity/user-assigned-identity)

**Comment by AlexanderSehr** [comment]
Closing as I closed the PR for being open too long and eventually being outdated compared to CARML upstream
