### ISSUE TITLE
[AVM Module Issue]: Update Naming to indicate Front Door Classic

### ISSUE THREAD

**Issue by cliveg** [Azure/bicep-registry-modules#985]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/network/front-door

### Description

Name doesn't indicate this is for Azure Front Door Classic. Should update the naming and maybe make mention there isn't yet a Azure Front Door Standard/Premium AVM yet.

**Comment by ChrisSidebotham** [comment]
@cliveg - I believe we tried to address this in the LevelUP Session. To your point I agree the `avm/res/network/front-door` is the "classic" resource for Azure Front Door. However, if you look in the Bicep reference, we do not have differing resource apis for the standard and premium sku's under the `Microsoft.Network/frontDoor` tree: [Reference](https://learn.microsoft.com/en-us/azure/templates/microsoft.network/frontdoors?pivots=deployment-language-bicep). However, to your point the front door Standard and Premium tiers are differing as they fall under the `Microsoft.Cdn/profiles` tree which we are pending migration from the original [CARML](https://github.com/Azure/ResourceModules/tree/main/modules/cdn/profile) repository. 

To clarify, I believe we should not change the current name of the service unless this is also aligned in the Bicep/ARM Reference documentation. If you follow the documentation for the service ([here](https://learn.microsoft.com/en-us/azure/frontdoor/create-front-door-template)) then you will see the ARM Template is using the CDN Namespace in the deployment templates.
