### ISSUE TITLE
main.json is modified or outdated. Please regenerate the file to fix it. 

### ISSUE THREAD

**Issue by bengeset96** [Azure/bicep-registry-modules#99]
Hi, 

@shenglol 

Have you seen this issue before with the `brm validate?` 

Locally it works fine, but in pipeline context it will throw this out.

![image](https://user-images.githubusercontent.com/99641908/165145579-9216693e-972d-44e5-bb58-5aa8959ce49e.png)

I have tried to add .gitattributes file with

```
* text=auto
*.bicep text eol=lf
```
Then clone repo again to trigger lf change. 

Same issue occurs. 

Running `git ls-files --eol`

![image](https://user-images.githubusercontent.com/99641908/165146352-d794718c-d078-4181-a06a-a89813d29093.png)

Even when setting both bicep and json files to lf manually in VS Code has no improvements. 

Do you have any idea how to handle such behavior?

Seems that #66 has been experiencing something similar.

**Comment by shenglol** [comment]
Hi @bengeset96, can you check what version of Bicep CLI is installed on your machine?

**Comment by bengeset96** [comment]
@shenglol 

Running Bicep CLI 0.5.6.

![image](https://user-images.githubusercontent.com/99641908/165147999-62df8a97-a277-4eee-8263-8b9df3ff6150.png)

**Comment by bengeset96** [comment]
Should probably start reading documentation better..

Sorce had 0.4 installed. Upgraded now with 0.5.6. 

![image](https://user-images.githubusercontent.com/99641908/165152299-22b8d452-b733-45b5-89a9-bdf1f558fe3a.png)

And now 

![image](https://user-images.githubusercontent.com/99641908/165152459-faf5e13a-4e72-46f5-b275-0642b4b8d803.png)

I was not aware that `brm validate` would check for 

![image](https://user-images.githubusercontent.com/99641908/165152661-3b02f1e8-54e1-4621-9d13-f9168d5dd658.png)

That is clever! 

@shenglol 

Thanks for responding so fast. Truly grateful.
